### ISSUE TITLE
[Geosphere Austria] Wrong precipitation values

### ISSUE THREAD

**Issue by kosmoz** [breezy-weather/breezy-weather#1002]
### Steps to reproduce

Go to precipitation tab while it's raining

### Expected behavior

Reasonable values shown

### Actual behavior

The values shown seem to accumulate, they never go down. This leads to some pretty ridiculous numbers

### Weather source used

Geosphere Austria

### Breezy Weather version

5.2.1

### Android version

Android 13

### Device

Fairphone 4

### Other details

![Screenshot_20240422-213545](https://github.com/breezy-weather/breezy-weather/assets/16959694/1d61b774-1f19-411c-91ce-efbe318d0a23)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open OR closed issue.
- [X] I checked that my issue is not covered in the [Frequently Asked Questions](https://github.com/breezy-weather/breezy-weather/blob/main/HELP.md) document.
- [X] I have updated the app to **[version 5.2.1 or later](https://github.com/breezy-weather/breezy-weather/releases/latest)** and I can reproduce the issue in this version.
- [X] I wrote my request in English, and any screenshot I attached are also in English (language can be changed from Settings > Appearance), unless my issue only happens with a specific language. I can write in my native language under the English text, if necessary.
- [X] I understand that this app is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY, so I may not get a positive reply to my request, if any at all.

**Comment by papjul** [comment]
I don't know why they do that, it's the first time I see something like that.

I will substract every hour, then
