### ISSUE TITLE
Continuation of Issue #957 CLOSED without Resolution

### ISSUE THREAD

**Issue by AnonemooseBear** [breezy-weather/breezy-weather#1004]
> I can't update to 5.2.x as this is the most recent version available on fdroid - which is the way apps are sourced for this device. My repos have been updated. Frankly, you could consider requiring to update to a version that's not available a secondary issue here!

I'm sorry but v5.1.8 is no longer supported and F-Droid default repo is not recommended for getting updates. We have [other F-Droid repos](https://github.com/breezy-weather/fdroid-repo) available with faster updates. If you don't want to use them, everytime you have an issue, it takes you about 20 seconds to [download the APK](https://github.com/breezy-weather/breezy-weather/releases/latest) and to update, while it would take me way more time to understand that something you report was actually fixed since then. Also, we have more detailed errors in v5.2.0 that would help me troubleshooting, so please save your app maintainers their time and take these 20 seconds to update. You just need to update, no need to uninstall and reinstall.

Once it's done and you can reproduce the issue with this new version, please export your crash log from `Settings` > `Debug`.

_Originally posted by @papjul in https://github.com/breezy-weather/breezy-weather/issues/957#issuecomment-2060364531_

You closed the issue before I had a chance to respond!

I've seen the problem with another app where there was a newer version available, and users (not just myself according to Github) couldn't update on fDroid.  The developers had to do something on their end with fDroid in order for it to become available to the public - hence my mentioning in the issue opened.  When I try to add the repo manually it won't work.  See screenshot.

![Screenshot_20240418_095247_org fdroid fdroid 1](https://user-images.githubusercontent.com/131646532/324957305-702654ce-4883-4388-a295-ebccabe234d9.jpg)

After a number of days of constantly updating the repos through fDroid, I finally saw the 5.2 version and have updated.  Unfortunately, that doesn't appear to have solved the problem.  Now the results are inconsistent.  Sometimes it will update and sometimes it will not.  I've been watching it for a few days to make sure I had a clear perspective of the apps behaviour.  As per your request here is a screenshot of the log.

![Screenshot_20240423_120634_at tomtasche reader 1](https://user-images.githubusercontent.com/131646532/324961399-b1f7158a-a3cf-4b57-941a-a1be285767b5.jpg)

What I am wondering is if the app is getting confused whether there is an internet connection or not, and failing based on trying to use a connection that is unavailable.  Basically as soon as WiFi is turned on that becomes the preferred source of internet, which results in "no internet" errors if WiFi is turned off after regardless of whether mobile data is available.  Again, this is something I've seen in other apps as an issue.  The reason why I suggest it is because there were no errors in updating at first, when only mobile data was on.  Then I had to access something locally via WiFi, so it was turned on.  After I finished WiFi was turned off and I went to bed leaving only mobile data on.  Normally I'd turn it off overnight, but since updates could run I left it on.  In the morning I had errors that the weather app failed to update again.

In my head, logically, it shouldn't be related to the phone sleeping (screen off) as the app has sufficient permission to use mobile data in the background.  It's also set to ignore all the battery stuff that would prevent it from doing that in the app, ignore batter stuff in the phone settings, and the phone is not reverting to any kind of power saving mode.

Anyhow, hope you keep this open to troubleshoot.  This is literally the perfect weather app.  Hoping kinks will come out in future updates, so I have to communicate what I'm experiencing.

**Comment by papjul** [comment]
I don't understand what you're saying about updating and all your screenshots are failing to load for some reason.

Please update to v5.2.1 from the GitHub releases. Just download the APK and install it on top of your existing installed app, then export your debug logs after the issue reproduces. The debug logs from v5.2.1 contains important informations that will help me troubleshoot.

**Comment by papjul** [comment]
And please use the "bug" template when creating an issue.

**Comment by papjul** [comment]
> We should be able to rely on fDroid for a current version if that's a way you're distributing the app. We are at your mercy to make sure that the most recent version is available there

Absolutely not. F-Droid maintainers are responsible for publishing my APKs, I'm not. F-Droid default repo is known to have a slow delay for publishing updates of all apps, not just Breezy Weather. People urged me to publish the app on F-Droid default repo even though I didn't want for many reasons, and I warned them I wouldn't be doing support for outdated versions and that they will have to update first if they wanted support.

If interested, have a look at better ways to get automatic updates here: https://github.com/breezy-weather/breezy-weather/blob/main/INSTALL.md#sources-to-get-breezy-weather-from

> It's not reasonable to continually check for individual APKs on every app,

I'm not asking you to update continuously manually, just once when you have an issue you're asked to update, and you don't respect this rule, and you already made me lose a lot of time telling you again and again to update. Why can't you follow a simple rule?

> if we install from an APK then fDroid may not recognize, and we won't be able to update it that way in the future

No, that's not the case. If you update to v5.2.1 manually, when v5.2.2 is out in F-Droid default repo, you will get the update from there.


Finally, I don't understand your screenshot about failure to add repository. There is no error message, I don't even know what you did.

Debug log must be published as text, not image, and it must be from v5.2.1.

**Comment by papjul** [comment]
> When fDroid says "Your apps are up to date" I take that at face value.

Then, open an issue at F-Droid to let them know the wording is not correct. Once again, I have no control over the publishing delays on F-Droid default repo. ALL apps are affected by these delays.

> As far as adding the individual repo in fDroid like you suggested in the original issue, that's the error messaged that comes up in fDroid when I try to add the repo with the address you posted.

You added the following URL, right? `https://breezy-weather.github.io/fdroid-repo/fdroid-version/fdroid/repo`

You can also just update once with the APK from GitHub releases if you can't get the repo to work, that's probably the simplest way.
