### ISSUE TITLE
Fix colons placement

### ISSUE THREAD

**Issue by nvllz** [breezy-weather/breezy-weather#101]
### Steps to reproduce

Open the app and tap on any hour-card inside the 'Hourly forecast' box.

### Expected behavior

The colons are aligned to the trailing words ('Precipitation: 0 mm' etc..).

### Actual behavior

![image](https://github.com/breezy-weather/breezy-weather/assets/110673332/bd2aace7-6f72-4cdb-8682-7f977899c253)

### Weather provider used

n/a

### Breezy Weather version

4.0.5-alpha

### Android version

n/a

### Device

n/a

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to **[latest version](https://github.com/breezy-weather/breezy-weather/releases/latest)**.

**Comment by papjul** [comment]
Given we have much more hourly information, this dialog will disappear in the future and be replaced by something similar to what is done for daily. I just opened #102 which will solve this issue.

Btw, I don't know yet but if there are still colons in the new view, we will have to implement a translation string, as some languages require spaces before colons (French, for example). I'm not a fan of colons so I will try to avoid.

**Comment by papjul** [comment]
Fixed as part of a33361a431c0cca673ac7e65234222ae11929d51
