### ISSUE TITLE
The Royal Netherlands Meteorological Institute

### ISSUE THREAD

**Issue by errrieee** [breezy-weather/breezy-weather#1025]
### Link to publicly available documentation of the API

https://developer.dataplatform.knmi.nl/open-data-api
https://dataplatform.knmi.nl/

### Available and not available data

Available datasets:
Climate
Precipitation
Seismology and Acoustics
Sunshine and Radiation
Temperature
Weather forecast
Wind

### Are you going to develop yourself the new source for the app?

No, I sadly don't equip the needed skills to code

### Give a bit more details or context about this source

The Royal Netherlands Meteorological Institute (KNMI) is the Dutch national weather service. So this would give the dutch users an accurate and centrified weather forecast. 

### Acknowledgements

- [X] I have searched [the existing sources](https://github.com/breezy-weather/breezy-weather/blob/main/docs/SOURCES.md) and [the existing new source requests](https://github.com/breezy-weather/breezy-weather/issues?q=is%3Aissue+label%3A%22New+source%22+no%3Amilestone+-label%3ADuplicate) and this is a new source, **NOT** a duplicate or related to another open OR closed issue.
- [X] This source has a free-tier available (not a trial period), and if it is a main weather source, it includes free hourly forecast
- [X] This source does not require sensitive information (billing info, phone number, etc) to subscribe to the free-tier
- [X] I understand there may be technical limitations that may prevent implementing this source (for example, the lack of coordinates information)
- [X] I wrote my request in English. I can write in my native language under the English text, if necessary.
- [X] I understand that this app is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY, so I may not get a positive reply to my request, if any at all.

**Comment by papjul** [comment]
To me, it looks like it only allows you to download the weather models, not get forecast for a specific longitude/latitude?
https://dataplatform.knmi.nl/group/weather-forecast?groups=weather-forecast

We can't download 667 MB of data at every refresh, and process it on a mobile device.
