### ISSUE TITLE
[Open-Meteo] Weather refresh failed on old Android version

### ISSUE THREAD

**Issue by AnonemooseBear** [breezy-weather/breezy-weather#1029]
### Steps to reproduce

1. Setup widget.
2. Wait until time passes for automatic update to run.
3. Receive error notification

### Expected behavior

Weather widget should update at specified intervals, and without having to open the entire app.

### Actual behavior

An error file is produced.  Replace LOCATION in the below error message with the location set in the widget.

`Errors during refresh
! Open-Meteo: Weather data refresh failed
- LOCATION`

### Weather source used

Open-Meteo

### Breezy Weather version

5.2.2_freenet

### Android version

Android 9

### Device

Huawei Mate 20 PRO

### Other details

This is a continuation of issue #957 and issue issue #1004 - that were both closed before I could provide a response.  Sorry, I'm not a developer or on GitHub on a daily basis.  I needed time to get the version requested, and let the widget run for a while to see if it was still happening.

On previous versions I had inconsistent results.  Sometimes it updates and sometimes it won't.  The same seems to be true for 5.2.2.  Here is the debug information from today.

`--------- beginning of main
05-02 14:26:19.136 12649 12649 E g.breezyweathe: Not starting debugger since process cannot load the jdwp agent.
--------- beginning of system
05-02 14:26:19.170 12649 12665 E AwareLog: AtomicFileUtils: readFileLines file not exist: android.util.AtomicFile@67245a8
05-02 14:26:19.171 12649 12659 E : [ZeroHung]zrhung_get_config: Get config failed for wp[0x0008]
05-02 14:26:19.191 12649 12662 E MemoryLeakMonitorManager: MemoryLeakMonitor.jar is not exist!
05-02 14:26:19.193 12649 12671 E : [ZeroHung]zrhung_get_config: Get config failed for wp[0x0102]
05-02 14:26:19.229 12649 12659 E : [ZeroHung]zrhung_get_config: Get config failed for wp[0x0008]
05-02 14:26:19.241 12649 12678 E SQLiteLog: (283) recovered 157 frames from WAL file /data/data/org.breezyweather/databases/breezyweather.db-wal
05-02 14:26:19.269 12649 12659 E : [ZeroHung]zrhung_get_config: Get config failed for wp[0x0008]
05-02 14:26:19.331 12649 12659 E : [ZeroHung]zrhung_get_config: Get config failed for wp[0x0008]
05-02 14:26:19.384 12649 12659 E : [ZeroHung]zrhung_get_config: Get config failed for wp[0x0008]
05-02 14:26:19.418 12649 12659 E : [ZeroHung]zrhung_get_config: Get config failed for wp[0x0008]
05-02 14:26:19.454 12649 12659 E : [ZeroHung]zrhung_get_config: Get config failed for wp[0x0008]
05-02 14:26:22.768 12649 12659 E : [ZeroHung]zrhung_get_config: Get config failed for wp[0x0008]
05-02 14:26:23.329 12649 12659 E : [ZeroHung]zrhung_get_config: Get config failed for wp[0x0008]
App version: 5.2.2_freenet (freenet, a4410615, 50202
Android version: 9 (SDK 28); build LYA-L0C 9.0.0.269(C792E19R1P17)
Device brand: HUAWEI
Device manufacturer: HUAWEI
Device name: HWLYA (LYA-L0C)
Device model: LYA-L0C`

I really hope this helps!

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open OR closed issue.
- [X] I checked that my issue is not covered in the [Frequently Asked Questions](https://github.com/breezy-weather/breezy-weather/blob/main/HELP.md) document.
- [X] I have updated the app to **[version 5.2.2 or later](https://github.com/breezy-weather/breezy-weather/releases/latest)** and I can reproduce the issue in this version.
- [X] I wrote my request in English, and any screenshot I attached are also in English (language can be changed from Settings > Appearance), unless my issue only happens with a specific language. I can write in my native language under the English text, if necessary.
- [X] I understand that this app is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY, so I may not get a positive reply to my request, if any at all.

**Comment by papjul** [comment]
Did the issue happen before May 2nd, 14:26? Because the debug logs show nothing, except noisy logs from Huawei (and it's missing line breaks).

Please export the debug logs when the issue happens.

Do you have issues with other apps, such as internet disconnecting? Looks like a device-specific issue

**Comment by prog-amateur2** [comment]
Hello there, I have the same issue (same error message with Open weather) on a Pixel 6a with GrapheneOS. 
My location is a well known city because I can have  weather data with this app before this error. 
There is no battery restriction on the app.

**Comment by papjul** [comment]
Please open your own issue, attaching your own log; you use a different weather source and a more recent Android version, it's unsure if it's related
