### ISSUE TITLE
"Current location" text in weather screen and widget is less informative than giving the name of the current location.

### ISSUE THREAD

**Issue by githubisviolatingthegpl** [breezy-weather/breezy-weather#1034]
### Steps to reproduce

"Geometric Weather" would give the name of the city you are currently detected as being in. This was actually helpful, as you could make sure that the locate has been properly updated when you arrive at a destination when traveling.

### Expected behavior

While giving the name of the city you're currently in sounds like a dumb "feature," it helps to verify that the detected location is correct. Differentiating between the currently detected location and manually entered locations can be done through a GPS icon or a small amount of parenthetical text, like "(detected)" or "(GPS)"

### Actual behavior

Currently, Breezy only shows "Current weather" in the weather screen and all widgets without giving any indication where it thinks that location is.

### Weather source used

Open-Meteo

### Breezy Weather version

5.2.2 (IzzyOnDroid)

### Android version

Android 14

### Device

Pixel 7

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open OR closed issue.
- [X] I checked that my issue is not covered in the [Frequently Asked Questions](https://github.com/breezy-weather/breezy-weather/blob/main/HELP.md) document.
- [X] I have updated the app to **[version 5.2.2 or later](https://github.com/breezy-weather/breezy-weather/releases/latest)** and I can reproduce the issue in this version.
- [X] I wrote my request in English, and any screenshot I attached are also in English (language can be changed from Settings > Appearance), unless my issue only happens with a specific language. I can write in my native language under the English text, if necessary.
- [X] I understand that this app is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY, so I may not get a positive reply to my request, if any at all.

**Comment by papjul** [comment]
Answer to this question just got added to FAQ: https://github.com/breezy-weather/breezy-weather/blob/main/HELP.md#app-shows-current-location-instead-of-the-reverse-geocoded-address

**Comment by githubisviolatingthegpl** [comment]
> Answer to this question just got added to FAQ: https://github.com/breezy-weather/breezy-weather/blob/main/HELP.md#app-shows-current-location-instead-of-the-reverse-geocoded-address

That is SUPER helpful, thank you. That fixed it for me, and I'm glad to now understand why that worked differently from the old app.

Thanks again, @papjul.
