### ISSUE TITLE
When using accuweather as source, the cloudy(阴天) weather icon/animation error in china city

### ISSUE THREAD

**Issue by lyrnya** [breezy-weather/breezy-weather#1044]
### Steps to reproduce

1.Use accuweather source
2.Add a Chinese city with a Partly cloudy(多云) current weather
3.It is found that the background weather animation is a gray animation with a cloudy day (阴天), and the weather icon displayed by small parts is cloudy(阴天). Not a Partly cloudy blue background(多云)
![961cd05b7e76f3c6b2ce9faf0de48a4](https://github.com/breezy-weather/breezy-weather/assets/92076022/b9a96bcf-8051-42d6-b8d7-24b0af9491d2)
![126269f19d9280252b3cce5680d4708](https://github.com/breezy-weather/breezy-weather/assets/92076022/e9853ce4-c5b3-4c08-975f-bd5ab14dbb78)
![497d5cecb3e9d9305817b0f1a10e085](https://github.com/breezy-weather/breezy-weather/assets/92076022/63d4d798-27ad-4068-b71b-7231fc1c7b87)

### Expected behavior

When Partly cloudy(多云), Partly cloudy(多云) animations and icons are displayed, instead of using the same icon in Partly cloudy(多云) and cloudy(阴天), there is no such problem using China source.

### Actual behavior

The animation and icons displayed in Partly cloudy(多云) and cloudy(阴天) are the same source in AccuWeather

### Weather source used

AccuWeather

### Breezy Weather version

5.2.3 Standard

### Android version

Android 14

### Device

Moto G54

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open OR closed issue.
- [X] I checked that my issue is not covered in the [Frequently Asked Questions](https://github.com/breezy-weather/breezy-weather/blob/main/HELP.md) document.
- [X] I have updated the app to **[version 5.2.3 or later](https://github.com/breezy-weather/breezy-weather/releases/latest)** and I can reproduce the issue in this version.
- [X] I wrote my request in English, and any screenshot I attached are also in English (language can be changed from Settings > Appearance), unless my issue only happens with a specific language. I can write in my native language under the English text, if necessary.
- [x] I understand that this app is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY, so I may not get a positive reply to my request, if any at all.

**Comment by papjul** [comment]
Not a bug in Breezy Weather.

It's a translation issue on AccuWeather side. Weather text correctly shows "Cloudy" in Xihu District, Zhejiang right now if you switch your language to English, while it shows 多云 if you switch to Chinese (Simplified).
