### ISSUE TITLE
India Meteorological Department

### ISSUE THREAD

**Issue by opusforlife2** [breezy-weather/breezy-weather#1053]
### Link to publicly available documentation of the API

https://mausam.imd.gov.in/imd_latest/contents/api.pdf

### Available and not available data

Daily and current temperature, rainfall, humidity, sunrise/sunset, wind, cloud cover.

### Are you going to develop yourself the new source for the app?

No

### Give a bit more details or context about this source

This is the national source for India. I've opened this issue because I've noticed over several weeks that the Open Meteo predictions seem to vary quite a bit from the actual weather here.

A caveat is that I couldn't find this document by navigating their website. It just happened to be indexed by search engines. Thus I have no idea whether the following are true or not, and can't think of a way to confirm except by trying to access the API:

> This source has a free-tier available (not a trial period), and if it is a main weather source, it includes free hourly forecast

> This source does not require sensitive information (billing info, phone number, etc) to subscribe to the free-tier

### Acknowledgements

- [X] I have searched [the existing sources](https://github.com/breezy-weather/breezy-weather/blob/main/docs/SOURCES.md) and [the existing new source requests](https://github.com/breezy-weather/breezy-weather/issues?q=is%3Aissue+label%3A%22New+source%22+no%3Amilestone+-label%3ADuplicate) and this is a new source, **NOT** a duplicate or related to another open OR closed issue.
- [X] This source has a free-tier available (not a trial period), and if it is a main weather source, it includes free hourly forecast
- [X] This source does not require sensitive information (billing info, phone number, etc) to subscribe to the free-tier
- [X] I understand there may be technical limitations that may prevent implementing this source (for example, the lack of coordinates information)
- [X] I wrote my request in English. I can write in my native language under the English text, if necessary.
- [X] I understand that this app is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY, so I may not get a positive reply to my request, if any at all.

**Comment by papjul** [comment]
When going to any of the link listed, I get “IP X.Y.Z.A needs to be whitelisted".

Looks like it is not available for IPs outside India?
If that's the case, unfortunately, even if someone from India would contribute it, I cannot commit to maintain a source I can't access :/

Let me know if you have other insights or if we can close ;)

**Comment by papjul** [comment]
Nevermind, it says "User has to provide their public IP so that same could be whitelisted at our end.".

That's way too complicated! We can't ask each Indian user to provide their IP. And what if you are on the go? It's impossible to whitelist all IP from all cell networks.

**Comment by papjul** [comment]
I believe they didn't properly an API key/rate limit system so they made a whitelist system, but it's only useful if you're consuming from a server which IP doesn't change, unlike mobile apps
