### ISSUE TITLE
Missing latest fdroid version

### ISSUE THREAD

**Issue by tuch96** [breezy-weather/breezy-weather#1058]
### Steps to reproduce

.

### Expected behavior

No more new versions appear on fdroid. The latest version is 5.2.1_freenet

### Actual behavior

.

### Weather source used

.

### Breezy Weather version

5.2.1_freenet

### Android version

Android 14

### Device

.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open OR closed issue.
- [X] I checked that my issue is not covered in the [Frequently Asked Questions](https://github.com/breezy-weather/breezy-weather/blob/main/HELP.md) document.
- [X] I have updated the app to **[version 5.2.3 or later](https://github.com/breezy-weather/breezy-weather/releases/latest)** and I can reproduce the issue in this version.
- [X] I wrote my request in English, and any screenshot I attached are also in English (language can be changed from Settings > Appearance), unless my issue only happens with a specific language. I can write in my native language under the English text, if necessary.
- [X] I understand that this app is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY, so I may not get a positive reply to my request, if any at all.

**Comment by papjul** [comment]
I have no publish rights on F-Droid default repo, it was already reported a week ago: https://gitlab.com/fdroid/fdroiddata/-/issues/3256

You should definitely not use F-Droid default repo if you want fast updates
