### ISSUE TITLE
Missing items displayed in daily and hourly trends

### ISSUE THREAD

**Issue by tuch96** [breezy-weather/breezy-weather#1059]
### Steps to reproduce

1. Open Settings
2. Mainscreen
3. Select an item (wind, sunshine etc.) in hourly trends
4. Then open the hourly trends and only 2 trends are displayed.

### Expected behavior

The settings in the daily and hourly trends area are not applied correctly. Either selected areas are missing or they are not displayed in the correct order. Please see the screenshots.

### Actual behavior

.

### Weather source used

Bright Sky

### Breezy Weather version

5.2.1_freenet

### Android version

Android 14

### Device

Pixel 5

### Other details

![Screenshot_20240516-211007](https://github.com/breezy-weather/breezy-weather/assets/57192210/ec715a6b-e36d-49c3-9ccf-3029bcb75d2e)
![Screenshot_20240516-211039](https://github.com/breezy-weather/breezy-weather/assets/57192210/051b44bc-2d10-44fe-a446-01fad084039e)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open OR closed issue.
- [X] I checked that my issue is not covered in the [Frequently Asked Questions](https://github.com/breezy-weather/breezy-weather/blob/main/HELP.md) document.
- [X] I have updated the app to **[version 5.2.3 or later](https://github.com/breezy-weather/breezy-weather/releases/latest)** and I can reproduce the issue in this version.
- [X] I wrote my request in English, and any screenshot I attached are also in English (language can be changed from Settings > Appearance), unless my issue only happens with a specific language. I can write in my native language under the English text, if necessary.
- [X] I understand that this app is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY, so I may not get a positive reply to my request, if any at all.

**Comment by papjul** [comment]
Read https://github.com/breezy-weather/breezy-weather/blob/main/docs/HOMEPAGE.md and https://github.com/breezy-weather/breezy-weather/blob/main/docs/SOURCES.md
