### ISSUE TITLE
Widget size/scale wrong - Material You Current 

### ISSUE THREAD

**Issue by music2myear** [breezy-weather/breezy-weather#1063]
### Steps to reproduce

Confirmed issue on both current version (5.2.3) and previous (5.2.2). OnePlus 8T running Android version 14, security update from April 5, 2024.

When widget is first added or when phone is restarted widget appears the preferred size me elements are visible. Unsure of trigger, but within an hour or so the widget shrinks to about a quarter of the desired size. Text size remains unchanged and is cut off as it extends beyond the widget's new limits. Using the resize widget commands I see the phone still has the correct space assigned to the widget. 

### Expected behavior

Widget should remain specified size. 

### Actual behavior

Widget shrinks to a quarter the signed space. Screenshots are of the shrunk widget and the assigned area. 
![Screenshot_2024-05-18-08-18-28-02_b783bf344239542886fee7b48fa4b892](https://github.com/breezy-weather/breezy-weather/assets/5528223/af100e84-8eae-4577-83b8-b2007e7559f8)
![Screenshot_2024-05-18-08-18-34-81_b783bf344239542886fee7b48fa4b892](https://github.com/breezy-weather/breezy-weather/assets/5528223/3d1684b1-85c3-40f9-93be-41c00aa57f9b)

### Weather source used

AccuWeather 

### Breezy Weather version

5.2.3

### Android version

Android 24

### Device

OnePlus 8T

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open OR closed issue.
- [X] I checked that my issue is not covered in the [Frequently Asked Questions](https://github.com/breezy-weather/breezy-weather/blob/main/HELP.md) document.
- [X] I have updated the app to **[version 5.2.3 or later](https://github.com/breezy-weather/breezy-weather/releases/latest)** and I can reproduce the issue in this version.
- [X] I wrote my request in English, and any screenshot I attached are also in English (language can be changed from Settings > Appearance), unless my issue only happens with a specific language. I can write in my native language under the English text, if necessary.
- [X] I understand that this app is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY, so I may not get a positive reply to my request, if any at all.

**Comment by papjul** [comment]
I think we already got a similar report, but the issue was also happening on Google weather widget, and was solved after changing launcher app, hinting to an issue on launcher app.

Please try the following:
1) Add Google weather widget. Report if issue reproduces or not
2) Try a different launcher app. Report if issue is still there or not

**Comment by music2myear** [comment]
I have disabled the Google Weather app, but I'll switch launchers and report in a day.

I was using the default OnePlus launcher when the issues began. I will switch to Nova Launcher and report.

________________________________

**Comment by papjul** [comment]
Duplicate of #992
