### ISSUE TITLE
[NWS] Reverse geocoding is incorrect

### ISSUE THREAD

**Issue by Slusho64** [breezy-weather/breezy-weather#1065]
### Steps to reproduce

I downloaded the app from the GitHub and set it up with precise location access all the time. I was sitting in the middle of Manhattan.

### Expected behavior

It should show New York as the current location.

### Actual behavior

It shows Hoboken as the current location.

### Weather source used

NWS

### Breezy Weather version

5.2.3

### Android version

Android 14

### Device

Samsung Galaxy S24 Ultra

### Other details

I do not have this problem with any other apps, including three other weather apps I was testing on the same day and at the same location. I tried removing the permission, restarting the app, removing the Current Location location, etc. I am not using a VPN.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open OR closed issue.
- [X] I checked that my issue is not covered in the [Frequently Asked Questions](https://github.com/breezy-weather/breezy-weather/blob/main/HELP.md) document.
- [X] I have updated the app to **[version 5.2.3 or later](https://github.com/breezy-weather/breezy-weather/releases/latest)** and I can reproduce the issue in this version.
- [X] I wrote my request in English, and any screenshot I attached are also in English (language can be changed from Settings > Appearance), unless my issue only happens with a specific language. I can write in my native language under the English text, if necessary.
- [X] I understand that this app is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY, so I may not get a positive reply to my request, if any at all.

**Comment by papjul** [comment]
1. Which weather apps with NWS support do you use?
2. Can you reproduce with other sources with reverse geocoding support?

**Comment by Slusho64** [comment]
Okay I didn't realize this was an issue with the NWS source. To answer your questions:

1. Today Weather simply shows "New York" while using NWS.
2. Switching to AccuWeather, it accurately shows my current location (Chelsea, Midtown, etc depending on where in the city I currently am). (As a side note, I have to restart the app to get rid of the location name if switching to Open-Meteo and I assume other sources without reverse geocoding.) 

So now I'm wondering if the data is accurate to my location and it's just the name that is wrong or if both are wrong. Also, I'm not sure why there's a big difference in the data between Open-Meteo and NWS when the Open-Meteo website says that it uses national weather services. The reason I chose NWS is that most people online seem to think NOAA is the most accurate vs others like AccuWeather, although I haven't seen a lot of talk about things like Open-Meteo. So I'm not sure which is truly best and which I should ultimately be using.

**Comment by papjul** [comment]
> Today Weather simply shows "New York" while using NWS.

It's not open source so I can't check, but I seemed to understand that they didn't use NWS reverse geocoding, but another one.

Regarding NWS reverse geocoding, you can see that for coordinates 40.7455, -73.9978 which is a point on Manhattan island, it shows Hoboken: https://api.weather.gov/points/40.7455,-73.9978

![image](https://github.com/breezy-weather/breezy-weather/assets/1449159/d4ec1521-95f3-4cb3-8b2f-aed06fc991a2)

I will close the issue as there is nothing we can do on our side. You should report this issue to [nco.ops@noaa.gov](mailto:nco.ops@noaa.gov) with the example of link above.

> So now I'm wondering if the data is accurate to my location and it's just the name that is wrong or if both are wrong.

Only the reverse geocoding is incorrect. But there is not that much difference between Manhattan weather and Hoboken weather. NWS weather is made on a 2,5 km x 2,5 km grid, so the two grids are probably next to each other.

> The reason I chose NWS is that most people online seem to think NOAA is the most accurate vs others like AccuWeather, although I haven't seen a lot of talk about things like Open-Meteo. So I'm not sure which is truly best and which I should ultimately be using.

You can see that NWS scores slightly better in New York City: https://forecastadvisor.com/NewYork/NewYork/10170/

The difference of % between sources using NWS data is mostly the weather icon from my understanding, the data shouldn't be different.

AccuWeather has a proprietary algorithm on top of NWS data from my understanding. Open-Meteo uses NWS raw data.
