### ISSUE TITLE
Meteogalicia source (Galician meteorology agency)

### ISSUE THREAD

**Issue by appuchias** [breezy-weather/breezy-weather#1066]
### Link to publicly available documentation of the API

https://meteo-estaticos.xunta.gal/datosred/infoweb/meteo/proxectos/meteosix/API_MeteoSIX_v4_gl.pdf

### Available and not available data

Available: Sky status, temperature, humidity, wind, precipitation, cloud cover, sea-level pressure and snow cover
Also, on sea spots: wave period, wave bearing, wave height, water temperature, salinity, 

### Are you going to develop yourself the new source for the app?

No, as I don't know Kotlin

### Give a bit more details or context about this source

This source has very accurate data in Galicia, and it's ran by the local administration.
It requires a free API key that has to be requested by sending an email to: administracion-web.meteogalicia@xunta.gal.

The API info homepage is the following: https://www.meteogalicia.gal/web/modelos-numericos/meteosix
The API base URL is: https://servizos.meteogalicia.es/apiv4/

### Acknowledgements

- [X] I have searched [the existing sources](https://github.com/breezy-weather/breezy-weather/blob/main/docs/SOURCES.md) and [the existing new source requests](https://github.com/breezy-weather/breezy-weather/issues?q=is%3Aissue+label%3A%22New+source%22+no%3Amilestone+-label%3ADuplicate) and this is a new source, **NOT** a duplicate or related to another open OR closed issue.
- [X] This source has a free-tier available (not a trial period), and if it is a main weather source, it includes free hourly forecast
- [X] I understand there may be technical limitations that may prevent implementing this source (for example, the lack of coordinates information)
- [X] This source does not require sensitive information (billing info, phone number, etc) to subscribe to the free-tier
- [X] I wrote my request in English. I can write in my native language under the English text, if necessary.
- [X] I understand that this app is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY, so I may not get a positive reply to my request, if any at all.

**Comment by delthia** [comment]
Another option from the same source is this: https://www.meteogalicia.gal/web/rss-georss-json
They don't call it an api, but most of the prediction and observation data exists there.

I also can't help with the kotlin side of things, but otherwise I'd be happy to help.

**Comment by papjul** [comment]
Is there a documentation... in English?

Isn't there a more automated way to register than writing an email (in galego I guess?)?

The rss-georss-json requires an id cancello, is there a web service that can return the nearest cancello from a longitude and latitude?

**Comment by delthia** [comment]
The only way to get the key is through the email. And now that you mention it, it is true that it doesn't geocode, there is a table to join the id with the name, so it could work by searching the place but not with location.
The API (the part that requires and API key) does allow you to do that.

**Comment by appuchias** [comment]
I'm not really sure about the English documentation.

Registration emails can be in other languages, I sent mine in Spanish and there were no problems.
A template email could be provided for easier registration, something like [this](mailto:administracion-web.meteogalicia@xunta.gal?subject=Solicitude%20clave%20API&body=Bo%20día,%0AGustaríame%20dispor%20dunha%20clave%20para%20a%20API.%0A%0AGrazas%20de%20antemán.).
- Subject: API key request
- Body:
```
Hi,
I'd like to get an API key.

Thanks in advance.
```


Regarding the translation from coords to concello, I think Nominatim would be fine, using their reverse search endpoint documented [here](https://nominatim.org/release-docs/develop/api/Reverse/), the concello would be in address>municipality (I think)

**Comment by papjul** [comment]
> Regarding the translation from coords to concello, I think Nominatim would be fine, using their reverse search endpoint documented [here](https://nominatim.org/release-docs/develop/api/Reverse/), the concello would be in address>municipality (I think)

We don't mix up sources. The concello must be provided by the weather source as there is no reason to think that an external source such as Nominatim would be in sync with a meteorological service. Also, Nominatim doesn't provide the mandatory timezone field (although for Spain, it could be hardcoded).

I need to take a closer look as the documentation isn't in English but it may be possible to get weather for specific longitude/latitude with the API.

**Comment by papjul** [comment]
It looks like the API indeed accepts longitude and latitude, so it's fine.

>> Are you going to develop yourself the new source for the app?
>
> No, as I don't know Kotlin

If you have programming experience in other languages, it will be straightforward. Most of the work has been abstracted, you can just look at existing sources. It's also documented here: https://github.com/breezy-weather/breezy-weather/blob/main/CONTRIBUTE.md#weather-sources

Otherwise, I can put it in "Open to contributions" but there is a high chance no one will pick it up. While variables are written in English in the API, there are point of attentions written in galego that the developer must read, so it restricts the implementation to something who can read and understand it.

Can you also give us the rate-limit of the API per API key? If this information is not public, can you write to them and ask them? Thanks!

**Comment by appuchias** [comment]
Once May ends I'll take a look at the existing sources and try to adapt one of them following the docs you provided if I can.

> Can you also give us the rate-limit of the API per API key? If this information is not public, can you write to them and ask them? Thanks!

I'm pretty sure it isn't rate-limited, it doesn't mention it in the API manual PDF and there isn't any response as "Too many requests" in pages 68 or 69.
The RSS/GeoRSS/JSON option mentioned by delthia doesn't requre a key, so I guess it isn't limited either.
