### ISSUE TITLE
WetterOnline

### ISSUE THREAD

**Issue by Wh1teT1ger55** [breezy-weather/breezy-weather#1068]
### Link to publicly available documentation of the API

https://wetteronline.readthedocs.io/de/latest/install.html

### Available and not available data

Available:
 - Weather
 - Temperature 
 - Probability of rain
 - Air pressure
 - Relative humidity
 - Wind speed
 - Sunrise/sunset time
 - Pollen count
 - Severe weather warnings
 
Not Available:
 - Air quality

### Are you going to develop yourself the new source for the app?

open to contributions

### Give a bit more details or context about this source

Before I found Breezy Weather, I was always using wetteronline.de, which predicted the weather with 99% accuracy. When I switched to Breezy Weather, I was initially impressed by the design and features. However, over time, I noticed that the weather data (regardless of the provider) was often incorrect.

I'm not sure if it's possible to integrate the wetteronline.de API into the app, but I would really appreciate it. Otherwise, I think I will have to stop using your App.

### Acknowledgements

- [X] I have searched [the existing sources](https://github.com/breezy-weather/breezy-weather/blob/main/docs/SOURCES.md) and [the existing new source requests](https://github.com/breezy-weather/breezy-weather/issues?q=is%3Aissue+label%3A%22New+source%22+no%3Amilestone+-label%3ADuplicate) and this is a new source, **NOT** a duplicate or related to another open OR closed issue.
- [X] This source has a free-tier available (not a trial period), and if it is a main weather source, it includes free hourly forecast
- [X] This source does not require sensitive information (billing info, phone number, etc) to subscribe to the free-tier
- [X] I understand there may be technical limitations that may prevent implementing this source (for example, the lack of coordinates information)
- [X] I wrote my request in English. I can write in my native language under the English text, if necessary.
- [x] I understand that this app is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY, so I may not get a positive reply to my request, if any at all.

**Comment by papjul** [comment]
Your link is invalid, it's an unofficial python library, we don't use this language.

Also, I don't see the point of this source? Why not use the DWD source directly since it's the same data?

**Comment by Wh1teT1ger55** [comment]
Sure, here is the text in English:

---

That's a pity. I'm not that familiar with APIs, so sorry about the suggestion.

However, the weather data is different. Here is a comparison between Wetteronline and BrightSky:

![Screenshot_20240522_184304_Brave](https://github.com/breezy-weather/breezy-weather/assets/125185383/a1b22206-ea0d-4ead-8f84-ff3da87c431c)
![Screenshot_20240522_184336_Breezy Weather](https://github.com/breezy-weather/breezy-weather/assets/125185383/c4cd60de-237d-4b03-871f-1adff5da2de0)
![Screenshot_20240522_184406_Brave](https://github.com/breezy-weather/breezy-weather/assets/125185383/7dc27cab-8827-4da1-bf3c-917442bc3916)
![Screenshot_20240522_184429_Breezy Weather](https://github.com/breezy-weather/breezy-weather/assets/125185383/bc67d353-d00f-448d-907b-8053f900fa71)

**Comment by papjul** [comment]
Regarding daily information, max/min temperature (which I believe WetterOnline website uses) is different from max temperature of the daytime period and min temperature of the overnight period. If that's the case, the values will always be different.

Regarding hourly information, it looks like Bright Sky is more accurate, right?

> That's a pity. I'm not that familiar with APIs, so sorry about the suggestion.

I will proceed to close then. I didn't find any API, feel free to reopen an issue if necessary. Even the Python package is not able to get weather for a longitude/latitude, only by name. Which is a problem, when you're looking for weather for Paris, Texas, and you get instead Paris, France. That's why we need to talk with longitude and latitude.
