### ISSUE TITLE
[location list] Automatically show keyboard when opening location search

### ISSUE THREAD

**Issue by min7-i** [breezy-weather/breezy-weather#108]
### Describe your suggested feature

Currently, two taps are needed to actually search for a location.

I'd suggest to directly select the location search input field and to show the keyboard when tapping the magnifying glass icon.

| tap 1 | tap 2 |
| --- | --- |
| ![Image_2](https://github.com/breezy-weather/breezy-weather/assets/97251923/54b976c8-63b8-44e4-b8ef-27dd44d2922f) | ![Image_1](https://github.com/breezy-weather/breezy-weather/assets/97251923/d92675c6-3ab2-480b-8a82-bb123b85f7ae) |

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to **[latest version](https://github.com/breezy-weather/breezy-weather/releases/latest)**.

**Comment by papjul** [comment]
I don’t believe that’s a good idea, as I believe user should select its weather provider before typing anything.
If you open the keyboard, then you suggest the user to search and then change weather provider, which feels less intuitive to me.

**Comment by papjul** [comment]
Won't fix this issue, but may be improved when redesigning search page in #139
