### ISSUE TITLE
API requests limit reached

### ISSUE THREAD

**Issue by theLord-81** [breezy-weather/breezy-weather#1096]
### Steps to reproduce

Just` installed the latest version from GitHub
Added a new weather location
The app is showing this message "API requests limit reached" 

### Expected behavior

Retrieve weather data for the requested location. 

### Actual behavior

The app is showing this message "API requests limit reached" 

### Weather source used

Open Weather

### Breezy Weather version

5.2.4

### Android version

Android 10

### Device

OnePlus 6

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open OR closed issue.
- [X] I checked that my issue is not covered in the [Frequently Asked Questions](https://github.com/breezy-weather/breezy-weather/blob/main/HELP.md) document.
- [X] I have updated the app to **[version 5.2.4 or later](https://github.com/breezy-weather/breezy-weather/releases/latest)** and I can reproduce the issue in this version.
- [X] I wrote my request in English, and any screenshot I attached are also in English (language can be changed from Settings > Appearance), unless my issue only happens with a specific language. I can write in my native language under the English text, if necessary.
- [X] I understand that this app is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY, so I may not get a positive reply to my request, if any at all.

**Comment by papjul** [comment]
Tap the "Help" button

**Comment by papjul** [comment]
There is also a more detailed explanation in the Frequently Asked Questions document that you read
