### ISSUE TITLE
air quality units text cuts off with system display screen zoom

### ISSUE THREAD

**Issue by mirror176** [breezy-weather/breezy-weather#1097]
### Steps to reproduce

Set system>display>screen zoom to the right of center
View air quality on vertical phone orientation.

### Expected behavior

Text area should be resized to fit such small text.

### Actual behavior

With units as ug/m^3 it cuts off the right side of the text with an ellipses instead of resizing the text area on all but the shortest lines. Becomes left aligned instead of right aligned when cutoff. "1 ug/m^3" fit while "6.6 ug/m^3" did not.

### Weather source used

open-meteo

### Breezy Weather version

5.2.4

### Android version

Android 13

### Device

Samsung Galaxy S20 FE 5G

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open OR closed issue.
- [X] I checked that my issue is not covered in the [Frequently Asked Questions](https://github.com/breezy-weather/breezy-weather/blob/main/HELP.md) document.
- [X] I have updated the app to **[version 5.2.4 or later](https://github.com/breezy-weather/breezy-weather/releases/latest)** and I can reproduce the issue in this version.
- [X] I wrote my request in English, and any screenshot I attached are also in English (language can be changed from Settings > Appearance), unless my issue only happens with a specific language. I can write in my native language under the English text, if necessary.
- [X] I understand that this app is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY, so I may not get a positive reply to my request, if any at all.

**Comment by papjul** [comment]
A screenshot is worth a thousand words 😁
Could you show what you see vs what you expect so we avoid any misunderstanding? Thanks!
