### ISSUE TITLE
Wind speed gets cut off if there are 4 details in header

### ISSUE THREAD

**Issue by elydpg** [breezy-weather/breezy-weather#1103]
### Steps to reproduce

1. If there are fewer than 4 details in the header, add details until there are more than 4
2. Notice that the wind speed will be cut off

### Expected behavior

Everything should be readable in the header. For example there is no problem when there are only 3 details visible in the header, as in this image
![20240609_113924](https://github.com/breezy-weather/breezy-weather/assets/8622264/d20eb019-904d-4451-8a18-44e9df736e7e)

### Actual behavior

The wind speed gets cut off because it does not fit in its allocated space  
![20240609_113955](https://github.com/breezy-weather/breezy-weather/assets/8622264/fb02faef-e883-47d9-839c-f4035e345f83)  
Note that I'm using km/h in this example but it also happens with the default m/s (more often due to the increased precision) and presumably other units as well

### Weather source used

N/A

### Breezy Weather version

5.2.4 standard

### Android version

12

### Device

Samsung Galaxy s10e

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open OR closed issue.
- [X] I checked that my issue is not covered in the [Frequently Asked Questions](https://github.com/breezy-weather/breezy-weather/blob/main/HELP.md) document.
- [X] I have updated the app to **[version 5.2.4 or later](https://github.com/breezy-weather/breezy-weather/releases/latest)** and I can reproduce the issue in this version.
- [X] I wrote my request in English, and any screenshot I attached are also in English (language can be changed from Settings > Appearance), unless my issue only happens with a specific language. I can write in my native language under the English text, if necessary.
- [X] I understand that this app is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY, so I may not get a positive reply to my request, if any at all.

**Comment by papjul** [comment]
Yes, it's an expected behavior. If you have a too small screen or accessibility settings enabled, you can either keep only 3 items or ignore that you can't read km/h, or switch to Bf unit. You might also want to follow #738

**Comment by elydpg** [comment]
I see also this is a dupe of #771. Hopefully #738 will resolve it :)
