### ISSUE TITLE
Sun and moon card display is inconsistent

### ISSUE THREAD

**Issue by elydpg** [breezy-weather/breezy-weather#1104]
### Breezy Weather version

5.2.4 standard

### Android version

12

### Device

Samsung Galaxy s10e

### Other details

This is a more general issue outlining the inconsistencies in the way that the data in the "Sun and moon" card is presented. 

As a normal, working as intended example, here is midday in Tel Aviv, Israel:  
![20240609_124459](https://github.com/breezy-weather/breezy-weather/assets/8622264/e6865033-3582-4b77-a7fd-7cbe57adaa22)

Here is Toronto, Canada in the early morning before sunrise and moonrise. As I would expect, the sun and moon simply do not appear:  
![20240609_114604](https://github.com/breezy-weather/breezy-weather/assets/8622264/1e197c0a-d90d-4457-9a6b-377a31091245)

Here is Auckland, New Zealand after sunset and after moonset. I would have expected it to look as in the previous picture, but instead the sun and moon are stuck on the end of the screen:  
![20240609_115728](https://github.com/breezy-weather/breezy-weather/assets/8622264/7bb4f149-7e82-45a6-8fae-6cdbd20ee3a7)

And here is Adelaide, Australia after sunset but before moonset. Same issue but it illustrates that moon and sun are getting stuck independently:  
![20240609_115749](https://github.com/breezy-weather/breezy-weather/assets/8622264/1dff3842-0117-44fa-8928-45f194a96c4f)

And then there's the whole mess of what happens in the high arctic. There seems to be no consistency here location to location.

In Svalbard, it shows sunrise and sunset at 01:00, and the sun doesn't even render for some reason. Moonrise and moonset appear from midnight to 23:59:  
![20240609_123132](https://github.com/breezy-weather/breezy-weather/assets/8622264/92d94cd5-1eb4-4650-91d8-1721eed66b0e)

In Alert, Canada it shows sunrise and sunset at 19:00, and moonrise and moonset are as in Svalbard (Note that I'm using Open Meteo here and not ECCC, see upcoming issue). Weirdly the sun path renders but no sun once again and it's put in night mode, even though it's the arctic and the sun is shining:  
![20240609_123154](https://github.com/breezy-weather/breezy-weather/assets/8622264/3a389c9b-9636-4f0f-b4f2-98e8c16a892f)

Finally this is I believe Barrow, Alaska, USA. Sun and moon are both from 00:00 to 23:59 and are rendering in the exact same spot:
![20240609_123202](https://github.com/breezy-weather/breezy-weather/assets/8622264/19618e5d-95dd-4938-9373-1d712626e402)

I think this is largely caused by the app assuming that every calendar day has exactly one sunrise and one sunset, in that order, which is a false assumption. It's also false for moonrise and moonset obviously, which will probably be something that more users experience especially as we head into the first quarter.

I'm not sure exactly how to fix this in code, but here are all of the logical possibilities for a given calendar day:

1. There are no sunsets or sunrises. In this case, it needs to be determined another way whether it is day or night in order to apply the theme accordingly. It might not make sense to render the sun in this case, even during daytime. 
2. There is exactly one sunrise. In this case the time before sunrise is night time and no sun should be rendered. After sunrise, render the sun in position based on the time until the earliest sunset in the next calendar day. 
3. There is exactly one sunset. In this case the time after sunset is night time, so no sun render, and before sunset render the sun in position based on the time since the latest sunrise in the previous calendar day.
4. There is sunrise followed by sunset. This is the typical case; after sunset and before sunrise is night time, in between is daytime. Render the sun accordingly. 
5. There is sunset followed by sunrise. In this case the time between sunset and sunrise is night time so no render. The time before sunset is daytime so do as in case 3, and the time after sunrise is also daytime so do as in case 2
6. There is sunset followed by sunrise followed by sunset. In this case do as in case 3 before the first sunset, otherwise do as in case 4. 
7. There is sunrise followed by sunset followed by sunrise. In this case do as in case 2 after the last sunrise, otherwise do as in case 4. 

The same logic applies to the moonrise and moonset, with the exception that there is no need to determine the theme, only the moon render position. I'm fairly sure as well that cases 6 and 7 don't happen for the moon, as the period between moonrises and moonsets is always about 25 hours. But it never hurts to be fully comprehensive 😅

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open OR closed issue.
- [X] I checked that my issue is not covered in the [Frequently Asked Questions](https://github.com/breezy-weather/breezy-weather/blob/main/HELP.md) document.
- [X] I have updated the app to **[version 5.2.4 or later](https://github.com/breezy-weather/breezy-weather/releases/latest)** and I can reproduce the issue in this version.
- [X] I wrote my request in English, and any screenshot I attached are also in English (language can be changed from Settings > Appearance), unless my issue only happens with a specific language. I can write in my native language under the English text, if necessary.
- [X] I understand that this app is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY, so I may not get a positive reply to my request, if any at all.

**Comment by papjul** [comment]
Please fill in every field in the template, notably the weather source. Please respect the "one bug = one issue" and "one suggestion = one idea". Please give more details: at what time of the location you screenshot you notice the behavior.

**Comment by elydpg** [comment]
It might be worth reopening this due to #1105. The reason I didn't add the weather source is that they are all clearly visible in the screenshots, and these issues seem to happen across multiple different sources. I perhaps could have specified each example's source in the text if that is more clear. But it's not just one source

**Comment by papjul** [comment]
Each source is computed differently, so yes, I need the details, and I believe most of what you report are not bugs but suggestions of changes ;)

**Comment by elydpg** [comment]
Hmm so what you're saying is since each source computes the sun and moon times differently then each source should be a different bug report? In that case I'll copy this comment over into an idea and make bug reports for each source individually. Unfortunately, without direct API access it's hard to do a lot of comprehensive testing per source, except maybe for Open Meteo so I'll probably make a new issue based on how Open Meteo handles it. Of course there is already the issue for Environment Canada which is separate because it causes a parse error.

**Comment by elydpg** [comment]
See #1106
