### ISSUE TITLE
Failed to parse weather data from Environment and Climate Change Canada

### ISSUE THREAD

**Issue by elydpg** [breezy-weather/breezy-weather#1105]
### Steps to reproduce

1. Try to add a location from the Canadian high arctic (examples: Alert, Resolute)

### Expected behavior

It should add normally. Places below the arctic circle, like Iqaluit, are added normally. 

### Actual behavior

"Failed to parse weather data" issue instead. The FAQ specifically states to report such issues

### Weather source used

Environment and Climate Change Canada

### Breezy Weather version

5.2.4 standard

### Android version

12

### Device

Samsung Galaxy s10e

### Other details

I suspect that this issue is related to #1106, as the locations that fail to add are all above the arctic circle, and so are currently experiencing all-day sunlight. My guess is that Environment Canada is providing that sun and moon data in a way that Breezy Weather is not expecting. 

Screenshot examples:
![Screenshot_20240609-131618_Breezy Weather](https://github.com/breezy-weather/breezy-weather/assets/8622264/45cfb154-2932-4cd0-800b-6e74c0d556de)
![Screenshot_20240609-122127_Breezy Weather](https://github.com/breezy-weather/breezy-weather/assets/8622264/f20e1dcc-cdee-4f92-b32f-3b0b3aab6d75)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open OR closed issue.
- [X] I checked that my issue is not covered in the [Frequently Asked Questions](https://github.com/breezy-weather/breezy-weather/blob/main/HELP.md) document.
- [X] I have updated the app to **[version 5.2.4 or later](https://github.com/breezy-weather/breezy-weather/releases/latest)** and I can reproduce the issue in this version.
- [X] I wrote my request in English, and any screenshot I attached are also in English (language can be changed from Settings > Appearance), unless my issue only happens with a specific language. I can write in my native language under the English text, if necessary.
- [X] I understand that this app is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY, so I may not get a positive reply to my request, if any at all.

**Comment by papjul** [comment]
Fixed in 5f48cd41960e0482f9c5c615a9dde03a0f6c2988
