### ISSUE TITLE
IMS: Incorrect UV Index categories

### ISSUE THREAD

**Issue by elydpg** [breezy-weather/breezy-weather#1108]
### Steps to reproduce

1. Add a location in Israel sourced from the Israel Meteorological Service
2. Check the hourly UV index forecast and look for a time when the UV index is equal to 6

### Expected behavior

It should appear orange indicating a "High" UV index, in line with the [WHO standard][1]

[1]: https://www.who.int/news-room/questions-and-answers/item/radiation-the-ultraviolet-(uv)-index

### Actual behavior

It appears yellow indicating a "Moderate" UV index

### Weather source used

Israel Meteorological Service

### Breezy Weather version

5.2.4 standard

### Android version

12

### Device

Samsung Galaxy s10e

### Other details

This is probably not a bug with Breezy Weather, but I'm reporting here just in case. Compare the Open-Meteo UV index with the IMS:
![Screenshot_20240610-105555_Breezy Weather](https://github.com/breezy-weather/breezy-weather/assets/8622264/4b3b5ff6-664e-4496-b24a-d03cb0c6bba3)
![Screenshot_20240610-105514_Breezy Weather](https://github.com/breezy-weather/breezy-weather/assets/8622264/d4d00039-8de5-429f-8ac1-4c6f7156d80c)

This miscategorization seems to contradict [the IMS's own website](https://ims.gov.il/en/UVIHourly) which says that 6 is "High" and 8 is "Very High". Here, IMS says that 8 is "High":  
![Screenshot_20240610-120744_Breezy Weather](https://github.com/breezy-weather/breezy-weather/assets/8622264/de43b6a3-c35e-4e40-b69f-1c72eaf50688)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open OR closed issue.
- [X] I checked that my issue is not covered in the [Frequently Asked Questions](https://github.com/breezy-weather/breezy-weather/blob/main/HELP.md) document.
- [X] I have updated the app to **[version 5.2.4 or later](https://github.com/breezy-weather/breezy-weather/releases/latest)** and I can reproduce the issue in this version.
- [X] I wrote my request in English, and any screenshot I attached are also in English (language can be changed from Settings > Appearance), unless my issue only happens with a specific language. I can write in my native language under the English text, if necessary.
- [X] I understand that this app is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY, so I may not get a positive reply to my request, if any at all.

**Comment by papjul** [comment]
I don't have an UV index of 8 with the cities you mention, but I believe 82b05538147e4af92ab66b7f1796ce84f678a5f1 would fix it
