### ISSUE TITLE
Open-Meteo: Incorrect UV Index categories 

### ISSUE THREAD

**Issue by elydpg** [breezy-weather/breezy-weather#1110]
### Steps to reproduce

1. Add a location sourced from Open-Meteo
2. Check the hourly UV index forecast and look for a time when the UV index is equal to 8

### Expected behavior

It should appear red indicating a "Very High" UV index, in line with the [WHO Standard][1]

[1]: https://www.who.int/news-room/questions-and-answers/item/radiation-the-ultraviolet-(uv)-index

### Actual behavior

It appears orange indicating a "Very high" 

### Weather source used

Open-Meteo

### Breezy Weather version

5.2.4 standard

### Android version

12

### Device

Samsung Galaxy s10e

### Other details

Unlike #1108 I do actually think this is a Breezy Weather bug, as Open-Meteo does not provide any categories with its UV indices. 
![Screenshot_20240610-105555_Breezy Weather](https://github.com/breezy-weather/breezy-weather/assets/8622264/cd390a0e-8c4d-46b8-a547-afac0c1160ef)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open OR closed issue.
- [X] I checked that my issue is not covered in the [Frequently Asked Questions](https://github.com/breezy-weather/breezy-weather/blob/main/HELP.md) document.
- [X] I have updated the app to **[version 5.2.4 or later](https://github.com/breezy-weather/breezy-weather/releases/latest)** and I can reproduce the issue in this version.
- [X] I wrote my request in English, and any screenshot I attached are also in English (language can be changed from Settings > Appearance), unless my issue only happens with a specific language. I can write in my native language under the English text, if necessary.
- [X] I understand that this app is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY, so I may not get a positive reply to my request, if any at all.

**Comment by papjul** [comment]
Categories are always calculated on app side, regardless of whether the source provides it.

Open-Meteo has a specificity: it provides non-rounded values of UV. Meaning, that you can end up with an UV of 7.99 that will be rounded to 8, but will be in the lower category.

I suggest we follow the issue in #1108 with any source but Open-Meteo due to this specificity.

**Comment by elydpg** [comment]
So this might actually be a rounding issue, as Open-Meteo supplies fractional UV indices but the WHO categories are only specified for integer values. Note this Open-Meteo example for Eilat, which has both "High" and "Very High" for UV index 8:
![Screenshot_20240610-124742_Breezy Weather.png](https://github.com/breezy-weather/breezy-weather/assets/8622264/7c0ea619-2dd7-47d9-8517-e23c39611f8c)

It seems that the categories are defined based on the integer part, while the number itself is rounded. I'm not sure if this is intentional, but I think it makes more sense to round first and then calculate the category. Honestly not sure though 🤷

**Comment by elydpg** [comment]
> Open-Meteo has a specificity: it provides non-rounded values of UV. Meaning, that you can end up with an UV of 7.99 that will be rounded to 8, but will be in the lower category.

yep I just realized this is the issue. Don't know the "correct" way to handle this tbh

**Comment by elydpg** [comment]
Assuming that #1108 is also caused by rounding issues, what should be done? Should I rename that issue?

**Comment by papjul** [comment]
No, #1108 is different, they only provide rounded values, and they provide hourly values.

Unrounded values should not exist, but in case we have them, we must provide the correct category for the unrounded values, not for the rounded value IMO.

**Comment by papjul** [comment]
Very high starts at 8.0 on my side, not at 7.01.

I believe that if Open-Meteo has values with decimals, it means that in the way you compute it, you end up with decimals at some point. So if you can find some WHO guidelines about the rounding policy, I will apply it if different than ours. Maybe 7.99 is expected to be truncated to 7.0 for example?

**Comment by elydpg** [comment]
I couldn't find any rounding information unfortunately. But it seems your rounding convention has precedent: The city of Hong Kong measures [UV index with decimals](https://www.hko.gov.hk/en/wxinfo/uvinfo/uvinfo.html) and uses the same rounding convention:  
![10 Jun 2024 15-minute _mean UV Index.png](https://github.com/breezy-weather/breezy-weather/assets/8622264/affe8d0b-bffb-4d2d-bb01-ee3589570152)

**Comment by papjul** [comment]
And Hong Kong is where the World Meteorological Organization is located, so I will trust them. Maybe we should show 1 decimal then? Although it still wouldn't fix the 7.95-7.99 case.
