### ISSUE TITLE
Sun and moon not rendering correctly after setting

### ISSUE THREAD

**Issue by elydpg** [breezy-weather/breezy-weather#1116]
### Steps to reproduce

1. Add a location after sunset and moonset

### Expected behavior

Expected no celestial bodies to show up because the sun and moon have already set

### Actual behavior

The sun and moon rendered on top of each other

### Weather source used

Open-Meteo, MET-Norway, Meteo-France, DMI, IMS, probably others

### Breezy Weather version

5.2.4 standard

### Android version

12

### Device

Samsung Galaxy s10e

### Other details

The behaviour seems to depend on weather source: The following are a series of test cases with different sources for the city of Auckland, New Zealand:

Open-Meteo renders the sun on top of the moon, both at the end of the curve:

![Screenshot_20240610-143102_Breezy Weather](https://github.com/breezy-weather/breezy-weather/assets/8622264/b8a7d2df-c81c-4aac-8c3d-0210f6cac5e7)

MET-Norway and DMI do the same thing:

![Screenshot_20240610-143127_Breezy Weather](https://github.com/breezy-weather/breezy-weather/assets/8622264/ad3422f1-ad1f-4d05-972d-dfbd39af0017)
![Screenshot_20240610-143213_Breezy Weather](https://github.com/breezy-weather/breezy-weather/assets/8622264/f6bdfbc5-a470-4ff9-88c1-f7d567d5f9ca)

As does the IMS, but ~~I will post an example of that later as that requires an Israeli location~~ Update: Here is an IMS Example in Tel Aviv:

![Screenshot_20240610-233558_Breezy Weather.png](https://github.com/breezy-weather/breezy-weather/assets/8622264/de148844-dac1-4f73-8c40-0b5df036a322)

Meteo-France correctly shows the moon (although the moonrise time is different from the others) unrendered but still renders the sun:

![Screenshot_20240610-143142_Breezy Weather](https://github.com/breezy-weather/breezy-weather/assets/8622264/175b3333-1239-4221-89a6-3db44b8551b2)

Interestingly, AccuWeather renders everything correctly, but the moonrise and moonset times are quite different from the others:

![Screenshot_20240610-143242_Breezy Weather](https://github.com/breezy-weather/breezy-weather/assets/8622264/030c7122-8e4b-4d30-be42-90bc65858d6d)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open OR closed issue.
- [X] I checked that my issue is not covered in the [Frequently Asked Questions](https://github.com/breezy-weather/breezy-weather/blob/main/HELP.md) document.
- [X] I have updated the app to **[version 5.2.4 or later](https://github.com/breezy-weather/breezy-weather/releases/latest)** and I can reproduce the issue in this version.
- [X] I wrote my request in English, and any screenshot I attached are also in English (language can be changed from Settings > Appearance), unless my issue only happens with a specific language. I can write in my native language under the English text, if necessary.
- [X] I understand that this app is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY, so I may not get a positive reply to my request, if any at all.

**Comment by papjul** [comment]
> Interestingly, AccuWeather renders everything correctly, but the moonrise and moonset times are quite different from the others

When the sun or moon sets, it stays at the end of the course, to make the difference with "not risen yet". At least, that's how I believe the UI designer intended it to be. I will update the documentation.

As for the cases where sun or moon don't remain at the end, it's because they are on a different day. For example, I'm pretty sure AccuWeather shows you data for next day (hence why you see very different values). I believe we could investigate it in a different issue if necessary.

**Comment by elydpg** [comment]
> The card is working on a daily basis. The app will look for today ephemeris data, so there is a difference between "not risen yet for this day" and "not risen yet for next day". So it makes sense when you look at it from today point of view.

Ah I see then. So perhaps you could distinguish "already set today" by keeping the thick outline of the sun's path but not actually rendering it? That way you don't have the sun awkwardly sitting there on top of the moon lol. Speaking of the moon, maybe it could get its own arc so as not to conflict with the sun? Ofc these are already separate issues...

> More generally regarsing the issues you report, you seem very passionated about astronomy, and I encourage you to use a dedicated app for that purpose, as they will do it much better than a weather app doing it just for convenience ;)

You are correct 😅 fortunately I already do have dedicated apps for that and I'm always on the lookout for more! I just really like the careful and meticulous attention to detail found in this app and I want to carry that over into the sun and moon card ☺️ Not to mention it also affects the theming and we wouldn't want to show the wrong theming now 🤭

**Comment by papjul** [comment]
> perhaps you could distinguish "already set today" by keeping the thick outline of the sun's path but not actually rendering it? That way you don't have the sun awkwardly sitting there on top of the moon lol. Speaking of the moon, maybe it could get its own arc so as not to conflict with the sun? Ofc these are already separate issues...

I'm not an UI designer, I have no idea how to change even little things without spending countless days on it. On top of that, I don't see a reason to change something people have been familiar with, with no complaints in years, but you can always suggest a pull request. And even if it's not accepted, you can still re-use it in your own app as part of #863. Anyway, changes to ephemeris card UI will not be worked on.

**Comment by elydpg** [comment]
Thanks for the documentation clarification 😌 tbf I'm not a UI designer either so I'd have just as much pain with that 😅 I think AccuWeather and Meteo-France not giving the right data is a problem though, so even though it says sources may vary I do want to figure out what is going on with those sources
