### ISSUE TITLE
Moon not appearing after midnight if moonset is after midnight

### ISSUE THREAD

**Issue by elydpg** [breezy-weather/breezy-weather#1117]
### Steps to reproduce

1. Add a location with moonset after midnight that is currently after midnight but before moonset

### Expected behavior

Moon should render in its proper path along the sky

### Actual behavior

Moon does not appear

### Weather source used

Open-Meteo, NWS, probably others

### Breezy Weather version

5.2.4 standard

### Android version

12

### Device

Samsung Galaxy s10e

### Other details

Examples:

Reykjavik, Iceland, source Open-Meteo

![Screenshot_20240610-030610_Breezy Weather](https://github.com/breezy-weather/breezy-weather/assets/8622264/3c91d286-f1f8-4e41-85ea-d89793e877f2)

Nome, Alaska, source NWS

![Screenshot_20240610-141358_Breezy Weather](https://github.com/breezy-weather/breezy-weather/assets/8622264/4818fc96-6cb1-4684-9250-2e1e1c583c3b)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open OR closed issue.
- [X] I checked that my issue is not covered in the [Frequently Asked Questions](https://github.com/breezy-weather/breezy-weather/blob/main/HELP.md) document.
- [X] I have updated the app to **[version 5.2.4 or later](https://github.com/breezy-weather/breezy-weather/releases/latest)** and I can reproduce the issue in this version.
- [X] I wrote my request in English, and any screenshot I attached are also in English (language can be changed from Settings > Appearance), unless my issue only happens with a specific language. I can write in my native language under the English text, if necessary.
- [X] I understand that this app is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY, so I may not get a positive reply to my request, if any at all.

**Comment by papjul** [comment]
> Add a location with moonset after midnight that is currently after midnight but before moonset

I think something is wrong in the wording or I don't understand it.

If I take the first screenshot: it's supposed to be 03:06, but we see no sun although it's supposed to rise at 03:02, and you expect to see the moon which isn't rising until 06:40? As for the sun, maybe it's just that you're on a different timezone with this location?

**Comment by elydpg** [comment]
> If I take the first screenshot: it's supposed to be 03:06, but we see no sun although it's supposed to rise at 03:02, and you expect to see the moon which isn't rising until 06:40?

It's 00:05; the clock in the details card is the location tz while the 03:06 is my local time 😅

**Comment by papjul** [comment]
> I should still see the moon since it's not supposed to set until 02:41 local time

As I already told you, the set time is always AFTER rise time. Meaning it's 02:41 D+1. The moon won't rise before 06:40. Well, technically, it can rise twice, but as I already told, almost all -if not all- sources show only one rise event and the first one occurring after midnight.

**Comment by elydpg** [comment]
> As I already told you, the set time is always AFTER rise time. Meaning it's 02:41 D+1. The moon won't rise before 06:40. Well, technically, it can rise twice, but as I already told, almost all -if not all- sources show only one rise event and the first one occurring after midnight.

Yes, true. That screenshot was taken on June 10 at 00:06 Iceland time, and so you're right the moonset in question was on 02:41 on June 11. Though [according to timeanddate.com](https://www.timeanddate.com/moon/iceland/reykjavik?month=6&year=2024) there was a moonset at 03:04 on June 10, so the moon was still up at 00:06 🤷

**Comment by papjul** [comment]
> Though [according to timeanddate.com](https://www.timeanddate.com/moon/iceland/reykjavik?month=6&year=2024) there was a moonset at 03:02 on June 10, so the moon was still up at 00:06 🤷

Yes, that's what I mentiomed at the end:

> Well, technically, it can rise twice, but as I already told, almost all -if not all- sources show **only one rise event and the first one occurring after midnight**.

Weather sources work like that, as they are on a day-by-day basis with only one event per day, so you need to look for an app dedicated to astronomy to get rid of that constraint ;)

**Comment by elydpg** [comment]
> Weather sources work like that, as they are on a day-by-day basis with only one event per day

In that case then it seems that this is WAI, no? I think this can be closed as WAI
