### ISSUE TITLE
Aemet source (Spain meteorology agency)

### ISSUE THREAD

**Issue by Rapou7** [breezy-weather/breezy-weather#1123]
### Link to publicly available documentation of the API

https://opendata.aemet.es/dist/index.html?

### Available and not available data

Daily Forecast ✅ Provided for 7 days in 6-hour intervals (00:00 / 12:00-18:00 / 18:00-24:00)
Hourly Forecast ✅ Provided for one and a half days
Weather Condition ✅ 
Temperature ✅ 
Precipitation Probability ✅ Provided in 6 hours intervals
Wind ✅ 
UV ✅ 
Air Quality ✅ 
Pollen ❌ Not available
Precipitation Nowcasting ❌ Not available
Alerts ✅ Weather alerts provided
Humidity ✅ 
Reverse Geocoding ✅ Provided

### Are you going to develop yourself the new source for the app?

No, i dont know kotlin, but im gonna try my best

### Give a bit more details or context about this source

This is the official source for Spain
It requires a free API key that has to be requested on their webpage: https://opendata.aemet.es/centrodedescargas/altaUsuario?
The API info homepage is the following: https://opendata.aemet.es/centrodedescargas/inicio
The API base URL is: https://opendata.aemet.es/opendata

### Acknowledgements

- [X] I have searched [the existing sources](https://github.com/breezy-weather/breezy-weather/blob/main/docs/SOURCES.md) and [the existing new source requests](https://github.com/breezy-weather/breezy-weather/issues?q=is%3Aissue+label%3A%22New+source%22+no%3Amilestone+-label%3ADuplicate) and this is a new source, **NOT** a duplicate or related to another open OR closed issue.
- [X] This source has a free-tier available (not a trial period), and if it is a main weather source, it includes free hourly forecast
- [X] This source does not require sensitive information (billing info, phone number, etc) to subscribe to the free-tier
- [X] I understand there may be technical limitations that may prevent implementing this source (for example, the lack of coordinates information)
- [X] I wrote my request in English. I can write in my native language under the English text, if necessary.
- [X] I understand that this app is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY, so I may not get a positive reply to my request, if any at all.

**Comment by papjul** [comment]
I had a look before and it seemed to me there was no way to get weather for a longitude and latitude, only by city ID, and there is no endpoint to get a city ID for a given longitude and latitude. Let me know if you find anything? In the absence

> No, i dont know kotlin, but im gonna try my best

This implies you already know programming. Kotlin is easy and we have documentation. If you already know Java or OOP, it should not be hard.

**Comment by papjul** [comment]
Ok, feel free to openna new issue if you have anything new
