### ISSUE TITLE
[AccuWeather] All days shifted when adding a city with a different day on a timezone different than system timezone

### ISSUE THREAD

**Issue by elydpg** [breezy-weather/breezy-weather#1124]
### Steps to reproduce

1. Add a city in New Zealand, like Auckland for example. Make sure the source is set to AccuWeather
2. Check the sun and moon time. Preferably, do this when is daytime in Auckland

### Expected behavior

The sun and moon times should be correct (consistent with the app documentation). If daytime, the sun should render

### Actual behavior

Incorrect data. Sun does not render

### Weather source used

Open-Meteo, AccuWeather, MET Norway, Meteo-France, possibly others

### Breezy Weather version

5.2.4 standard

### Android version

12

### Device

Samsung Galaxy s10e

### Other details

This seems to only happen when I was testing locations in New Zealand, especially with AccuWeather. It may happen in other places and with other sources but I've not checked that. I tested Open-Meteo, AccuWeather, MET Norway, Meteo-France, and DMI, for June 12 New Zealand time. 

Here is what happened for Auckland:

![Screenshot_20240611-224351_Breezy Weather](https://github.com/breezy-weather/breezy-weather/assets/8622264/1f4578a1-6743-464e-b5a5-6ea6213d6717)
![Screenshot_20240611-224419_Breezy Weather](https://github.com/breezy-weather/breezy-weather/assets/8622264/4b24367d-29d6-467f-ab54-dc1ccbd004c8)
![Screenshot_20240611-224440_Breezy Weather](https://github.com/breezy-weather/breezy-weather/assets/8622264/364cfbee-7b5e-459f-a37e-89d989c880e6)
![Screenshot_20240611-224452_Breezy Weather](https://github.com/breezy-weather/breezy-weather/assets/8622264/b5dbf3d6-6777-40fc-b4dd-a30ed6caaf50)
![Screenshot_20240611-224510_Breezy Weather](https://github.com/breezy-weather/breezy-weather/assets/8622264/843451a6-4216-491a-8e12-fc4b574ab425)

It seems that AccuWeather shows data that is different from the others: it's hard to tell with the sun data, except that the sun doesn't render, but with the moon data it is easy to check that this is the moon data for June 13, not June 12. Same thing happens in Wellington:

![Screenshot_20240611-224702_Breezy Weather](https://github.com/breezy-weather/breezy-weather/assets/8622264/dabb3708-49c8-46e7-882e-1230073e119b)
![Screenshot_20240611-224724_Breezy Weather](https://github.com/breezy-weather/breezy-weather/assets/8622264/a31fe9f6-de52-4c87-930e-20fe8cc42ffa)
![Screenshot_20240611-224754_Breezy Weather](https://github.com/breezy-weather/breezy-weather/assets/8622264/1817d772-ab3c-4202-9fe5-e3a658d52984)
![Screenshot_20240611-224808_Breezy Weather](https://github.com/breezy-weather/breezy-weather/assets/8622264/e6a9131b-16ca-44ae-935c-e2ffee593c75)
![Screenshot_20240611-224819_Breezy Weather](https://github.com/breezy-weather/breezy-weather/assets/8622264/c86273d6-5f12-4b9b-80fb-bd53fa148cdb)

In the Chatham Islands, it's even worse: All the sources except DMI provide incorrect data:

![Screenshot_20240611-224918_Breezy Weather](https://github.com/breezy-weather/breezy-weather/assets/8622264/73c70bbc-f71e-43ad-b953-76414fb8d7ce)
![Screenshot_20240611-224932_Breezy Weather](https://github.com/breezy-weather/breezy-weather/assets/8622264/8e50043f-3d43-48a2-8305-d003e2356ca8)
![Screenshot_20240611-224958_Breezy Weather](https://github.com/breezy-weather/breezy-weather/assets/8622264/c7aca8e6-1d3d-47dd-8b89-ee18fb7481a8)
![Screenshot_20240611-225026_Breezy Weather](https://github.com/breezy-weather/breezy-weather/assets/8622264/6bce366a-88c9-4857-a3c3-6b91e510f2d4)
![Screenshot_20240611-225041_Breezy Weather](https://github.com/breezy-weather/breezy-weather/assets/8622264/65d3fe1f-af1d-4b67-b3b7-12efadca5d1a)

The data from Open-Meteo and Meteo-France seems to be correct but the sun still doesn't render 🤷

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open OR closed issue.
- [X] I checked that my issue is not covered in the [Frequently Asked Questions](https://github.com/breezy-weather/breezy-weather/blob/main/HELP.md) document.
- [X] I have updated the app to **[version 5.2.4 or later](https://github.com/breezy-weather/breezy-weather/releases/latest)** and I can reproduce the issue in this version.
- [X] I wrote my request in English, and any screenshot I attached are also in English (language can be changed from Settings > Appearance), unless my issue only happens with a specific language. I can write in my native language under the English text, if necessary.
- [X] I understand that this app is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY, so I may not get a positive reply to my request, if any at all.

**Comment by papjul** [comment]
I will tag this as AccuWeather-specific issue for now.

Something is definitely wrong with this source, as it doesn't support yesterday data. All days seem shifted.
The first day from AccuWeather is 2024-06-12 with day temperature 14.7 °C and night temperature 7.9 °C which are showing on Yesterday 11/06 on my side.

I would bet this has something to do with having a system timezone on a given day, and adding a city from a different timezone which is on a different day.

**Comment by papjul** [comment]
Everything is fixed: day shift on AccuWeather, missing sun, and any other potentially impacted sources (I'm almost sure there are).

**Comment by elydpg** [comment]
> Everything is fixed: day shift on AccuWeather, missing sun, and any other potentially impacted sources (I'm almost sure there are).

The clock just struck midnight in my local time and the issue persists:

![Screenshot_20240612-000342_Breezy Weather.png](https://github.com/breezy-weather/breezy-weather/assets/8622264/75d8efe6-0b60-4036-b990-3b4bbd122363)

Can you check if the patch fixes your issue if you set your system time to UTC+3 in which it is now past midnight on 12 June?

**Comment by papjul** [comment]
It's probably just cache client or server side, just retry tomorrow morning.

**Comment by elydpg** [comment]
Is server side caching supposed to last 2 hours?

![Screenshot_20240612-020414_Breezy Weather.png](https://github.com/breezy-weather/breezy-weather/assets/8622264/f96dbd09-02e7-4304-a5fa-ec0234482c30)

**Comment by papjul** [comment]
Are you sure the debug build you're running is 7133619 or later? Can you screenshot Settings > Info icon on top right to confirm?

**Comment by elydpg** [comment]
It's still happening even though Tel Aviv and Auckland and Chatham Islands are currently on the same time and it's well past midnight local time (almost 11:00):

Auckland:

![Screenshot_20240612-103604_Breezy Weather.png](https://github.com/breezy-weather/breezy-weather/assets/8622264/5fd175be-e50f-4e4d-8ccb-a1724639d82f)

Chatham Islands:

![Screenshot_20240612-103634_Breezy Weather.png](https://github.com/breezy-weather/breezy-weather/assets/8622264/35c4b81e-cf4a-445b-bce6-1ad4290eacc8)
![Screenshot_20240612-103655_Breezy Weather.png](https://github.com/breezy-weather/breezy-weather/assets/8622264/6b6f5c4d-bcab-40f0-a6d6-ef7eee031caa)
![Screenshot_20240612-103733_Breezy Weather.png](https://github.com/breezy-weather/breezy-weather/assets/8622264/6dd5f95d-b82c-4d75-b287-55ca3ebc7ba3)
![Screenshot_20240612-103751_Breezy Weather.png](https://github.com/breezy-weather/breezy-weather/assets/8622264/9b366b08-fd0d-42e1-a35b-59fd9b7ffed5)
![Screenshot_20240612-103814_Breezy Weather.png](https://github.com/breezy-weather/breezy-weather/assets/8622264/4eeaa6d0-b592-4310-99d4-f71ac41a884f)

**Comment by papjul** [comment]
I reported the Chatham Islands bug here: open-meteo/open-meteo#847

Please try latest `main` branch and report a bug on other sources if you notice the same thing. Debug builds now have the day displaying in daily details view to help troubleshooting.

Otherwise, wait for next release build.

> trying to build from source seems quite confusing; do you have an apk of it?

We don't offer debug builds. What's confusing? Just click the “Run” button in Android Studio.

**Comment by elydpg** [comment]
> We don't offer debug builds. What's confusing? Just click the “Run” button in Android Studio.

I suppose it's more accurate to say that I didn't have android studio installed and it's a hassle to download to test a single thing :/

I finally got an emulated version of the app running but it doesn't have AccuWeather available 😭

**Comment by papjul** [comment]
> it doesn't have AccuWeather available 

Make sure you run `basic` flavor (it should be the default):
![image](https://github.com/breezy-weather/breezy-weather/assets/1449159/90f1d4e4-d1c2-4ed8-8fc9-a7df2da1fdd7)

Ensure you input your private API key in Settings, or only use sources without mandatory API key.

**Comment by elydpg** [comment]
Okay yea I had to register for an AccuWeather API key to test it, but it seems that the correct data appears now :)

![Screenshot_20240612_211943](https://github.com/breezy-weather/breezy-weather/assets/8622264/f75e2f41-a29f-4afc-b0b9-5739758a5d70)
![Screenshot_20240612_211850](https://github.com/breezy-weather/breezy-weather/assets/8622264/1037e857-8307-4ecb-b480-29fddc0d5686)

I do see that the moon phase is different though; my guess is that's just a difference in how the sources determine it
