### ISSUE TITLE
Reject sunrise data from sources if it is not on the same day

### ISSUE THREAD

**Issue by papjul** [breezy-weather/breezy-weather#1126]
Some sources give us a sunrise on next day, noticeable on places in the world far from UTC+0. Since it's not a specific source issue, but many sources are affected, we should reject data in these cases and recompute it ourselves.

**Comment by elydpg** [comment]
![20240612_210628](https://github.com/breezy-weather/breezy-weather/assets/8622264/06d85a59-dd05-4e84-a251-1528a3ce52a4)

I noticed it for the first time here in Tel Aviv that the moonrise data is for the next day :| weird cause it's not so far from UTC

Title should be changed to sunrise/moonrise data btw

**Comment by papjul** [comment]
> Title should be changed to sunrise/moonrise data btw

I need to think about it
