### ISSUE TITLE
Meteo-France: Weather conditions aren't translated

### ISSUE THREAD

**Issue by elydpg** [breezy-weather/breezy-weather#1130]
### Steps to reproduce

1. Make sure the app is set to English, and add a location with source "Meteo-France"
2. Click on a day in the daily forecast
3. Note the name of the weather condition

### Expected behavior

Name of the weather condition appears in English (or the app's language if the app isn't set to French)

### Actual behavior

Name of the weather condition appears in French:

![Screenshot_20240613-133252_Breezy Weather](https://github.com/breezy-weather/breezy-weather/assets/8622264/b04afc82-be32-40a9-b133-8e6ab8e9abf6)

### Weather source used

Meteo-France

### Breezy Weather version

5.2.4 standard

### Android version

12

### Device

Samsung Galaxy s10e

### Other details

This might or might not be a bug, as the name of the weather condition is probably fetched from the source. What's weird is that the name of the weather condition appears in English on the main screen though:

![Screenshot_20240613-134117_Breezy Weather](https://github.com/breezy-weather/breezy-weather/assets/8622264/e1799aec-03c3-4c27-96fb-44bdca2ecb2f)
![Screenshot_20240613-134122_Breezy Weather](https://github.com/breezy-weather/breezy-weather/assets/8622264/58e1086b-2321-48a5-9650-4dbc7e7234ca)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open OR closed issue.
- [X] I checked that my issue is not covered in the [Frequently Asked Questions](https://github.com/breezy-weather/breezy-weather/blob/main/HELP.md) document.
- [X] I have updated the app to **[version 5.2.4 or later](https://github.com/breezy-weather/breezy-weather/releases/latest)** and I can reproduce the issue in this version.
- [X] I wrote my request in English, and any screenshot I attached are also in English (language can be changed from Settings > Appearance), unless my issue only happens with a specific language. I can write in my native language under the English text, if necessary.
- [X] I understand that this app is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY, so I may not get a positive reply to my request, if any at all.

**Comment by papjul** [comment]
There is no localization of the forecast. I recommand you use a different source if you don't speak French.

**Comment by elydpg** [comment]
Wait so then why does it show as English on the main screen?

**Comment by papjul** [comment]
It's not a forecast. Observations are provided through a different endpoint that supports localization (which is limited to English I believe).

**Comment by elydpg** [comment]
Ah. I can confirm that the current weather main screen is always English, even if I change the app language:

![Screenshot_20240613-152749_Breezy Weather.png](https://github.com/breezy-weather/breezy-weather/assets/8622264/4fc5a1b0-8d49-4443-b105-1ff3d17c56f6)

However this might be because my system language is set to English; In #1012 I see a screenshot where the main screen shows the weather in Persian:

![sketch-1710532065642](https://github.com/breezy-weather/breezy-weather/assets/65030817/124ed93b-d726-417b-9971-a85af8c7d1b2)

Not sure what's up with that 🤷 ideally it should follow app language tho (if it's localizable)

**Comment by papjul** [comment]
> the current weather main screen is always English, even if I change the app language

I use Météo France in French and it is definitely in French there.

> In https://github.com/breezy-weather/breezy-weather/discussions/1012 I see a screenshot where the main screen shows the weather in Persian

I'm almost sure it's not Météo France. There is no reason to think Météo France would provide weather in Persian.
