### ISSUE TITLE
Weather condition names follow system language over app language on Android < 13

### ISSUE THREAD

**Issue by elydpg** [breezy-weather/breezy-weather#1132]
### Steps to reproduce

1. Make sure the app is set to English and NOT "Follow System"
2. Set the system language to Spanish and restart the app
3. Add a new location with source Open-Meteo (so as to avoid using cached data)

### Expected behavior

Weather condition names appear in the app language (English)

### Actual behavior

Weather condition names appear in the system language (Spanish):

![Screenshot_20240613-190304_Breezy Weather](https://github.com/breezy-weather/breezy-weather/assets/8622264/70858f80-7905-4d79-a905-6b515989ec51)
![Screenshot_20240613-190318_Breezy Weather](https://github.com/breezy-weather/breezy-weather/assets/8622264/8863a158-0e21-424b-8869-43e9e341f2c4)
![Screenshot_20240613-190335_Breezy Weather](https://github.com/breezy-weather/breezy-weather/assets/8622264/ba8306d9-808b-435e-90da-597acdca9a45)

### Weather source used

Open-Meteo, MET Norway, Meteo-France, DMI, probably others

### Breezy Weather version

5.2.4 standard

### Android version

12

### Device

Samsung Galaxy s10e

### Other details

This behaviour happens from pretty much all worldwide sources that I tried, as well as the IMS (Yes apparently the IMS can provide weather condition names in Spanish; who knew?) and NWS. Notable exceptions include:

Meteo-France: Current weather condition follows system language, Forecast weather conditions are always in French (Since Meteo-France doesn't localize forecast weather conditions - see #1130)

AccuWeather: All weather conditions are in English only (probably because AccuWeather doesn't localize anything)

ECCC: Strangely, always in English. Except if the current weather condition is Thunderstorms, that follows the system language for some reason (though forecasts are only in English):

![Screenshot_20240613-195738_Breezy Weather](https://github.com/breezy-weather/breezy-weather/assets/8622264/5c6e7fcc-463d-46b5-9a7d-ab28ffddec61)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open OR closed issue.
- [X] I checked that my issue is not covered in the [Frequently Asked Questions](https://github.com/breezy-weather/breezy-weather/blob/main/HELP.md) document.
- [X] I have updated the app to **[version 5.2.4 or later](https://github.com/breezy-weather/breezy-weather/releases/latest)** and I can reproduce the issue in this version.
- [X] I wrote my request in English, and any screenshot I attached are also in English (language can be changed from Settings > Appearance), unless my issue only happens with a specific language. I can write in my native language under the English text, if necessary.
- [X] I understand that this app is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY, so I may not get a positive reply to my request, if any at all.

**Comment by papjul** [comment]
Your issue only happens because you changed system language recently. No one does that.

Please try to clear cache data first. Custom app language is natively and fully supported only starting from Android 13 and previous Android versions are known to keep cache even if system language was changed recently.

**Comment by elydpg** [comment]
I don't think it has to with clearing my cache; I tried again but this time I cleared the app cache and restarted my phone after switching the language. Still happens:

![Screenshot_20240614-120208_Breezy Weather.png](https://github.com/breezy-weather/breezy-weather/assets/8622264/1be4fc4e-5615-4c98-a3ba-d9a882799ba5)

**Comment by papjul** [comment]
This issue is not reproducible in Android 14.

> Custom language per app is natively and fully supported only starting from Android 13

I recommand you update to the latest version of Android and retry

**Comment by elydpg** [comment]
So my device doesn't support Android 13+ so I can't do that :( However I tested it in a Pixel 8 Pro emulator in Android 12, 13, and 14 and I can confirm that it's buggy just like on my device in Android 12 and working as intended on Android 13 and 14.

These quirks are still present though:

> Meteo-France: Current weather condition follows system language, Forecast weather conditions are always in French (Since Meteo-France doesn't localize forecast weather conditions - see #1130)
> 
> AccuWeather: All weather conditions are in English only (probably because AccuWeather doesn't localize anything)
> 
> ECCC: Strangely, always in English. Except if the current weather condition is Thunderstorms, that follows the system language for some reason (though forecasts are only in English):

In particular, that ECCC localizes only current weather thunderstorms and nothing else is still a problem but that's a separate issue

**Comment by papjul** [comment]
> Features that will no longer be available
> - Backport features/fixes from latest Android versions to older Android versions

Re-implementing the per-app language feature from Android 13+ in Android < 13 falls in this category.

**Comment by elydpg** [comment]
Yep was just confirming that it's an Android < 13 issue. Will close then
