### ISSUE TITLE
No fallback to real temperature when feels like temperature missing in hourly forecast

### ISSUE THREAD

**Issue by elydpg** [breezy-weather/breezy-weather#1133]
### Steps to reproduce

Add the following cities using ECCC:

1. Toronto
2. Vancouver
3. Calgary

### Expected behavior

All of them should have the same data (up to applicability)

### Actual behavior

All of them have different data

### Weather source used

ECCC

### Breezy Weather version

5.2.4 standard

### Android version

12

### Device

Samsung Galaxy s10e

### Other details

It might be intentional that different cities are just supplied different data from ECCC. However with the "Feels like" data I don't understand the discrepancy here, especially with the blank forecast

![Screenshot_20240613-202344_Breezy Weather](https://github.com/breezy-weather/breezy-weather/assets/8622264/9d757cf4-3023-440d-b1d0-a31c03952f56)
![Screenshot_20240613-202603_Breezy Weather](https://github.com/breezy-weather/breezy-weather/assets/8622264/f09c2871-4511-448b-b961-efa496774990)
![Screenshot_20240613-202720_Breezy Weather](https://github.com/breezy-weather/breezy-weather/assets/8622264/1548cbaf-ed24-4661-9b8b-cd2cca11370a)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open OR closed issue.
- [X] I checked that my issue is not covered in the [Frequently Asked Questions](https://github.com/breezy-weather/breezy-weather/blob/main/HELP.md) document.
- [X] I have updated the app to **[version 5.2.4 or later](https://github.com/breezy-weather/breezy-weather/releases/latest)** and I can reproduce the issue in this version.
- [X] I wrote my request in English, and any screenshot I attached are also in English (language can be changed from Settings > Appearance), unless my issue only happens with a specific language. I can write in my native language under the English text, if necessary.
- [X] I understand that this app is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY, so I may not get a positive reply to my request, if any at all.

**Comment by papjul** [comment]
I don't understand your issue here? We put the data we find. Some stations can report different data, especially when they are run by different provinces.

Feels like temperature may only be computed under certain conditions and only when all mandatory data is available. Version 5.2.5 will also compute apparent temperature when not available from source.

**Comment by elydpg** [comment]
I think I assumed that this was the app failing to parse source data consistently? Otherwise why would there be an empty graph there?

But no, turns out ECCC just doesn't send out "Feels like" data consistently at all, as seen here in their app:

![Screenshot_20240614-110539_Breezy Weather.png](https://github.com/breezy-weather/breezy-weather/assets/8622264/04dfe297-df12-4532-8658-1c01709b6261)
![Screenshot_20240614-110144_WeatherCAN.png](https://github.com/breezy-weather/breezy-weather/assets/8622264/30862199-d32a-48c2-b514-4ac2e0cacad1)

I *think* this is supposed to mean that the feels like is the same as the actual temperature? I don't know though so this is probably WAI for when some data exists but not the whole graph

**Comment by papjul** [comment]
I will have a look at why it doesn't fallback to real temperature when data is missing (it's supposed to, to avoid this kind of weird chart)
