### ISSUE TITLE
NWS: Failed to parse weather data in cities with probability of thunder with decimals

### ISSUE THREAD

**Issue by elydpg** [breezy-weather/breezy-weather#1137]
### Steps to reproduce

1. Add a location in Guam, Northern Mariana Islands, or American Samoa, with source NWS

### Expected behavior

Should add normally

### Actual behavior

Failed to parse weather data:

![Screenshot_20240614-195805_Breezy Weather](https://github.com/breezy-weather/breezy-weather/assets/8622264/55b3e93d-491e-45c8-8c95-1f195bc261c6)
![Screenshot_20240614-195946_Breezy Weather](https://github.com/breezy-weather/breezy-weather/assets/8622264/b7ff1a24-a53b-4b58-9b0a-b60f00458c9c)
![Screenshot_20240614-200101_Breezy Weather](https://github.com/breezy-weather/breezy-weather/assets/8622264/54eed805-146e-4830-9a6a-dd62c0dfffa9)

### Weather source used

NWS

### Breezy Weather version

5.2.4 standard

### Android version

12

### Device

Samsung Galaxy s10e

### Other details

Another one of these 🤷 reporting as per the FAQ. Puerto Rico and the USVI (the other American overseas territories) seem to work fine

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open OR closed issue.
- [X] I checked that my issue is not covered in the [Frequently Asked Questions](https://github.com/breezy-weather/breezy-weather/blob/main/HELP.md) document.
- [X] I have updated the app to **[version 5.2.4 or later](https://github.com/breezy-weather/breezy-weather/releases/latest)** and I can reproduce the issue in this version.
- [X] I wrote my request in English, and any screenshot I attached are also in English (language can be changed from Settings > Appearance), unless my issue only happens with a specific language. I can write in my native language under the English text, if necessary.
- [X] I understand that this app is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY, so I may not get a positive reply to my request, if any at all.

**Comment by elydpg** [comment]
I mean ok? Not sure it's relevant though...

[breezyweather_crash_logs.txt](https://github.com/user-attachments/files/15842022/breezyweather_crash_logs.txt)

**Comment by papjul** [comment]
Can you export after the failure happens? Looks like the app was closed in-between

**Comment by elydpg** [comment]
Okay I added Guam and then right after exported the crash logs

[breezyweather_crash_logs.txt](https://github.com/user-attachments/files/15842143/breezyweather_crash_logs.txt)

**Comment by papjul** [comment]
I don't know why you have no logs, but I found the origin of the issue, will fix
