### ISSUE TITLE
Weathet Alert notifications are 20-30 minutes late

### ISSUE THREAD

**Issue by ToughDBlue** [breezy-weather/breezy-weather#1143]
### Steps to reproduce

Setup weather alerts

### Expected behavior

When the NWS issues an alert Breezy Weather should send a real time alert and not wait 20-30 minutes to send a notification

### Actual behavior

When the NWS issues a Special Weather Statement, Watch, or Warning Breezy Weather doesn't send a notification for it for at least 20 minutes.

### Weather source used

AccuWeather

### Breezy Weather version

5.2.4

### Android version

Android 14

### Device

Pixel 7

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open OR closed issue.
- [X] I checked that my issue is not covered in the [Frequently Asked Questions](https://github.com/breezy-weather/breezy-weather/blob/main/HELP.md) document.
- [X] I have updated the app to **[version 5.2.4 or later](https://github.com/breezy-weather/breezy-weather/releases/latest)** and I can reproduce the issue in this version.
- [X] I wrote my request in English, and any screenshot I attached are also in English (language can be changed from Settings > Appearance), unless my issue only happens with a specific language. I can write in my native language under the English text, if necessary.
- [X] I understand that this app is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY, so I may not get a positive reply to my request, if any at all.

**Comment by papjul** [comment]
It's not a bug, there is no push feature

**Comment by ToughDBlue** [comment]
> It's not a bug, there is no push feature

So it's normal for a tornado warning to be 20 minutes late in a notification. If so, that's really not an alert notification and is not helpful. Can you make it a push feature?

**Comment by papjul** [comment]
> So it's normal for a tornado warning to be 20 minutes late in a notification?

20 minutes after it begins or 20 minutes after the alert has been emitted and is active? That's not the same thing.

Alerts are pulled at your requested refresh rate. If you have a documentation about a pushed alerts system, please open a new issue using the "New source" template.

**Comment by papjul** [comment]
> The alert appears 20 minutes after the NWS issued the Thunderstorm Watch.

So, it's normal? If the alert was issued at 10:00 and your next refresh of data is scheduled at 10:20, you will receive it at 10:20.

> I noticed the "Severe Weather Alerts" does use push notifications. Here is the GitHub page for it. https://github.com/qconrad/severe-weather-alerts

Unfortunately, this project is not FOSS, it depends on proprietary dependencies like Firebase. And we have no plans to include proprietary dependencies.

**Comment by ToughDBlue** [comment]
> So, it's normal? If the alert was issued at 10:00 and your next refresh of data is scheduled at 10:20, you will receive it at 10:20.

So finding a way to make the alerts real time would be helpful because I would like to be alerted right away for a Tornado Warning and not 20 minutes later or the next refresh time. Real time weather alerts are needed during life threatening conditions.

> Unfortunately, this project is not FOSS, it depends on proprietary dependencies like Firebase. And we have no plans to include proprietary dependencies.

Totally understandable and thank you for not having plans to include proprietary dependences.

**Comment by papjul** [comment]
> Real time weather alerts are needed during life threatening conditions.

Shouldn't life threatening alerts be emitted through other means such as SMS? https://en.m.wikipedia.org/wiki/Emergency_population_warning

Only the weather source can push alerts to its subscribers from server-side, and if they do it, they will probably do it through proprietary dependencies like Google Services as the goal is to be battery-efficient by unifying the reception of all notifications. Chances are low they will use an alternative system.

As an alternative, try typing "`your source` real time alerts` to see if they provide something else, like subscribing to SMS alerts or something.
