### ISSUE TITLE
Perceived temperature wrong in Germany

### ISSUE THREAD

**Issue by notune** [breezy-weather/breezy-weather#1157]
### Steps to reproduce

Select any location in Germany with the default data provider (dwd) and look at the perceived temperature. 

### Expected behavior

Perceived temperature should be much higher, for example in Berlin it was 16°C instead of 24°C.

### Actual behavior

The perceived temperature was much lower then it should be, looking at other sources such as weather.com, there it was 24°C vs 24°C real temperature. 

### Weather source used

DWD

### Breezy Weather version

5.2.4

### Android version

Android 14

### Device

Pixel 8 Pro

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open OR closed issue.
- [X] I checked that my issue is not covered in the [Frequently Asked Questions](https://github.com/breezy-weather/breezy-weather/blob/main/HELP.md) document.
- [X] I have updated the app to **[version 5.2.4 or later](https://github.com/breezy-weather/breezy-weather/releases/latest)** and I can reproduce the issue in this version.
- [X] I wrote my request in English, and any screenshot I attached are also in English (language can be changed from Settings > Appearance), unless my issue only happens with a specific language. I can write in my native language under the English text, if necessary.
- [X] I understand that this app is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY, so I may not get a positive reply to my request, if any at all.

**Comment by papjul** [comment]
Feels like temperature is subjective and is not an universal formula, hence differences. DWD doesn't provide any feels like temperature natively, it fallbacks to the wet bulb temperature formula in Breezy Weather.

**Comment by notune** [comment]
Still maybe we could think of some new formula? Because for example today we have 20°C feels like temperate vs 30°C real temperature. Weather.com reports 31°C feels like temperature. So it's off by 11°C which is quite extreme in my opinion. I am also willing to look into it if I have some free time maybe. 
![Screenshot_20240626-160015](https://github.com/breezy-weather/breezy-weather/assets/25132780/a9c3b1d3-8bc6-471d-b492-7b9600e68d5f)

**Comment by papjul** [comment]
> Still maybe we could think of some new formula?

The wet bulb formula is correct.

The apparent temperature will be available in next version, see #1085 

There are no plans to add more.
