### ISSUE TITLE
Alerts are scrolled to bottom when opened

### ISSUE THREAD

**Issue by NBA613** [breezy-weather/breezy-weather#116]
### Steps to reproduce

Open a weather alert

### Expected behavior

Beginning of alert should be displayed

### Actual behavior

End of alert is displayed, requiring the user to scroll up to the beginning to read it correctly.

### Weather provider used

AccuWeather

### Breezy Weather version

4.0.5-Alpha

### Android version

Android 13

### Device

Pixel 6 Pro

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to **[latest version](https://github.com/breezy-weather/breezy-weather/releases/latest)**.

**Comment by papjul** [comment]
I guess this happens when you have many alerts at the same time, and app is jumping to the alert you tapped on.
Please provide a city in your province that has the same alerts so we can reproduce.

**Comment by NBA613** [comment]
> I guess this happens when you have many alerts at the same time, and app is jumping to the alert you tapped on.

Happening with only one alert as well. The alert page is always scrolled to bottom. Noticing this issue since Geometric weather. Example: Chicago, Illinois USA.
