### ISSUE TITLE
Light theme when sun is down with day/night mode for locations enabled

### ISSUE THREAD

**Issue by neunzehnachtneun** [breezy-weather/breezy-weather#1163]
### Steps to reproduce

While the setting ist turned off, day/nicht mode is working. Ehen I turn on the switch, its not Wirkung anymore. Seems to be the other way round.

Thanks!

### Expected behavior

See description and screenshot.

### Actual behavior

![Screenshot_20240629-205823](https://github.com/breezy-weather/breezy-weather/assets/18753899/b2d9c502-6c6b-4c04-a308-16ba8593e06f)
![Screenshot_20240629-205836](https://github.com/breezy-weather/breezy-weather/assets/18753899/97b4cf69-2599-453d-96d2-2931375b8200)
![Screenshot_20240629-205846](https://github.com/breezy-weather/breezy-weather/assets/18753899/6e3092be-cbee-41d0-a39a-e63b3a35b9e7)
![Screenshot_20240629-205858](https://github.com/breezy-weather/breezy-weather/assets/18753899/577c9acb-b368-4446-bb8e-63a7b50f49dc)

### Weather source used

Bright sky

### Breezy Weather version

5.2.5

### Android version

Android 14

### Device

Pixel 6a

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open OR closed issue.
- [X] I checked that my issue is not covered in the [Frequently Asked Questions](https://github.com/breezy-weather/breezy-weather/blob/main/HELP.md) document.
- [X] I have updated the app to **[version 5.2.5 or later](https://github.com/breezy-weather/breezy-weather/releases/latest)** and I can reproduce the issue in this version.
- [X] I wrote my request in English, and any screenshot I attached are also in English (language can be changed from Settings > Appearance), unless my issue only happens with a specific language. I can write in my native language under the English text, if necessary.
- [X] I understand that this app is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY, so I may not get a positive reply to my request, if any at all.

**Comment by papjul** [comment]
I don't know, sun is setting at 21:32 in Berlin today according to https://www.timeanddate.com/sun/germany/berlin so I don't see anything wrong?

**Comment by papjul** [comment]
Berlin is nighttime now on my side with Bright Sky source

**Comment by neunzehnachtneun** [comment]
Hmm, actually there is no night mode at all, if the setting is enabled. Ill add some Screenshots later.

**Comment by papjul** [comment]
In that case, please make a screenshot of the Sun & Moon card and include the system time from your statebar (assuming your system time is UTC+2).

**Comment by neunzehnachtneun** [comment]
I am sorry. I misunderstood the feature. In fact it is working is expected.

Thanks for your explanatory questions!
