### ISSUE TITLE
Background animation of main screen shows rain despite Precipitation Nowcasting card showing it's not raining

### ISSUE THREAD

**Issue by PrivacyFriendlyMuffins** [breezy-weather/breezy-weather#1164]
### Steps to reproduce

Not sure if it would happen with anyone else, but...

1. Set location.
2. Set Open-Meteo for every source.
3. Enabled precipitation nowcasting card.
4. Check the screen, I guess.

See below for more details.

### Expected behavior

The background animation should match the listed weather conditions (or at least not contradict it).

### Actual behavior

The precipitation nowcasting is saying precipitation "expected to start at 21:15". However, despite this, it is currently 20:55 and decidedly *not* raining and the background animation is that of rain.

![Screenshot_20240629-205511](https://github.com/breezy-weather/breezy-weather/assets/86497467/3394cf91-fda4-4b3a-8053-2341b7da39e7)

I can't think of anything more to say, but if there are any other details I should provide, feel free to let me know. If there are any logs I can provide, please also let me know there and I'll provide those as well.

### Weather source used

Open-Meteo

### Breezy Weather version

5.2.5

### Android version

Android 11

### Device

Motorola One 5G Ace

### Other details

**Location**: Current Location
(It does the same thing even if I set the location to my specific town. I am in the US.)

**Weather Sources**
- **Main Source**: Open-Meteo
- **Air Quality**: Main source
- **Pollen**: Main source
- **Precipitation nowcasting**: Main source
- **Alerts**: National Weather Service (NWS)
- **Temperature normals**: None

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open OR closed issue.
- [X] I checked that my issue is not covered in the [Frequently Asked Questions](https://github.com/breezy-weather/breezy-weather/blob/main/HELP.md) document.
- [X] I have updated the app to **[version 5.2.5 or later](https://github.com/breezy-weather/breezy-weather/releases/latest)** and I can reproduce the issue in this version.
- [X] I wrote my request in English, and any screenshot I attached are also in English (language can be changed from Settings > Appearance), unless my issue only happens with a specific language. I can write in my native language under the English text, if necessary.
- [X] I understand that this app is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY, so I may not get a positive reply to my request, if any at all.

**Comment by papjul** [comment]
Open-Meteo does not have any observation station data. I believe they show data from the closest hour (21:00) instead. Feel free to report the issue to Open-Meteo if that's an important matter to you.

**Comment by PrivacyFriendlyMuffins** [comment]
> Open-Meteo does not have any observation station data. I believe they show data from the closest hour (21:00) instead. Feel free to report the issue to Open-Meteo if that's an important matter to you.

I do not understand. Open-Meteo said "Precipitation soon", which means it knows it's not raining at the moment. Therefore, shouldn't it also know not to show the rain animation?

**Comment by papjul** [comment]
Open-Meteo does not say "Precipitation soon", we do, based on 15 min by 15 min data. The background animation is based on `current` weather code reported by Open-Meteo, which is a different kind of data. Please report discrepancies between `current` and `15_minutely` to Open-Meteo directly.

**Comment by PrivacyFriendlyMuffins** [comment]
Very well. I apologize. I was merely trying to understand.
