### ISSUE TITLE
[China Source]Nowcast precipitation appears to be inaccurate

### ISSUE THREAD

**Issue by lyrnya** [breezy-weather/breezy-weather#1165]
### Steps to reproduce

There was an issue before that mentioned that the Chinese source of Breeze Weather is the same as Xiaomi Weather, but the precipitation forecasts are inconsistent.

### Expected behavior

If their sources are consistent, then the precipitation nowcasts should be consistent.

### Actual behavior

![Screenshot_20240701-081453](https://github.com/breezy-weather/breezy-weather/assets/92076022/76dcc83c-1453-4164-8e63-9c353a24d2b5)
![Screenshot_20240701-081500](https://github.com/breezy-weather/breezy-weather/assets/92076022/1e851336-2116-418e-96cf-54856a469826)
As you can see, the Breeze Weather rainfall histogram is inconsistent with Xiaomi Weather, refreshing the same location at the same time.

### Weather source used

China Source

### Breezy Weather version

5.2.5

### Android version

Android 14

### Device

Moto G54

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open OR closed issue.
- [X] I checked that my issue is not covered in the [Frequently Asked Questions](https://github.com/breezy-weather/breezy-weather/blob/main/HELP.md) document.
- [X] I have updated the app to **[version 5.2.5 or later](https://github.com/breezy-weather/breezy-weather/releases/latest)** and I can reproduce the issue in this version.
- [ ] I wrote my request in English, and any screenshot I attached are also in English (language can be changed from Settings > Appearance), unless my issue only happens with a specific language. I can write in my native language under the English text, if necessary.
- [X] I understand that this app is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY, so I may not get a positive reply to my request, if any at all.

**Comment by papjul** [comment]
How is that different?

**Comment by lyrnya** [comment]
The rain forecast for Breeze Weather corresponds to the light rain level, while the rain forecast for Xiaomi Weather corresponds to the heavy rain level.

**Comment by papjul** [comment]
Here are the thresholds in Breezy Weather:
- Light: 5 mm/h
- Medium: 10 mm/h
- Heavy: 15 mm/h

What are the thresholds in Xiaomi Weather?

**Comment by papjul** [comment]
Either they consider 0.3 mm/h to be heavy (which is clearly not), or their chart is not matching any scale (for example, if the max of the period is 0.3 mm/h, 0.3 mm/h will be "heavy", while if the max is 15 mm/h, 15 mm/h will be "heavy", and if there is any 0.3 mm/h during the period it will appear as very small, just like in Breezy Weather chart).

Let me know if there is anything more to add, or if we can just close the issue?

**Comment by lyrnya** [comment]
My doubts have been resolved
