### ISSUE TITLE
Can not add location Dover (UK)

### ISSUE THREAD

**Issue by ceving** [breezy-weather/breezy-weather#1174]
### Steps to reproduce

I tried to add the location Dover in UK (latitude: 51.12598, longitude: 1.31257)

I tried different searches:

  - dover
  - dover uk
  - uk dover
  - dover, uk
  - ct16 1bz

### Expected behavior

It should be possible to add Dover (UK).

### Actual behavior

I can not find a way to add Dover (UK). The search result lists only locations in the USA and Kanada.

The Open-Meteo database contains Dover, but it is shown only when you raise the number of search results:
https://open-meteo.com/en/docs/geocoding-api#name=dover&count=100

It is not possible to raise the number of search results in Breezy Weather.

### Weather source used

Open-Meteo

### Breezy Weather version

5.2.3_freenet

### Android version

Android 14

### Device

Pixel 8

### Other details

It may be useful to sort the location search result by the distance to the current location. If you are in Europe it may be less likely that you are interested in the weather in the USA.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open OR closed issue.
- [X] I checked that my issue is not covered in the [Frequently Asked Questions](https://github.com/breezy-weather/breezy-weather/blob/main/HELP.md) document.
- [X] I have updated the app to **[version 5.2.5 or later](https://github.com/breezy-weather/breezy-weather/releases/latest)** and I can reproduce the issue in this version.
- [X] I wrote my request in English, and any screenshot I attached are also in English (language can be changed from Settings > Appearance), unless my issue only happens with a specific language. I can write in my native language under the English text, if necessary.
- [X] I understand that this app is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY, so I may not get a positive reply to my request, if any at all.

**Comment by papjul** [comment]
Open-Meteo search is based on the address syntax which is comma-separated.
In other words, in your case, you must write:
Dover, United Kingdom

**Comment by ceving** [comment]
You should try your suggestion yourself, before you close the issue. Searching for "Dover, United Kingdom" works in the Open-Meteo website, but returns nothing in Breezy Weather.

**Comment by papjul** [comment]
It used to work, but now it no longer works neither on the website or app (both use the same API). I have no idea why, but you can report Open-Meteo search issues here: https://github.com/open-meteo/geocoding-api

**Comment by papjul** [comment]
Ah, I understand why, it only works when you set max limit to 100, which is definitely an issue on Open-Meteo side. The limit of 100 should be on the number of results, not on the 100 results of "Dover" then filtered by "United Kingdom"

**Comment by ceving** [comment]
What is the solution to my problem? I still can not add Dover (UK).

**Comment by papjul** [comment]
If you can wait:
- Get the fix on Open-Meteo side
- Use #10 

Otherwise, you will need to use a different search source, such as AccuWeather. You don't have to use AccuWeather as your weather source, you can just use it to search.
