### ISSUE TITLE
Widgets load indefinitely

### ISSUE THREAD

**Issue by Dogway** [breezy-weather/breezy-weather#1199]
### Steps to reproduce

Update BreezyWeather to latest

### Expected behavior

Keep my configuration

### Actual behavior

The widget is reset

### Weather source used

OpenMeteo, Automatic

### Breezy Weather version

5.2.5

### Android version

Android 14

### Device

Sony Xperia 10 IV

### Other details

Basically I had set BreezyWeather nicely with some tags for extra information in the widget, when updating to latest 5.2.5 version now everything is blank and Mosaic mode is gone, therefore I can't barely do anything customization wise.
`$ws$, $d$🌡️$ctd$($atd$) (UV:$cuv$) $enter$🔆$0sr$🌚$0ss$ 💦$ch$$cwd$ $cps$ $l$:$ut$`

And here is different layouts I had for the widget. I guess this is now not possible?
![Screenshot_20240709-134920](https://github.com/user-attachments/assets/03b9aa4d-1a18-4032-ab58-916a7db0b910)

Thank you!

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open OR closed issue.
- [X] I checked that my issue is not covered in the [Frequently Asked Questions](https://github.com/breezy-weather/breezy-weather/blob/main/HELP.md) document.
- [X] I have updated the app to **[version 5.2.5 or later](https://github.com/breezy-weather/breezy-weather/releases/latest)** and I can reproduce the issue in this version.
- [X] I wrote my request in English, and any screenshot I attached are also in English (language can be changed from Settings > Appearance), unless my issue only happens with a specific language. I can write in my native language under the English text, if necessary.
- [X] I understand that this app is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY, so I may not get a positive reply to my request, if any at all.

**Comment by Dogway** [comment]
I found that I can find Mosaic mode if I choose the Day Details widget.
In any case, I set Mosaic and the above code and the widget stays blank, as if blocked. Maybe this is now incompatible with my phone. I downloaded the standard version ( breezy-weather-v5.2.5_standard.apk )

**Comment by papjul** [comment]
1) What is Mosaic mode?
2) Did you uninstall app before updating?
3) If you just updated, did the widget disappear from the homescreen after updating, or was the widget still there and the config was reset?
4) Is your issue about a config loss or about a feature that disappeared with the update?

**Comment by Dogway** [comment]
1. Third item in the drop down after settings the "Daily" widget
2. No, I didn't uninstall. I updated in order to keep my settings.
3. Here's the image of how it looks now.
4. The issue is that even if I set up the widget, weather provider, view mode, and details tags, it still keeps on "idling". Looks like more of a core issue to me, maybe I need to download the armv8a?
5. 
![Screenshot_20240715-133547](https://github.com/user-attachments/assets/5a5fc9de-a138-42b2-8176-c9c1de6fa7bf)
![Screenshot_20240715-133707](https://github.com/user-attachments/assets/5c209e22-1351-42c9-a31a-3e12b03a8d3f)

**Comment by Dogway** [comment]
It won't let me define a location. It basically only asks for location permissions and that's all....

EDIT: Aaaaalright, I actually had to OPEN the APP to see the location list. Since the APP didn't auto-place onto the home screen, I thought everything there was to it was the widget options, and then under APP information, opening the APP settings...

Thanks for your help!
