### ISSUE TITLE
[Baidu IP location] Returns Success when there is an error

### ISSUE THREAD

**Issue by biminwansui** [breezy-weather/breezy-weather#1209]
### Steps to reproduce

After I enter the baiduAPI key and select the Baidu location service, the software is not able to get the location.

### Expected behavior

The correct location should be obtained, when I select Baidu Location Service and enter the requested api

### Actual behavior

The software prompts failed to fine current location
![Screenshot_20240720-154411_Breezy Weather](https://github.com/user-attachments/assets/e2993fdf-91b0-4382-b74c-ac696a500853)

### Weather source used

china 

### Breezy Weather version

5.2.6

### Android version

android 14

### Device

xiaomi 11

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open OR closed issue.
- [X] I checked that my issue is not covered in the [Frequently Asked Questions](https://github.com/breezy-weather/breezy-weather/blob/main/HELP.md) document.
- [X] I have updated the app to **[version 5.2.6 or later](https://github.com/breezy-weather/breezy-weather/releases/latest)** and I can reproduce the issue in this version.
- [X] I wrote my request in English, and any screenshot I attached are also in English (language can be changed from Settings > Appearance), unless my issue only happens with a specific language. I can write in my native language under the English text, if necessary.
- [X] I understand that this app is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY, so I may not get a positive reply to my request, if any at all.

**Comment by biminwansui** [comment]
App version: 5.2.6 (basic, 11c2c6cd, 50206
Android version: 14 (SDK 34); build AP1A.240505.005
Device brand: Xiaomi
Device manufacturer: Xiaomi
Device name: venus (venus_global)
Device model: M2011K2G

**Comment by papjul** [comment]
Not helpful, unfortunately

What do you see when you go to:
`https://api.map.baidu.com/location/ip?ak=YOUR_KEY_HERE`
?

**Comment by biminwansui** [comment]
{"status":200,"message":"APP不存在，AK有误请检查再重试"}
translate into English is
{"status":200,"message":"APP does not exist, AK is wrong, please check and retry"}

**Comment by papjul** [comment]
So your API key is not valid ;)

Additionally, you need to report to Baidu that 200 is the error code "Success". They need to fix the HTTP error code and use something else like 403 Forbidden or something like that, otherwise we can't catch the error and show an appropriate message in app. Let us know when it's done, thanks!

**Comment by biminwansui** [comment]
I re-applied a Baidu API, and this time I used the application name "weather" instead of "breezy" in the application page. I'm so happy to say that it worked! I realized that I didn't use the correct application name to apply for the key, so I'm really grateful for your help and reply!
I think it would be really helpful to add a wiki about how to apply and use the key correctly. That way, even someone like me who isn't super tech-savvy can use Breezy without any problems!

**Comment by papjul** [comment]
I don't speak Chinese so I can't help you on how to subscribe for an API key.

> Additionally, you need to report to Baidu that 200 is the error code "Success". They need to fix the HTTP error code and use something else like 403 Forbidden or something like that, otherwise we can't catch the error and show an appropriate message in app. Let us know when it's done, thanks!

This problem remains, so please contact them so we can show better error messages in the app. Thanks!

**Comment by biminwansui** [comment]
I understand, I checked Baidu's documentation, the different numbers that appear in the call api, they have a table stating what each error number represents, so when someone requests a Baidu api and the corresponding number appears, they can search through the search engine to find the corresponding error, and Baidu has the corresponding official documentation,  so I think when requesting a Baidu api with an error, you can display in the app interface the link you sent me to show the error，the following screenshot of the document's section content![Screenshot_20240721-004053_Firefox.png](https://github.com/user-attachments/assets/a3f125f4-e285-4d0e-8e7d-8485135a040a)

**Comment by papjul** [comment]
I was not talking about this `200` but about the `200 OK` HTTP header code here:
![Screenshot_20240721_083544](https://github.com/user-attachments/assets/9ec4dd47-6caf-478f-b0c6-2b191dc794de)

Anyway, I catched the status `200` from the response to show "API unauthorized" instead of "Failed to find current location", but you should definitely report to Baidu that their headers are wrong.

**Comment by papjul** [comment]
Fixed in bd39433dc854a70e510a76af1538908cb52d206b
