### ISSUE TITLE
Background location permission dialog not being triggered

### ISSUE THREAD

**Issue by ecawthorne** [breezy-weather/breezy-weather#1215]
### Steps to reproduce

1. Fresh install of app
2. Enable location permissions

### Expected behavior

After enabling location permissions, the dialog for enabling background location updates should appear, followed by redirection to the location permissions screen for the app.

### Actual behavior

After location is enabled, the app does not show any dialog for background location updates.

### Weather source used

N/A

### Breezy Weather version

5.2.7

### Android version

Android 14

### Device

Pixel 6 Pro

### Other details

Related to #216 as the same bug would happen for this dialog if not fixed beforehand.

I believe the fix would just be changing this condition: https://github.com/breezy-weather/breezy-weather/blob/dc1808121702f1bbc9cba527290b123232451fe8/app/src/main/java/org/breezyweather/main/MainActivity.kt#L532-L535

and performing an initial location update. I'm not sure if this is intended behavior, but if so I apologize for the confusion!

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open OR closed issue.
- [X] I checked that my issue is not covered in the [Frequently Asked Questions](https://github.com/breezy-weather/breezy-weather/blob/main/HELP.md) document.
- [X] I have updated the app to **[version 5.2.6 or later](https://github.com/breezy-weather/breezy-weather/releases/latest)** and I can reproduce the issue in this version.
- [X] I wrote my request in English, and any screenshot I attached are also in English (language can be changed from Settings > Appearance), unless my issue only happens with a specific language. I can write in my native language under the English text, if necessary.
- [X] I understand that this app is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY, so I may not get a positive reply to my request, if any at all.

**Comment by papjul** [comment]
Yes, I wonder what happened, it used to be shown 🤔

Looks like you got it right, you can make a PR to inverse the permission check ;)

**Comment by ecawthorne** [comment]
I'm happy to try to pick this up, but after looking into it more this change may be more involved than I originally thought. The fix itself is fairly straightforward, but when fixed it creates another minor bug(?). The dialog is only triggered when the user initially gives the app location permissions so if the user triggers the dialog and then pauses the app the dialog disappears and the prompt for getting permissions for background location never appears.

<video 
src='https://github.com/user-attachments/assets/b4483224-3913-4210-b13d-b8e23d07e99f' width=180 
/>

Is that the intended behavior or should it be similar to the initial location dialog where it persists until the user presses the next / set button?

**Comment by papjul** [comment]
Fixed in 39bb1e6df7716c3136e77ec59fb482d17679e75c

I believe it's similar to #216.
I don't think it's worth spending too much time on rather edge-cases, especially as there is #740 (feel free to comment on this issue if that's something you would be interested working on).
