### ISSUE TITLE
No more "Precipitation" for "Meteo France" source

### ISSUE THREAD

**Issue by FoxP** [breezy-weather/breezy-weather#1235]
### Steps to reproduce

On latest version (5.2.6), "Precipitation" data is no more visible for "Meteo France" source.
Example : for "Toulouse" City (France).

### Expected behavior

Get back the "Precipitation data", as it's hard to know if it will rain or not then. :-)

### Actual behavior

Chance source to "Open Meteo" fixes the issue.

### Weather source used

Meteo France

### Breezy Weather version

5.2.6

### Android version

Android 14

### Device

Google Pixel 7 Pro

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open OR closed issue.
- [X] I checked that my issue is not covered in the [Frequently Asked Questions](https://github.com/breezy-weather/breezy-weather/blob/main/HELP.md) document.
- [X] I have updated the app to **[version 5.2.6 or later](https://github.com/breezy-weather/breezy-weather/releases/latest)** and I can reproduce the issue in this version.
- [X] I wrote my request in English, and any screenshot I attached are also in English (language can be changed from Settings > Appearance), unless my issue only happens with a specific language. I can write in my native language under the English text, if necessary.
- [X] I understand that this app is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY, so I may not get a positive reply to my request, if any at all.

**Comment by papjul** [comment]
I don't know which precipitation data you're talking about, but I can see precipitation in Lyon today with Météo France.

**Comment by FoxP** [comment]
You are right, it is now fixed on all my phones (without updating the Breazy Weather app). 🫨 
It was probably due to the Meteo France API ?

**Comment by papjul** [comment]
Forecast can change. Maybe the most probable scenario back then was a scenario with no precipitation expected, and now the most probable scenario is one with precipitation. In any case, there is no reason to think there was any issue, it's totally possible to have a dry summer with no precipitation.

**Comment by FoxP** [comment]
@papjul : reproduced this morning for Toulouse (France) city : "Precipitation" tab is missing

Meteo France : 
![Screenshot_20240802-090501](https://github.com/user-attachments/assets/f8dfb73d-c769-412a-af71-3bd93d342f3b)

AccuWeather : 
![Screenshot_20240802-090438](https://github.com/user-attachments/assets/09f863c4-76f6-45be-b8fc-0215ce54929e)

**Comment by papjul** [comment]
Like I told you, nothing wrong. It's not because AccuWeather thinks it will rain that Météo-France needs to think the same.

**Comment by FoxP** [comment]
But Meteo-France also predicts rain...

![image](https://github.com/user-attachments/assets/951f36af-fb94-4794-8fa2-9648340c4f79)

**Comment by papjul** [comment]
I don't know why they show a rain icon when there is a 20% probability this scenario will happen.

If chance of rain is 20% probable, the most logical thing is that there will be no precipitation, that's why you see no precipitation.

If you look closer the icon is a thunder icon. My theory is that given thunder is the most unpredictable thing in meteorology BUT can be dangerous, they prefer showing thunder to avoid any risk, even if chances it will happen are low.
