### ISSUE TITLE
Weather icon packs (from chronus) compatibility issues.

### ISSUE THREAD

**Issue by AxiK101** [breezy-weather/breezy-weather#1244]
### Steps to reproduce

1.Install an icon pack for chronus via Google play store.
2.Go to settings and check it.
3.Refresh weather and see if the new icons appear.

### Expected behavior

All weather icon packs should be supported

### Actual behavior

Many icon packs do not be recognized, instead default icons be applied.
![20240808-143542](https://github.com/user-attachments/assets/aea4de6c-0715-4f20-badc-59d0188ad107)
![20240808-143528](https://github.com/user-attachments/assets/aba3d6b1-8c81-49b9-aad3-18b5bb2ea9a9)
![20240808-143514](https://github.com/user-attachments/assets/ded7ef4a-17c1-48ed-a907-4366251b49ea)
![20240808-143455](https://github.com/user-attachments/assets/fe95ac3f-c539-420c-a052-90693a2f16fa)

### Weather source used

AccuWeather

### Breezy Weather version

5.2.6

### Android version

Android 14 HyperOS

### Device

Xiaomi Mi 11i

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open OR closed issue.
- [X] I checked that my issue is not covered in the [Frequently Asked Questions](https://github.com/breezy-weather/breezy-weather/blob/main/HELP.md) document.
- [X] I have updated the app to **[version 5.2.6 or later](https://github.com/breezy-weather/breezy-weather/releases/latest)** and I can reproduce the issue in this version.
- [X] I wrote my request in English, and any screenshot I attached are also in English (language can be changed from Settings > Appearance), unless my issue only happens with a specific language. I can write in my native language under the English text, if necessary.
- [X] I understand that this app is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY, so I may not get a positive reply to my request, if any at all.

**Comment by papjul** [comment]
Can you share the link to one Chronus icon pack where you experience the issue?
