### ISSUE TITLE
Crash when automatic update is performed after app start while battery saver is active

### ISSUE THREAD

**Issue by min7-i** [breezy-weather/breezy-weather#125]
### Steps to reproduce

1. Add the daily widget to your home screen with the last update time as subtitle.
2. Go to Breezy Weather settings.
3. Set the refresh interval to 30 minutes.
4. Go back to the main screen.
5. Pull to refresh.
6. Close the app. (remove it from the recent apps)
7. Set a timer around the time when the next refresh should happen (~30 min.).
8. Activate the battery saver mode of your phone. (This should prevent the app from performing the next refresh in the background.)
10. After 30 min. have passed, check the last update time on the daily widget.
11. If that was more than 30 min. ago, open the app.
12. The weather data is updated and the snackbar "Updated in background" is displayed.
13. If the background animation is on, it will start lagging.
14. The app force closes / crashes.

https://github.com/breezy-weather/breezy-weather/assets/97251923/d3b6f181-0006-4fc4-9739-6e44ff688f4b

### Expected behavior

While battery saver mode is active, the weather data is updated after the app has been opened without causing a crash.

### Actual behavior

The weather data is updated, but shortly afterwards the app crashes (see steps 13, 14).

### Weather provider used

Open-Meteo

### Breezy Weather version

4.1.0-beta

### Android version

Android 13 (GrapheneOS)

### Device

Google Pixel 6a

### Other details

App settings
- Update method: Android worker; didn't test the alternative
- Widget on home screen (text and daily widget); didn't test it without widgets
- Background animation: system default (enabled); other animations disabled

Android settings
- App battery usage setting for Breezy Weather: optimized
- No other battery saver apps; just the default Android battery saver

I've experienced this crash in a previous alpha version, but couldn't reproduce it back then. Thus, I'd say it's not related to the changes that came with 4.1.0-beta. (I also didn't try to reproduce it in Geometric Weather.)

I reopened the app after the crash and tried to get a crash log via the debug menu, but this is all it contained:

```
--------- beginning of main
07-09 10:02:56.973   673   673 E g.breezyweather: Not starting debugger since process cannot load the jdwp agent.
07-09 10:02:57.217   673   673 E cutils-trace: Error opening trace file: No such file or directory (2)
07-09 10:02:57.455   673   673 E org.breezyweather: Unable to find pattern file or unable to map it for am
07-09 10:02:57.935   673   730 E cutils-trace: Error opening trace file: No such file or directory (2)
07-09 10:03:18.287  1992  1992 E g.breezyweather: Not starting debugger since process cannot load the jdwp agent.
07-09 10:03:18.386  1992  1992 E cutils-trace: Error opening trace file: No such file or directory (2)
07-09 10:03:18.481  1992  1992 E org.breezyweather: Unable to find pattern file or unable to map it for am
07-09 10:03:18.840  1992  2037 E cutils-trace: Error opening trace file: No such file or directory (2)
App version: 4.1.0-beta (standard, 40100
Android version: 13 (SDK 33)
Android build ID: TQ3A.230705.001.2023070500
Device brand: google
Device manufacturer: Google
Device name: bluejay
Device model: Pixel 6a
Device product name: bluejay
```

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to **[latest version](https://github.com/breezy-weather/breezy-weather/releases/latest)**.

**Comment by papjul** [comment]
I do have this snackbar "Updated in background" from time to time, but I don’t experience any lag or crash when this happens.

Can you try the specific following steps?
1. Update to 4.1.1-beta which contains certain logic changes regarding updates, especially on widgets
2. Turn off battery saving mode and redo the test
3. If it works, turn on "No restriction" for this app optimization, and turn on "Battery saving" mode

And tell me the result of 2 and 3.

**Comment by papjul** [comment]
Additionally, from what I can see on video, and given you have no crash log, it seems to me that the app is not crashing but your battery saver is just killing the app because it’s doing too heavy work and you requested to save battery life.

Please make sure that both "Always show crash dialogue" and "Show background ANRs" are enabled in [Android developer settings](https://developer.android.com/studio/debug/dev-options).

**Comment by papjul** [comment]
I couldn't reproduce by following exactly your step-by-step, battery optimized for this app and battery-saving enabled. Note that I did the test on 4.1.1-beta.

If the problem is still there on 4.1.1-beta for you, and you followed steps from my previous comments, then please check upstream on GrapheneOS known issues about battery saving mode.
