### ISSUE TITLE
Add option to temp units to have both F and C displayed

### ISSUE THREAD

**Issue by Batcastle** [breezy-weather/breezy-weather#1251]
I understand this is a niche use case, but the idea is to have the ability, at least in the header, to have both Fahrenheit and Celsius temperatures displayed.

The reason I want this added, is for people in the US trying to learn Celsius. But also it can help if you talk to people in the US or travel a lot and need to convert the temp. I understand this can take up a lot of extra space, and potential require a massive redesign, which is why I am only asking for this in the header.

Thank you for the consideration!

**Comment by papjul** [comment]
Please use the Idea template next time ;)

Duplicate of #961
