### ISSUE TITLE
[AccuWeather for China]still  Wrong unit for nowcasting resulting in small values in the chart

### ISSUE THREAD

**Issue by bush911** [breezy-weather/breezy-weather#1257]
### Steps to reproduce

  #1233  has reported similar issue regarding China source.
When it is raining or it is about to rain:
 1. Change Precipitation now casting source into AccuWeather.
 2. Check the Precipitation chart.

### Expected behavior

the chart should be like the following chart from China source, which lately be fixed by 5.2.7
![Screenshot_20240815-082232](https://github.com/user-attachments/assets/9eebbfa0-2ade-4021-a342-e8658969d8aa)

### Actual behavior

But I actually saw the chart like this:
![Screenshot_20240815-082303](https://github.com/user-attachments/assets/66dae04b-53a6-40b5-8a94-f7c92bbac5a6)

The 2 screenshots were taken at almost the same time, at the same location, except different Precipitation casting source

### Weather source used

AccuWeather for Precipitation casting source, China or AccuWeather for main source 

### Breezy Weather version

5.2.7

### Android version

Android 14

### Device

Pixel 6

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open OR closed issue.
- [X] I checked that my issue is not covered in the [Frequently Asked Questions](https://github.com/breezy-weather/breezy-weather/blob/main/HELP.md) document.
- [X] I have updated the app to **[version 5.2.7 or later](https://github.com/breezy-weather/breezy-weather/releases/latest)** and I can reproduce the issue in this version.
- [X] I wrote my request in English, and any screenshot I attached are also in English (language can be changed from Settings > Appearance), unless my issue only happens with a specific language. I can write in my native language under the English text, if necessary.
- [X] I understand that this app is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY, so I may not get a positive reply to my request, if any at all.

**Comment by papjul** [comment]
The unit of AccuWeather rainfall is dbz. I double checked the formula to convert dbz to mm/h and it is correct. There is no issue.

Additionally, two sources don't necessarily have tge same data, and I don't consider the China source a reference given we have no documentation of the unit used and it was just a guess it was mm and not mm/h in the previous issue.

**Comment by bush911** [comment]
> The unit of AccuWeather rainfall is dbz. I double checked the formula to convert dbz to mm/h and it is correct. There is no issue, this is just a light rain, and values are not "very small", just normal for a light rain.
> 
> Additionally, two sources don't necessarily have the same data, and I don't consider the China source a reference given we have no documentation of the unit used and it was just a guess it was mm and not mm/h in the previous issue.
Thank you!
**I will double check and let you know, the following is just for your information.**
I don't know anything about coding. But at the time I took screenshots, It was raining moderately, not small rain. The AccuWeather Precipitation chart is not supposed to be very small. I should have taken the full screenshot.

**Comment by papjul** [comment]
> at the time I took screenshots, It was raining moderately, not small rain

Despite its name, AccuWeather doesn't guarantee any accuracy. Additionally, what you consider "Moderate" rain might be considered "Light" in our scale. 2 mm/h (as seen in your screenshot) is considered moderate in some scales.
