### ISSUE TITLE
App detected as malicious by some antivirus

### ISSUE THREAD

**Issue by papjul** [breezy-weather/breezy-weather#1268]
**Update: So far, Avast and Norton recognized it was a false positive.**

If you *still* experience issues with another antivirus provider, please report a false positive. You can backup your claim with the following:
- App is open source and built with a GitHub CI, guaranteeing it matches the source code which can be audited by anyone
- If they can provide the class they detected as doing something malicious (which will be obfuscated due to minifying), we can track back the class in the original source code with the [mapping file provided with each release](https://github.com/breezy-weather/breezy-weather/releases) to see exactly what triggers the antivirus, and maybe adjust our algorithm if relevant

___

VirusTotal v5.2.5 - ~~1/70~~ 0/70 now: https://www.virustotal.com/gui/file/0a8f49667cd298ea0e1e0ddca53a04848685c24001639f687a679eb64c840619

VirusTotal v5.2.6 - 4/70: https://www.virustotal.com/gui/file/d1264227d6c6732a2b113bbfdff44ac47a77836bc8216b3ab201aaf5e93cf87c

VirusTotal v5.2.7 - ~~4/70~~ 1/70 now: https://www.virustotal.com/gui/file/4696108cc41771c7322f4e5937632c5d212e30cad2450d6fd4080505a7fa1e2c

| Vendor | Version | Contacted |
|---|---|---|
| Avast-Mobile | ~~5.2.5+~~ ~~5.2.6 only~~ None, now | Yes (@papjul), on 2024-08-22 |
| Avira (no cloud) | ~~5.2.6+~~ 5.2.6 only | Not to our knowledge |
| Cynet | ~~5.2.6+~~ 5.2.6 only | Not to our knowledge |
| Symantec Mobile Insight | 5.2.6+ | Not to our knowledge |
| WithSecure | ~~5.2.6+~~ 5.2.6 only | Not to our knowledge |

### Breezy Weather version

Since ~~5.2.5~~ 5.2.6

### Other details

Changelog between v5.2.5 and v5.2.6:
https://github.com/breezy-weather/breezy-weather/compare/v5.2.5...v5.2.6

I see nothing suspicious, dependencies must be investigated.

~~What's curious is that the number of antivirus detecting a malicious file increase with each version, why is that? If something suspicious was introduced in v5.2.5, the signature of that suspicious behavior should be equally detected on each version. Could it be a newer detection of each antivirus, and they have some sort of caching and they flag as negative if the previous analysis was successful?~~

Now they all show up as malicious starting from v5.2.6

**Comment by demanuPL** [comment]
My phone also detected it as maleware, I'm attaching the screenshot (its in Polish language)
![Screenshot_20240821_225020_com huawei systemmanager](https://github.com/user-attachments/assets/779daf02-bad4-4c05-817d-a98d2a568ff8)

**Comment by papjul** [comment]
> it detects as collecting data or excessive permissions

Can you share that report? Which data, which permissions?

**Comment by papjul** [comment]
Thank you, we now have a more homogeneous report, all 5 companies report malicious in v5.2.6 and v5.2.7 equally, and nothing in v5.2.5.

**Comment by papjul** [comment]
I asked for a detailed report to Avast (I would be particularly interested if it is due to a dependency), I didn't receive a reply yet, but so far, a few companies recognized it was a false positive.

So what I suggest for now if you still experience an issue is to report a false positive to your antivirus provider. You can backup your claim with the following:
- App is open source and built with a GitHub CI, guaranteeing it matches the source code which can be audited by anyone
- If they can provide the class they detected as doing something malicious (which will be obfuscated due to minifying), we can track back the class in the original source code with the [mapping file provided with each release](https://github.com/breezy-weather/breezy-weather/releases) to see exactly what triggers the antivirus, and maybe adjust our algorithm if relevant

**Comment by Robin42069-cpu** [comment]
![Screenshot_20240823_160616_Surfshark](https://github.com/user-attachments/assets/0ef79cd9-c11d-4226-9f92-6c7f8fea82f7)

 My surfshark VPN antivirus says this is infected. This is just to help you and inform you on what is giving the false positive. Not me complaining about it. The weird thing is it only popped up in the last few days before it was fine.

**Comment by papjul** [comment]
Please follow instructions from first post to report a false positive to your antivirus vendor.

**Comment by Robin42069-cpu** [comment]
Here was their response. Sorry I couldn't provide more help.
	

Tommy Ruell (Surfshark)

Aug 25, 2024, 06:19 GMT+3

Hey there! 👋
 
Thank you for getting in touch and we hope you're doing well.
 
Unfortunately, we cannot specify that information and fulfill your request due to security measures, therefore, we recommend excluding the Breezy Weather app from the Antivirus scan. 🙏
 
If you have any questions or need additional information, please do not hesitate to ask.

**Comment by papjul** [comment]
"security reasons"? If there is really a malicious behavior in one of my dependencies, they should do the opposite and tell us, so we can fix it and make other open source apps depending on it aware of it!

**Comment by misibacsi** [comment]
virustotal v2. 5.2

![Screenshot_20240826_065605.jpg](https://github.com/user-attachments/assets/e86c99a2-894d-49b4-a583-296c16b1ec46)

**Comment by papjul** [comment]
Thank you for your reports; now only Symantec Mobile Insight still detects latest v5.2.7 as infected.

Since v5.2.6 is still detected as positive, this probably means they whitelist each version manually :(
It's annoying because if some day the app is really infected by a dependency, this means we won't be able to tell the difference between this and the false positive.

Unfortunately, there is nothing we can do, so I will proceed to close the issue as "dependency issue", and I refer you to the first post for ways to report a false positive to your antivirus provider every time there is a new Breezy Weather version.

**Comment by papjul** [comment]
Unrelated to the detection by other antivirus providers, but since yesterday, Sangfor Engine Zero detects all apps depending on [AboutLibraries](https://github.com/mikepenz/AboutLibraries) as infected, which means A LOT of open source apps. Reported here: mikepenz/AboutLibraries#1019

**Comment by LeavingBeta** [comment]
I am using F-Secure antivirus and the Breezy Weather app was just flagged as infected.

The app was installed through F Droid on Android 14.

**Comment by papjul** [comment]
Please install v5.2.7. As you can see, WithSecure no longer flags it as infected: https://www.virustotal.com/gui/file/4696108cc41771c7322f4e5937632c5d212e30cad2450d6fd4080505a7fa1e2c?nocache=1

**Comment by derei** [comment]
Surfshark Antivirus still reporting malware as of Sept 4th, ver. 5.2.7 (ANDROID/AVE.Evo.cuixd).

**Comment by papjul** [comment]
> Surfshark Antivirus still reporting malware as of Sept 4th, ver. 5.2.7 (ANDROID/AVE.Evo.cuixd).

Please follow instructions from first post to report a false positive

**Comment by papjul** [comment]
No longer detected as malicious by any provider since v5.2.8. Please follow instructions from first post to report a false positive if it happens again.
