### ISSUE TITLE
Notification widget malfunction - unable to update (Open-Meteo)

### ISSUE THREAD

**Issue by Moostek** [breezy-weather/breezy-weather#1276]
### Steps to reproduce

Notification widget get a sub-notification telling me that it was unable to update & the temperature in my phone's notification bar is stuck on the night temperature.

### Expected behavior

I expect the notification bar temperature will be the same as the actual temperature. I also expect to do not receive the issue notifications (see below).

### Actual behavior

Notification widget getting a sub-notification telling me that it was unable to update. The temperature in my phone's notification bar is stuck on the night temperature (20°C), while the actual daily temperature is 30°C, So it does not show the actual temperature in the notification bar. But in the app itself and in the notification widget (after I expand the widget for a day/week overview), the actual temperature works correctly (it shows 30°C).  

When i click on this sub-notification for more information, i get this message in my web browser: "Errors during refresh. ! Open-Meteo: Expiry of the time limit for the request - current location"

I kept the Weather sources on the default values and the location service is allowed, of course. 

Can you examine this and fix it, please? 

### Weather source used

Open-Meteo

### Breezy Weather version

5.2.7_freenet

### Android version

Android 12

### Device

Samsung Galaxy S10

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open OR closed issue.
- [X] I checked that my issue is not covered in the [Frequently Asked Questions](https://github.com/breezy-weather/breezy-weather/blob/main/HELP.md) document.
- [X] I have updated the app to **[version 5.2.7 or later](https://github.com/breezy-weather/breezy-weather/releases/latest)** and I can reproduce the issue in this version.
- [X] I wrote my request in English, and any screenshot I attached are also in English (language can be changed from Settings > Appearance), unless my issue only happens with a specific language. I can write in my native language under the English text, if necessary.
- [X] I understand that this app is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY, so I may not get a positive reply to my request, if any at all.

**Comment by papjul** [comment]
The notification-widget is updated after a successful refresh, not when it failed (in which case we don't have the newer data necessary for updating the notification-widget). See also documentation: https://github.com/breezy-weather/breezy-weather/blob/main/docs/UPDATES.md

"Request time out" means that it failed to contact Open-Meteo server after 30 seconds of trying. Please check your Internet connection or retry later.

**Comment by Moostek** [comment]
Ok, I understand. In such cases the problem is on my side (internet connection). Or possibly it can be the issue on weather provider too.
