### ISSUE TITLE
Snackbar is partly behind navigation bar [Android 9]

### ISSUE THREAD

**Issue by min7-i** [breezy-weather/breezy-weather#128]
### Steps to reproduce

This is probably only happening on older Android versions. I tested this on my LG G6 running Android 9.

1. Go to settings => appearance.
2. Change the app language.
3. A snackbar is displayed.

### Expected behavior

The entire snackbar should be displayed above the navigation bar.

### Actual behavior

The snackbar is partly behind the navigation bar which makes it tricky to tap on the action; in this case the restart action.

![Image_1.jpg](https://github.com/breezy-weather/breezy-weather/assets/97251923/dcbee7d1-336c-477e-bf8d-d2b83cad101c)

### Weather provider used

n/a

### Breezy Weather version

4.1.1-beta

### Android version

Android 9

### Device

LG G6

### Other details

On my Pixel 6a (Android 13) snackbars are properly displayed above the navigation bar.

I could reproduce this behavior in Geometric Weather on my LG.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to **[latest version](https://github.com/breezy-weather/breezy-weather/releases/latest)**.

**Comment by papjul** [comment]
Can you reproduce in Geometric Weather (you can have a snackbar by changing Language preference)?

**Comment by min7-i** [comment]
I suppose the remark about Geometric Weather was lost among the other information :smile:

Here's a screenshot from Geometric Weather:
![Image_0.jpg](https://github.com/breezy-weather/breezy-weather/assets/97251923/d67b7037-ee16-467a-8b6e-7a47929b83f1)

**Comment by papjul** [comment]
Snackbar used by the app is a customized one (I don’t know why).
I believe if we switch to official Material 3 libs, it would be fixed
