### ISSUE TITLE
Temperature does not refresh in the Notification bar

### ISSUE THREAD

**Issue by Moostek** [breezy-weather/breezy-weather#1284]
### Steps to reproduce

The notification bar does not show actual weather temperature. It shows the last one before the network failure.

### Expected behavior

I expect the actual temperature in notification bar according to actual refresh. 

### Actual behavior

Hello, from time to time I face failure of the network because of temporarily weak signal, so I get the Breezy Weather notification telling me that it was unable to refresh the actual weather state (I use 1,5h interval). But the problem is, that the old temperature stays in the notification bar, even the network was established and there were several new successful refreshes. I also have to note, that inside the app the weather refresh works well (it is not stuck), and when I tap the app icon or notification widget, the actual temperature is refreshed. Well, it seems that the only way to update my notification temperature icon is the manual way: tap on forecast area in the notification widget. I am not sure, but there might be an interaction with daily forecast notification.

### Weather source used

Open-Meteo

### Breezy Weather version

5.2.7_freenet

### Android version

Android 12

### Device

Samsung Galaxy S10

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open OR closed issue.
- [X] I checked that my issue is not covered in the [Frequently Asked Questions](https://github.com/breezy-weather/breezy-weather/blob/main/HELP.md) document.
- [X] I have updated the app to **[version 5.2.7 or later](https://github.com/breezy-weather/breezy-weather/releases/latest)** and I can reproduce the issue in this version.
- [X] I wrote my request in English, and any screenshot I attached are also in English (language can be changed from Settings > Appearance), unless my issue only happens with a specific language. I can write in my native language under the English text, if necessary.
- [X] I understand that this app is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY, so I may not get a positive reply to my request, if any at all.

**Comment by papjul** [comment]
I'm not sure to understand: if it failed to refresh, the temperature in the notification is not "old", it's the one from the last successful refresh, right?

The temperature in the notification bar is updated after a successful refresh, because when it failed, we just don't have any newer data, we keep the latest data.

**Comment by Moostek** [comment]
It is hard to describe this issue as I am sure about the principle of this issue. But I found that the daily weather forecast in notification widget has something to do with this. I found that until I delete the daily notification, the temperature in notification bar is not actual one, but the one from the daily forecast - so this is the one thing. 

The other thing is that if the internet connection is lost in scheduled time for the refresh, I expect that the temperature in notification bar will be automatically updated in nearest upcoming refresh interval. But as mentioned above, there is probably an interaction with daily forecast message that blocks to see actual temperature in notification bar (until I delete the daily forecast in the notification widget area).

**Comment by papjul** [comment]
Are you talking about "Notification for the day's forecast"? There is no temperature icon on this one, only on the notification-widget. The icon for the day's forecast is just a basic cloud icon.

If you have two notifications (notification-widget and notification of the day's forecast), Android merges the two notifications and will only display the icon of one of them in the notification bar as you can see from the small bar on top of them here:
![IMG_20240912_081347](https://github.com/user-attachments/assets/ab2948e7-0eb0-4a5a-884c-030a46b0d1f9)

If you experience something else, please attach a screenshot in English showing the issue.

**Comment by papjul** [comment]
Are you talking about this issue where the grouped icon doesn't match any of the two notifications?
![IMG_20240912_083128](https://github.com/user-attachments/assets/0db44d16-4e2b-431c-b42b-7dbacb612ea6)

Breezy Weather does not group notifications or choose the icon Android decides to keep, we just send our notifications to the Android notification manager. If that's the issue you encounter, please check the [Android issue tracker](https://issuetracker.google.com/issues?q=Android) for existing issues (or create a new issue), and report back here for other users experiencing the same issue.

**Comment by Moostek** [comment]
Yes, I know that it is not grouped, of course. Sure, the daily forecast notification has different temperature from up to date temperature in let s say 2PM. All I say is that the daily forecast somehow blocks the actual temperature in notification bar - it shows the temperature from daily forecast widget in the notification bar -  until I delete the daily forecast.

**Comment by papjul** [comment]
I'm completely lost now; if you use the "daily forecast notification" terms for both the notification-widget and the notification for the day's forecast, it's hard to understand.

There is no such thing as "temperature icon in statusbar", it's actually an icon for each notification, and when there are more than 1 notification, only one of them is shown in the statusbar by Android.

Please explain with the correct terms and with screenshots in English the issue you encounter and what you expect exactly.

**Comment by Moostek** [comment]
English is not my native language, I am sorry. Status Bar = Notification area, the stripe on upper side of the display, the area where are icons like time, wi-fi, battery and also temperature. Daily forecast = the forecast which I get every day (I have set up this on 7AM). Until I delete the Daily forecast notification from notification section, I do not see actual temperature in the Status bar.

**Comment by papjul** [comment]
How different is it from the Android issue I mentioned about the grouped icon not matching any of the two notifications icons?

**Comment by Moostek** [comment]
Well, I do not know how to described it better. I tried to describe the issue in my previous posts, that is all I can do, I guess.

**Comment by papjul** [comment]
So it's not the same issue?

> Well, I do not know how to described it better.

I asked twice for screenshots. An image is worth a thousand words, as we say ;)

**Comment by Moostek** [comment]
No, it is another issue. As described. It is about the temperature in the "status bar" - as I tried to explain above.

**Comment by papjul** [comment]
>> It is about the temperature in the "status bar"

> There is no such thing as "temperature icon in statusbar", it's actually an icon for each notification, and when there are more than 1 notification, only one of them is shown in the statusbar by Android.

**Comment by Moostek** [comment]
No, I can see the temperature in the "status bar", it is temperature from BreezyWeather. I do not use any other weather app. The temperature icon is in the company of other icons as time, strength of wi-fi signal, time etc.

**Comment by papjul** [comment]
We have a translation issue here, please re-read carefully what I wrote. It's not just a temperature in the statusbar, it's an icon coming from a notification. So if you only focus on the statusbar and not on the notifications, we will never understand each other.

Anyway, please send screenshots so I can understand: notifications + statusbar + main screen of the app. All of them in English. Thanks

**Comment by Moostek** [comment]
I am sorry, I tried to help, but I have no time for this yet.

**Comment by papjul** [comment]
Alright, then I will close the issue as we are unable to do anything due to lack of information. Feel free to re-open a new issue later with the missing infos, whenever you have time ;)

**Comment by Moostek** [comment]
Do not be touched with my words of lack of my time. It seems you are unpatient. I explained it all. And it seems it was wasted time here. So in the meantime, I will get back to other app, which works correctly. When it will be fixed, I will gladly return to BreezyWeather.

**Comment by papjul** [comment]
No, I just don't want to leave open something we are not even sure is a Breezy Weather bug (with the little informations I have, I cannot reproduce anything caused by the app).

I think saying that I wasted your time and that I lack patience is a complete lack of respect towards someone doing this app and this support for you for free on his free time.

I was patient, I spent a lot of time trying to understand your issue, but you didn't provide the necessary informations for the investigation despite being asked 4 times to provide the screenshots of real-life examples. You're the only one responsible for the waste of your time and mine by not providing the missing pieces of information...

**Comment by Moostek** [comment]
I did not wasted my time by myself. I explained (or at least tried to explain) this issue twice, maybe three times. The patience is desired from both sides here. You managing it here, you close it, etc. Note that some issues are hard to explain. So for now, I switch to other weather app.

**Comment by papjul** [comment]
Yes, it's correct you tried to explain multiple times, but because we are having translation issues, I asked for screenshots that would help us understand each other. I'm pretty sure the issue is *much* simpler to understand in screenshots than in words.

The way we manage issues is only maintainers to decide. It's not just you; when users don't provide the missing informations, we close it because:
- the issue cannot be investigated (especially in device-specific issues, which might be your case)
- the user no longer uses the app
- the issue is potentially fixed in a newer version
- etc

So if we are in one of these cases, we close it to not clutter the issue list, and help maintainers have in sight things where actions can be done. It doesn't mean your issue *doesn't* exist. In fact, if someone else experiences the same issue, they can just open a new issue, and we will redo the investigation

**Comment by Moostek** [comment]
Yes, I understand, I will try to get back to the issue with some printscreens when I have more time.
