### ISSUE TITLE
Pirate Weather

### ISSUE THREAD

**Issue by kkfong** [breezy-weather/breezy-weather#129]
### Describe your suggested feature

Is there anyway to support this additional weather provider : pirate weather?

https://pirate-weather.apiable.io/

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to **[latest version](https://github.com/breezy-weather/breezy-weather/releases/latest)**.

**Comment by papjul** [comment]
Yes, please have a look at: https://github.com/breezy-weather/breezy-weather/blob/main/CONTRIBUTE.md

**Comment by papjul** [comment]
I got no reply so I tagged your issue as "Open to contributions" but if you want to work on it, let me know and I will remove it to avoid two persons working on the same provider at the same time.

**Comment by kkfong** [comment]
So sorry for the late reply
been super busy IRL
I am not really a software developer, but I did read your documentation

and after reading the code, I THINK I can copy/paste my way

However, I can't make any commitment when (or if) this may be done
and I certainly could come across some technical road block that stop me from moving forward

If others more capable want to take on this, please go ahead

Again, I will work on it, just not sure if I can finish it

BTW, appreciate how your current codebase work for weather provider.  Makes it somewhat easy for someone with my technical background to make changes

**Comment by papjul** [comment]
Yes, I made some efforts to make sure that all weather sources are now "self-contained" and that you have almost nothing to touch to core code of the app. I remember when I contributed my first source to this app, I add to modify so many files everywhere haha

If you are a novice, I will suggest to wait for #180 to be completed. This will give you much less work.

**Comment by papjul** [comment]
Implemented, will be available in next version.
