### ISSUE TITLE
Rainy weather icon no difference between heavy rain and light rain?

### ISSUE THREAD

**Issue by xfdyd** [breezy-weather/breezy-weather#1290]
### Steps to reproduce

Open the main interface.

### Expected behavior

There should be light, moderate, and heavy rain icons, and the difference is displayed.

### Actual behavior

Including hourly forecasts, and daily forecasts, the rain icons are all heavy rain, there is no difference.

### Weather source used

It's all the same.

### Breezy Weather version

5.7.0 freenet

### Android version

android 13

### Device

lebest l23 pro

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open OR closed issue.
- [X] I checked that my issue is not covered in the [Frequently Asked Questions](https://github.com/breezy-weather/breezy-weather/blob/main/HELP.md) document.
- [X] I have updated the app to **[version 5.2.7 or later](https://github.com/breezy-weather/breezy-weather/releases/latest)** and I can reproduce the issue in this version.
- [X] I wrote my request in English, and any screenshot I attached are also in English (language can be changed from Settings > Appearance), unless my issue only happens with a specific language. I can write in my native language under the English text, if necessary.
- [X] I understand that this app is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY, so I may not get a positive reply to my request, if any at all.

**Comment by papjul** [comment]
Not a bug
