### ISSUE TITLE
Closing weather sources dialog also closes edit location dialog

### ISSUE THREAD

**Issue by ecawthorne** [breezy-weather/breezy-weather#1298]
### Steps to reproduce

1. Open edit location dialog
2. Open weather sources dialog
3. Press either cancel or save

### Expected behavior

Only the weather sources dialog should close.

### Actual behavior

The weather sources closes and then the edit location dialog also closes.

### Weather source used

AccuWeather

### Breezy Weather version

5.2.7

### Android version

Android 14

### Device

Pixel 6 Pro

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open OR closed issue.
- [X] I checked that my issue is not covered in the [Frequently Asked Questions](https://github.com/breezy-weather/breezy-weather/blob/main/HELP.md) document.
- [X] I have updated the app to **[version 5.2.7 or later](https://github.com/breezy-weather/breezy-weather/releases/latest)** and I can reproduce the issue in this version.
- [X] I wrote my request in English, and any screenshot I attached are also in English (language can be changed from Settings > Appearance), unless my issue only happens with a specific language. I can write in my native language under the English text, if necessary.
- [X] I understand that this app is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY, so I may not get a positive reply to my request, if any at all.

**Comment by papjul** [comment]
It's not a bug, it's an expected behavior, it saves you a click. If an user change the weather sources, chances are very low they also want to change something else (they can still come back to the preferences otherwise). There are also technical reasons where we need to apply the changes immediately. It's not technically unfeasible but would add some overhead.

**Comment by ecawthorne** [comment]
Makes sense to me. Thanks for the clarification!

**Comment by ecawthorne** [comment]
Sorry to ping you on this again, this dialog also closes the main dialog when the user presses cancel. I looked into it and it seems that removing just this line [this line](https://github.com/breezy-weather/breezy-weather/blob/000ea8d488e27dd95ab00100637ccfad7d15e235/app/src/main/java/org/breezyweather/common/ui/composables/LocationPreferences.kt#L127) would cause it to behave the same way as the other buttons for the edit location dialog.

If you think it's worth the effort I can open a pull request for it. Either way works!

**Comment by papjul** [comment]
Fixed, I just wanted to make sure the changes made before tapping "Cancel" were not kept in memory
