### ISSUE TITLE
Bureau of Meteorology Australia using undocumented API

### ISSUE THREAD

**Issue by lichenophile** [breezy-weather/breezy-weather#1299]
### Link to publicly available documentation of the API

https://api.weather.bom.gov.au/v1/

### Available and not available data

Collection of examples can be found here:
https://github.com/bremor/bureau_of_meteorology/blob/main/api%20doc/API.md

### Are you going to develop yourself the new source for the app?

open to contributions

### Give a bit more details or context about this source

Unlike an old request in this repo for BoM (https://github.com/breezy-weather/breezy-weather/issues/416) which wasn't an API at all, this perhaps is actually usable. I've been using the [Home Assistant Component](https://github.com/bremor/bureau_of_meteorology/) that is using this API for years now and it is reliable.

### Acknowledgements

- [X] I have searched [the existing sources](https://github.com/breezy-weather/breezy-weather/blob/main/docs/SOURCES.md) and [the existing new source requests](https://github.com/breezy-weather/breezy-weather/issues?q=is%3Aissue+label%3A%22New+source%22+no%3Amilestone+-label%3ADuplicate) and this is a new source, **NOT** a duplicate or related to another open OR closed issue.
- [X] This source has a free-tier available (not a trial period), and if it is a main weather source, it includes free hourly forecast
- [X] This source does not require sensitive information (billing info, phone number, etc) to subscribe to the free-tier
- [X] I understand there may be technical limitations that may prevent implementing this source (for example, the lack of coordinates information)
- [X] I wrote my request in English. I can write in my native language under the English text, if necessary.
- [X] I understand that this app is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY, so I may not get a positive reply to my request, if any at all.

**Comment by papjul** [comment]
https://api.weather.bom.gov.au/v1/locations?search=-12.463763,130.844398

> This Application Programming Interface (API) is owned by the Bureau of Meteorology (Bureau). You must not use, copy or share it. Please contact us for more information on ways in which you can access our data. Follow this link http://www.bom.gov.au/inside/contacts.shtml to view our contact details.

This API cannot be used by other people than the BoM. Other apps must use the paid API, as documented by the BoM.
