### ISSUE TITLE
Location access in background "Permission revoked"

### ISSUE THREAD

**Issue by kkfong** [breezy-weather/breezy-weather#130]
### Steps to reproduce

During initial startup, I give the app Location permission : Allow only while using the app, and everything seems to run fine

Once I am insdie the app, I goto Setting -> Location -> "Location access in background"

I give Breey-Weather location permission "Allow all the time"

Now I am back in Breezy-Weather, and I goto Setting -> Location -> "Location access in background",  it now shows "Permission revoked"

### Expected behavior

when I go into Settings -> Location -> Location access in background, and make my selection, I should be able to go back in again to verify my choice, or change it

### Actual behavior

When I go into Settings -> Location -> Location access in background, and make my selection/preferences, and then revisit the same setting again, I get "Permission revoked" message.

### Weather provider used

AccuWeather and OPenWeather

### Breezy Weather version

4.1.0-alpha

### Android version

Android 13 June Update

### Device

Pixel 7 pro

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to **[latest version](https://github.com/breezy-weather/breezy-weather/releases/latest)**.

**Comment by papjul** [comment]
From Android 13, location permissions in settings are switches (below, Android doesn’t allow to revoke permissions).
Just tap again on the permission and you can grant it again.
