### ISSUE TITLE
Notification-widget doesn't show up

### ISSUE THREAD

**Issue by Sirsendu3** [breezy-weather/breezy-weather#1307]
### Steps to reproduce

1 open settings 
2.widget and luve wallpapers
3. Enable:
    a notification widget
    b persistent 
    c temp. as status bar icon
    d use feels like temperature

### Expected behavior

Went to settings enabled the persistent weather Notification and enabled **Use Feels like temperature** . 
A notification should've popped up when I restarted the app or when I enabled the option. 

### Actual behavior

Went to settings enabled the persistent weather Notification and enabled **Use Feels like temperature** . No notification pop up.

### Weather source used

AccuWeather

### Breezy Weather version

Since 5.2.8 (worked before)

### Android version

Android 14

### Device

Realme Narzo 50 Pro

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open OR closed issue.
- [X] I checked that my issue is not covered in the [Frequently Asked Questions](https://github.com/breezy-weather/breezy-weather/blob/main/HELP.md) document.
- [X] I have updated the app to **[version 5.2.8 or later](https://github.com/breezy-weather/breezy-weather/releases/latest)** and I can reproduce the issue in this version.
- [X] I wrote my request in English, and any screenshot I attached are also in English (language can be changed from Settings > Appearance), unless my issue only happens with a specific language. I can write in my native language under the English text, if necessary.
- [X] I understand that this app is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY, so I may not get a positive reply to my request, if any at all.

**Comment by papjul** [comment]
I can't reproduce.

Your steps to reproduce are very specific: do you mean the notification appears, but once you enable "Use feels like temperature", it disappears?

**Comment by Sirsendu3** [comment]
No, it just doesn't appear anymore I tried few times even
unistall-reinstall cycle but nothing changed
After the update the notification just disappeared.
Thanks for listening.

**Comment by papjul** [comment]
So, in your steps to reproduce, steps 3b, c and d are not necessary to reproduce?

> unistall-reinstall cycle but nothing changed

Did you grant notification permissions after re-installing? Can you double check?

**Comment by Sirsendu3** [comment]
I checked notification permissions I did gave it access the 2nd time after
reinstalling but for 1st time it didn't ask permission since it was an
update to older version.

**Comment by papjul** [comment]
Can you share your crash logs?
Settings > Debug

**Comment by Sirsendu3** [comment]
Just pasting all of it here.

--------- beginning of main
09-16 15:00:55.549 28665 28665 E g.breezyweather: Unknown bits set in
runtime_flags: 0x40000000
09-16 15:00:55.553 28665 28665 E g.breezyweather: Not starting debugger
since process cannot load the jdwp agent.
09-16 15:00:55.574 28665 28680 E g.breezyweather: Could not write anonymous
vdex /system_ext/framework/oat/arm64/mediatek-framework.vdex: Could not
open /system_ext/framework/oat/arm64/mediatek-framework.vdex for writing
09-16 15:00:55.669 28665 28665 E SchedAssist: ofbOpen failed with error=No
such file or directory
09-16 15:00:55.669 28665 28665 E SchedAssist: sysOpen failed with error=No
such file or directory
09-16 15:00:55.669 28665 28665 E SchedAssist: sharedImFd failed with
error=Permission denied
09-16 15:00:55.695 28665 28700 E QT      : [QT]file does not exist
09-16 15:00:55.698 28665 28700 E QT      : [QT]file does not exist
--------- beginning of system
09-16 15:00:55.808 28665 28665 E OplusCustomizeRestrictionManager:
sInstance is null, start a new sInstance
09-16 15:00:55.920 28665 28665 E OplusBracketLog: [OplusViewMirrorManager]
updateHostViewRootIfNeeded, not support ***@***.***
09-16 15:00:56.002 28665 28698 E OpenGLRenderer: Unable to match the
desired swap behavior.
09-16 15:00:57.769 28665 28665 E OplusBracketLog: [OplusViewMirrorManager]
updateHostViewRootIfNeeded, not support ***@***.***
09-16 15:00:57.868 28665 28698 E OpenGLRenderer: Unable to match the
desired swap behavior.
09-16 15:00:58.283 28665 28665 E OplusBracketLog: [OplusViewMirrorManager]
updateHostViewRootIfNeeded, not support ***@***.***
09-16 15:00:58.344 28665 28698 E OpenGLRenderer: Unable to match the
desired swap behavior.
09-16 15:00:59.379 28665 28698 E OpenGLRenderer: Unable to match the
desired swap behavior.
App version: 5.2.8 (basic, 7fcc13ce, 50208
Android version: 14 (SDK 34); build RMX3771_14.0.0.900(EX01)
Device brand: realme
Device manufacturer: realme
Device name: RE58B8L1 (RMX3771)
Device model: RMX3771

**Comment by papjul** [comment]
It's #231. In theory, it should already work with SeedVault or Google backup.

**Comment by BraveFalconfromTinyCastle** [comment]
I had the same issue. Restarting the device fixed it.

**Comment by Sirsendu3** [comment]
Ok, thanks for the update. I will try it now after update

**Comment by srmihnev** [comment]
I can confirm the problem with the persistent notifications.
After upgrade few days ago to Android 14 (Nokia X10) the notifications show up in the notification bar when the app is running, but after I lock the phone and few minutes of inactivity after I unlock the phone, there is no notification for the temperature in the status bar.
I have disabled battery optimization, and enabled notification permissions.

Breezy Weather version
5.2.8 (worked before update to Android 14)
Android version
Android 14 (Vendor OTA update)
Device
Nokia X10

**Comment by papjul** [comment]
Solution was provided. Closing as stale
