### ISSUE TITLE
Nowcasting chart overlapping texts of threshold lines

### ISSUE THREAD

**Issue by humpyalpha** [breezy-weather/breezy-weather#1310]
### Steps to reproduce

1. City: Select Songjiang , Shanghai
2. Main source: Select 中国

### Expected behavior

![微信图片_20240916163329](https://github.com/user-attachments/assets/4545bd25-5725-46f4-9546-15747abdd16b)

### Actual behavior

text overlapped

### Weather source used

中国

### Breezy Weather version

breezy-weather-v5.2.8_standard

### Android version

Xiaomi HyperOS 1.0.8.0.UMCCNXM（Android 13）

### Device

Xiaomi 13

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open OR closed issue.
- [X] I checked that my issue is not covered in the [Frequently Asked Questions](https://github.com/breezy-weather/breezy-weather/blob/main/HELP.md) document.
- [X] I have updated the app to **[version 5.2.8 or later](https://github.com/breezy-weather/breezy-weather/releases/latest)** and I can reproduce the issue in this version.
- [X] I wrote my request in English, and any screenshot I attached are also in English (language can be changed from Settings > Appearance), unless my issue only happens with a specific language. I can write in my native language under the English text, if necessary.
- [X] I understand that this app is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY, so I may not get a positive reply to my request, if any at all.

**Comment by papjul** [comment]
What do you suggest to workaround the issue? Should we just hide Light and Medium thresholds when maximum precipitation of the period is above Heavy?

**Comment by humpyalpha** [comment]
Yes, that's definitely a good solution. Besides that option, I think we could use different colored threshold lines to represent Heavy, Medium, and Light. Alternatively, we could use layered backgrounds in different colors instead of threshold lines. These are just some of my preliminary thoughts; you can choose the option you think works best.

**Comment by papjul** [comment]
It already exists, actually.

The light and medium lines are removed when the chart goes above twice the heavy level.
Looks like you have a special font and/or increased font size that doesn't allow you to see texts correctly at levels below "twice the heavy level".
So what I will do is tweak it slightly so that when max precipitation of the chart is:
- Below heavy level: keep all 3 lines
- Between heavy level and 2 * heavy level: keep light and heavy lines
- Above 2 * heavy level: keep heavy line only
