### ISSUE TITLE
AccuWeather show different forecasts for close locations

### ISSUE THREAD

**Issue by zzColin** [breezy-weather/breezy-weather#1313]
### Steps to reproduce

At Shanghai, China, using ip.sb location service and AccuWeather source:
1. Add "Current location" to the location list
   (this will be shown as "Huangpu District", which is a district of Shanghai, in main screen)
2. Add "Huangpu District" of Shanghai, China to the location list
3. Add "Shanghai" of Shanghai, China to the location list

### Expected behavior

Same (or at least similar) forecasts should be shown for the three locations.

### Actual behavior

The "Current location" one is showing completely different forecast from the other two.

### Weather source used

AccuWeather

### Breezy Weather version

5.2.8

### Android version

Android 14

### Device

OnePlus 7 Pro (crDroid 10.8)

### Other details

Relevant Screenshots:

Location list:
![Screenshot_20240917-233917_Breezy Weather](https://github.com/user-attachments/assets/f604c1d9-f529-4e0a-881f-152df7d07cdd)

Current location:
![Screenshot_20240917-233747_Breezy Weather](https://github.com/user-attachments/assets/af9ce955-08bc-45cf-973e-24c5b8a8db36)

Manual location (Huangpu District, Shanghai, China):
![Screenshot_20240917-233758_Breezy Weather](https://github.com/user-attachments/assets/93782d2d-8392-4bf8-a8a1-7809e058b37b)

Manual location (Shanghai, Shanghai, China)
![Screenshot_20240917-233808_Breezy Weather](https://github.com/user-attachments/assets/cf951a0e-ab02-47db-a1a4-7d0d0d297384)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open OR closed issue.
- [X] I checked that my issue is not covered in the [Frequently Asked Questions](https://github.com/breezy-weather/breezy-weather/blob/main/HELP.md) document.
- [X] I have updated the app to **[version 5.2.8 or later](https://github.com/breezy-weather/breezy-weather/releases/latest)** and I can reproduce the issue in this version.
- [X] I wrote my request in English, and any screenshot I attached are also in English (language can be changed from Settings > Appearance), unless my issue only happens with a specific language. I can write in my native language under the English text, if necessary.
- [X] I understand that this app is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY, so I may not get a positive reply to my request, if any at all.

**Comment by zzColin** [comment]
I have also tried other available sources (except OpenWeather which returns "API limit reached"), and none of them are having this issue.

**Comment by papjul** [comment]
IP.SB is a service based on your IP, so it's not supposed to have a great level of accuracy.
You can check by yourself: https://api.ip.sb/geoip
Take the longitude and latitude, and check in an app how far you're from the Huangpu District.

Huangpu District is a different point than the center point of Shanghai which is a very big city.

So in the end, what I mean is that you have 3 different points resulting in 3 different forecasts? Nothing suspicious here.

Also, I'm not sure how Breezy Weather would be involved in the bug you report. I mean, we just show you the data sent by the AccuWeather API?

Please clarify what you expect from us ;)

**Comment by zzColin** [comment]
> IP.SB is a service based on your IP, so it's not supposed to have a great level of accuracy. You can check by yourself: https://api.ip.sb/geoip Take the longitude and latitude, and check in an app how far you're from the Huangpu District.
> 
> Huangpu District is a different point than the center point of Shanghai which is a very big city.
> 
> So in the end, what I mean is that you have 3 different points resulting in 3 different forecasts? Nothing suspicious here.
> 
> Also, I'm not sure how Breezy Weather would be involved in the bug you report. I mean, we just show you the data sent by the AccuWeather API?
> 
> Please clarify what you expect from us ;)

I have already checked ip.sb, and noticed nothing wrong, which is returning Shanghai, China, with latitude and longitude corresponding to some place at Huangpu District.

I also compared the forecast shown for current location "Huangpu District" with manually added "Huangpu District" in my bug report, but they are also completely different. I think at least this is suspicious.

However, strangely though, the issue magically disappeared itself just right now... I'll close it for now and notice if this would happen again. Thanks!

**Comment by papjul** [comment]
I believe AccuWeather updated their forecast between the moment you added the 1st location and the other two?
