### ISSUE TITLE
Live wallpaper preview stays in history after finishing

### ISSUE THREAD

**Issue by ecawthorne** [breezy-weather/breezy-weather#1316]
### Steps to reproduce

1. Open live wall paper preview
2. Press any back button or close breezy weather.

### Expected behavior

When navigating away from the preview I would expect not to have a extra disconnected window left behind

### Actual behavior

The preview stays in the history and can still be accessed after moving away from that screen or closing the main app entirely.

### Weather source used

AccuWeather

### Breezy Weather version

5.2.7

### Android version

Android 14

### Device

Pixel 6 Pro

### Other details

I think this can be fixed by just changing [this line](https://github.com/breezy-weather/breezy-weather/blob/f3ee681534c6acaeb46f4f2070d3576c2a4304c3/app/src/main/java/org/breezyweather/settings/compose/WidgetsSettingsScreen.kt#L115) and [this line](https://github.com/breezy-weather/breezy-weather/blob/f3ee681534c6acaeb46f4f2070d3576c2a4304c3/app/src/main/java/org/breezyweather/settings/compose/WidgetsSettingsScreen.kt#L118) in WidgetsSettingsScreen.kt from:

```Java
.addFlags(Intent.FLAG_ACTIVITY_NEW_TASK))
```

to:

```Java
.addFlags(Intent.FLAG_ACTIVITY_NEW_TASK and Intent.FLAG_ACTIVITY_EXCLUDE_FROM_RECENTS))
```

I'm just opening an issue first because I'm not 100% sure if this is a bug or intended behavior.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open OR closed issue.
- [X] I checked that my issue is not covered in the [Frequently Asked Questions](https://github.com/breezy-weather/breezy-weather/blob/main/HELP.md) document.
- [X] I have updated the app to **[version 5.2.8 or later](https://github.com/breezy-weather/breezy-weather/releases/latest)** and I can reproduce the issue in this version.
- [X] I wrote my request in English, and any screenshot I attached are also in English (language can be changed from Settings > Appearance), unless my issue only happens with a specific language. I can write in my native language under the English text, if necessary.
- [X] I understand that this app is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY, so I may not get a positive reply to my request, if any at all.

**Comment by papjul** [comment]
> I'm just opening an issue first because I'm not 100% sure if this is a bug or intended behavior.

I have no idea neither; I don't use recents.

Muzei does it the same way:
https://github.com/muzei/muzei/blob/6dd2e308f39984efa229b74d1a47b7ad5436c7a6/main/src/main/java/com/google/android/apps/muzei/IntroFragment.kt#L54

Since it's a different app opening, I'm not that surprised it shows separately in recent apps?

**Comment by ecawthorne** [comment]
It might be more of a UX issue than a bug then? The app that it opens isn't normally accessible by users, it can only be launched by other apps. I think from a user's POV it might make sense to only see it as part of the main app instead of as a separate one due to that. It reduces clutter a bit too.

For reference, this is the difference:

[History.webm](https://github.com/user-attachments/assets/3fb3ea3e-0e7e-4df7-964d-00e2e3d5229a)

[No History.webm](https://github.com/user-attachments/assets/0f8639f6-c3ff-4a19-9b84-21d3ce1faddf)

[This line](https://github.com/breezy-weather/breezy-weather/blob/f3ee681534c6acaeb46f4f2070d3576c2a4304c3/app/src/main/java/org/breezyweather/settings/compose/WidgetsSettingsScreen.kt#L115) would also need to add the no history flag.

**Comment by papjul** [comment]
Alright, the changes look good to me, you can submit a PR ;)
