### ISSUE TITLE
Live background for lock screen works only a short time on Fairphone 5

### ISSUE THREAD

**Issue by BuZZ-dEE** [breezy-weather/breezy-weather#1323]
### Steps to reproduce

Set live background also for the lock screen.

### Expected behavior

Lock screen shows the live background for an unlimited time.

### Actual behavior

After a short time the live background is replaced by the default Fairphone 5 background for the lock screen.

### Weather source used

Open-Meteo

### Breezy Weather version

5.2.8_freenet

### Android version

Android 14

### Device

Fairphone 5

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open OR closed issue.
- [X] I checked that my issue is not covered in the [Frequently Asked Questions](https://github.com/breezy-weather/breezy-weather/blob/main/HELP.md) document.
- [X] I have updated the app to **[version 5.2.8 or later](https://github.com/breezy-weather/breezy-weather/releases/latest)** and I can reproduce the issue in this version.
- [X] I wrote my request in English, and any screenshot I attached are also in English (language can be changed from Settings > Appearance), unless my issue only happens with a specific language. I can write in my native language under the English text, if necessary.
- [X] I understand that this app is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY, so I may not get a positive reply to my request, if any at all.

**Comment by papjul** [comment]
Make sure battery optimization for the app is turned off.

If it doesn't help, here is the link to Fairphone support: https://support.fairphone.com/hc/en-us/articles/115001041206-Find-fix-an-issue-yourself

**Comment by BuZZ-dEE** [comment]
@papjul battery optimization for the app is turned off.
