### ISSUE TITLE
[Location search] Add info when no location is found

### ISSUE THREAD

**Issue by min7-i** [breezy-weather/breezy-weather#133]
### Steps to reproduce

1. Open the location search.
2. Enter a search term that'll yield no results, like 'dndnrnnr'.

### Expected behavior

An info, e.g. a snackbar, appears saying that no location was found.

That was the case in earlier alpha version, until and including 4.0.4-alpha:
![location search](https://github.com/breezy-weather/breezy-weather/assets/97251923/0733ee04-34e9-47f5-80d1-4bfb04d76ebb)

### Actual behavior

No information is shown.

### Weather provider used

AccuWeather

### Breezy Weather version

4.1.1-beta

### Android version

Android 13 (GrapheneOS)

### Device

Google Pixel 6a

### Other details

I'm not sure if the removal of the snackbar was intential, but in my opinion showing an info when there are no results would be helpful.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to **[latest version](https://github.com/breezy-weather/breezy-weather/releases/latest)**.

**Comment by papjul** [comment]
The "Failed to find current location" was a mistake, because it did succeed but the result was an empty list.
I guess adding a snackbar saying "No results found" would not hurt.
