### ISSUE TITLE
Rapidly appearing/disappearing 'background services' notification

### ISSUE THREAD

**Issue by Laura7089** [breezy-weather/breezy-weather#1331]
On boot, the app continuously opened and closed a notification, several times per second. Android settings tells me that it's in the "Background services" notification category.

I'm using lineageOS on dumpling, android version 11.

**Comment by Laura7089** [comment]
App version is Stable 5.2.8.

**Comment by papjul** [comment]
Please re-open your issue using templates from the GitHub website: https://github.com/breezy-weather/breezy-weather/issues/new/choose

Add a screenshot of your notification history (enable it first, if it's not already).
