### ISSUE TITLE
Barometric prison bug

### ISSUE THREAD

**Issue by EdgarOns** [breezy-weather/breezy-weather#1341]
### Steps to reproduce

The barometric pressure displayed by the Open-Meteo provider is incorrect compared to that displayed by other applications that also use Open-Meteo.

### Expected behavior

The barometric pressure at sea level is very different from that on a mountain. With altitude, the barometric pressure gradually decreases. Open-Meteo is very accurate with this data. I'll give you an example: I use an application called Rain and that also uses Open-Meteo data. In the city of Madrid right now it indicates a barometric pressure of 945 hP, in La Paz (Bolivia, at 4,000 meters above sea level) it indicates a pressure of 651 hPa and on Mount Everest (at 8,848 meters above sea level) it indicates a pressure of 353 hPa, which is correct and consistent with professional and real meteorological patterns and standards. However, Breezy Weather barely changes the barometric pressure data. In Madrid it indicates a pressure of 1018 hPa, in La Paz it indicates a pressure of 1014 hPa and on Mount Everest it indicates a pressure of 1018 hPa, which is evidently erroneous and inconsistent with reality. It would be interesting to review the Open-Meteo API and source code for this application, update and fix this bug.

### Actual behavior

The Breezy Weather data using Open-Meteo does not correspond to the data that Open-Meteo actually offers in its API for applications.

### Weather source used

Open-Meteo 

### Breezy Weather version

5.2.8

### Android version

Android 13

### Device

Xiaomi Redmi Note 12 Pro

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open OR closed issue.
- [X] I checked that my issue is not covered in the [Frequently Asked Questions](https://github.com/breezy-weather/breezy-weather/blob/main/HELP.md) document.
- [X] I have updated the app to **[version 5.2.8 or later](https://github.com/breezy-weather/breezy-weather/releases/latest)** and I can reproduce the issue in this version.
- [X] I wrote my request in English, and any screenshot I attached are also in English (language can be changed from Settings > Appearance), unless my issue only happens with a specific language. I can write in my native language under the English text, if necessary.
- [X] I understand that this app is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY, so I may not get a positive reply to my request, if any at all.

**Comment by papjul** [comment]
Not a bug. All sources use sea level pressure because that's the standard. See also discussion #429
