### ISSUE TITLE
GPS location is wrong

### ISSUE THREAD

**Issue by EdgarOns** [breezy-weather/breezy-weather#1342]
### Steps to reproduce

1. Error. 2. Correction.

### Expected behavior

Your GPS location should be accurate using the device's GPS positioning + data + high-quality WiFi.

### Actual behavior

The GPS location is obviously wrong. The margin of error is very large. Very imprecise. They should update and review this.

### Weather source used

Open-Meteo, Accuweather, Met Norway and all metrology providers in the app.

### Breezy Weather version

Breezy Weather 5.2.8

### Android version

Android 13

### Device

Xiaomi Redmi Note 12 Pro

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open OR closed issue.
- [X] I checked that my issue is not covered in the [Frequently Asked Questions](https://github.com/breezy-weather/breezy-weather/blob/main/HELP.md) document.
- [X] I have updated the app to **[version 5.2.8 or later](https://github.com/breezy-weather/breezy-weather/releases/latest)** and I can reproduce the issue in this version.
- [X] I wrote my request in English, and any screenshot I attached are also in English (language can be changed from Settings > Appearance), unless my issue only happens with a specific language. I can write in my native language under the English text, if necessary.
- [X] I understand that this app is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY, so I may not get a positive reply to my request, if any at all.

**Comment by papjul** [comment]
> Your GPS location should be accurate using the device's GPS positioning + data + high-quality WiFi.

It's up to you to enable "Precise location" in Android settings. And also make sure you didn't switch the default "Android" option for "Location source" in Breezy Weather settings.

> The GPS location is obviously wrong.

Please show the obvious evidence that it's a GPS issue, and not a weather data issue, since it works fine on other devices.

**Comment by Stzyxh** [comment]
I have an similar Issue in my Fairphone 4 Android 13. The location that is shown is a country and not a city. The GPS works really well in other apps.
I also checked for the "precise location" permission. But its turned on

**Comment by papjul** [comment]
Is the GPS location OR the reverse geocoding wrong? I.e. is the weather correct but the country wrong OR both the weather and country wrong?

**Comment by EdgarOns** [comment]
> > Su ubicación GPS debe ser precisa utilizando el posicionamiento GPS del dispositivo + datos + WiFi de alta calidad.
> 
> Depende de usted habilitar la "Ubicación precisa" en la configuración de Android. Además, asegúrese de no haber cambiado la opción predeterminada "Android" por "Fuente de ubicación" en la configuración de Breezy Weather.
> 
> > La ubicación GPS es obviamente errónea.
> 
> Muestre evidencia obvia de que es un problema de GPS y no de datos meteorológicos, ya que funciona bien en otros dispositivos.

I have precise location and direct location feed enabled on my device. I also always have background location allowed to Breezy Weather, but it's still inaccurate. In fact, the margin of error for the location it shows me is between 1.5 and 3 kilometers from where I live. Maybe it's my device, who knows. It is a Redmi Note 12 Pro purchased less than a year ago.

**Comment by papjul** [comment]
Where does that quote in Spanish comes from?

Otherwise, it's correct, it's Fused precision. It will use neighborhood granularity precision. It ensures a good privacy level by not sending your exact position to your selected weather sources, but precise enough to get the same weather data (or almost the same), and it's battery-friendly as most of the time, it will not require the GPS

**Comment by papjul** [comment]
> The margin of error is very large. Very imprecise.

> the margin of error for the location it shows me is between 1.5 and 3 kilometers from where I live

So it's neither very large or very imprecise, but acceptable from a meteorological forecast point.

I will close this as "Missing documentation" and I will complete the documentation later to avoid similar questions ;)
