### ISSUE TITLE
Add a night background for splash screen

### ISSUE THREAD

**Issue by papjul** [breezy-weather/breezy-weather#137]
### Describe your suggested feature

Currently the app opens with a blue sky in background, however this can be a bit too bright when requesting a dark mode environment.

I suggest adding a "night" background by default (same color as clear night animation), then switch to current blue sky if user prefers the light theme.

The reason is due to this bug: https://stackoverflow.com/questions/63187994/how-to-place-the-splash-screen-for-dark-and-light-mode-in-android

In that case, it’s best to have a dark theme first to not have a bright splash screen that then switch to a darker splash screen.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to **[latest version](https://github.com/breezy-weather/breezy-weather/releases/latest)**.

**Comment by Atn-D** [comment]
Can you propose a non-living background, uni color material you?

**Comment by papjul** [comment]
Splash screen isn't animated, it's just an unicolor background with the logo on top of it.

**Comment by papjul** [comment]
This issue has not been planned yet.

The implementation is the one described in first post.

**Comment by shaft17** [comment]
> Would it be a good idea to simply change the colour `#5F96D0` in the following to `#191B1D`? (or some other colour with a soft/darker hue)

I agree, this would be a quick temporary solution.
But I also do understand that the "branding" of Breezy is the light blue...

**Comment by Korb** [comment]
> the "branding" of Breezy is the light blue...

I’m quite happy if the application is launched by tapping on the blue icon. But if I'm using a device with an AMOLED screen, and prefer to minimize battery consumption, and prefer comfort when using the smartphone in the dark, I prefer to have `#000` as the background, and use the system brightness settings to control the brightness of text and graphics, and only their.

**Comment by papjul** [comment]
> I'm using a device with an AMOLED screen, and prefer to minimize battery consumption

Pure black does not save more battery than gray on multiple hours of test: https://www.xda-developers.com/amoled-black-vs-gray-dark-mode/

I think we can extrapolate the same results with blue on a 500 ms splashscreen.

> and prefer comfort when using the smartphone in the dark, I prefer to have `#000` as the background, and use the system brightness settings to control the brightness of text and graphics, and only their.

The splashscreen is very brief, compared to -let’s say- the weather background on main screen of the app.

For the app, please have a look at #147. However, it’s only to replace the gray background. If you want a pure black and white app and you're a developer, we support [`WeatherSpec` from Gadgetbridge](https://codeberg.org/Freeyourgadget/Gadgetbridge/src/tag/0.80.0/app/src/main/java/nodomain/freeyourgadget/gadgetbridge/model/WeatherSpec.java) that allows you to re-use Breezy Weather data on your own app. We are also working on our own spec that will make more data available.

**Comment by min7-i** [comment]
With #1336 merged, I can submit a PR for this with the following approach:
| Android version | splash screen |
| --- | --- |
| >= 12 | light theme -> light version<br>night theme -> night version |
| < 12 | night version |

----

Should we keep the red splash screen for the debug version? In that case I'd create a night version for that as well.

**Comment by papjul** [comment]
Hmm, let me recall this issue: on Android >= 12, with your fix, the splash screen will no longer blinks, right?
If that's correct, let's leave EoL Android versions with the classic blue light.

For the night version, we can use the same color as the "clear night" animated background. Since it's a gradient from `#141c2c` to `#000000`, you can try either `#141c2c` or the middle value `#0a0e16` and picks the one that suits best.

And yes, for the debug version, we will keep the red splash screen, but in the night version, there needs to be a darker red version, so we can test ;)

Thanks!

**Comment by min7-i** [comment]
> on Android >= 12, with your fix, the splash screen will no longer blink, right?

Correct. Android knows which theme the app uses so the correct version of the splash screen will be applied.
