### ISSUE TITLE
Units setting doesn't allow date display changes

### ISSUE THREAD

**Issue by frigeky00** [breezy-weather/breezy-weather#1385]
### Steps to reproduce

1. Open the app
2. Click on cog wheel
3. Click on Appearance
4. Click on Units

### Expected behavior

The settings (which already allow for localisation such as Celsius/Farenheit, etc.) should allow for date formatting.

### Actual behavior

Date formatting is not possible and the date is always "month/day", even though many users (non-US/UK) might want to display it as "day/month".

### Weather source used

N/A

### Breezy Weather version

Stable 5.2.8

### Android version

N/A

### Device

N/A

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open OR closed issue.
- [X] I checked that my issue is not covered in the [Frequently Asked Questions](https://github.com/breezy-weather/breezy-weather/blob/main/HELP.md) document.
- [X] I have updated the app to **[version 5.2.8 or later](https://github.com/breezy-weather/breezy-weather/releases/latest)** and I can reproduce the issue in this version.
- [X] I wrote my request in English, and any screenshot I attached are also in English (language can be changed from Settings > Appearance), unless my issue only happens with a specific language. I can write in my native language under the English text, if necessary.
- [X] I understand that this app is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY, so I may not get a positive reply to my request, if any at all.

**Comment by papjul** [comment]
Date formatting is not an unit. Date formatting is inherited from your localization. For example, in English, you may want to change your localization to English (US) if you want MM/DD format, or others English such as English (UK) or English (CA) or English (AU) if you want DD/MM.
