### ISSUE TITLE
MetOffice DataHub [UK]

### ISSUE THREAD

**Issue by bunburya** [breezy-weather/breezy-weather#1386]
### Link to publicly available documentation of the API

https://datahub.metoffice.gov.uk/docs/f/category/site-specific/overview

### Available and not available data

Available: Hourly, three-hourly and daily forecasts for temperature, wind, precipitation, humidity, mean sea level pressure, visibility and UV index data. Also provides a short summary of the weather at the given time (via a "[significant weather code](https://www.metoffice.gov.uk/services/data/datapoint/code-definitions)").

Not available: Air quality, pollen, moon phase.

### Are you going to develop yourself the new source for the app?

Yes I am happy to look at developing it (but cannot commit to a timeline so equally happy for others to contribute).

### Give a bit more details or context about this source

The Met Office is the official weather service for the United Kingdom. It has previously been discussed (#923) and was not considered appropriate for inclusion as it required a phone number to get an API key. While the API key registration page does include a field for a phone number, it is not mandatory and not required to obtain a free API key. What is needed is an email address, name, "country of origin" and where you heard about the service.

### Acknowledgements

- [X] I have searched [the existing sources](https://github.com/breezy-weather/breezy-weather/blob/main/docs/SOURCES.md) and [the existing new source requests](https://github.com/breezy-weather/breezy-weather/issues?q=is%3Aissue+label%3A%22New+source%22+no%3Amilestone+-label%3ADuplicate) and this is a new source, **NOT** a duplicate or related to another open OR closed issue.
- [x] This source has a free-tier available (not a trial period), and if it is a main weather source, it includes free hourly forecast
- [X] This source does not require sensitive information (billing info, phone number, etc) to subscribe to the free-tier
- [X] I understand there may be technical limitations that may prevent implementing this source (for example, the lack of coordinates information)
- [X] I wrote my request in English. I can write in my native language under the English text, if necessary.
- [X] I understand that this app is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY, so I may not get a positive reply to my request, if any at all.

**Comment by chunshek** [comment]
Hi @bunburya! Have you started working on this yet?

**Comment by bunburya** [comment]
Hi there, yes I have been working on this. Hoping to have a PR soon(ish).
