### ISSUE TITLE
Unable to add widget to home screen 

### ISSUE THREAD

**Issue by matheucomth** [breezy-weather/breezy-weather#1387]
### Steps to reproduce

When pressing the widget and dragging it to the home screen, nothing happens. Unable to add the widget to the home screen.

https://github.com/user-attachments/assets/3202dbbb-0f36-4122-a076-ccccef3ac169

### Expected behavior

When dragging the widget to the HyperOS desktop, the widget should be added to the home screen.

### Actual behavior

It occurs frequently 

### Weather source used

Open-Meteo

### Breezy Weather version

5.2.8

### Android version

Android 14

### Device

Redmi 12

### Other details

HyperOS 1.0.8

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open OR closed issue.
- [X] I checked that my issue is not covered in the [Frequently Asked Questions](https://github.com/breezy-weather/breezy-weather/blob/main/HELP.md) document.
- [X] I have updated the app to **[version 5.2.8 or later](https://github.com/breezy-weather/breezy-weather/releases/latest)** and I can reproduce the issue in this version.
- [X] I wrote my request in English, and any screenshot I attached are also in English (language can be changed from Settings > Appearance), unless my issue only happens with a specific language. I can write in my native language under the English text, if necessary.
- [X] I understand that this app is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY, so I may not get a positive reply to my request, if any at all.

**Comment by papjul** [comment]
Can you open the app first?

If it still doesn't work, try another launcher maybe?

**Comment by matheucomth** [comment]
I fixed it by downgrading the HyperOS Launcher, apparently it's a Xiaomi bug. Thanks dev.
