### ISSUE TITLE
Badan Meteorologi, Klimatologi, dan Geofisika (Indonesia)

### ISSUE THREAD

**Issue by chunshek** [breezy-weather/breezy-weather#1395]
### Link to publicly available documentation of the API

Undocumented API used by https://cuaca.bmkg.go.id/

### Available and not available data

❌ Daily Forecast
✅ Hourly Forecast (9 days)
✅ Weather Condition
✅ Temperature
✅ Precipitation
❌ Precipitation Probability
✅ Wind
❌ UV
❌ Sun and Moon
❌ Moon Phase
✅ Current
❌ Air Quality
❌ Pollen
❌ Precipitation Nowcasting
✅ Alerts
❌ Temperature Normals
✅ Humidity
❌ Dew Point
❌ Pressure
✅ Cloud Cover
✅ Visibility
❌ Ceiling
❌ Precipitation Duration
❌ Sunshine Duration
❌ Search
✅ Reverse Geocoding

### Are you going to develop yourself the new source for the app?

Yes, coding and testing it at the moment

### Give a bit more details or context about this source

[Badan Meteorologi, Klimatologi, dan Geofisika](https://www.bmkg.go.id/) is the national meteorological agency of Indonesia. It offers hour-by-hour forecasts for Indonesia on a per-coordinate basis on its [weather site](https://cuaca.bmkg.go.id/).

The source also offers two types of weather alerts:
- Nowcasting Warnings for severe weather that lasts a few hours – these are only in Indonesian
- Impact Based Forecasts for severe weather expected to have impact for a whole day (issued up to 3 days in advance) – these are in both Indonesian and English

### Acknowledgements

- [X] I have searched [the existing sources](https://github.com/breezy-weather/breezy-weather/blob/main/docs/SOURCES.md) and [the existing new source requests](https://github.com/breezy-weather/breezy-weather/issues?q=is%3Aissue+label%3A%22New+source%22+no%3Amilestone+-label%3ADuplicate) and this is a new source, **NOT** a duplicate or related to another open OR closed issue.
- [X] This source has a free-tier available (not a trial period), and if it is a main weather source, it includes free hourly forecast
- [X] This source does not require sensitive information (billing info, phone number, etc) to subscribe to the free-tier
- [X] I understand there may be technical limitations that may prevent implementing this source (for example, the lack of coordinates information)
- [X] I wrote my request in English. I can write in my native language under the English text, if necessary.
- [X] I understand that this app is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY, so I may not get a positive reply to my request, if any at all.

**Comment by papjul** [comment]
Merged
