### ISSUE TITLE
India Meteorological Department

### ISSUE THREAD

**Issue by chunshek** [breezy-weather/breezy-weather#1396]
### Link to publicly available documentation of the API

Undocumented API used by https://mausamgram.imd.gov.in/

### Available and not available data

❌ Daily Forecast
✅ Hourly Forecast (10 days)
❌ Weather Condition
✅ Temperature
✅ Precipitation
❌ Precipitation Probability
✅ Wind
❌ UV
❌ Sun and Moon
❌ Moon Phase
❌ Current
❌ Air Quality
❌ Pollen
❌ Precipitation Nowcasting
❌ Alerts
❌ Temperature Normals
✅ Humidity
❌ Dew Point
❌ Pressure
✅ Cloud Cover
❌ Visibility
❌ Ceiling
❌ Precipitation Duration
❌ Sunshine Duration
❌ Search
❌ Reverse Geocoding

### Are you going to develop yourself the new source for the app?

Yes, coding and testing it at the moment

### Give a bit more details or context about this source

[India Meteorological Department](https://mausam.imd.gov.in/) is the national meteorological agency of India. This source was previously mentioned in #1053 but was dismissed as those API links require IP whitelisting.

However, it operates a meteogram service called [Mausamgram](https://mausamgram.imd.gov.in/), where one can obtain hourly forecast data on a per-coordinate basis. The forecast data is offered at a 0.125° × 0.125° spatial resolution, and 1-hourly (up to 1.5 days), 3-hourly (up to 5 days), as well as 6-hourly (up to 10 days) temporal resolutions.

### Acknowledgements

- [X] I have searched [the existing sources](https://github.com/breezy-weather/breezy-weather/blob/main/docs/SOURCES.md) and [the existing new source requests](https://github.com/breezy-weather/breezy-weather/issues?q=is%3Aissue+label%3A%22New+source%22+no%3Amilestone+-label%3ADuplicate) and this is a new source, **NOT** a duplicate or related to another open OR closed issue.
- [X] This source has a free-tier available (not a trial period), and if it is a main weather source, it includes free hourly forecast
- [X] This source does not require sensitive information (billing info, phone number, etc) to subscribe to the free-tier
- [X] I understand there may be technical limitations that may prevent implementing this source (for example, the lack of coordinates information)
- [X] I wrote my request in English. I can write in my native language under the English text, if necessary.
- [X] I understand that this app is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY, so I may not get a positive reply to my request, if any at all.

**Comment by papjul** [comment]
Merged for v5.3.0
