### ISSUE TITLE
background "current location" weather update fails when no GNSS reception

### ISSUE THREAD

**Issue by lmamane** [breezy-weather/breezy-weather#1397]
### Steps to reproduce

1. On a device where GNSS is the only location provided (no Google/WiFi location provider, no Apple UnifiedNlp bacdkend, no LocalWifiNlpBackend, etc)
2. configure breezy weather to upgrade current location weather e.g. every 1.5h
3. give it all permissions to precise locations, etc
4. take the Android device outside of GNSS reception (e.g. indoors no windows)
5. Wait the refresh interval

### Expected behavior

The weather update should (silently) reuse the last known location and fetch weather for that last known location.

### Actual behavior

Weather information is not updated at all, and an error is displayed in notification.

### Weather source used

Open-Meteo

### Breezy Weather version

5.2.8

### Android version

Android 13 - LineageOS

### Device

LE2123 lemonadep OnePlus 9 Pro

### Other details

Location service used: Android

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open OR closed issue.
- [X] I checked that my issue is not covered in the [Frequently Asked Questions](https://github.com/breezy-weather/breezy-weather/blob/main/HELP.md) document.
- [X] I have updated the app to **[version 5.2.8 or later](https://github.com/breezy-weather/breezy-weather/releases/latest)** and I can reproduce the issue in this version.
- [X] I wrote my request in English, and any screenshot I attached are also in English (language can be changed from Settings > Appearance), unless my issue only happens with a specific language. I can write in my native language under the English text, if necessary.
- [X] I understand that this app is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY, so I may not get a positive reply to my request, if any at all.

**Comment by papjul** [comment]
> Weather information is not updated at all, and an error is displayed in notification.

There is an error indeed, but the location is refreshed with last known coordinates. Can you check last refresh time and confirm it didn't refresh?

**Comment by lmamane** [comment]
On Tue, Nov 05, 2024 at 10:18:43AM -0800, Julien Papasian wrote:
> There is an error indeed, but the location is refreshed with last
> known coordinates. Can you check last refresh time and confirm it
> didn&#39;t refresh?

My memory is that I saw it not refreshed (age of larger than refresh
interval), but I cannot reproduce that now. Maybe I was mistaken.

**Comment by papjul** [comment]
Maybe there was an additional error? Such as a network drop, server unavailable, etc.

Anyway, feel free to open a new issue if you can identify a step-by-step ;)
