### ISSUE TITLE
[MET No] Weather data fails to refresh when there is one day with two moonrise

### ISSUE THREAD

**Issue by vodkapmp** [breezy-weather/breezy-weather#141]
### Steps to reproduce

1. Add location north of 63rd parallel (Examples: Reykjavik, Trondheim, Tromsø, Oulu, Rovaniemi)
2. Go back to look at the forecast

### Expected behavior

Adding these locations should show the forecast for them.

### Actual behavior

The error "Weather data refresh failed" shows. And there is no forecast.

### Weather provider used

MET

### Breezy Weather version

4.1.2-beta

### Android version

Android 13, GrapheneOS 2023071100

### Device

Google Pixel 7 Pro

### Other details

These locations do have forecasts on Yr.no, the consumer frontend for METs data.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to **[latest version](https://github.com/breezy-weather/breezy-weather/releases/latest)**.

**Comment by papjul** [comment]
Found that the issue happen when there is at least one day with two moonrise.

This is day 2 for Reykjyavik:
![image](https://github.com/breezy-weather/breezy-weather/assets/1449159/b2056742-dfb9-4095-bde6-494c0d5814b9)

While it could have been easily solved, MET.no API decided to send two different kind of data.
And this is day 1:
![image](https://github.com/breezy-weather/breezy-weather/assets/1449159/545f6964-e1bd-4e4e-8dd7-8988870adeda)

Technically speaking, this mean that the API is sending us a list or a single element.
The correct implementation would have been to always implement a list, even if it is single inside.

Parsing of API is extremely rigid, you can’t expect potatoes and then be delivered a potato and a tomato.

MET.no API is known to have other issues. For example, when sunset ends after midnight, it will put the wrong day.
Example:
2023-07-12
Sunrise: 2023-07-12 03:12
Sunset: 2023-07-12 00:24
Wrong day on sunset.

It seems ironic that the most appropriate weather provider for nordic areas is unable to handle these cases.

So, in the end, I should probably just ditch this API, and implement something like [commons-suncalc](https://github.com/shred/commons-suncalc).

I had a look at other providers:
AccuWeather and OpenWeather won’t show the moonrise from 23:41.

On 2023-07-14, no provider showed any data, including MET.no which showed moonrise on 2023-07-13 but never showed the moonset.

Other providers don’t have this data.

At the moment, the only thing I can suggest is using a different provider. Open-Meteo is known to include MET.no data, but will use a mix of different models to complete missing data.
