### ISSUE TITLE
"Access Location Permission Missing" when location is turned off

### ISSUE THREAD

**Issue by Magicrafter13** [breezy-weather/breezy-weather#1413]
### Steps to reproduce

1. Install app on stock Galaxy S23 Ultra via F-Droid.
2. Add current location as a location source.
3. Enable all location related permissions for the app.

### Expected behavior

Since it has been granted location permission, it should should the weather in my area.

### Actual behavior

Screen stays mostly blank with a with toast message saying "Access Location Permission Missing".

### Weather source used

Default (Open-Meteo)

### Breezy Weather version

5.2.8_freenet

### Android version

Android 14

### Device

Samsung Galaxy S23 Ultra (Verizon)

### Other details

![Screenshot_20241110_104352_Breezy Weather](https://github.com/user-attachments/assets/36d6699c-827f-4fe0-9c41-2a7bb87cc7a0)
![Screenshot_20241110_104405_Permission controller](https://github.com/user-attachments/assets/dad31245-e382-4b54-853d-fe0d8d8ce160)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open OR closed issue.
- [X] I checked that my issue is not covered in the [Frequently Asked Questions](https://github.com/breezy-weather/breezy-weather/blob/main/HELP.md) document.
- [X] I have updated the app to **[version 5.2.8 or later](https://github.com/breezy-weather/breezy-weather/releases/latest)** and I can reproduce the issue in this version.
- [X] I wrote my request in English, and any screenshot I attached are also in English (language can be changed from Settings > Appearance), unless my issue only happens with a specific language. I can write in my native language under the English text, if necessary.
- [X] I understand that this app is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY, so I may not get a positive reply to my request, if any at all.

**Comment by Magicrafter13** [comment]
Welp.

I never turn my location off. Not sure how between now and Thursday it got turned off...

But yeah, that was it...

Is there any way to make the error message reflect that or does missing permission and location-off look the same in the Android API?

**Comment by Magicrafter13** [comment]
Ah, that's unfortunate. Perhaps the system APIs will become more granular at some point. It would be cool if an app with location permission could try to access location while its off, and have the system UI go "this app would like to turn on your location" with an allow/deny button.

**Comment by papjul** [comment]
In #1467, a "Location access is off" was successfully implemented. A button next to the error message will directly take you to the location settings where you can turn it on.

This will be available from next version (v5.3.0).
