### ISSUE TITLE
Rewrite legacy widgets in Material You

### ISSUE THREAD

**Issue by TheTrashCrafter** [breezy-weather/breezy-weather#142]
### Describe your suggested feature

When creating a Widget with Background Color all it does is use white or black, but not Material You themed. The solution would probably look like Googles Widget or Weather Today's widget (both not Foss sadly).

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to **[latest version](https://github.com/breezy-weather/breezy-weather/releases/latest)**.

**Comment by papjul** [comment]
I can’t find the examples you are mentioning. Can you show screenshots?

As you are mentioning background color white/black, I think you are not talking about Material You widgets.
There are 2 available to pick, are they doing what you are looking for with the background?
Others were made in pre-Material You area and will probably be left untouched.
I know original Geometric Weather developer had plans to add more Material You widgets, in case these 2 are not what you are looking for.

**Comment by TheTrashCrafter** [comment]
@papjul Exactly, these two widgets do what I mean, but it's just 2 out of 13. Are you planning on adding Material You to other widgets too?

**Comment by papjul** [comment]
No, I don't plan it myself as it would probably require a full rewrite to take into account the new palette.

If original developer comes back and implements new Material You widgets, they will be merged.

**Comment by papjul** [comment]
Before you ask, basically, we need your idea to be rewritten to cover more cases, either:
- Rewrite legacy widgets in Material You
- Have new Material You widgets

Once you picked up one of these two, please update your title and description so that I will open it to contributions, and contributors will easily be able to understand from the title what they need to do ;)

You can also open a second issue if you would like both.

**Comment by TheTrashCrafter** [comment]
Hi, I renamed the title.

**Comment by papjul** [comment]
After the widgets overhaul #937, all widgets will be able to use Material You
