### ISSUE TITLE
Suplant previous forecast notification - a single forecast instead of two

### ISSUE THREAD

**Issue by marcosilva85** [breezy-weather/breezy-weather#1433]
### Steps to reproduce

1. Enable forecast notifications at night (next day forecast) and morning (current day forecast)

### Expected behavior

New morning notification should supplant older notification, since they're forecasting the same day.

### Actual behavior

You have two forecast notifications in the morning (and the earliest one from the night is outdated).
![42951634-b343-4d16-8ead-f15eb838958a](https://github.com/user-attachments/assets/d2c90d79-28df-4a73-8121-f718ff0936f0)

### Weather source used

*

### Breezy Weather version

5.2.8

### Android version

14

### Device

pixel 6

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open OR closed issue.
- [X] I checked that my issue is not covered in the [Frequently Asked Questions](https://github.com/breezy-weather/breezy-weather/blob/main/HELP.md) document.
- [X] I have updated the app to **[version 5.2.8 or later](https://github.com/breezy-weather/breezy-weather/releases/latest)** and I can reproduce the issue in this version.
- [X] I wrote my request in English, and any screenshot I attached are also in English (language can be changed from Settings > Appearance), unless my issue only happens with a specific language. I can write in my native language under the English text, if necessary.
- [X] I understand that this app is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY, so I may not get a positive reply to my request, if any at all.

**Comment by papjul** [comment]
Not a bug. See also #970

**Comment by marcosilva85** [comment]
Thanks for quickly curating it @papjul .
Could you please add  your opinion as developer about the "feature" then, since here and in #970 there's no comments yet?

**Comment by papjul** [comment]
It's accepted and tagged as "Open to contributions". OP mentions a code example that can be followed ;)
