### ISSUE TITLE
Japan Meteorological Agency (Japan)

### ISSUE THREAD

**Issue by chunshek** [breezy-weather/breezy-weather#1454]
### Link to publicly available documentation of the API

Undocumented API used by https://www.jma.go.jp/

### Available and not available data

✅ Daily Forecast (7 days)
✅ Hourly Forecast (3-hourly for up to 2 days)
✅ Weather Condition
✅ Temperature
❌ Precipitation
✅ Precipitation Probability
✅ Wind
❌ UV
❌ Sun and Moon
❌ Moon Phase
✅ Current
❌ Air Quality
❌ Pollen
❌ Precipitation Nowcasting
✅ Alerts
✅ Temperature Normals
✅ Humidity
❌ Dew Point
✅ Pressure
❌ Cloud Cover
✅ Visibility
❌ Ceiling
❌ Precipitation Duration
❌ Sunshine Duration
❌ Search
✅ Reverse Geocoding

### Are you going to develop yourself the new source for the app?

Yes, coding and testing it at the moment

### Give a bit more details or context about this source

[Japan Meteorological Agency](https://www.jma.go.jp/) is the official meteorological service of Japan. It offers current observations, local bulletin, daily and 3-hourly forecasts, temperature normals, and alerts. Reverse geolocation is also possible with GeoJson files.

In addition, alert headlines are available in the following languages, which will be added in the PR:
- English
- Indonesian
- Japanese
- Korean
- Portuguese
- Simplified Chinese
- Spanish
- Traditional Chinese
- Vietnamese
- Burmese (not yet supported by Breezy Weather)
- Khmer (not yet supported by Breezy Weather)
- Mongolian (not yet supported by Breezy Weather)
- Nepali (not yet supported by Breezy Weather)
- Tagalog (not yet supported by Breezy Weather)
- Thai (not yet supported by Breezy Weather)

### Acknowledgements

- [X] I have searched [the existing sources](https://github.com/breezy-weather/breezy-weather/blob/main/docs/SOURCES.md) and [the existing new source requests](https://github.com/breezy-weather/breezy-weather/issues?q=is%3Aissue+label%3A%22New+source%22+no%3Amilestone+-label%3ADuplicate) and this is a new source, **NOT** a duplicate or related to another open OR closed issue.
- [X] This source has a free-tier available (not a trial period), and if it is a main weather source, it includes free hourly forecast
- [X] This source does not require sensitive information (billing info, phone number, etc) to subscribe to the free-tier
- [X] I understand there may be technical limitations that may prevent implementing this source (for example, the lack of coordinates information)
- [X] I wrote my request in English. I can write in my native language under the English text, if necessary.
- [X] I understand that this app is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY, so I may not get a positive reply to my request, if any at all.

**Comment by papjul** [comment]
You can initialize the translation files in the missing languages. Of course the rest of the app will fallback to English, but at least the weather details will be in a language they are (probably) more comfortable with ;)

**Comment by chunshek** [comment]
There are strings from a few of the weather sources I have worked on recently for these "missing languages". Maybe I can collect and organize them in translation files, and file them as a separate PR. It won't be perfect but will be a start.

| Language      | HKO | JMA | MeteoLux | NAMEM |
|---------------|-----|-----|----------|-------|
| Burmese       |     | ✅   |          |       |
| Khmer         |     | ✅   |          |       |
| Luxembourgish |     |     | ✅        |       |
| Mongolian     |     | ✅   |          | ✅     |
| Nepali        | ✅   | ✅   |          |       |
| Punjabi       | ✅   |     |          |       |
| Tagalog       | ✅   | ✅   |          |       |
| Thai          | ✅   | ✅   |          |       |
| Urdu          | ✅   |     |          |       |

Types of strings available:
- HKO: weather conditions, interface text labels, HKO-specific alerts
- JMA: interface text labels, JMA-specific alerts
- MetroLux: weather conditions, interface text labels, MetroLux-specific alerts
- NAMEM: weather conditions, interface text labels

Let me know what you think.

**Comment by papjul** [comment]
Sure, but let's hold that off until I review all source-related PR, so that we avoid useless conflicts ;)
