### ISSUE TITLE
Incorrect Weather Condition and Air Pollution Levels

### ISSUE THREAD

**Issue by Fluffgar** [breezy-weather/breezy-weather#1462]
### Steps to reproduce

Not yet determined. 

### Expected behavior

See relatively accurate weather info (as is usually the case when using the app). 

### Actual behavior

In the case of incorrect weather: The app often reports fog when there is none. 

In the case of incorrect air pollution levels: The app often reports dramatically higher levels of pollutants than are present according to other sources. This happens a lot more often than the wrather issue. 

### Weather source used

Open Meteo

### Breezy Weather version

stable 5.2.8_freenet

### Android version

Android 13

### Device

Samsung S20

### Other details

I have the sense that the two issues are related. But no solid proof yet. Regardless, I am not complaining. It's a good app. 

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open OR closed issue.
- [X] I checked that my issue is not covered in the [Frequently Asked Questions](https://github.com/breezy-weather/breezy-weather/blob/main/HELP.md) document.
- [X] I have updated the app to **[version 5.2.8 or later](https://github.com/breezy-weather/breezy-weather/releases/latest)** and I can reproduce the issue in this version.
- [X] I wrote my request in English, and any screenshot I attached are also in English (language can be changed from Settings > Appearance), unless my issue only happens with a specific language. I can write in my native language under the English text, if necessary.
- [X] I understand that this app is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY, so I may not get a positive reply to my request, if any at all.

**Comment by papjul** [comment]
We don't produce the weather data, we only display it. Feel free to try other sources if they feel more consistent to you ;)
