### ISSUE TITLE
[Main source] Warn the user when a specific feature failed instead of silently failing/failing the whole weather refresh

### ISSUE THREAD

**Issue by papjul** [breezy-weather/breezy-weather#1473]
Currently, most sources work the following way when they are used as main source:
- If alert failed to refresh but everything else succeed, the whole weather refresh is aborted with an error and nothing is saved
- If normals failed to refresh but everything else succeed, the whole weather refresh succeed and is saved, but the user doesn't know normals failed

Improve the situation by extending the `WeatherWrapper` to in both cases warn the user with a similar message like "The following features failed to refresh: Alerts, Normals" but still save everything else.

It should support all the currently split features. However, we need to think what to do when the astro endpoint fails, which is not considered a separate feature.

**Comment by chunshek** [comment]
Would Air Quality and Pollen be treated similarly?

**Comment by papjul** [comment]
Added support in b090aa9b17899c690e38eedc27bf0a99ecc0de76

Implemented only in Météo-France atm
