### ISSUE TITLE
When there are 2 or more refresh errors, only 1 is showing on main screen

### ISSUE THREAD

**Issue by papjul** [breezy-weather/breezy-weather#1474]
The snackbar seems to handle only one at a time. Works fine in background

**Comment by min7-i** [comment]
Currently, only the first registered error is passed in the [view model](https://github.com/breezy-weather/breezy-weather/blob/318afb39ecaa3f93f0dfea954c32c471f800d386/app/src/main/java/org/breezyweather/main/MainActivityViewModel.kt#L228).

While we can only show one snackbar at a time anyway, we could still pass the complete list of errors. If there is only one error, we'd keep the current logic.

However, if there is more than one error, we could show a generic snackbar saying that there are multiple errors and add an action which opens a dialog/bottom sheet containing the complete list of errors. If an action is defined for the [RefreshErrorType](https://github.com/breezy-weather/breezy-weather/blob/main/app/src/main/java/org/breezyweather/main/utils/RefreshErrorType.kt) we could make the corresponding list items clickable as well.


I have something like this in mind (just as a quick draft):
| snackbar | details dialog |
| --- | --- |
| ![Screenshot_20241130-210912](https://github.com/user-attachments/assets/3f4729a4-0ea5-4f6c-83f3-2d63588f29b5) | ![Screenshot_20241130-210915](https://github.com/user-attachments/assets/c5907a21-6ef7-4799-acd3-1853c349b462) |

**Comment by papjul** [comment]
Ah, that would be nice indeed, I wouldn't have represented it better! Would you like to work on it?
