### ISSUE TITLE
V5.3.0 prerelease notifies of v5.2.8 update

### ISSUE THREAD

**Issue by papjul** [breezy-weather/breezy-weather#1511]
### Steps to reproduce

1. Settings
2. About
3. Check for updates

### Expected behavior

No new updates

### Actual behavior

Lower version update notification

### Weather source used

N/A

### Breezy Weather version

5.3.0

### Android version

N/A

### Device

N/A

### Other details

Not reproducible in debug

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open OR closed issue.
- [X] I checked that my issue is not covered in the [Frequently Asked Questions](https://github.com/breezy-weather/breezy-weather/blob/main/HELP.md) document.
- [X] I have updated the app to **[version 5.3.0 or later](https://github.com/breezy-weather/breezy-weather/releases/latest)** and I can reproduce the issue in this version.
- [X] I wrote my request in English, and any screenshot I attached are also in English (language can be changed from Settings > Appearance), unless my issue only happens with a specific language. I can write in my native language under the English text, if necessary.
- [X] I understand that this app is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY, so I may not get a positive reply to my request, if any at all.

**Comment by bush911** [comment]
I have never succeded in checking update. It always says **Failed to connect to api.github.com/ 127.0.0.1:443**
