### ISSUE TITLE
Dagger 2.53/2.53.1 causes builds to fail on Windows

### ISSUE THREAD

**Issue by min7-i** [breezy-weather/breezy-weather#1525]
### Steps to reproduce

Create a build on Windows.

See https://issuetracker.google.com/issues/383578358 for details. The issue has already been fixed, so there'll probably be a new release soon.

### Expected behavior

Build is successful.

### Actual behavior

Build fails.

### Weather source used

N/A

### Breezy Weather version

Latest commit 53c8c26

### Android version

N/A

### Device

N/A

### Other details

Version 2.52 still works.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open OR closed issue.
- [X] I checked that my issue is not covered in the [Frequently Asked Questions](https://github.com/breezy-weather/breezy-weather/blob/main/HELP.md) document.
- [X] I have updated the app to **[version 5.3.1 or later](https://github.com/breezy-weather/breezy-weather/releases/latest)** and I can reproduce the issue in this version.
- [X] I wrote my request in English, and any screenshot I attached are also in English (language can be changed from Settings > Appearance), unless my issue only happens with a specific language. I can write in my native language under the English text, if necessary.
- [X] I understand that this app is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY, so I may not get a positive reply to my request, if any at all.

**Comment by papjul** [comment]
Fixed in v2.54
