### ISSUE TITLE
Environment Canada

### ISSUE THREAD

**Issue by nevillepark** [breezy-weather/breezy-weather#153]
### Describe your suggested feature

Would it be possible to add [Environment Canada](https://api.weather.gc.ca/) as a weather provider? It would be nice to get official windchill and humidex temperatures.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to **[latest version](https://github.com/breezy-weather/breezy-weather/releases/latest)**.

**Comment by papjul** [comment]
Yes, please check: https://github.com/breezy-weather/breezy-weather/blob/main/CONTRIBUTE.md

There is no humidex temperature in database, so you will have to re-use one of the available "feels like" temperature. Apparent temperature can probably fit.

**Comment by papjul** [comment]
I got no reply so I tagged your issue as "Open to contributions" but if you want to work on it, let me know and I will remove it to avoid two persons working on the same provider at the same time.

**Comment by nevillepark** [comment]
I am very bad at coding and don't really know my way around weather APIs, so if anyone else wants to work on it they're welcome to!

**Comment by papjul** [comment]
I had a look at weather API, however it seems to me it only has endpoints for stations.
This might be a misunderstanding from me, but it looks like it is not possible to just ask for weather data for a specific lon and lat.

**Comment by ganeshlab** [comment]
Found this project that has a [list](https://github.com/austinhuang0131/CanadaWeather/blob/master/canadaWeather/src/main/assets/sitelist-base-v3.xml) of the stations and their coordinates. Maybe something like it can be used to match the closest station to the coordinates entered by the user.

**Comment by papjul** [comment]
> Found this project that has a [list](https://github.com/austinhuang0131/CanadaWeather/blob/master/canadaWeather/src/main/assets/sitelist-base-v3.xml) of the stations and their coordinates. Maybe something like it can be used to match the closest station to the coordinates entered by the user.

Are there users that wants to have the weather condition from a far away station? Stations are really spread apart, there are only 900 stations in the whole Canada, the 2nd biggest country in the world.

Wouldn't it be better to just use Environment Canada directly from Open-Meteo? Not only, it will be more accurate as it would be computed for a given lon and lat, but Open-Meteo would also complete missing data with other sources.

(I’m taking the example of Open-Meteo, but I’m pretty sure other sources are using the same models, either exactly (Open-Meteo) or with additional computation from their past experiences (AccuWeather for example))

**Comment by ganeshlab** [comment]
The majority of the population is concentrated around a few of those stations. I don't think you'll find many canadian users who'll have an issue with that list. I can't speak to which would be better but as an example, I have found accuweather to be mostly inaccurate with forecasts.

**Comment by papjul** [comment]
> The majority of the population is concentrated around a few of those stations. I don't think you'll find many canadian users who'll have an issue with that list. I can't speak to which would be better but as an example, I have found accuweather to be mostly inaccurate with forecasts.

Sure, in that case, we can add a location search that will be a station search instead ;)

There are tons of APIs listed, so if you could provide direct links to documentation of the following endpoints to ease the work of contributors that will work on it:
- Station search endpoint
- Hourly forecast endpoint
- Any other endpoint you find useful (such as air quality)

Thank you!

**Comment by papjul** [comment]
Looking at the app you linked earlier, I found they use a different endpoint that will probably be more useful as its per Canadian city:
https://eccc-msc.github.io/open-data/msc-data/citypage-weather/readme_citypageweather_en/

We could make a city search from the siteList.xml, however, it seems to lack major required information:
- TimeZone (that one can probably be hardcoded list per province, I guess? And updated if timezone changes, probably doesn’t happen a lot in a lifetime of an app)
- Longitude and latitude (we use that for many features, we can’t have nullable values here)

**Comment by ganeshlab** [comment]
Station list in json with the coordinates:
https://collaboration.cmc.ec.gc.ca/cmc/cmos/public_doc/msc-data/citypage-weather/site_list_en.geojson

Example:
https://dd.weather.gc.ca/citypage_weather/xml/ON/s0000458_e.xml

**Comment by papjul** [comment]
Thank you very much!

I open it again to contributions. Two things to keep in mind:
- We have no XML source at the moment, so you will need to add the relevant Kotlinx serializer in libraries
- We have no source which don't allow reverse geocoding, so I will need to add a way to not enable this source in the weather source list for current location

**Comment by papjul** [comment]
To keep the app technical implementation, sources must implement either endpoints by coordinates, or a reverse geocoding endpoint.

So you need to find (or implement) a service such as what https://brightsky.dev/ does for DWD meteorological source.

Basically, we query a server with coordinates, and the server, using data from the meteorological source, gives the response from the nearest station that it calculated.

This implementation makes it useful to other weather apps, at the same time.

**Comment by papjul** [comment]
Support for ECCC will be added in next version, thanks to a new endpoint providing the data I was previously missing
