### ISSUE TITLE
Bring back Circular Sky from old Geometric Weather versions

### ISSUE THREAD

**Issue by nevillepark** [breezy-weather/breezy-weather#154]
### Describe your suggested feature

Hi, thank you for keeping development going on this great app! One feature I miss from Geometric Weather is the "circular sky" interface style. It has fewer animations than the default style, which can make me a little motion sick sometimes. 

I can use Android's accessibility settings to turn off animations entirely system-wide, but animations are configurable/not a problem for me in virtually every other app I use, so it feels like overkill. It would be nice to either have the ability to 

a) reduce/turn off the animation via an in-app setting, or  
b) bring back an alternative style that also uses colours and shapes to convey current time and weather, but doesn't use constant animations. 

Thanks!

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to **[latest version](https://github.com/breezy-weather/breezy-weather/releases/latest)**.

**Comment by papjul** [comment]
I don't know what this "Circular sky" is, are you sure you disabled animations from Settings > Main screen? If that's the case, please screenshot the place where you are encountering animations that are making you motion sick.

**Comment by min7-i** [comment]
The latest official release of Geometric Weather (version 3.013) included a setting called "circular sky". That setting seems to have been removed in the two beta versions that were released afterwards. 

I didn't know about that feature either until now, but this is what it looks like:

https://github.com/breezy-weather/breezy-weather/assets/97251923/d402a9ec-2b92-410f-8e1c-f26e527783de

**Comment by papjul** [comment]
Given how the header looks like now, this won’t be possible to bring this back.
Additionally, Wangdaye probably had good reasons to remove it.

In either case, I have no interest in maintaining two background types. If you don’t like animations, you can just disable them in app settings. And if you still don’t like the background with no animation, then you should probably use a different app at this point 😆

**Comment by NBA613** [comment]
How about changing disable animation to having all the animations frozen in place, instead of being removed altogether? At the moment, disable animation removes the clouds/sun/stars/rain/snow... altogether, and leaves us with just the colored backgrounds.

**Comment by papjul** [comment]
> How about changing disable animation to having all the animations frozen in place, instead of being removed altogether? At the moment, disable animation removes the clouds/sun/stars/rain/snow... altogether, and leaves us with just the colored backgrounds.

Clouds and sun, why not, but "frozen in space" shooting stars, rain and snow look terrible (try by yourself by taking a screenshot).

If you would like to go that way, please update your issue as your title and description are not clear at all.

**Comment by nevillepark** [comment]
OK, thanks for sharing your reasoning.

This is a dealbreaker for me, so I will go back to using Geometric Weather.

**Comment by papjul** [comment]
> This is a dealbreaker for me, so I will go back to using Geometric Weather.

You’re free to use the app you like the most (although I would advise against an unmaintained app for security reasons), but I think there is a misunderstanding there.

Breezy Weather removes no feature over Geometric Weather regarding the background.
The only difference is the "disable animation" feature that was *added* in Breezy Weather, and it does indeed removes all animated elements *at the moment*, but if you want to bring back the same behavior as Geometric Weather before that feature was added, you can just force background animation to be enabled.

In any case, Geometric Weather has no “static rain all over the background” feature.

**Comment by papjul** [comment]
Reopened as #195

**Comment by papjul** [comment]
Reopening as it looks like many people are still using an old version of Geometric Weather because this feature is missing in later versions of Geometric Weather. See WangDaYeeeeee/GeometricWeather#505

It would be best to reach us via Matrix or leave a message here if you plan on working on it, so we can make sure the implementation will be clean.

**Comment by papjul** [comment]
Just to be sure, circular sky implementation is:
1. Always blue background (even if it's cloudy outside), right? Having a grey background when it's cloudy is not acceptable, right?
2. Instead, it uses the empty space above temperature to show weather icon, right?
