### ISSUE TITLE
[AccuWeather] Alerts fail to update in South Africa

### ISSUE THREAD

**Issue by colour-in-space** [breezy-weather/breezy-weather#1542]
### Steps to reproduce

1. Update to stable 5.3.1
2. Enable notification widget and set to persistent
3. Use AccuWeather as source

### Expected behavior

Notification widget updates (per time interval chosen in settings) but no notification sound or vibration.

### Actual behavior

Notification widget updates as describe above

AND the following notification appears:
"1 update(s) failed
Tap to see details"
This notification groups with the widget and needs to be dismissed (swiped away) to show the widget properly.
This notification also comes with a vibration on connected smart watch.

Tapping to see details reveals this message:
"! AccuWeather: Source failed to update: Alerts
- (__location name__)"

### Weather source used

AccuWeather

### Breezy Weather version

5.3.1

### Android version

10

### Device

LG G7 thinQ 

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open OR closed issue.
- [X] I checked that my issue is not covered in the [Frequently Asked Questions](https://github.com/breezy-weather/breezy-weather/blob/main/HELP.md) document.
- [X] I have updated the app to **[version 5.3.1 or later](https://github.com/breezy-weather/breezy-weather/releases/latest)** and I can reproduce the issue in this version.
- [X] I wrote my request in English, and any screenshot I attached are also in English (language can be changed from Settings > Appearance), unless my issue only happens with a specific language. I can write in my native language under the English text, if necessary.
- [X] I understand that this app is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY, so I may not get a positive reply to my request, if any at all.

**Comment by papjul** [comment]
Works fine in Helsinki, Finland. If your issue is about a specific country, region or city, we need to know which one.

**Comment by colour-in-space** [comment]
Durban, South Africa

**Comment by papjul** [comment]
I can reproduce the issue.

Unfortunately, it's server side error (error 500), so there's nothing we can do.

Did it work in the past and suddenly stopped working (in that case it would be a temporary error)? Or did it never work (and in that case I need to exclude South Africa from supported countries of AccuWeather)?

**Comment by colour-in-space** [comment]
It worked prior to most recent update to the app.

**Comment by papjul** [comment]
Is AccuWeather your main source as well, or do you use it only as your alert source?

There were some changes to error handling in v5.3 and it's possible that in previous versions alert silently failed

**Comment by colour-in-space** [comment]
AccuWeather main and default

**Comment by papjul** [comment]
Looking at the code from v5.2.8, we can see that in case of alert failure, it would return an empty alert list without any error:
https://github.com/breezy-weather/breezy-weather/blob/v5.2.8/app/src/src_nonfreenet/org/breezyweather/sources/accu/AccuService.kt#L170-L174

So at the moment, we don't know if it's a temporary error or not. The API documentation doesn't mention any country limitation.

I'm leaving this open and we will see again in a week.

In the meantime, you can use an alternative source. For example, WMO SWIC works partially for South Africa (truncated description).

**Comment by papjul** [comment]
So, in next version, when such an issue happens (alerts by coordinates endpoint doesn't work), it will fallback to alerts for your city instead.

However, it doesn't look like AccuWeather is a reliable source for South Africa. Using WMO SWIC as alert source, I can see an alert in Durban tomorrow, but none in AccuWeather (using the alert by city endpoint).

**Comment by colour-in-space** [comment]
Awesome! Thanks.

In the meantime I've switched to open-metro and WMO SWIC for alerts. Happy with that

**Comment by bush911** [comment]
Same here in China. Got several daily updates failure notification. It seems that manually refershing works fine.
