### ISSUE TITLE
Other notifications should not hide notification widget

### ISSUE THREAD

**Issue by supsm** [breezy-weather/breezy-weather#1543]
### Steps to reproduce

1. turn on "Notification of severe weather alerts", "Notifications of precipitations", and "Notification widget"
2. wait for a severe weather or precipitation alert to appear

### Expected behavior

The severe weather / precipitation alert should not hide the notification widget. The notification widget should still be visible in the lock screen and notifications tray without expanding the notification.

### Actual behavior

The notification widget is not visible at all without expanding the notification
(notification pulldown)
![ss1](https://github.com/user-attachments/assets/5c5dd986-99a5-4f65-8d43-9a9329f2897f)
(lock screen)
![ss3](https://github.com/user-attachments/assets/9a58cbf3-6adc-4f9f-95c6-85052e9c13f0)
This is especially annoying in the lock screen because the notification widget will not be accessible without unlocking

It appears that the alerts have higher priority than the notification widget and thus hides it.
![ss2](https://github.com/user-attachments/assets/fb5ee75d-5b8d-45e3-adc3-166f7b093548)

Additionally, the notification tray icon for is incorrect and does not display the temperature (which it should due to the notification widget), rather it shows some random download icon.
![ss3](https://github.com/user-attachments/assets/42be2039-1253-4770-b30d-1bcd62740d4a)

### Weather source used

accuweather

### Breezy Weather version

5.3.1

### Android version

14

### Device

Pixel 7

### Other details

related: #1421.  
Note that this issue pertains specifically to severe weather / precipitation alerts, which are part of the normal, expected behavior of the app, whereas #1421 relates to failed updates which is arguably user error.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open OR closed issue.
- [X] I checked that my issue is not covered in the [Frequently Asked Questions](https://github.com/breezy-weather/breezy-weather/blob/main/HELP.md) document.
- [X] I have updated the app to **[version 5.3.1 or later](https://github.com/breezy-weather/breezy-weather/releases/latest)** and I can reproduce the issue in this version.
- [X] I wrote my request in English, and any screenshot I attached are also in English (language can be changed from Settings > Appearance), unless my issue only happens with a specific language. I can write in my native language under the English text, if necessary.
- [X] I understand that this app is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY, so I may not get a positive reply to my request, if any at all.

**Comment by papjul** [comment]
Same answer as #1421:

> I don't think it's a bug as I never documented anywhere this behavior, nor intended a specific behavior.

Feel free to check existing suggested ideas or open one to discuss the specification further.

**Comment by supsm** [comment]
This current behavior essentially means that the notification widget cannot be used with the weather alerts, which I don't think is intended. Unlike #1421, both the behavior of the notification widget and weather alerts were working properly individually, but when used together they conflict due to the notification widget being hidden.

**Comment by papjul** [comment]
All notifications were created in a single group, and Android collapses notifications when there are more than 1 in the same group, so the behavior is as intended. Both notifications work perfectly, they are just collapsed as intended.

I understand that this is a frustrating behavior because you can't see the notification expanded anymore and I understand you see it as a bug, but this can't qualify as a bug, because there is nothing to "fix". It is working as intended, and if the behavior must change, the new behavior must be defined as part of a new implementation.
We currently have 12 types of notifications. Should we split all of them in 12 groups? I don't think so, that would be overkill. If not then, which ones must be split from which ones?
That must be debated, and decided between different options (keeping one group, spliting some notifications (and defining which ones) into different groups, making one group per notification, etc).

**Comment by papjul** [comment]
As for the "download" icon, it was already reported here and there, and we have no way of changing it. Android takes care of choosing the grouped icon by itself. In your case, this is the icon for the "Update in progress" notification that disappeared once the update progress was complete. As to why Android keeps that icon as the grouped icon, even if the notification disappeared, we have no idea why, and we can't change it.

**Comment by supsm** [comment]
> We currently have 12 types of notifications. Should we split all of them in 12 groups? I don't think so, that would be overkill. If not then, which ones must be split from which ones?
IMO the Forecast and Widget should each be their own group since they are meant to be looked at for reference, and all others should be in a single category since those are meant to alert the user of some event (i.e. they are "normal" notifications)
