### ISSUE TITLE
Changing Weather Providers Issue

### ISSUE THREAD

**Issue by HonestAbe7** [breezy-weather/breezy-weather#163]
### Steps to reproduce

1. I clicked to change weather provider.

2. I also tried to put in my zip code for the current location after I changed weather providers.

### Expected behavior

I tried to change from AccuWeather to OpenWeather and nothing seemed to change. I even tried to add my location hoping it was OpenWeather but it was still AccuWeather.

### Actual behavior

Nothing changed.

### Weather provider used

AccuWeather

### Breezy Weather version

4.1.3-beta

### Android version

10

### Device

LG L355DL to 

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to **[latest version](https://github.com/breezy-weather/breezy-weather/releases/latest)**.

**Comment by min7-i** [comment]
From your description I'm assuming that you manually added a location and you're not talking about the current location (GPS).

If you want to use a different weather provider for a location, you need to readd the location, which means that you'll temporarily have the same location twice in your location list.

Here's a screen recording showing the steps to choose different weather providers.

https://github.com/breezy-weather/breezy-weather/assets/97251923/798b966d-a129-455f-915f-7b36ece6a12b

First remark: Regarding OpenWeather, it seems that the daily request limit for the default API key that comes with the app has been reached. That's probably why, currently, weather data cannot be fetched from OpenWeather.

Second remark: ZIP codes aren't supported reliably by all weather providers. If you can't find your location via zip code, it's best to use the name of your location instead.

If you try to follow the steps in the screen recording, are you able to successfully choose a different weather provider for your desired location?

**Comment by HonestAbe7** [comment]
Yes! The above video worked. I had to download a separate video app to view the codec. So basically, if this happens again, we just need to click on the bottom, at the location screen, to change weather providers since going to settings under weather providers doesn't change anything. Thanks for helping me. 

Now, I might need help with creating widgets for the different weather providers. I don't see anywhere in the widget to have a title for location and which weather provider. Nor a setting to switch providers either in the widget settings. Again, I could open up a separate issue if you would like me to do so. 😁

**Comment by HonestAbe7** [comment]
I was successful at changing the weather provider and had 2 widgets and then they both went to OpenWeather.

**Comment by min7-i** [comment]
> So basically, if this happens again, we just need to click on the bottom, at the location screen, to change weather providers

Doing so will change the weather provider for **newly added** locations, but not for locations that already exist in your location list.
</br>
> ... since going to settings under weather providers doesn't change anything.

The setting "Weather provider for current location" (in the "weather providers" category) only affects your current location (GPS location). Changing that won't have any effect on the locations you added manually via the location search.
![current location GPS](https://github.com/breezy-weather/breezy-weather/assets/97251923/4387fe85-de75-4b94-abc3-ad7bda322275)
</br>
> I don't see anywhere in the widget to have a title for location and which weather provider. Nor a setting to switch providers either in the widget settings.

It's not possible to do that in the widgets. Widgets will always display data for your first location in the location list, which means that the weather provider that was set for that specific location will be used. The "Multi City" widget will display the top 3 locations from the location list.

| screenshot | explanation |
| --- | --- |
| ![location list](https://github.com/breezy-weather/breezy-weather/assets/97251923/ac6f2c7a-80db-43b6-91af-aef2c1eaf511) | - all widgets will display Madrid with data provided by Open-Meteo</br>- the Multi City widget will display Madrid [Open-Meteo], London [Open-Meteo] and Barcelona [OpenWeather] |

**Comment by lrq3000** [comment]
Please clarify in doc or show in gui that current gps can now be swiped left to access the option to change the location, it took me a while to figure this out. Or better, at the bottom of each main screen, it's written "Data from Source", then on the right at the exact same level it's written "Modify", but tapping this does not allow to modify the source but which cards are displayed! I suggest to replace this function of the Modify button into editing the data source.

**Comment by papjul** [comment]
> Please clarify in doc or show in gui that current gps can now be swiped left to access the option to change the location, it took me a while to figure this out.

The left swipe was already there before. Even if you don't figure it out, you can just delete location and recreate it, the result will be the same. We are still lacky on documentation, but as I am doing both the code and documentation, I can't do many things at once. It's a very easy task and pull requests are welcome.

> Or better, at the bottom of each main screen, it's written "Data from Source", then on the right at the exact same level it's written "Modify", but tapping this does not allow to modify the source but which cards are displayed! I suggest to replace this function of the Modify button into editing the data source.

I agree, I already have in the back of mind to add location-specific settings there (such as #89 or #200), as cards list are not location-specific but applies to all locations, so it's not a good idea to put this kind of setting there (this is a legacy from Geometric Weather). Best would be to open a new Idea issue for this.

I would suggest continuing our discussion either in a new issue or in a discussion thread, as you're commenting on an issue from v4.1.3 about a change introduced in v4.3.0.

**Comment by lrq3000** [comment]
@papjul ah sorry I thought that what was discussed above was replaced by this swipe action. I will see what I can do. About deleting, i think it works only if i have no other specific place saved, right? 

Anyway the app is awesome, it's the only thing that I thought was a bit frustrating and it's just a doc issue, so great job, thank you very much! 😃

**Comment by papjul** [comment]
> I suggest to replace this function of the Modify button into editing the data source.

@lrq3000 This will be available with next release. The Modify button will open a new dialog allowing you to change multiple settings (main screen settings, for current location: weather source and location service, for manually added locations: resident city). Additional per-location settings will be implemented in future releases.

@HonestAbe7 We are waiting for additional info from you since 2 weeks ago. If you found a solution since then, please write it there in case other people have the same issue as you. Without any additional comment from you, this issue will be closed in two weeks to not keep stale issues, thank you for your understanding!

**Comment by HonestAbe7** [comment]
I am satisfied with the responses and changes to this. Not sure what "additional info" is needed from me. Thank you all for your help.

**Comment by papjul** [comment]
The issue is still opened so we thought you still needed something. I’m closing it then.
