### ISSUE TITLE
[Widgets] Newly added widgets keep loading until opening the app

### ISSUE THREAD

**Issue by min7-i** [breezy-weather/breezy-weather#167]
### Steps to reproduce

1. Make sure you have at least one location in your location list for which weather data is available.
2. On your home screen add a new Breezy Weather widget.
3. Watch the widget and check if data is displayed.

https://github.com/breezy-weather/breezy-weather/assets/97251923/2194c489-1eba-4bb1-acce-745375f419a4

### Expected behavior

The widget immediately displays the weather data.

### Actual behavior

The widget keeps loading. You need to open the app once for data to successfully appear in the widget.

### Weather provider used

N/A

### Breezy Weather version

4.2.0-beta

### Android version

Android 13 (GrapheneOS)

### Device

Google Pixel 6a

### Other details

I also noticed that adding a new widget triggers a refresh of all locations. I don't know the internal logic, but at least for the widget it would be sufficient to only refresh the locations that are displayed in the widget.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to **[latest version](https://github.com/breezy-weather/breezy-weather/releases/latest)**.

**Comment by papjul** [comment]
> I also noticed that adding a new widget triggers a refresh of all locations. I don't know the internal logic, but at least for the widget it would be sufficient to only refresh the locations that are displayed in the widget.

The logic is common to all widgets, and there is one widget with multiple cities, so we need to refresh all locations for all.

It is refreshed in background because at the end of the process, it calls a function that refresh widget view (if you don't do it, it will show empty data).

A fix for both issues is probably to just call this function instead of triggering a whole refresh.

**Comment by min7-i** [comment]
Due to the current logic, a background refresh is even triggered when reconfiguring a widget, e.g. changing the text size, which isn't really necessary. So changing that to only call the function refreshing the widget view sounds like a good idea.

**Comment by papjul** [comment]
I opened #172 for the follow up of other situations in which background refreshes are triggered.
