### ISSUE TITLE
[Main screen] Gravity sensor animation stutters

### ISSUE THREAD

**Issue by min7-i** [breezy-weather/breezy-weather#174]
### Steps to reproduce

1. Pick a location where it's currently cloudy, e.g. London.
2. Enable the gravity sensor animation in settings.
3. Back on the main screen, tilt your phone horizontally and vertically and watch the background animation.

### Expected behavior

The background animation moves smoothly following the phone's movement.

### Actual behavior

The background animation stutters.

This seems to be a regression from alpha versions.

See screen recordings for a comparison of the alpha and beta versions.

https://github.com/breezy-weather/breezy-weather/assets/97251923/9b0dabb6-494d-4f59-ba72-dbb7534b5396

https://github.com/breezy-weather/breezy-weather/assets/97251923/60f1caac-557c-46fc-a326-8251bc2abbc9

### Weather provider used

N/A

### Breezy Weather version

Regression introduced in v4.1.0

### Android version

Android 13 (GrapheneOS)

### Device

Google Pixel 6a

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to **[latest version](https://github.com/breezy-weather/breezy-weather/releases/latest)**.

**Comment by papjul** [comment]
It's very subtle.

Could you:
- Pinpoint the exact version in which it was introduced (I suspect it is 4.1.0-beta)
- Let me know if other weather conditions are affected

You can use the live wallpaper preview from Settings > Widgets for easy switch of weather condition.

**Comment by min7-i** [comment]
Correct, it started with 4.1.0-beta.

All backgrounds that have the circles at the top are affected: partly cloudy, cloudy, haze and thunder. I couldn't test the fog background as that showed me the clear background. So I can't say if that is affected as well.

> It's very subtle.

It probably depends on how you move your phone. If you're tilting your phone around the vertical axis, you can see the circles jumping from left to right or vice versa when crossing the middle; in case of my phone that's when crossing the position of the front camera.

In my opinion, it's quite noticeable. But then again I'm normally disabling this setting. So I can't say how users feel about it who are actively using this setting.

**Comment by Cod3dDOT** [comment]
I managed to reproduce this on Pixel 4a. Stuttering only occurs when tilting device to the left, and happens on all animated backgrounds.
