### ISSUE TITLE
[AccuWeather] "Degree day" value is always 0 °C for Daytime 

### ISSUE THREAD

**Issue by tuxiqae** [breezy-weather/breezy-weather#176]
### Steps to reproduce

1. Enter an AccuWeather location (either static or dynamic)
2. Click on a value under `Daily forecast`
3. Look at the value under `Daytime` -> `Temperature` -> `Degree Day`
4. Confirm that it is equal to `0 °C` no matter what the time/location is.

### Expected behavior

I would expect the real temperature to appear there.

### Actual behavior

Always contains null value (0 °C)

### Weather provider used

AccuWeather

### Breezy Weather version

4.2.1-beta F-Droid

### Android version

Android 13 

### Device

-

### Other details

The app looks fantastic, your CI flow as well, thanks!

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to **[latest version](https://github.com/breezy-weather/breezy-weather/releases/latest)**.

**Comment by papjul** [comment]
`0` is not the same thing as `null`. Only AccuWeather provides degree day, you won’t see it `0 °C` for degree day on providers with `null` values here.

Just to clarify, daytime degree day is the heating degree day, and nighttime degree day is the cooling degree day.

I tweaked the design a little for next version so it’s less confusing, see below.

Taking a hot place in the world with air conditioning needs and no heating needs:
<img src="https://github.com/breezy-weather/breezy-weather/assets/1449159/3ef9c710-ce19-45d0-ba1f-90a35ecc0d9c" alt="Heating degree day 0 °C / Cooling degree day 5 °C" width="300" />

Taking a cold place in the world with heating needs and no air conditioning needs:
<img src="https://github.com/breezy-weather/breezy-weather/assets/1449159/d79ccfac-9779-4742-8c59-a9d33985aa81" alt="Heating degree day 2 °C / Cooling degree day 0 °C" width="300" />

Let me know if it’s clearer for you now.

**Comment by tuxiqae** [comment]
@papjul  Sorry, but I cannot say that I understand the UI, what does Degree day/night represent?

**Comment by papjul** [comment]
> @papjul Sorry, but I cannot say that I understand the UI, what does Degree day/night represent?

You can download v4.3.0, there is no longer any Degree day by day/night, it’s only Heating degree day and Cooling degree day now, just like on my screenshots.
