### ISSUE TITLE
Fastlane changelogs are too long and have wrong format

### ISSUE THREAD

**Issue by IzzySoft** [breezy-weather/breezy-weather#178]
### Steps to reproduce

look at them

### Expected behavior

max 500 chars, plain text

### Actual behavior

more than 500 chars for en-US, HTML

### Weather provider used

n/a

### Breezy Weather version

n/a

### Android version

n/a

### Device

n/a

### Other details

Fastlane changelogs are limited to 500 char and must be plain text (not HTML).

```
en-US/changelogs/40102.txt has 1053 chars
en-US/changelogs/40103.txt has 1383 chars
en-US/changelogs/40201.txt has 625 chars
```

And they use HTML, which is not supported at this place (it will be rendered as plain text).

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to **[latest version](https://github.com/breezy-weather/breezy-weather/releases/latest)**.

**Comment by papjul** [comment]
I can remove HTML and just make manual bullet points, but it appears fine everywhere I looked, whether it's on your website, on F-Droid for Geometric Weather app, or on Droid-ify. Full description also contains HTML.

Regarding the size limit, I don't see anything written here: https://docs.fastlane.tools/actions/supply/#changelogs-whats-new
Do you have any other technical doc maybe? Because 500 characters is ridiculously low.

**Comment by IzzySoft** [comment]
> but it appears fine everywhere I looked

Then you were lucky: per definitionem, it's just plain text and should be rendered as such. Full description is something different, there HTML is permitted.

I leave it to you of course; as long as it stays within 500 char, it doesn't yield any reports. I don't remember where that limit is defined either (fastlane documentation is quite spread across multiple places), I just remember I found that and thus added it to my cheat sheet. Also, F-Droid sticks to that limit and truncates everything beyond.

> Because 500 characters is ridiculously low.

It's almost ridiculously high. Remember those metadata are intended for display in catalogs. For example, the official F-Droid client shows this appended directly to the app description (so does their website, and so does mine). So these files should just hold the most important changes, not complete changelogs – for the latter, you can have e.g. a `Changelog.md` in your repo, or add them to the release notes :wink: For a technical doc mentioning that, see [e.g. here](https://f-droid.org/en/docs/All_About_Descriptions_Graphics_and_Screenshots/#fastlane-structure) for F-Droid's.

**Comment by papjul** [comment]
> > but it appears fine everywhere I looked
> 
> Then you were lucky: per definitionem, it's just plain text and should be rendered as such. Full description is something different, there HTML is permitted.

OK, I can make simple lists then, this will also be easier for me ;) Maybe some apps will interpret it as Markdown and will be bullet points.


> > Because 500 characters is ridiculously low.
> 
> It's almost ridiculously high. Remember those metadata are intended for display in catalogs. For example, the official F-Droid client shows this appended directly to the app description (so does their website, and so does mine). So these files should just hold the most important changes, not complete changelogs

In that case, I prefer to make a `default.txt` inside `changelogs/` directory that says to go to GitHub to check release notes, it’s better than arbitrarily decide some bugs are more worth than others to be present in the changelog and I don’t want to maintain two release notes at each version.

**Comment by IzzySoft** [comment]
> OK, I can make simple lists then, this will also be easier for me ;)

Sounds good!

> I prefer to make a `default.txt`

which unfortunately will be ignored by my repo, sorry. For only saying "go to GitHub to check release notes", there's the `Changelog:` entry in the YAML.

**Comment by papjul** [comment]
> > I prefer to make a `default.txt`
> 
> which unfortunately will be ignored by my repo, sorry.

What about `fastlane/metadata/android/changelog.txt` then?
https://docs.fastlane.tools/actions/set_changelog/#set_changelog

> For only saying "go to GitHub to check release notes", there's the `Changelog:` entry in the YAML.

Is it something I need to add in Fastlane or is it metadata you need to add in your repo?

**Comment by IzzySoft** [comment]
> What about

My repo only recognizes changelogs by the `versionCode`.

> Is it something I need to add in Fastlane or is it metadata you need to add in your repo?

That's set up in my repo:

```yaml
Categories:
  - Internet
License: LGPL-3.0-only
AuthorName: Breezy Weather
AuthorWebSite: https://amenysta.net/
SourceCode: https://github.com/breezy-weather/breezy-weather
IssueTracker: https://github.com/breezy-weather/breezy-weather/issues
Translation: https://hosted.weblate.org/projects/breezy-weather/breezy-weather-android/#information
Changelog: https://github.com/breezy-weather/breezy-weather/releases
```
