### ISSUE TITLE
Make resident feature km radius configurable

### ISSUE THREAD

**Issue by papjul** [breezy-weather/breezy-weather#188]
### Describe your suggested feature

Currently, it’s 20 km radius.

Main issue is to handle imperial system.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to **[latest version](https://github.com/breezy-weather/breezy-weather/releases/latest)**.

**Comment by LuccoJ** [comment]
For me personally, 20km is too large. In the mountains you can have very different conditions much closer than that. But for large cities, 20km may be okay. So I second this idea, I realize that adding more and more settings is not always advisable, but I feel this setting is worth having.

**Comment by papjul** [comment]
Obsolete as of v5.0
