### ISSUE TITLE
Add ECMWF Api

### ISSUE THREAD

**Issue by dravolin** [breezy-weather/breezy-weather#189]
### Describe your suggested feature

Would be great if the ecmwf api could be added, as it's one of the most accurate forecasting apis out there. It's also provided by open-meteo: https://open-meteo.com/en/docs/ecmwf-api

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to **[latest version](https://github.com/breezy-weather/breezy-weather/releases/latest)**.

**Comment by papjul** [comment]
From my understanding of the notification on the top of this page, the Open-Meteo implementation has a spatial resolution of 44 km, and not 9 km, so it may not be as accurate.

It seems to me it’s already used in Open-Meteo in combination with other models up to 1 km to help not having missing data, see generic API models:
![image](https://github.com/breezy-weather/breezy-weather/assets/1449159/58dcb8f9-2733-42fa-865f-5b8fa4f892a3)

So what would be the difference between:
https://open-meteo.com/en/docs/ecmwf-api
and
https://open-meteo.com/en/docs
with parameter `&models=ecmwf_ifs04`?

**Comment by dravolin** [comment]
I actually found out that the openweather api also uses ECMWF so I am closing this issue.
