### ISSUE TITLE
Remove Shooting Stars From Clear Night Animated Background

### ISSUE THREAD

**Issue by NBA613** [breezy-weather/breezy-weather#190]
### Describe your suggested feature

I find the fast shooting stars to be highly distracting and unnecessary. I personally don't think the shooting stars reflect a typical clear night.  
Can the shooting stars be removed? - Leaving just the dark background and twinkling stars (maybe more of them?).
Or if the shooting stars must be there, maybe just less of them and less frequent?
Thanx!

### Other details

Also see [https://github.com/WangDaYeeeeee/GeometricWeather/issues/392]

Thanks for taking over and improving this wonderful abandoned app!

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to **[latest version](https://github.com/breezy-weather/breezy-weather/releases/latest)**.

**Comment by coxackie** [comment]
I like the idea of more of twinkling and less of shooting stars, but not getting rid of the shooting starts completely.

**Comment by maniel** [comment]
yeah, or even ability to make it more subtle

**Comment by papjul** [comment]
I agree it doesn't feel like a clear night sky when there are too many shooting stars. I like the idea of more twinkling stars and less often shooting stars, just like when you have thunder condition, it only flash from time to time ;)

I leave this open to contributions. This is the file to edit: https://github.com/breezy-weather/breezy-weather/blob/main/app/src/main/java/org/breezyweather/theme/weatherView/materialWeatherView/implementor/MeteorShowerImplementor.kt

Instructions:
To make it feel natural:
1) Time between each shooting star should be randomized
2) Shooting stars should not appear every time at the same place (currently, you have many shooting stars at different places, with slightly different colors/weight)

**Comment by Cod3dDOT** [comment]
Opened #240, which is a simple hardcoded change to spawn shooting stars with a random delay between 5 and 35 seconds. Also, made twinkling stars a bit larger. Should remove the overwhelming meteor shower.

**Comment by papjul** [comment]
Merged
