### ISSUE TITLE
[Main screen] Rewrite the logic and make mutable data more consistent

### ISSUE THREAD

**Issue by papjul** [breezy-weather/breezy-weather#198]
### Describe your idea

Currently uses: StateFlow, callable, LiveData, EventBus.

We should probably rewrite it more consistently and reduce spaghetti code.

Especially, callable is now called in the background which forced us to use `postValue` instead of `setValue` of live data. ~~This change might be at the origin of some race condition observed by some users (keep showing the refresh icon instead of showing updated data).~~ Probably unrelated, but still would avoid some issues I think.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to **[latest version](https://github.com/breezy-weather/breezy-weather/releases/latest)**.

**Comment by min7-i** [comment]
Remark from #215: the snackbar that is shown when a force refresh is performed currently says “Updated in background” which is kind of misleading as it's not a background update. If the snackbar stays it might be good to rephrase the text to something like "Update automatically".

**Comment by papjul** [comment]
I removed this snackbar in 4018a1365a5e0999293751117e86b3c6fb2abbfa as it annoyed me.
Not sure what I will do in #198 regarding this

**Comment by papjul** [comment]
58c1bc155b73882ecce85010cac2b447dfd6d8f1 replaced most of `LiveData` with `StateFlow`, however there is a side effect due to the different implementation of `observe` vs `collect`. `observe` stops when lifecycle is destroyed, while `collect` only works when lifecycle is started. This means that a new collect will be done every time the app is resumed. I had to put a workaround on the `currentLocation` state flow to avoid a refresh of the view everytime there is a switch of activity.
Ultimately, we should probably use `SharedFlow` to emit values when necessary instead of collecting `StateFlow`.

Anyway, the fact that we no longer have the issue linked to `postValue` with `LiveData`, we can now remove the milestone of v4.6 since it’s no longer a priority.

**Comment by papjul** [comment]
Closing technical issues
