### ISSUE TITLE
Hourly forecast is vertically compressed

### ISSUE THREAD

**Issue by Cris-Edmundson** [breezy-weather/breezy-weather#202]
### Steps to reproduce

View the hourly forecast

### Expected behavior

Should be less compressed

### Actual behavior

It's compressed and a bit difficult to read

### Weather provider used

Any, but I'm using open-meteo

### Breezy Weather version

 4.3.0-beta

### Android version

12

### Device

pixel 3

### Other details

Geometric weather:
![Screenshot_20230721-043156](https://github.com/breezy-weather/breezy-weather/assets/16363899/4145fb99-a5be-4e0b-9a5f-e7746482b79d)
Breezy weather
![Screenshot_20230721-043134](https://github.com/breezy-weather/breezy-weather/assets/16363899/270b98e7-fdd8-446f-8f80-92cb53514cac)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to **[latest version](https://github.com/breezy-weather/breezy-weather/releases/latest)**.

**Comment by papjul** [comment]
This was a change introduced by Wangdaye on its `dev` branch, unsure why
