### ISSUE TITLE
风力单位中增加蒲福风力级别

### ISSUE THREAD

**Issue by Naivev** [breezy-weather/breezy-weather#203]
### Describe your idea

相比米每秒这种数字，蒲福风力等级更常用和直观

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to **[latest version](https://github.com/breezy-weather/breezy-weather/releases/latest)**.

**Comment by papjul** [comment]
Please write in English.

Beaufort wind scale is already in the app, it’s called “wind strength”.
