### ISSUE TITLE
[Location list] Swipe left animation stays after cancelling weather provider dialog for current location

### ISSUE THREAD

**Issue by min7-i** [breezy-weather/breezy-weather#205]
### Steps to reproduce

1. Add the current location in the location list.
2. Swipe left on the current location to open the dialog for selecting the weather provider.
3. Tap cancel or tap outside the dialog.

### Expected behavior

The location entries including "current location" are displayed.

### Actual behavior

The settings animation for the current location is still visible.

![grafik](https://github.com/breezy-weather/breezy-weather/assets/97251923/97add080-b2bd-4bea-8297-43c59e1bdbea)

### Weather provider used

N/A

### Breezy Weather version

4.3.0-beta

### Android version

Android 13 (GrapheneOS)

### Device

Google Pixel 6a

### Other details

The animation properly disappears when selecting a weather provider in the dialog.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to **[latest version](https://github.com/breezy-weather/breezy-weather/releases/latest)**.

**Comment by papjul** [comment]
Same issue happens when a single location is deleted.
