### ISSUE TITLE
Don’t show alerts with low severity on first card

### ISSUE THREAD

**Issue by yonoff** [breezy-weather/breezy-weather#208]
### Describe your idea

Please add an option to disable / hide alerts in main screen (daily forecast card).
Moving the alerts to separate card is also be good.

### Other details

![Screenshot_20230722-141703](https://github.com/breezy-weather/breezy-weather/assets/9549832/8410e463-072b-4992-a883-4be8aab877f5)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to **[latest version](https://github.com/breezy-weather/breezy-weather/releases/latest)**.

**Comment by papjul** [comment]
Can you explain a bit the reason(s) why you want to hide weather alerts?

I feel like adding a preference to disable this (or as a separate card you can remove) would be a dangerous move, as it’s the kind of thing you set once and forget, and then when there is a particular dangerous weather condition, you’re not made aware of it.

This is why alerts are always put on top of the first card so you can’t miss them.

If this is a deal-breaker for you, at the moment you can use Open-Meteo or MET Norway which don’t provide any alert.

**Comment by yonoff** [comment]
In the place where I usually am, this yellow extreme heat alert is constantly present throughout the summer.  Accordingly, it does not carry any useful information, but only visually interferes.

**Comment by papjul** [comment]
In that case, you probably want to hide alerts that have a low-level of importance, but keep others.

In Europe, we mostly have yellow/orange/red system, but in US it’s different with all kind of colors. In China, there are blue alerts as well. And then, you have providers that don’t give us the color (OpenWeather), so I can’t even filter on this criteria…

So, simple need, but complex solution, I will have to think about it again.

**Comment by papjul** [comment]
Priority of alerts was replaced with severity, and all sources now use the same severity scale as the CAP protocol:
- Extreme
- Severe
- Moderate
- Minor
- (Unknown)

Should make the implementation easier, however still need to find a good UI/UX part for the settings/display of remaining alerts.
