### ISSUE TITLE
无法自动更新啊

### ISSUE THREAD

**Issue by Gu0830** [breezy-weather/breezy-weather#214]
### Steps to reproduce

新下载的这个软件 自启动 允许后台高耗电都打开了 可是还是无法自动更新天气 必须打开软件他才能刷新
![Screenshot_20230723_202208](https://github.com/breezy-weather/breezy-weather/assets/73874861/531c1392-317b-444d-8cae-2da521a81d9d)
![Screenshot_20230723_202212](https://github.com/breezy-weather/breezy-weather/assets/73874861/260bbc9d-11f0-4e7d-a0d5-989409416b4f)

### Expected behavior

应该会自动刷新

### Actual behavior

没有自动刷新

### Weather source used

AccuWeather

### Breezy Weather version

4.3.0 测试

### Android version

安卓13

### Device

iQOO neo8 pro 

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to **[latest version](https://github.com/breezy-weather/breezy-weather/releases/latest)**.

**Comment by papjul** [comment]
We no longer run any service in the background, the job is scheduled and then taken care by Android, so it does reduce battery consumption.

If you run a device that implements non-standard Android principles and doesn’t want to launch our scheduled jobs, then you might be interested in applying a few changes to have a more standard Android behavior:
https://dontkillmyapp.com/vivo

If you still need help, please reopen an issue written in English.

**Comment by Gu0830** [comment]
可以添加一个后台隐藏的功能吗？  这样就可以锁定后台了
