### ISSUE TITLE
Bad contrast on Daily trend widget with dark theme

### ISSUE THREAD

**Issue by heberjeur** [breezy-weather/breezy-weather#227]
### Steps to reproduce

Add a widget , dark background

### Expected behavior

Completely white text color 

### Actual behavior

Gray and thin day data

### Weather source used

AccuWeather

### Breezy Weather version

4.3

### Android version

Android 11

### Device

Samsung A50

### Other details

![Screenshot_20230725-233800_One UI Home](https://github.com/breezy-weather/breezy-weather/assets/11852634/4f90c878-2558-45fe-b239-4ed8dbe5e827)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I read the [Help](https://github.com/breezy-weather/breezy-weather/blob/main/HELP.md) documentation.
- [X] I have updated the app to **[latest version](https://github.com/breezy-weather/breezy-weather/releases/latest)**.

**Comment by heberjeur** [comment]
Any updates of this ?

**Comment by papjul** [comment]
It's open to contributions ;)

**Comment by ludles** [comment]
I found the old GeometricWeather's colour scheme might be a better option ;)

![Snipaste_2024-02-19_12-36-43](https://github.com/breezy-weather/breezy-weather/assets/37469405/73528da4-59a5-46c8-9efe-2b80d34a6a55)

**Comment by heberjeur** [comment]
@ludles, yes, I'm still using the old GeometricWeather...

**Comment by ludles** [comment]
> @ludles, yes, I'm still using the old GeometricWeather...

I am in the process of migrating. Because I can no longer get the data from AccuWeather in GeometricWeather (https://github.com/WangDaYeeeeee/GeometricWeather/issues/469) since last week, and it has not been maintained for quite some time so there is very thin hope that it will get fixed :(

**Comment by papjul** [comment]
> @ludles, yes, I'm still using the old GeometricWeather...

Wow, really? You went back to using an old version of Geometric Weather (not even latest release), just because of this bug? :o

Just to clarify: Breezy Weather is based on Geometric Weather v2023-01-27,  v3.013 was release on 2021-04-15, that's almost 3 years ago, a lot of things changed since then!

I would say that rather than using a colour scheme from an old version, it's best to replicate what's inside the app right now. We have the same chart inside the app, and there is no contrast issue when the background is dark or light.

**Comment by min7-i** [comment]
@papjul If this is only about updating the colors used in the widget to match the ones used in the in-app version of the chart, I can take a look at it.

**Comment by papjul** [comment]
Yes, it's probably just a matter of matching with in-app colors but widgets have other mechanisms such as opacity or maybe Material You background color that may have justified that colors differs from app. Requires some tests afterwards to make sure it's all good x)

**Comment by yuipp** [comment]
I too used old original geometric weather 3.013 because this issue, but now it's can't update weather data.

So I start used Breezy. Will be very thankful for fixing ❤️

**Comment by heberjeur** [comment]
Thanks 🥳 @papjul
