### ISSUE TITLE
precipitation probability either  0% or 1%

### ISSUE THREAD

**Issue by trend-1** [breezy-weather/breezy-weather#246]
### Steps to reproduce

use openweathermap with metric units api call 3.0

### Expected behavior

A number between 0 and 100 should show up. (And does so in other apps using the same source.)

### Actual behavior

precipitation probability shows either 0% or 1% but never the real probability

### Weather source used

openweathermap

### Breezy Weather version

4.4.0-beta

### Android version

13

### Device

motorola

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I read the [Help](https://github.com/breezy-weather/breezy-weather/blob/main/HELP.md) documentation.
- [X] I have updated the app to **[latest version](https://github.com/breezy-weather/breezy-weather/releases/latest)**.

**Comment by trend-1** [comment]
Just tested it with 4.4.1-beta but the problem does not seem to be resolved. 

Still only giving me either 0% or 1%. 
Clearing cache / restart didn't change results.

**Comment by papjul** [comment]
Issue was fixed 9 hours ago. Release v4.4.1 is from yesterday.

**Comment by trend-1** [comment]
You're right, my bad.
Thanks, will wait for the new version.
