### ISSUE TITLE
Add additional location service, as alternative to Baidu IP location/GPS

### ISSUE THREAD

**Issue by tomac4t** [breezy-weather/breezy-weather#249]
### Describe your idea

This is an idea discussed at Matrix.

Use IP geolocation to avoid exposing your exact GPS location to weather service providers. Accuracy is lost, but privacy is improved.

[Geometric Weather](https://github.com/WangDaYeeeeee/GeometricWeather)/[Breezy Weather](https://github.com/breezy-weather/breezy-weather) currently provides Baidu IP Location. But Baidu is only available in China, and the rate limit of the API prevents it from working properly. In addition, the Baidu Map API for personal use requires a Chinese ID number and face recognition, which is very unfriendly to privacy. The coordinate returned by the API is gcj02, which is the coordinate of the non-public algorithm and cannot be used directly. For Baidu Map API documentation, see: https://lbsyun.baidu.com/faq/api?title=webapi/ip-api-base

The following are currently available alternatives:

|  API endpoint   | Format | ToS  | Rate limiting |
|  ----  | ---- | ---- | ---- |
| https://geoip.ubuntu.com/lookup  | XML | NO | N/A |
| https://geoip.kde.org/v1/ubiquity | XML | NO | N/A |
| https://geoip.xfce.org/ | XML | NO | N/A |
| http://ip-api.com/json/ | JSON | [YES](https://ip-api.com/docs/legal) | [45/minute](https://ip-api.com/) |
| https://ipinfo.io/json | JSON | [YES](https://ipinfo.io/terms-of-service) | [50K/month](https://ipinfo.io/developers#rate-limits) with an free account|
| https://api.ip.sb/geoip | JSON | [YES](https://ip.sb/terms-of-use/) | N/A |

The problem with `ip-api.com` is that its location is not very accurate. `ipinfo.io` provides a ~very suitable~ rate limit without token, but its location [in China seems to be very inaccurate](https://hostloc.com/thread-1004461-1-1.html). So my personal preference is `ip.sb`. These apis provide the value of longitude and latitude, same as GPS.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to **[latest version](https://github.com/breezy-weather/breezy-weather/releases/latest)**.

**Comment by papjul** [comment]
I would prefer to keep Baidu IP location, it’s very lightweight so I see no reason to remove it.

I agree with you, I like `ip.sb`, and we found it was really accurate for both you and me, so I will implement this one.

Additionally, it has reverse geocoding support, so it can very useful for weather sources without geocoding. In current state, location services only returns lon/lat, but I think it should be easy to extend it to also returns city information, instead of relying on a later call to reverse geocoding which might not exist on some weather sources ;)

**Comment by LuccoJ** [comment]
I want to point out that probably all of these services, or at least ip.sb for sure, are nonfree, and so is there database, and as such they would attract an F-Droid anti-feature unless you put them in a separate module like you wanted to do for weather sources themselves.

**Comment by papjul** [comment]
> I want to point out that probably all of these services, or at least ip.sb for sure, are nonfree, and so is there database, and as such they would attract an F-Droid anti-feature unless you put them in a separate module like you wanted to do for weather sources themselves.

So, having AccuWeather as one of the weather sources doesn't imply the "non-free" anti-feature, but having `ip.sb` as one of the location sources does? What's the difference?

**Comment by LuccoJ** [comment]
@papjul having AccuWeather as one of the sources definitely does unless it's *not default and discouraged*, but you said you were going to have weather sources as separate APKs.

ip.sb would also likely not trigger the anti-feature if it's disabled by default, and enabling it is not recommended or somehow indicates clearly to the user that it's going to use a proprietary service. Or else, if it's a separate APK that doesn't even come with the main app.

The same is valid for both.

**Comment by papjul** [comment]
F-Droid version will use FOSS sources (Open-Meteo and GPS) by default and when trying to use a different source for the first time, a dialog with links to terms and privacy policy will open and user will be able to choose between "Continue" and "Cancel". To my knowledge, there is no other weather app that go that far, but I feel like it's an important thing to do.

Additionally, any source that requires a secret will not be available by default for F-Droid, the user will have to add its API key in settings, so they will have to have accepted terms and privacy policy to get an API key from the source website.

It will take time to implement in app, so I prefer focusing on stabilizing app and adding important features before working on F-Droid specific features (although non-F-Droid users can also be interested by terms/privacy policy).

**Comment by LuccoJ** [comment]
Note that using network location/(in addition or instead of GPS) is fine for F-Droid, because your app would just be invoking a standard Android API, while whether the implementation is free or proprietary depends on the phone, but doesn't impact the free status of your app.

**Comment by papjul** [comment]
This code is only part of the Google Play release that was not released yet (see `src_gplay` in path).

Both Google Play and not Google Play releases use device network provider (if any).
The Google Play release has a proprietary "fused location" feature on top of it, this feature only works on devices with Google Play Services, so it will only be released on Google Play.
