### ISSUE TITLE
Weather Data Updating With Notification

### ISSUE THREAD

**Issue by HonestAbe7** [breezy-weather/breezy-weather#254]
### Steps to reproduce

This is automatically done by default.

### Expected behavior

Would like a setting to not get notified that the weather data is being updated.

### Actual behavior

It updates and that cloud icon shows on my notifications. I thought it was from Google or WhatsApp at first.

### Weather source used

AccurWeather

### Breezy Weather version

4.4.1-beta

### Android version

Android 10

### Device

LG L355DL

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I read the [Frequently Asked Questions](https://github.com/breezy-weather/breezy-weather/blob/main/HELP.md) document and followed instructions if relevant.
- [X] I have updated the app to **[latest version](https://github.com/breezy-weather/breezy-weather/releases/latest)**.

**Comment by papjul** [comment]
It's not a bug, it's an Android requirement, and it ensures the job will not be killed during a potentially long-running process.
See technical doc: https://developer.android.com/guide/background/persistent/how-to/long-running

If you don't want to see any notification related to background services, just turn off the "Background services" channel in Android settings for the app?
