### ISSUE TITLE
Allergen labels invisible with "Dark mode" set to "Day / Night" due to wrong text color

### ISSUE THREAD

**Issue by noscirep** [breezy-weather/breezy-weather#257]
### Steps to reproduce

1. Ensure that "Dark mode" is set to "Day / Night" under "Settings" > "Appearance".
2. Scroll down to the "Allergen" card.

It's possible that this issue doesn't arise after sunset, when the "Night" part of the "Day / Night" mode is active. Will check tonight and report back, if necessary.

### Expected behavior

The allergen labels ("Birch", "Grass", etc.) should be visible.

### Actual behavior

The allergen labels ("Birch", "Grass", etc.) are not really visible due to white text on white background (the faint text can be seen if the screen is viewed at a certain angle, at least on my device).
![breezy-weather-allergens-wrong-color](https://github.com/breezy-weather/breezy-weather/assets/50173279/25b3438d-d86c-4a20-9800-1be6a4348164)

### Weather source used

Open-Meteo

### Breezy Weather version

4.4.1-beta

### Android version

Android 12

### Device

OnePlus Nord

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I read the [Frequently Asked Questions](https://github.com/breezy-weather/breezy-weather/blob/main/HELP.md) document and followed instructions if relevant.
- [X] I have updated the app to **[latest version](https://github.com/breezy-weather/breezy-weather/releases/latest)**.

**Comment by papjul** [comment]
> It's possible that this issue doesn't arise after sunset, when the "Night" part of the "Day / Night" mode is active.

Indeed, it happened when location day/night is different from app theme.
It is fixed in af178a80af7458c96a816b4d2a763c492826f5e9

**Comment by papjul** [comment]
In the meantime, you can switch the Dark Mode preference as a workaround.
