### ISSUE TITLE
Rename "Dark mode" setting to "Theme"

### ISSUE THREAD

**Issue by noscirep** [breezy-weather/breezy-weather#261]
### Describe your idea

I would like to suggest that the "Dark mode" setting be renamed to "Theme" (or something similar). "Dark mode" sounds like a simple on/off kind of thing, whereas "Theme" seems more appropriate given the available options for the setting in question.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] My idea is not related to an existing feature described in the [Homepage](https://github.com/breezy-weather/breezy-weather/blob/main/docs/HOMEPAGE.md) document.
- [X] I have updated the app to **[latest version](https://github.com/breezy-weather/breezy-weather/releases/latest)**.

**Comment by papjul** [comment]
I'm surprised to see this issue arises for the second time in such a short period (I think the first was on Matrix). I don't understand why it seems so important but let's dive into it, so it stays for the record ;)

I think "Dark mode" is appropriate as it lets you choose between light and dark (with different modes available to apply it) whereas "Theme" - while can also be used as in "Dark theme" - would fit more for the general appearance of the app, such as being able to customize Monet dynamic colors. If we decide "Dark mode" becomes "Theme", then we will be stuck later if we decide to have a "Theme" feature (on which "Dark mode" can be applied or not).

Additionally, "Dark mode" is specific to what it does, while "Theme" is more generic, so from a user experience point of view, it is a regression.

For reference, here is a screenshot of Tachiyomi appearance settings:
![IMG_20230731_072706](https://github.com/breezy-weather/breezy-weather/assets/1449159/900da91c-c5e4-4eb5-8c3f-fec63d240529)

**Comment by noscirep** [comment]
What can I say, great minds think alike. :) No, seriously, I guess what you are saying makes sense. Thank you for the explanation, @papjul.
