### ISSUE TITLE
[Widgets] Add Custom Text/Font Colors

### ISSUE THREAD

**Issue by DevMasterBlake** [breezy-weather/breezy-weather#264]
### Describe your idea

Is it possible to add a feature that allows custom text fonts to match homescreen themes?

The attached screenshot shows Today Weather widget at the top matching my wallpaper, the next two widgets are from Breezy Weather, which only allows either black or white text/font. 

### Other details

![Screenshot_20230730_195524_Nova7](https://github.com/breezy-weather/breezy-weather/assets/124249252/8c7652e0-82ae-4c49-92e9-c64d1a854341)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] My idea is not related to an existing feature described in the [Homepage](https://github.com/breezy-weather/breezy-weather/blob/main/docs/HOMEPAGE.md) document.
- [X] I have updated the app to **[latest version](https://github.com/breezy-weather/breezy-weather/releases/latest)**.

**Comment by Cod3dDOT** [comment]
I think the effort to add new features to legacy widgets is better suited to first implement #142. Then it will be much easier to add like this.

**Comment by papjul** [comment]
Yes, unfortunately, widget part is a full-time job on this project, and text color is just one part of it.

The right way would be to:
- Make a state of art of existing weather apps
- Design thinking to make the best UX from the best features found in this state of art
- Allow Material you widgets to be configurable
- Decide what to do with legacy widgets (rewrite them, merge some of them (I find many to be very similar), etc)

While the easy way could be to just implement every requested widget feature on top of each other, I think it's important for the health of the app to handle all widget-related things from the ground as part of a bigger project, that I unfortunately cannot take care of at the moment :/

There are many core features I want to handle first and I consider widgets as "nice to have" priority for now. There are also future core features that will then land on widgets (see also #252).

So I'm putting this message here for the record, I'm not ignoring this idea, it just can't be handled in the short term ;)

**Comment by DevMasterBlake** [comment]
I totally understand and appreciate your timely response. If I had the expertise, I'd be happy to contribute but I'm merely in the learning stages. Thank you again for all you do.

**Comment by papjul** [comment]
Currently, we allow to choose between black & white texts to allow for a good contrast with the wallpaper. Using primary color is the responsibility of the widget designer so that it's not used for every text, but creates a hierarchy between primary colors and regular body color (have a look at Material You widgets). Using other colors is not an option that will be offered in Breezy Weather itself, but can technically be done from an outside app re-using our data from Gadgetbridge (or our own future #863).
