### ISSUE TITLE
Microsoft (Azure Maps)

### ISSUE THREAD

**Issue by Cod3dDOT** [breezy-weather/breezy-weather#265]
### Link to publicly available documentation of the API

https://learn.microsoft.com/en-us/rest/api/maps/weather

### Available and not available data

Available: Air Quality, Minutely/Hourly/Daily/ forecasts, Historical data, current conditions (wind/precipitation/temperature)
Not available: Astronomy

### Are you going to develop yourself the new source for the app?

Yes

### Give a bit more details or context about this source

Shows up as accurate weather source for my location, so decided to implement it.

### Acknowledgements

- [X] This weather source has a free-tier available with hourly forecast
- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written the name of the source as the title of this issue.
- [X] I have updated the app to **[latest version](https://github.com/breezy-weather/breezy-weather/releases/latest)** and this source is not part of it.

**Comment by papjul** [comment]
I'm having trouble to find a free-tier for weather data. The "Standard S0" only mentions weather tiles, and explicit exclude "Weather" from the 25000 common rate-limit. Can you help me?

**Comment by Cod3dDOT** [comment]
https://azure.microsoft.com/en-us/pricing/details/azure-maps/
Gen2 pricing has weather under Location Insights listed as 1000. I assumed that it is free 1000 requests/month. It is not a lot, but it unlocks full api access, so we can support enterprice features without a subscription. I have confirmed that itworks using my api key.

**Comment by papjul** [comment]
> Gen2 pricing has weather under Location Insights listed as 1000. I assumed that it is free 1000 requests/month.

Unfortunately, unless it is a mistake, if there is no unit, it means you have 1000 free calls, then it’s done. It’s not refilled every month. Since the billing is per number of transactions and not a defined amount of transactions per month, I’m pretty sure I have the correct understanding. But let me know if you find something else.

**Comment by papjul** [comment]
Leaving open for search/reverse geocoding

**Comment by papjul** [comment]
Closing as source requires credit card info and will bill after 1000 calls.

If you are interested in using it, @Cod3dDOT will maintain it on a branch on their fork.
