### ISSUE TITLE
Improve location parsing on AccuWeather 

### ISSUE THREAD

**Issue by glemco** [breezy-weather/breezy-weather#267]
### Steps to reproduce

Searching for some cities/districts (visible in Turkey) doesn't return the proper name, in the search results the name is in parenthesis but after selection, nothing is displayed.

### Expected behavior

If the city name is empty (for whatever reason, call it a bug in the API), we should display at least something else, like the name shown in parenthesis. 

### Actual behavior

In this specific example, turkey has a kind of odd  (IMO, no offence 😅) way to represent cities/provinces/districts.
Take Istanbul, it qualifies somehow as a province, but it's so huge that if you want to get some accurate weather, you need to put the district as well. However most district have an empty city name as returned from AccuWeather (try to search for Uskudar, you see the district name and the same in parenthesis, but search for Umraniye or Kadikoy and you'd see just the one in parenthesis).
The same behaviour happens to what can be seen as an actual city (rather than a district) in other provinces, e.g. Corlu.

### Weather source used

AccuWeather

### Breezy Weather version

4.4.1 beta

### Android version

Android 12

### Device

Oneplus 8T

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I read the [Frequently Asked Questions](https://github.com/breezy-weather/breezy-weather/blob/main/HELP.md) document and followed instructions if relevant.
- [X] I have updated the app to **[latest version](https://github.com/breezy-weather/breezy-weather/releases/latest)**.

**Comment by papjul** [comment]
Once next release is available, you will have to re-add your existing locations

**Comment by glemco** [comment]
Great, thanks for the quick fix!
