### ISSUE TITLE
[Location list] Stay informed card stays visible after allowing notifications via settings / app-info

### ISSUE THREAD

**Issue by min7-i** [breezy-weather/breezy-weather#268]
### Steps to reproduce

1. Start with a clean install of the app.
2. Add a new location.
3. Go to settings -> notifications.
4. Activate the notification for alerts about precipitation.
5. Allow notifications.
6. Go back to the location list.

### Expected behavior

The "stay informed" card isn't visible anymore.

### Actual behavior

The "stay informed" card is still visible. However, tapping on it has not effect anymore as notifications have already been allowed.

### Weather source used

N/A

### Breezy Weather version

4.4.1-beta

### Android version

Android 13 (GrapheneOS)

### Device

Google Pixel 6a

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I read the [Frequently Asked Questions](https://github.com/breezy-weather/breezy-weather/blob/main/HELP.md) document and followed instructions if relevant.
- [X] I have updated the app to **[latest version](https://github.com/breezy-weather/breezy-weather/releases/latest)**.

**Comment by papjul** [comment]
556c8d398432f2015a8bcf49c30ec12beec36c9d will improve this a bit. Needs a full app restart.
