### ISSUE TITLE
Allergen card shown with AccuWeather even with no allergen data

### ISSUE THREAD

**Issue by LuccoJ** [breezy-weather/breezy-weather#273]
### Steps to reproduce

1. Be somewhere not in the US
2. Enable an Open-Meteo provider anywhere
3. Pick AccuWeather as your provider for some other location

### Expected behavior

You should see an allergen card (if enabled) in the Open-Meteo location, but you shouldn't see it in the AccuWeather location because the data are not provided.

### Actual behavior

Instead, I see an allergen card with AccuWeather too, just with everything set to "0".

### Weather source used

AccuWeather

### Breezy Weather version

4.4.1-beta

### Android version

Android 10

### Device

Samsung Galaxy S5

### Other details

I imagine that maybe people in the US have the same problem if they select Open-Meteo instead, but I haven't verified that.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I read the [Frequently Asked Questions](https://github.com/breezy-weather/breezy-weather/blob/main/HELP.md) document and followed instructions if relevant.
- [X] I have updated the app to **[latest version](https://github.com/breezy-weather/breezy-weather/releases/latest)**.

**Comment by papjul** [comment]
> I imagine that maybe people in the US have the same problem if they select Open-Meteo instead, but I haven't verified that.

No, it doesn't reproduce in that case. We have 6 allergens available with Open-Meteo (and 8 in total) and only those currently measured are displayed (that means 4 allergens in Europe, and 0 in US).

So, let me check if that's because:
- AccuWeather tells us they measured 0 / m³ for the given pollen
- Wrong convert from `null` to `0` on our side

**Comment by papjul** [comment]
![image](https://github.com/breezy-weather/breezy-weather/assets/1449159/4acee4e4-ec17-4729-8f85-5ba150635fa6)

Urgh, that’s what I thought. What a great idea it is to say “I measured 0 / m³ and trust me, it’s good”…

For this source, I will replace all 0 with null if and only if all allergens from the 15-day period are 0 / m³.
