### ISSUE TITLE
Fails to Update Weather Status

### ISSUE THREAD

**Issue by SleepDaemon** [breezy-weather/breezy-weather#276]
### Steps to reproduce

Either manually or when it auto updates

### Expected behavior

Should Update the status of the current weather

### Actual behavior

Just fails and gives error log

![Screenshot_20230801_080254_HTML Viewer](https://github.com/breezy-weather/breezy-weather/assets/88533953/88e5eb6a-ee02-471c-a2e9-a63c699d148a)

# Separate crash log from the debug button
### Weather source used

Accuweahter

### Breezy Weather version

v4.4.1-beta

### Android version

Android 13/OneUI 5.1

### Device

Samsung Galaxy S22+

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I read the [Frequently Asked Questions](https://github.com/breezy-weather/breezy-weather/blob/main/HELP.md) document and followed instructions if relevant.
- [X] I have updated the app to **[latest version](https://github.com/breezy-weather/breezy-weather/releases/latest)**.

**Comment by papjul** [comment]
"Request timed out" is not app issue.

**Comment by SleepDaemon** [comment]
> "Request timed out" is not app issue.

I'm guessing it's enterprise API limitations

**Comment by papjul** [comment]
No, "time out" means you failed to have a response from the server within a given time (30 seconds in Breezy Weather). Please check your network.
