### ISSUE TITLE
[New widget] Hourly summary table

### ISSUE THREAD

**Issue by Iz-zzzzz** [breezy-weather/breezy-weather#277]
### Describe your idea

The widget shows a lot of information in hourly like Temp., Rain, Wind, Wind dir., Weather icon (can customize) with easily understand layout.

Is it possible to add a widget shows information like attached screenshot?  

### Other details

![1YH-fHX2Z8AYy9jLg4Pnwn8dlV13x_HMxgaz858SySPC88-ukNw](https://github.com/breezy-weather/breezy-weather/assets/57972212/e743ce0c-145f-485a-aaa0-3537a863a310) (Windy app)

(Thank you for fixing issues I had with the original one :D )

### Reason
- Windy app provides only own data difference from Breezy Weather can use data from many providers.
- Windy app usually error when reload data.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] My idea is not related to an existing feature described in the [Homepage](https://github.com/breezy-weather/breezy-weather/blob/main/docs/HOMEPAGE.md) document.
- [X] I have updated the app to **[latest version](https://github.com/breezy-weather/breezy-weather/releases/latest)**.

**Comment by papjul** [comment]
Am I understanding correctly you want a hourly widget that is a table summary of temperature/rain/wind for the next 5~6 hours?

**Comment by Iz-zzzzz** [comment]
> Am I understanding correctly you want a hourly widget that is a table summary of temperature/rain/wind for the next 5~6 hours?

next 48+ hr depends on providers.

**Comment by papjul** [comment]
But you asked for a widget, right?

Currently, on homescreen, our hourly trends can fit 5 hours on widget widget. I think with a table, I can fit 6~7 but not more or it will be impossible to read.

**Comment by Iz-zzzzz** [comment]
> But you asked for a widget, right?
> 
> Currently, on homescreen, our hourly trends can fit 5 hours on widget width. I think with a table, I can fit 6~7 but not more or it will be impossible to read.

Sorry for incorrect information. I have edited my incorrect one.

**Comment by papjul** [comment]
App is not designed for 3-hour forecast.

It’s too tiny, when resizing about the size of a phone:
<img src="https://user-images.githubusercontent.com/57972212/257551946-e743ce0c-145f-485a-aaa0-3537a863a310.png" alt="" width="300" />

Also, it lacks breathing, so after adding whitespace, I wouldn’t be able to fit many hours.

So, we could make a table for the next 6~8 hours maybe, but not next 24 hours.

If you are looking for next 24-hour graphs, you may be interested by #252 instead
