### ISSUE TITLE
[Location edit] Resident location description is cut off when enabling the setting

### ISSUE THREAD

**Issue by min7-i** [breezy-weather/breezy-weather#286]
### Steps to reproduce

1. Choose a location where the resident location setting is disabled.
2. On the main screen scroll down and tap on edit.
3. Enable the resident location setting.

### Expected behavior

The entire description is visible.

### Actual behavior

Only the first two lines of the description are visible:
![cut off](https://github.com/breezy-weather/breezy-weather/assets/97251923/fdcd35ac-7a91-416d-9b77-790ce5c21fef)

The entire text is only visible after closing and reopening the dialog.

### Weather source used

N/A

### Breezy Weather version

4.4.1-beta

### Android version

Android 13 (GrapheneOS)

### Device

Google Pixel 6a

### Other details

On a side note, I think the text for the description ( location_resident_location_summaryOn ) is mixed up. It currently says "Enabled. Shown if within 20 km of current location, hidden otherwise.", but it should be "... Hidden if within..., visible otherwise.", right?

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I read the [Frequently Asked Questions](https://github.com/breezy-weather/breezy-weather/blob/main/HELP.md) document and followed instructions if relevant.
- [X] I have updated the app to **[latest version](https://github.com/breezy-weather/breezy-weather/releases/latest)**.

**Comment by papjul** [comment]
I don't like bugs that I can't reproduce haha

> On a side note, I think the text for the description ( location_resident_location_summaryOn ) is mixed up. It currently says "Enabled. Shown if within 20 km of current location, hidden otherwise.", but it should be "... Hidden if within..., visible otherwise.", right?

No, if you are within 20 km of manually added location, it will take manually added location over current location, otherwise it will switch to current location (when you're travelling, for example). I think it's mostly because you have your home location and then you're not going to add a manual location for every place you visit. I don't understand much the point of this feature, but I know at least one person that loves it.

**Comment by min7-i** [comment]
> I don't like bugs that I can't reproduce haha

Oh, I assumed that happens on all devices. At least it doesn't seem to be restricted to Android 13, because I can reproduce it on my LG G6 with Android 9.

> No, if you are within 20 km of manually added location, it will take manually added location over current location, otherwise it will switch to current location...

The help dialog ( location_resident_dialog ) describes it the other way round. That also makes more sense in my opinion:
![resident location help dialog](https://github.com/breezy-weather/breezy-weather/assets/97251923/3757ca4c-4bad-4950-828f-f2729f8123dd)

I just briefly tested it and that's also the way it behaves in version 4.4.1: the resident location is hidden when it matches the current location.

**Comment by papjul** [comment]
Ah, yes, you're right, I wrote this summary by memory, and since I don't really understand the purpose of the feature (I mean just use current location all the time?), I wrote what I thought it was doing 😅

**Comment by papjul** [comment]
> The entire text is only visible after closing and reopening the dialog.

I initially missed that part, that is rather unexpected.

In the meantime, I fixed the summary and made it shorter. I might also gain a few pixels by fixing paddings, but might not be enough, especially in other languages.

**Comment by min7-i** [comment]
After installing 4.5.0-beta it seems that the actual issue is that the dialog box itself is not resized instantly when the size of one of the text boxes inside changes.

The description for the resident location is now complete visible, however, the option for editing the weather sources is mostly hidden after the resident location was enabled. Reopening the dialog resizes it correctly, so that is a workaround.
![Inkededit dialog size](https://github.com/breezy-weather/breezy-weather/assets/97251923/f52963a3-12e8-4ad8-912d-da755ec4fa44)
