### ISSUE TITLE
Support for Meteoalarm warnings

### ISSUE THREAD

**Issue by Marko-98** [breezy-weather/breezy-weather#290]
Hello!

Please add support for Meteoalarm warnings in the app. It's a service made by EUMETNET which puts severe weather warnings for European countries. 
Meteoalarm feeds are freely available here: https://feeds.meteoalarm.org/

Thanks!

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] My idea is not related to an existing feature described in the [Homepage](https://github.com/breezy-weather/breezy-weather/blob/main/docs/HOMEPAGE.md) document.
- [X] I have updated the app to **[latest version](https://github.com/breezy-weather/breezy-weather/releases/latest)**.

**Comment by papjul** [comment]
As far as I know, MeteoAlarm doesn't provide alerts by longitude/latitude, only by country.

If you have information that I don’t have, please reopen an issue by selecting "New source".

**Comment by Marko-98** [comment]
@papjul There are geocoordinates on their website also, in JSON format.

https://edrop.zamg.ac.at/owncloud/index.php/s/5dwRiKmsF3r54tb

**Comment by papjul** [comment]
The app can't download a 20 MB file, then do polygon calculation for all regions of Europe to maybe find a matching one. We need a source where for a given longitude/latitude, they give us the list of matching alerts.
It’s not the job of the app to do polygon calculation, we are not a server, we are running on mobile devices, some with low specs.

**Comment by papjul** [comment]
Reopening as we will soon have an offline reverse geocoding that will detect country at 110 m accuracy (see #693).
Once we get the correct country, we could then query the correct CAP file.
Unfortunately, this requires to open each alert link to get the polygons and then see if current longitude and latitude matches, so it's rather not optimized.
The good thing, however, is that the source covers the whole Europe and is free to use without any API key.

**Comment by papjul** [comment]
It won’t be possible to implement alerts from Meteo Alarm directly as it would require bundling a 40 MB file of geometries in the app.

However, Meteo Alarm alerts are now implemented through the WMO Severe Weather project and will be available in next version: 5.1.4.
