### ISSUE TITLE
AccuWeather is missing as a secondary source

### ISSUE THREAD

**Issue by min7-i** [breezy-weather/breezy-weather#297]
### Steps to reproduce

1. Add a location with a provider other than AccuWeather, e.g. Open-Meteo.
2. On the main screen open the edit dialog.
3. Open the weather source dialog.
4. Select the "minutely forecast" or "alert" option.

### Expected behavior

AccuWeather is **available** as an option.

### Actual behavior

AccuWeather is **missing** as an option.

### Weather source used

Open-Meteo

### Breezy Weather version

4.5.0-beta

### Android version

Android 13 (GrapheneOS)

### Device

Google Pixel 6a

### Other details

Tested via upgrading from 4.4.1-beta, but that shouldn't make a difference, I guess.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I read the [Frequently Asked Questions](https://github.com/breezy-weather/breezy-weather/blob/main/HELP.md) document and followed instructions if relevant.
- [X] I have updated the app to **[latest version](https://github.com/breezy-weather/breezy-weather/releases/latest)**.

**Comment by papjul** [comment]
Fixed in 1425d9c3f7e275b01887c2227eb8b651f39bc7cf
