### ISSUE TITLE
Adding an automatic update option and an auto updater

### ISSUE THREAD

**Issue by ayntk-ai** [breezy-weather/breezy-weather#298]
### Describe your idea

I would like to see an update notification when the app is has an update available.
It would also be great if I could update the app by simply clicking a button in the app, rather than having to download the new APK each time. It would also be great if the app would automatically update itself to the new version.
If this feature already exists, then I would love to hear how to enable it, and if not, I would love to see it implemented.
Thank you so much for this great app.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] My idea is not related to an existing feature described in the [Homepage](https://github.com/breezy-weather/breezy-weather/blob/main/docs/HOMEPAGE.md) document.
- [X] I have updated the app to **[latest version](https://github.com/breezy-weather/breezy-weather/releases/latest)**.

**Comment by papjul** [comment]
What you are looking for is [Obtainium](https://github.com/ImranR98/Obtainium).
