### ISSUE TITLE
When 'Yesterday/Alert lines in trends' setting disabled also apply setting to widgets

### ISSUE THREAD

**Issue by chocmake** [breezy-weather/breezy-weather#309]
### Describe your idea

Currently disabling the 'Yesterday/Alert lines in trends' settings only disables the lines in the main app but leaves the lines visible on the weekday widget.

Perhaps could consider sync'ing the setting so it applies to both the app and widget for consistency.

Thanks for maintaining this app btw :)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] My idea is not related to an existing feature described in the [Homepage](https://github.com/breezy-weather/breezy-weather/blob/main/docs/HOMEPAGE.md) document.
- [X] I have updated the app to **[latest version](https://github.com/breezy-weather/breezy-weather/releases/latest)**.

**Comment by papjul** [comment]
Implemented in a39bc817a09ebbabff3667bc85e43b0f98c46619
