### ISSUE TITLE
Add “Refresh widget when clicked” function

### ISSUE THREAD

**Issue by PumpkinJui** [breezy-weather/breezy-weather#322]
### Describe your idea

Actually, this is a function in Geometric Weather. But I didn't find it in the same setting section in Breeze Weather and I want it back.
When I wanted to refresh the widget's data or keep the app alive, I found it not easy. In Breezy Weather, clicking widgets will open the main GUI of the app. Then when I wanted to remove it from the Recents page, the app was killed again.
If the function is back, I can decide how the app identifies the action of clicking a widget. And that can save me from making the weather app alive all the time.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] My idea is not related to an existing feature described in the [Homepage](https://github.com/breezy-weather/breezy-weather/blob/main/docs/HOMEPAGE.md) document.
- [X] I have updated the app to **[latest version](https://github.com/breezy-weather/breezy-weather/releases/latest)**.

**Comment by papjul** [comment]
> Actually, this is a function in Geometric Weather.

I can’t reproduce. When I tap a widget in latest version of Geometric Weather, it just opens the app.

> Then when I wanted to remove it from the Recents page, the app was killed again.

Removing an app from Recents page is not supposed to kill an app. If your manufacturer did something like that, please check https://dontkillmyapp.com/ to find ways to circumvent this behavior.

**Comment by PumpkinJui** [comment]
> I can’t reproduce. When I tap a widget in latest version of Geometric Weather, it just opens the app.

But I can. Did you open that function in the Settings page? Or maybe that is not the version 3.0.10_pub?

![Screenshot_2023-08-08-16-49-23-04.png](https://github.com/breezy-weather/breezy-weather/assets/76104432/55b5295f-a665-482b-a70b-9ef9c572d750)

(The third one. In English version it is “Refresh widget when clicked”.)

You can enable “Send Notification”, then completely kill Geometric Weather from background. That should make the notification cleared too. Then, click the blank of a widget. This won't open the app but restart it. Here is a screen record about that.

https://github.com/breezy-weather/breezy-weather/assets/76104432/0dcc6203-a5cb-46e4-9bdd-3b2c25ca228a

The upper one is from Breezy Weather. The other is from Geometric Weather.

---

> Removing an app from Recents page is not supposed to kill an app.

Please check the video thanks. My phone is weird and has lots of limits.

---

> If your manufacturer did something like that, please check https://dontkillmyapp.com/ to find ways to circumvent this behavior.

ah... That website doesn't have instructions to my phone. Maybe an OPPO R11s powered by Android 8.1.0 is out of fashion?

**Comment by papjul** [comment]
> > I can’t reproduce. When I tap a widget in latest version of Geometric Weather, it just opens the app.
> 
> But I can. Did you open that function in the Settings page? Or maybe that is not the version 3.0.10_pub?

The latest version is 3.102. I seem to understand that that feature was removed by Wangdaye (and I agree with his choice, you shouldn’t be able to refresh weather from within a widget, that’s what the background update job is for).


> > If your manufacturer did something like that, please check https://dontkillmyapp.com/ to find ways to circumvent this behavior.
> 
> ah... That website doesn't have instructions to my phone. Maybe an OPPO R11s powered by Android 8.1.0 is out of fashion?

Instructions for Oppo are here: https://dontkillmyapp.com/oppo

Says you need to pin the app to prevent it from being killed when cleared from recents.

I have no intention to implement workarounds for bugs from manufacturers, so if you can’t find that feature/that feature is not available on your Oppo, I would suggest you NEVER clear any app from recents page (Breezy Weather or any other app) because it can lead to very unexpected behavior in apps.
