### ISSUE TITLE
Inverted time & dates in the Arabic UI 

### ISSUE THREAD

**Issue by mohammed-3baid** [breezy-weather/breezy-weather#324]
### Steps to reproduce

In the main page, it's translation-related bug.

### Expected behavior

The time format should be the same as any other digital clock in any language HH:MM + (ص/م) for (AM/PM) on the left side of the clock.
The date format should be DD:MM:YYYY, but Arabic is RTL so it's look like YYYY:MM:DD

### Actual behavior

The time looks like MM:HH (inverted format), even though it's not inverted in some places like: air quality and sun & moon cards.
And the date format is also inverted: M:D

### Weather source used

AccuWeather

### Breezy Weather version

Beta-4.4.1

### Android version

Android 12

### Device

Google Pixel 4a

### Other details

My system language is English, breezy weather's language is Arabic.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I read the [Frequently Asked Questions](https://github.com/breezy-weather/breezy-weather/blob/main/HELP.md) document and followed instructions if relevant.
- [X] I have updated the app to **[latest version](https://github.com/breezy-weather/breezy-weather/releases/latest)**.

**Comment by papjul** [comment]
Fixed in f3b0ad6ab01bb250b43ca3f440142b80c74a4c2e and a39bc817a09ebbabff3667bc85e43b0f98c46619
