### ISSUE TITLE
[Homepage] Refresh time language is not updating

### ISSUE THREAD

**Issue by limonovthesecond2** [breezy-weather/breezy-weather#326]
### Steps to reproduce

1. Change language in app's settings
2. Update homepage

### Expected behavior

Update time should be displayed in the appropriate language

### Actual behavior

Shows the time in the previous language

### Weather source used

AccuWeather

### Breezy Weather version

4.5.2-beta

### Android version

Android 12

### Device

Xiaomi Redmi Note 10 Pro

### Other details

The only way I found to fix the update time language after changing the language is to clear the cache

![Despite the language is now Chinese, the refresh time is still in Polish](https://github.com/breezy-weather/breezy-weather/assets/118817903/a7ee8ae2-58c0-4d7b-8014-b10241291d6a)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I read the [Frequently Asked Questions](https://github.com/breezy-weather/breezy-weather/blob/main/HELP.md) document and followed instructions if relevant.
- [X] I have updated the app to **[latest version](https://github.com/breezy-weather/breezy-weather/releases/latest)**.
- [X] I wrote my request in English, and any screenshot I attached are also in English (language can be changed from Settings > Appearance)

**Comment by papjul** [comment]
Fixed in c8fc27541587aa38000ddfa5584e5ed9c6a01f44
