### ISSUE TITLE
Add ability to select UV index for widget and customise widget 

### ISSUE THREAD

**Issue by A-Khatri** [breezy-weather/breezy-weather#327]
### Describe your idea

It would be great if the app could be able to have ability to customise widgets as well as add information to widgets for example hourly selection of chosen specific. i.e. wind, UV etc.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] My idea is not related to an existing feature described in the [Homepage](https://github.com/breezy-weather/breezy-weather/blob/main/docs/HOMEPAGE.md) document.
- [X] I have updated the app to **[latest version](https://github.com/breezy-weather/breezy-weather/releases/latest)**.

**Comment by A-Khatri** [comment]
I think different. I'm looking for a widget that can display the current or hourly UV index as there isn't a way I found able to.

**Comment by papjul** [comment]
For current UV, choose customized subtitle and input `$cuv$`.

For hourly, I'm not sure to understand how it differs from #14.

**Comment by A-Khatri** [comment]
Thanks that is what I wanted!
