### ISSUE TITLE
Precise location only in AccuWeather

### ISSUE THREAD

**Issue by Rexadev** [breezy-weather/breezy-weather#329]
### Steps to reproduce

I can't get precise weather in any service eexcept AccuWeather.

I know Met Norway and OpenWeatherMaps support it

### Expected behavior

It should

### Actual behavior

Location search failed

### Weather source used

AccuWeather

### Breezy Weather version

4.4.1-beta

### Android version

Android 11

### Device

vince crDroid Official microG

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I read the [Frequently Asked Questions](https://github.com/breezy-weather/breezy-weather/blob/main/HELP.md) document and followed instructions if relevant.
- [X] I have updated the app to **[latest version](https://github.com/breezy-weather/breezy-weather/releases/latest)**.
- [X] I wrote my request in English, and any screenshot I attached are also in English (language can be changed from Settings > Appearance)

**Comment by papjul** [comment]
Please fill in the form correctly and reopen an issue if it reproduces after updating to latest version.
