### ISSUE TITLE
When Search on any service combining city, state or country doesn't work for most countries outside US

### ISSUE THREAD

**Issue by Rexadev** [breezy-weather/breezy-weather#330]
### City + Country

New York USA doesn't work
New York United doesn't work
New York US works

### Greenville a place in NYC, NY, USA

`Greenville New` doesn't work
`Greenville` shows all Greenvilles in the world

### Expected behavior

User may specify country and/or state to better filter results 

and also precise city if not always available

### Actual behavior

See steps to reproduce

### Weather source used

Any

### Breezy Weather version

4.4.1-beta

### Android version

Android 11

### Device

vince crDroid Official

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I read the [Frequently Asked Questions](https://github.com/breezy-weather/breezy-weather/blob/main/HELP.md) document and followed instructions if relevant.
- [X] I have updated the app to **[latest version](https://github.com/breezy-weather/breezy-weather/releases/latest)**.
- [X] I wrote my request in English, and any screenshot I attached are also in English (language can be changed from Settings > Appearance)

**Comment by papjul** [comment]
AccuWeather:
`Greenville, NY` works
`Greenville, New York` works

GeoNames:
`Greenville, NY` doesn’t work
`Greenville, New York` works

OpenWeather:
`Greenville, NY` doesn’t work
`Greenville, New York` doesn’t work

I would suggest switching the default location search in settings for your usage.

**Comment by Rexadev** [comment]
s

**Comment by Rexadev** [comment]
# [Related] [Feature Request] Add a "location picker". It is hard to know to what accuracy a service provides weather for.
@papjul

**Comment by Rexadev** [comment]
Searching from Country to Smaller place doesn't work example - `United States New York`
@papjul

**Comment by papjul** [comment]
One issue = one request, if we are done with this issue, please close it.

Adding a location from map is already tracked as #10

**Comment by Rexadev** [comment]
> Searching from Country to Smaller place doesn't work example - `United States New York` @papjul

@papjul not closing this one I am add to the issue

**Comment by Rexadev** [comment]
It hard to know to what accuracy a service provides weather for.
going from big to small eliminates all location user is not concerned with.
Typing a city name and app suggesting cities from other states or countries is annoying

@papjul

**Comment by papjul** [comment]
Write your address in the correct format as described in my previous comment, and you will be able to add a city for a specific province and country.
