### ISSUE TITLE
Automatic weather update fails, location is invalid error

### ISSUE THREAD

**Issue by ayntk-ai** [breezy-weather/breezy-weather#331]
### Steps to reproduce

1. Use your location to get current weather
2. Set Refresh Weather to 30min
3. First setting the location fails with accu weather in EU and also the others
4. Then setting the location suddenly works with open meteo sometimes
5. Then after 30min when it should update, a message comes in saying update failed.
-> Maybe these bugs are two different ones, but I think they are related.

### Expected behavior

The location should be set immediately and then the app should be able to update the weather as set in the settings.

### Actual behavior

It does not set the location, with some providers it only works sometimes.
Instead of doing an update after 30 minutes, a notification comes in saying
_1 update failed_
And the details of the notification say
_Failed to update
! Invalid location, please delete and add again._

### Weather source used

AccuWeather and Open Meteo

### Breezy Weather version

4.5.2-beta

### Android version

Android 12 and 13

### Device

Pixel 7 and Samsung Galaxy A12

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I read the [Frequently Asked Questions](https://github.com/breezy-weather/breezy-weather/blob/main/HELP.md) document and followed instructions if relevant.
- [X] I have updated the app to **[latest version](https://github.com/breezy-weather/breezy-weather/releases/latest)**.
- [X] I wrote my request in English, and any screenshot I attached are also in English (language can be changed from Settings > Appearance)

**Comment by papjul** [comment]
Thank you for reporting, although critical, no one detected it during the pre-release phase. I will push v4.5.3-beta in a few minutes.

**Comment by ayntk-ai** [comment]
Thank you for this great app. I am still learning to program so this is the only way I can contribute at the moment.

**Comment by papjul** [comment]
No need to! If you would like to help with the app, you can install prereleases when they are available.
On [main page](https://github.com/breezy-weather/breezy-weather) tap on Watch button to be notified of new releases.
Reporting issues on prereleases before they are stable would help me a lot for stable releases of better quality ;)
