### ISSUE TITLE
Air quality sometimes not visible

### ISSUE THREAD

**Issue by ayntk-ai** [breezy-weather/breezy-weather#332]
### Steps to reproduce

1. Set the Accu Weather as the main source and open weather for allergens.
2. Then the air quality should section should show, but it does not -> when I refresh it appears and then another refresh later it is gone again.

### Expected behavior

Air quality should always be visible.

### Actual behavior

It sometimes disappears

### Weather source used

AccuWeather and Open Meto

### Breezy Weather version

4.5.2-beta

### Android version

Android 12 and 13

### Device

Pixel 7 and Samsung Galaxy A12

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I read the [Frequently Asked Questions](https://github.com/breezy-weather/breezy-weather/blob/main/HELP.md) document and followed instructions if relevant.
- [X] I have updated the app to **[latest version](https://github.com/breezy-weather/breezy-weather/releases/latest)**.
- [X] I wrote my request in English, and any screenshot I attached are also in English (language can be changed from Settings > Appearance)

**Comment by papjul** [comment]
Weather sources changes are applied on next refresh, however it should not disappear after the first refresh.

I cannot reproduce, can you give an example of location impacted? Doesn't have to be your location for privacy reasons.

**Comment by ayntk-ai** [comment]
It may have something to do with getting the location, when I search for a location it appears and with my current location with accu weather it says failed to find current location. With open meteo it finds the location and when I switch back to accu weather after it has found my location the air quality disappears. And for the allergens I set open meto manually.

**Comment by papjul** [comment]
Yes, probably, please [retry with v4.5.3-beta](https://github.com/breezy-weather/breezy-weather/releases/tag/v4.5.3-beta).

**Comment by ayntk-ai** [comment]
It is still there.
As soon as I select Open Meteo for allergens with the main source being Accu Weather, the air quality disappears (with Accu Weather). When I select Open Meteo for Air Quality aswell it stays, but this was not the case before 4.5.2, and without allergen only Accu Weather the air quality stays.

**Comment by papjul** [comment]
Oh, I can reproduce it now with following settings (I had a hard time understanding what you did):
- Main source: AccuWeather
- Air quality: Main source
- Allergens: Open-Meteo
