### ISSUE TITLE
Let us select the day for the next hourly forecast

### ISSUE THREAD

**Issue by ayntk-ai** [breezy-weather/breezy-weather#333]
### Describe your idea

Let us select the day for the hourly forecast so that we can easily switch between days and their respective hourly weather. Because now we have to scroll in the nex ours view, to the day in the hourly forecast, which is not ideal. And in the next day view we do not get the hourly forecast. Either let us select the day in the next hour section, or in the next day section, if I click on a day that already has an hourly forecast, it will show it in the overview. Obviously only if this is possible.
Thanks for a great app.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] My idea is not related to an existing feature described in the [Homepage](https://github.com/breezy-weather/breezy-weather/blob/main/docs/HOMEPAGE.md) document.
- [X] I have updated the app to **[latest version](https://github.com/breezy-weather/breezy-weather/releases/latest)**.

**Comment by papjul** [comment]
Duplicate as #13 (or at least, that's how I will implement it)
