### ISSUE TITLE
API limit reached when I can still make requests on browser

### ISSUE THREAD

**Issue by SpookedByRoaches** [breezy-weather/breezy-weather#343]
### Steps to reproduce

Refresh weather info.

### Expected behavior

It should show the weather.

### Actual behavior

It says "API limit reached"

### Weather source used

All of them

### Breezy Weather version

4.5.3-beta

### Android version

Android 13

### Device

Google Pixel 6

### Other details

I have tried to change the weather source but the issue is the same. I've also made an API request on the browser and open-meteo replies with no issue.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I read the [Frequently Asked Questions](https://github.com/breezy-weather/breezy-weather/blob/main/HELP.md) document and followed instructions if relevant.
- [X] I have updated the app to **[latest version](https://github.com/breezy-weather/breezy-weather/releases/latest)**.
- [X] I wrote my request in English, and any screenshot I attached are also in English (language can be changed from Settings > Appearance)

**Comment by papjul** [comment]
I can't reproduce.

Lacks a lot of info: what is your location service, are you using current location or manually added location?

**Comment by papjul** [comment]
As reported on Matrix, OpenWeather and Pirate Weather are currently rate-limited (either as main source or secondary). If you want to keep using them, you will have to add your own API key.

In next version, I will add the name of the weather source having the rate limit in the snackbar error message.

If that solved your issue, please let us know.

**Comment by SpookedByRoaches** [comment]
> I can't reproduce.
> 
> Lacks a lot of info:
> 
>     1. what is your location service?
> 
>     2. are you using current location or manually added location?
> 
>     3. is it a fresh install or did it happen suddenly?
> 
>     4. any other relevant info
1. Android (according to the app)
2. Current location
3. Happens every so often
4. One other thing is that the app takes a long time before finally reporting that the service has hit the rate limit.

> As reported on Matrix, OpenWeather and Pirate Weather are currently rate-limited (either as main source or secondary). If you want to keep using them, you will have to add your own API key.
> 
> In next version, I will add the name of the weather source having the rate limit in the snackbar error message.
> 
> If that solved your issue, please let us know.
I understand that the rate is limited but the problem is that after the app told me that I've reached the rate limit. I went to the browser and made a request 
`https://api.open-meteo.com/v1/forecast?latitude=52.52&longitude=13.41&hourly=temperature_2m`
and the browser showed me the JSON response immediately. Unless the app is making the requests from a central server and reporting it back to my client, I don't think I really hit the rate limit. 

Although, it seems like I can get the data now without any issue for now. But it happened a couple of times in the past 3 months, so I don't think this is a fluke. Please let me know if I can do something to gather more information.

**Comment by papjul** [comment]
>     2. Current location
>     4. One other thing is that the app takes a long time before finally reporting that the service has hit the rate limit.

It's not the service that is taking time to report the rate limit, here is what happens:
1) App requests updated coordinates (takes 10 seconds to have as precise coordinates as possible)
2) Service reports it's rate-limited (takes milliseconds)

You can add your location manually if you don't want step 1.

> Although, it seems like I can get the data now without any issue for now. But it happened a couple of times in the past 3 months, so I don't think this is a fluke. Please let me know if I can do something to gather more information.

Yes, for each location where this issue happens, go to footer, tap Edit > Sources, and make a screenshot. Post screenshots here.

**Comment by papjul** [comment]
There is no such thing as a "default weather source", when you add your current location initially, app asks you to choose which source you want to use without preselecting any source for you. Only you decide which source you want to use.

**Comment by SpookedByRoaches** [comment]
Then I must have chosen AccuWeather and forgot about it? I don't know.

**Comment by papjul** [comment]
I'm not aware of rate-limit issues with AccuWeather but I don't use so I can't say. If there are, you may need to use your own API key.

**Comment by chriskangr** [comment]
Same here. This is happening to me with the OpenWeather source.
In every refresh, it keeps whining "! API requests limit reached" With API key Default(unchanged).
If I put my API key it always says "API access unauthorized",
if I put it in the browser my API key no problem.
1.location service: android
2. In both cases the shame
3. fresh install

V 4.5.4-b and olders
openplus 6t
Android 11

Also:
Bug #299 it remains unresolved on my device.

Thanks for sharing your beautiful work with us!!!

**Comment by papjul** [comment]
> Same here. This is happening to me with the OpenWeather source. In every refresh, it keeps whining "! API requests limit reached" With API key Default(unchanged). If I put my API key it always says "API access unauthorized", if I put it in the browser my API key no problem. 1.location service: android 2. In both cases the shame 3. fresh install

Please [read FAQ](https://github.com/breezy-weather/breezy-weather/blob/main/HELP.md#required-api-key-missing--api-requests-limit-reached--api-access-unauthorized--update-not-yet-available), API limit reached is a different issue than "API access unauthorized".

> Also: Bug #299 it remains unresolved on my device.

I can see it fixed in daily, but not in hourly, I thought I had fixed both back then. Will check.

**Comment by chriskangr** [comment]
Yes, I know that's a different matter...
Thanks for the link, my question is solved.

You're right, it's only on the hourly.
