### ISSUE TITLE
New logo

### ISSUE THREAD

**Issue by timber-they** [breezy-weather/breezy-weather#348]
### Steps to reproduce

Look at the logo.

### Expected behavior

It shouldn't look the way.

### Actual behavior

It does look like a swastika, which is problematic, because it's a fascist symbol.

### Weather source used

All

### Breezy Weather version

All

### Android version

All

### Device

All

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I read the [Frequently Asked Questions](https://github.com/breezy-weather/breezy-weather/blob/main/HELP.md) document and followed instructions if relevant.
- [X] I have updated the app to **[latest version](https://github.com/breezy-weather/breezy-weather/releases/latest)**.
- [X] I wrote my request in English, and any screenshot I attached are also in English (language can be changed from Settings > Appearance)

**Comment by papjul** [comment]
Are you using the monochrome icon?

**Comment by papjul** [comment]
OK, I checked the monochrome icon and it looked even less like a swastika, so it's not that.

Basically, the logo conveys 3 ideas:
- A windmill for "Breezy"
- A sun for weather
- A paper windmill (geometrical shape) to remind its origin (Geometric Weather)

I forwarded the issue to the designer, I'm kinda sad to let go of the third idea but I would prefer people to not be reminded of something like that in this joyful and colorful logo.

**Comment by papjul** [comment]
Implemented in de7321c609fa628091c3550d0f177208bd06c682
