### ISSUE TITLE
Text hard to read with sun and wind wallpapers

### ISSUE THREAD

**Issue by DylanAkp** [breezy-weather/breezy-weather#349]
### Actual behavior
The application provides a few wallpapers by default, they are nice, and all are blue or purple, with the exception of 2:
- Wind
- Clear sky

(they are yellow)
This isn't a big issue except that, with material you, the system accent become yellow, which makes things hard to read on the UI.

### Describe your idea
Maybe a blue skye with a yellow sun, and grey or blue background for wind

### Breezy Weather version
4.2.4-beta

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] My idea is not related to an existing feature described in the [Homepage](https://github.com/breezy-weather/breezy-weather/blob/main/docs/HOMEPAGE.md) document.
- [X] I have updated the app to **[latest version](https://github.com/breezy-weather/breezy-weather/releases/latest)**.

**Comment by papjul** [comment]
Can you show examples?

Isn't accented color generated by the Material You system from the wallpaper color taking into account contrast with the surface?
