### ISSUE TITLE
Update Fastlane

### ISSUE THREAD

**Issue by papjul** [breezy-weather/breezy-weather#35]
### Describe your suggested feature

So that correct information are showing in Izzy/F-Droid stores.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to **[latest version](https://github.com/breezy-weather/breezy-weather/releases/latest)**.

**Comment by gbakeman** [comment]
I'm excited to start using this app to replace Geometric Weather. If this issue is the one that will get it on the FOSS stores, then I'll be eagerly monitoring this one! Thank you!

**Comment by papjul** [comment]
> I'm excited to start using this app to replace Geometric Weather. If this issue is the one that will get it on the FOSS stores, then I'll be eagerly monitoring this one! Thank you!

See #6 

Regarding this issue, it was partially updated yesterday, we still miss updating Italian translation and having newer French screenshots to be on par with Geometric Weather.
