### ISSUE TITLE
Dark Mode No Longer Dark 4.5.4-beta

### ISSUE THREAD

**Issue by WithThisHerring** [breezy-weather/breezy-weather#356]
### Steps to reproduce

Update Breezy to new version 4.5.4-beta
Turn on Dark Mode

Other:
Breezy installed via Izzy

### Expected behavior

Main weather screens should have dark backgrounds.
Settings page should have dark background.

### Actual behavior

Main weather screens have light backgrounds.
Settings page has (correct) dark background.

### Weather source used

Accuweather

### Breezy Weather version

4.5.4-beta

### Android version

CalyxOS 4.11.3

### Device

Pixel 4A5G

### Other details

Previously, this worked correctly.

Still love this app!  Thanks!

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I read the [Frequently Asked Questions](https://github.com/breezy-weather/breezy-weather/blob/main/HELP.md) document and followed instructions if relevant.
- [X] I have updated the app to **[version 4.5.4](https://github.com/breezy-weather/breezy-weather/releases/latest)**.
- [X] I wrote my request in English, and any screenshot I attached are also in English (language can be changed from Settings > Appearance)

**Comment by papjul** [comment]
"Day / Night mode for locations" had to be reset in v4.5.4. It has always been enabled by default but if you turned it off previously, you will have to turn it off again as it was moved to a separate preference. You can go to Settings > Appearance to change it.
