### ISSUE TITLE
Add "my location" icon when displaying current location

### ISSUE THREAD

**Issue by NBA613** [breezy-weather/breezy-weather#360]
### Describe your idea

When the home screen is displaying the current location, there can be a ["my location"](https://fonts.google.com/icons?query=rock&icon.query=my+location) icon next to the city name. This would indicate that the location displayed is the user's current location and not a saved location. 

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] My idea is not related to an existing feature described in the [Homepage](https://github.com/breezy-weather/breezy-weather/blob/main/docs/HOMEPAGE.md) document.
- [X] I have updated the app to **[version 4.5.4](https://github.com/breezy-weather/breezy-weather/releases/latest)**.

**Comment by papjul** [comment]
Implemented in c5088c1b64242297b584ebd3a106aff4ecfa31ad
