### ISSUE TITLE
[Alerts] Width of details card is too narrow when it contains a short message

### ISSUE THREAD

**Issue by min7-i** [breezy-weather/breezy-weather#367]
### Steps to reproduce

This can be tested with a location that has an alert with a short message. Currently, Lyon (via Météo-France) works:
1. Add Lyon via Météo-France.
2. Open the alert details.
3. Check the last alert message.

### Expected behavior

The width of the details card should be fixed filling the entire width of the screen (minus margins).

### Actual behavior

The details card is only as wide as the text it contains:
![Image_0](https://github.com/breezy-weather/breezy-weather/assets/97251923/86eb809d-57e5-420f-a756-22e96138666c)

![InkedImage_2](https://github.com/breezy-weather/breezy-weather/assets/97251923/356cf82b-96fb-4930-b377-7b032b9249a1)

### Weather source used

Météo-France

### Breezy Weather version

4.5.4-beta

### Android version

Android 13 (GrapheneOS)

### Device

Google Pixel 6a

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I read the [Frequently Asked Questions](https://github.com/breezy-weather/breezy-weather/blob/main/HELP.md) document and followed instructions if relevant.
- [X] I have updated the app to **[version 4.5.4](https://github.com/breezy-weather/breezy-weather/releases/latest)**.
- [X] I wrote my request in English, and any screenshot I attached are also in English (language can be changed from Settings > Appearance)

**Comment by papjul** [comment]
I noticed that, and the fix would have been as easy as adding `.fillMaxWidth()`, but I didn’t do it, because I was wondering if it wouldn’t look too wide on tablet.

Looks actually pretty good:
![image](https://github.com/breezy-weather/breezy-weather/assets/1449159/1a9be170-46c6-4ad4-b990-9ffdd0d9c88a)
