### ISSUE TITLE
Choose your location in the widget?

### ISSUE THREAD

**Issue by bristow** [breezy-weather/breezy-weather#375]
### Describe your idea

I live in a french village that locates me several hundred kilometres away on Breezy Weather, I don't know why.
But, i can find my village when I add a town.

Would it be possible to choose my location in the widget settings :

![Screenshot_20230816-161709_Breezy Weather](https://github.com/breezy-weather/breezy-weather/assets/1156507/e22894a1-04fd-4b23-a64c-06f9f2d803fa)

Thank you for this fabulous app!

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] My idea is not related to an existing feature described in the [Homepage](https://github.com/breezy-weather/breezy-weather/blob/main/docs/HOMEPAGE.md) document.
- [X] I have updated the app to **[version 4.5.4](https://github.com/breezy-weather/breezy-weather/releases/latest)**.

**Comment by papjul** [comment]
The widget takes the first location. Being able to choose which location from the location list to use is something we are thinking of for next-gen widgets.

If the "current location" cannot find you reliably, you can:
1) Open the app
2) Tap location list icon
3) Tap Search icon
4) Search your village, tap it exactly with dashes if there are (see also upstream issue open-meteo/geocoding-api#10)
5) Put it first in your list
6) (Optional) Remove your current location by swipe delete

**Comment by bristow** [comment]
Oh great, it worked perfectly. I didn't know the widget took the first location in the list.

Thanks for the quick reply!
