### ISSUE TITLE
Themed Icon is away since the last release

### ISSUE THREAD

**Issue by w9925** [breezy-weather/breezy-weather#377]
### Steps to reproduce

Update to 4.6.0 beta

### Expected behavior

Monocrome Icon on home screen

### Actual behavior

Icon is in color

### Weather source used

NA

### Breezy Weather version

4.6.0

### Android version

13

### Device

Pixel 7 Pro

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I read the [Frequently Asked Questions](https://github.com/breezy-weather/breezy-weather/blob/main/HELP.md) document and followed instructions if relevant.
- [X] I have updated the app to **[version 4.5.4 or later](https://github.com/breezy-weather/breezy-weather/releases/latest)**.
- [X] I wrote my request in English, and any screenshot I attached are also in English (language can be changed from Settings > Appearance)

**Comment by papjul** [comment]
Fixed in e66b9dfb4b6db48157aff979b8faf9d10f0d4f73
