### ISSUE TITLE
Widgets not updating for hours

### ISSUE THREAD

**Issue by HonestAbe7** [breezy-weather/breezy-weather#378]
### Describe your idea

When I have a widget on my home screen, it is not being updated for hours. I set the refresh rate to 30 minutes but can't find a separate setting for the widgets.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] My idea is not related to an existing feature described in the [Homepage](https://github.com/breezy-weather/breezy-weather/blob/main/docs/HOMEPAGE.md) document.
- [X] I have updated the app to **[version 4.5.4 or later](https://github.com/breezy-weather/breezy-weather/releases/latest)**.

**Comment by papjul** [comment]
Widgets are updated when background update job completes.

Please read https://github.com/breezy-weather/breezy-weather/blob/main/HELP.md#background-updates-are-not-working
