### ISSUE TITLE
UV index not showing in main screen header

### ISSUE THREAD

**Issue by kremzli** [breezy-weather/breezy-weather#380]
### Steps to reproduce

1. Set UV index to show in the main screen header
2. Go look, no UV index in the header

### Expected behavior

UV index should show in main screen header as per the setting

### Actual behavior

No UV index in the header

### Weather source used

Open Meteo and Open Weather

### Breezy Weather version

4.6.1-beta

### Android version

One UI 5.1 (Android 13)

### Device

Samsung Galaxy A33

### Other details

Settings:

![Screenshot_20230817_031922_Breezy Weather](https://github.com/breezy-weather/breezy-weather/assets/87526638/52f9b852-f34d-4b45-83d4-97b37b9f1f2d)

Result:

![Screenshot_20230817_031928_Breezy Weather](https://github.com/breezy-weather/breezy-weather/assets/87526638/1fd97b4a-55fe-4400-b277-c0e581b8d817)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I read the [Frequently Asked Questions](https://github.com/breezy-weather/breezy-weather/blob/main/HELP.md) document and followed instructions if relevant.
- [X] I have updated the app to **[version 4.5.4 or later](https://github.com/breezy-weather/breezy-weather/releases/latest)**.
- [X] I wrote my request in English, and any screenshot I attached are also in English (language can be changed from Settings > Appearance)

**Comment by papjul** [comment]
There is no UV at night.
