### ISSUE TITLE
National Severe Weather Warnings not received

### ISSUE THREAD

**Issue by nrestell** [breezy-weather/breezy-weather#383]
### Steps to reproduce

Source: AccuWeather
When a severe weather alert is issued ("Yellow Warning for Thunderstorms") you get a notification in AccuWeather but not in Breezy (with AccuWeather as primary source, and notifications turned on).

### Expected behavior

Weather warning should come as a notification and be displayed on the screen when in the app

### Actual behavior

No notification and no weather warning shown on screen at all

### Weather source used

AccuWeather

### Breezy Weather version

4.6.0-beta

### Android version

Android 14 (Beta 5)

### Device

Google Pixel 6 Pro

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I read the [Frequently Asked Questions](https://github.com/breezy-weather/breezy-weather/blob/main/HELP.md) document and followed instructions if relevant.
- [X] I have updated the app to **[version 4.5.4 or later](https://github.com/breezy-weather/breezy-weather/releases/latest)**.
- [X] I wrote my request in English, and any screenshot I attached are also in English (language can be changed from Settings > Appearance)

**Comment by papjul** [comment]
Did you mean you get a notification in Geometric Weather but not in AccuWeather? Where in the world can I reproduce it right now?

**Comment by nrestell** [comment]
I get a notification on AccuWeather (and MetOffice) app but not in Breezy.
In expecting the alert for Burton on Trent, and Willenhall in the UK currently.

**Comment by papjul** [comment]
I'm unable to reproduce your issue.

I added Willenhall and I do have an upcoming alert displayed.

If I put Willenhall as my first location and let the background update job run, I get the notification.

**Comment by nrestell** [comment]
It appears that my service had stopped running. Restarting this has created the alert on the main screen.
