### ISSUE TITLE
AccuWeather doesn’t report any alert if at least one alert is missing a start time or end time

### ISSUE THREAD

**Issue by nrestell** [breezy-weather/breezy-weather#384]
### Describe your idea

AccuWeather alert to flood warnings issued from the UK Environment Agency. These would be good to have in Breezy as well as the Weather Warnings.

**Alert shown in AccuWeather:**
![Screenshot_20230818-073459](https://github.com/breezy-weather/breezy-weather/assets/141779566/4c93ed49-d80c-4d79-8dd5-500b157dc554)
![Screenshot_20230818-073512](https://github.com/breezy-weather/breezy-weather/assets/141779566/8504b5c4-3331-436c-82dc-9f0ebdd65bbd)

**Only the Weather Warning is shown in Breezy:**
![Screenshot_20230818-073544](https://github.com/breezy-weather/breezy-weather/assets/141779566/72d1a4cf-2da5-4fcd-b944-d882293874ff)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] My idea is not related to an existing feature described in the [Homepage](https://github.com/breezy-weather/breezy-weather/blob/main/docs/HOMEPAGE.md) document.
- [X] I have updated the app to **[version 4.5.4 or later](https://github.com/breezy-weather/breezy-weather/releases/latest)**.

**Comment by papjul** [comment]
Breezy Weather asks for alerts by longitude/latitude to avoid cities such as New York returning alerts for all neighbourhoods of the whole city, which would be a lot.

From my investigation, AccuWeather doesn't give us this alert if we ask alerts by longitude/latitude, but does if we request it for the whole city. In that later case, the alert is only emitted for Upper Tame, but I couldn’t find this district on a map. If by "Upper Tame" they mean "above River Tame", it seems rather far away from it, so it shouldn’t be valid where you are.

Also, there are two Willenhall really close to each other, and you never mention which one it is in your issues, I will need that information ;)

**Comment by papjul** [comment]
I can confirm, according to this map, that Willenhall, Coventry, UK does not have a flood alert right now:
https://check-for-flooding.service.gov.uk/target-area/033WAF303?v=map&lyr=mv,ts,tw,ta&fid=flood.033WAF303&ext=-2.296727,52.279801,-1.304442,52.671627

**Comment by nrestell** [comment]
Hi,

I am referring to Willenhall, Walsall (didn't realise there was one in Coventry!)

From the EA website, it shows the potential flooding in the area, and it does cover this Willenhall (I've highlighted this on the pic):
![23-08-18--082721](https://github.com/breezy-weather/breezy-weather/assets/141779566/c7aa7086-e4e2-40e9-ae45-24f85c50294e)

**Comment by papjul** [comment]
Now, I can reproduce the issue when fake travelling to a point near the river. I will look into it.

**Comment by papjul** [comment]
The issue is caused by flood alert missing the end time (it’s a continuous alert).
Even worse, if there is a flood alert (or any other that doesn't have a start or end time), no other alert will be reported.
The issue has been happening since almost the beginning of the fork.
An emergency fix is coming.
