### ISSUE TITLE
Widget: make tap on clock configurable

### ISSUE THREAD

**Issue by abonhote** [breezy-weather/breezy-weather#390]
### Describe your idea

Tapping on the clock opens the alarm part of the "clock" app on my samsung. This should be configurable IMHO.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] My idea is not related to an existing feature described in the [Homepage](https://github.com/breezy-weather/breezy-weather/blob/main/docs/HOMEPAGE.md) document.
- [X] I have updated the app to **[version 4.5.4 or later](https://github.com/breezy-weather/breezy-weather/releases/latest)**.

**Comment by papjul** [comment]
I’m not sure to understand, if I had the default clock from Android, when I tap on it, it opens the Clock app, and there is no other configuration available. Can you clarify what kind of configuration you are expecting?

**Comment by abonhote** [comment]
It seems to look after an "alarm" intent, which is a separate thing on Samsung devices. I cleared the defaults and I had two alarm apps to choose from.

Well, never mind, I installed a clock app from fdroid which does this differently.

**Comment by papjul** [comment]
> It seems to look after an "alarm" intent

Yes, that’s how it works. Except Alarm and Clock are part of the "same" thing.

We use ACTION_SHOW_ALARMS, probably the same intent as what other clock widgets are doing:
https://developer.android.com/reference/kotlin/android/provider/AlarmClock

If you were able to workaround Samsung-specific behavior by installing another app, great, I'm closing this issue then, thank you for leaving a comment explaining how you did it if other users are having the same issue ;)
