### ISSUE TITLE
Météo France displays incorrect temperatures on the daily forecast

### ISSUE THREAD

**Issue by HommeCrabe** [breezy-weather/breezy-weather#393]
### Steps to reproduce

1. Add Villeurbanne (69100 France) as location
2. Pick "Météo France" as weather source
3. Look at daily forecast
4. Compare with official Météo France values : https://meteofrance.com/previsions-meteo-france/villeurbanne/69100

### Expected behavior

Temperatures should be the same between the app and Météo France.

### Actual behavior

Temperatures differ slightly on certain days.

Breezy Weather:
![breezy1](https://github.com/breezy-weather/breezy-weather/assets/48383143/ea221c73-d4d2-41bb-95f3-70832f626330)

Météo France:
![meteofrance1](https://github.com/breezy-weather/breezy-weather/assets/48383143/cb1f0dd1-e68b-4aa4-9f95-7ad1e81984cb)

They are however correct on Geometric Weather 3.102:
![geometric1](https://github.com/breezy-weather/breezy-weather/assets/48383143/262d9fdd-5077-4658-84ac-695e534b0572)

### Weather source used

Météo France

### Breezy Weather version

4.5.4 and 4.6.2

### Android version

Android 10

### Device

Huawei P20

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I read the [Frequently Asked Questions](https://github.com/breezy-weather/breezy-weather/blob/main/HELP.md) document and followed instructions if relevant.
- [X] I have updated the app to **[version 4.5.4 or later](https://github.com/breezy-weather/breezy-weather/releases/latest)**.
- [X] I wrote my request in English, and any screenshot I attached are also in English (language can be changed from Settings > Appearance)

**Comment by papjul** [comment]
Geometric Weather is incorrect. Correct night temperature is the overnight one and it matches what your screenshot of website shows.

You can read more about it here: https://github.com/breezy-weather/breezy-weather/blob/main/docs/HOMEPAGE.md#daily-forecast
