### ISSUE TITLE
The sun wallpaper/background looks strange

### ISSUE THREAD

**Issue by rencornationers** [breezy-weather/breezy-weather#394]
### Steps to reproduce

- Just open the app
- or set the live wallpaper...
- or test it out in settings menu...

### Expected behavior

The same sun background just like in Geometric Weather

### Actual behavior

For some reason, the two layers of the sun in Breezy Weather became the same size, which caused the solar gradient to become unbalanced and strange... In Geometric Weather, this background is displayed normally.

### Weather source used

AccuWeather

### Breezy Weather version

4.5.4-beta

### Android version

Android 11

### Device

Realme C3

### Other details

![Screenshot_2023_08_20_17_24_43_45_7a877250e9599c2457e62eb3b38206f6](https://github.com/breezy-weather/breezy-weather/assets/47507225/7306dd92-25c1-4bdd-bca0-cc127ec17eb7)
![Screenshot_2023_08_20_17_24_59_58_7a877250e9599c2457e62eb3b38206f6](https://github.com/breezy-weather/breezy-weather/assets/47507225/73d0e875-5b4a-41b6-95dc-e38cccdc584c)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I read the [Frequently Asked Questions](https://github.com/breezy-weather/breezy-weather/blob/main/HELP.md) document and followed instructions if relevant.
- [X] I have updated the app to **[version 4.6.3 or later](https://github.com/breezy-weather/breezy-weather/releases/latest)**.
- [X] I wrote my request in English, and any screenshot I attached are also in English (language can be changed from Settings > Appearance)

**Comment by papjul** [comment]
Adding a screenshot of them side by side to make it easier to understand:
![image](https://github.com/breezy-weather/breezy-weather/assets/1449159/136cadcc-5e1e-42cd-b15f-dc4f54204425)

Correct one is on the left.
