### ISSUE TITLE
UX: choice of making a location resident "disappears" after turning it on if current location is nearby

### ISSUE THREAD

**Issue by LuccoJ** [breezy-weather/breezy-weather#396]
### Steps to reproduce

1. Enable current location
2. Add a location <20km from the current one (but do not make it resident right away)
3. "Edit" this latter location
4. Enable the "Resident location" toggle

### Expected behavior

I would expect the toggle to become enabled, and to be able to disable it again

### Actual behavior

The whole screen switches to the current location (because the new resident location is <20km to it), and the "Resident location" setting disappears from the screen.

Now the only way to make it stop being a resident location is to open the list and swipe right, but someone who just saw the "Resident location" toggle before may not even know this is an option.

### Weather source used

AccuWeather

### Breezy Weather version

4.6.3-beta

### Android version

Android 13

### Device

Oneplus 8T

### Other details

I meant to include a video here, but I'm stuck with Github not accepting larger than 10MB, imgur not accepting longer than 60 seconds, and Matrix not giving me a downloadable URL.

So for now, I'll link to the Matrix message containing the video: https://matrix.to/#/!UsLJwohQFZyhuvymKZ:matrix.org/$KIye1ptjEU6LBQYgqKhhnEKpqsRcPtn6KMvIJzPbNy8?via=matrix.org (note: the video contains spoken audio in English).

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I read the [Frequently Asked Questions](https://github.com/breezy-weather/breezy-weather/blob/main/HELP.md) document and followed instructions if relevant.
- [X] I have updated the app to **[version 4.6.3 or later](https://github.com/breezy-weather/breezy-weather/releases/latest)**.
- [X] I wrote my request in English, and any screenshot I attached are also in English (language can be changed from Settings > Appearance)

**Comment by papjul** [comment]
Obsolete as of v5.0.
