### ISSUE TITLE
Wrong language for weather warnings in German

### ISSUE THREAD

**Issue by ayntk-ai** [breezy-weather/breezy-weather#398]
### Steps to reproduce

1. Set the application language to german
2. get a weather warning

### Expected behavior

1. warnings should be translated to german

### Actual behavior

1. warning is only partially translated
![image](https://github.com/breezy-weather/breezy-weather/assets/122374094/bf2901a3-d3f2-4a0d-afb5-5a3a140d53ff)

### Weather source used

AccuWeather

### Breezy Weather version

4.6.3-beta

### Android version

Android-13

### Device

Pixel 7

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I read the [Frequently Asked Questions](https://github.com/breezy-weather/breezy-weather/blob/main/HELP.md) document and followed instructions if relevant.
- [X] I have updated the app to **[version 4.6.3 or later](https://github.com/breezy-weather/breezy-weather/releases/latest)**.
- [X] I wrote my request in English, and any screenshot I attached are also in English (language can be changed from Settings > Appearance)

**Comment by papjul** [comment]
Can you give a city name? I can't seem to find any orange alert in Germany right now.

**Comment by ayntk-ai** [comment]
Lichtenstein, Switzerland

**Comment by papjul** [comment]
Looks like data is correct to me:
https://www.accuweather.com/de/ch/winterthur/316623/weather-warnings/316623?alertId=1392965&areaId=pfungen-hettlingen

**Comment by ayntk-ai** [comment]
Ok makes sense. Strange that they are not translating it
