### ISSUE TITLE
Notification channels are not declared

### ISSUE THREAD

**Issue by papjul** [breezy-weather/breezy-weather#40]
### Steps to reproduce

1. Fresh install

### Expected behavior

All notification channels should be available in Android app settings

### Actual behavior

No notification channels available in Android app settings

### Weather provider used

All

### Breezy Weather version

4.0.0-alpha

### Android version

All

### Device

All

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to **[latest version](https://github.com/breezy-weather/breezy-weather/releases/latest)**.

**Comment by min7-i** [comment]
Looking at the channel names I noticed that all of them are prefixed with the name of the app. Sure, it's just a minor detail, but if you ask me, removing that part would improve the readability.

| ![notification channels](https://github.com/breezy-weather/breezy-weather/assets/97251923/7f797ab4-93de-4960-adf1-42883984764b) | ![notification channels 2](https://github.com/breezy-weather/breezy-weather/assets/97251923/b0ad8287-0062-4925-ad95-db5c84a78af8) |

I don't know if it makes sense to combine it with this issue or if it's better to create a separate one. In the latter case, just let me know and I'll create a new issue.

**Comment by papjul** [comment]
Don't worry, I will fix everything at once. I think we need to fix group channel as well (everything is in Other currently)
