### ISSUE TITLE
Add At-A-Glance Widget (Similar to Android 12/12.1) and Customize Widget Size/Color

### ISSUE THREAD

**Issue by dhirenvasnani** [breezy-weather/breezy-weather#402]
### Describe your idea

I'm a user of Breezy Weather and I'm excited about the app's recent updates. I'd like to propose a couple of feature requests that I believe would enhance the user experience:

1) At-A-Glance Widget: I'd love to see the addition of an "At-A-Glance" widget that provides a quick overview of the current weather conditions, date, day, month. This widget would be similar to the one found in Pixels running Android 12/12.1.

2) Customizable Widget Size and Color: Previously, the Material You widget size was 2x2, which I found to be a perfect fit for my home screen layout. Unfortunately, it seems that the widget size has been changed to 3x2 in a recent update. I'd like to request the option to revert back to the previous 2x2 size. Additionally, having the ability to customize the color of the Material You widget(For older Android 8.0+ versions) to match my home screen's aesthetic would be a fantastic addition.

### Other details

I believe these enhancements would make Breezy Weather even more user-friendly and visually appealing. Thank you for considering my suggestions, and I look forward to seeing how Breezy Weather continues to evolve!

Thanks, Dhiren Vasnani

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] My idea is not related to an existing feature described in the [Homepage](https://github.com/breezy-weather/breezy-weather/blob/main/docs/HOMEPAGE.md) document.
- [X] I have updated the app to **[version 4.6.3 or later](https://github.com/breezy-weather/breezy-weather/releases/latest)**.

**Comment by papjul** [comment]
> Anyone there?

Yes.

**Comment by dhirenvasnani** [comment]
> > Anyone there?
> 
> Yes.

Will the feature requested by me added?

**Comment by papjul** [comment]
This issue is in "Needs review" status, we can't tell you at this state.

**Comment by e-t-l** [comment]
Note that [Another Widget](https://github.com/tommasoberlose/another-widget) already provides a Google-like At-A-Glance widget and allows you to set Breezy Weather as the source. It may be preferable to direct users to that app rather than add additional work, maintenance, and bloat to this project.

**Comment by dhirenvasnani** [comment]
> Note that [Another Widget](https://github.com/tommasoberlose/another-widget) already provides a Google-like At-A-Glance widget and allows you to set Breezy Weather as the source. It may be preferable to direct users to that app rather than add additional work, maintenance, and bloat to this project.

Yeah, i know about "another widget" but it consumes alot of battery. Anyways, I found an alternative called "[Smartspacer]"(https://github.com/KieronQuinn/Smartspacer/releases/tag/1.1)

Thanks for replying.

**Comment by papjul** [comment]
Can you explain what's the difference between At a glance widgets and standard widgets? I find a lot of articles enthusiasts about this, but they don't explain how they differ and where you can find them. A technical doc on how to implement would also be appreciated. Thanks!

**Comment by e-t-l** [comment]
> Can you explain what's the difference between At a glance widgets and standard widgets

My (possibly incorrect) understanding is that At A Glance is just the name for the Google Pixel built-in homescreen widget that shows the date, time, weather, as well as upcoming calendar events, currently playing media, etc. It's kind of an all-in-one, and it has a specific aesthetic as well.

> Yeah, i know about "another widget" but it consumes alot of battery. Anyways, I found an alternative called [Smartspacer](https://github.com/KieronQuinn/Smartspacer/releases/tag/1.1)

god Kieron Quinn is such a genius. I have a ton of his apps, and I'll now be checking out this one!
