### ISSUE TITLE
[Gadgetbridge] Incorrect precipitation probability

### ISSUE THREAD

**Issue by StevenAlexander44** [breezy-weather/breezy-weather#404]
### Describe your idea

Currently (in the last few hours), the implementation by Cod3dDOT has worked, but it would be nice to have options to:
1. Use the "feels like" temperature instead of real temperature
2. Choose between up-to-date weather or X hours forecast (maybe this should be in the gadgetbridge app?)

Also, I noticed that the debug "show cached weather" returns weird results. See screenshot:

### Other details

![Screenshot_20230821-225132_Gadgetbridge (Nightly)](https://github.com/breezy-weather/breezy-weather/assets/64290624/734c0c1c-8f1d-4ab3-90dd-fa071cb86d95)
Min temp: New York
Precip probability: 2500%
Using [Gadgetbridge nightly](https://freeyourgadget.codeberg.page/fdroid/repo/) commit 74dc0f70a

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] My idea is not related to an existing feature described in the [Homepage](https://github.com/breezy-weather/breezy-weather/blob/main/docs/HOMEPAGE.md) document.
- [X] I have updated the app to **[version 4.6.3 or later](https://github.com/breezy-weather/breezy-weather/releases/latest)**.

**Comment by papjul** [comment]
> 1. Use the "feels like" temperature instead
> 2. Use up-to-date weather or X hours forecast (maybe this should be in the gadgetbridge app?)

These data are currently not supported by the weather spec of Gadgetbridge as far as I know. The switch must also be on their side.

> Also, I noticed that the debug "show cached weather" returns weird results. See screenshot:
> 
> ### Other details
> ![Screenshot_20230821-225132_Gadgetbridge (Nightly)](https://user-images.githubusercontent.com/64290624/262205970-734c0c1c-8f1d-4ab3-90dd-fa071cb86d95.png) Min temp: New York Precip probability: 2500% Using [Gadgetbridge nightly](https://freeyourgadget.codeberg.page/fdroid/repo/) commit 74dc0f70a

Which source is it? Will look into it.

**Comment by StevenAlexander44** [comment]
This screenshot is accuweather, but I also tried another one (forgot which one) and got the same issue of "Min temp: New York"

**Comment by papjul** [comment]
> This screenshot is accuweather, but I also tried another one (forgot which one) and got the same issue of "Min temp: New York"

Probability will be fixed. Min temp must be reported to Gadgetbridge. Please link here the issue for this bug and the other ones for your feature requests in case someone is looking for it ;)

**Comment by LuccoJ** [comment]
Agreed, "Min temp" showing the location must be on the Gadgetbridge side as the *actual* min temp is shown correctly on my watch.

I think an option to use "Feels like" could be done without telling Gadgetbridge, but would only make sense if there is also "Feels like" information for the high and low, otherwise we'd be showing mismatched temperatures.

Showing an n-hour forecast instead of the current temperature does sound a bit like a hack that goes further than Gadgetbridge and the wearables ever intended: there are already forecasts for days ahead, but the current day is supposed to be high, low, and current, and has long been understood as such by wearable users.

**Comment by papjul** [comment]
> I think an option to use "Feels like" could be done without telling Gadgetbridge, but would only make sense if there is also "Feels like" information for the high and low, otherwise we'd be showing mismatched temperatures.

Yes, it's technically feasible, but I disagree it should be done on our side, otherwise each weather app would have to implement their own "switch". It's much more efficient for this feature to be done on Gadgetbridge side.

**Comment by joserebelo** [comment]
> Showing an n-hour forecast instead of the current temperature does sound a bit like a hack that goes further than Gadgetbridge and the wearables ever intended: there are already forecasts for days ahead, but the current day is supposed to be high, low, and current, and has long been understood as such by wearable users.

Zepp OS devices actually do support hourly forecasts (up to 72h ahead), and display a graph. This would have to be supported by the Gadgetbridge weather spec though (as indeed should the "feels like" value).

Extending the weather spec on the Gadgetbridge is not out of the question. Zepp OS devices support [a lot](https://codeberg.org/Freeyourgadget/Gadgetbridge/src/commit/2320043c008e47b1ea6e3156bd85987079996d5d/app/src/main/java/nodomain/freeyourgadget/gadgetbridge/service/devices/huami/Huami2021Weather.java) of weather fields that are currently not available to Gadgetbridge - and I see that quite a few of them are available in Breezy Weather :)

**Comment by arjan-s** [comment]
Came here to report the precipitation chance value in Gadgetbridge being inflated by a 100 times, and found this issue existed already. Thanks!

**Comment by papjul** [comment]
Fixed in 310a2ac1cb78a70109da62f6c6283e8d63b743f7
