### ISSUE TITLE
OpenWeather API says "Limit reached" after 1 use

### ISSUE THREAD

**Issue by HarriBuh** [breezy-weather/breezy-weather#405]
Not sure whether this has been issued here already.
Right after adding an OpenWeather source there is already the error message that the limit was reached. This can't be true, because I hardly used it at all (=1 time, some seconds ago).

Happens in the latest beta of 4.6.4 and before.

**Comment by papjul** [comment]
API key is shared by all users, that's why we suggest to use your own key to have your own limit.
