### ISSUE TITLE
Widget background color based on day/night

### ISSUE THREAD

**Issue by starvingarden** [breezy-weather/breezy-weather#409]
### Steps to reproduce

Configure a widget and set the background color to Day/Night. The background color changes based on whether Android is in light mode or dark mode.

### Expected behavior

Setting the background color for a widget to day/night should cause the background to be light when it is daytime, and dark when it is nighttime.

### Actual behavior

Setting the background color for a widget to day/night sets the background color based on whether Android is in light mode or dark mode, instead of whether it is day or night for the widget location.

### Weather source used

AccuWeather

### Breezy Weather version

4.6.3 beta

### Android version

Android 13 (GrapheneOS)

### Device

Google Pixel 7

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I read the [Frequently Asked Questions](https://github.com/breezy-weather/breezy-weather/blob/main/HELP.md) document and followed instructions if relevant.
- [X] I have updated the app to **[version 4.6.3 or later](https://github.com/breezy-weather/breezy-weather/releases/latest)**.
- [X] I wrote my request in English, and any screenshot I attached are also in English (language can be changed from Settings > Appearance)

**Comment by papjul** [comment]
Was it working in a previous version?

**Comment by Cod3dDOT** [comment]
Does not work in Geometric Weather for me.
