### ISSUE TITLE
Bureau of Meteorology [BOM] (Australia)

### ISSUE THREAD

**Issue by HelmetOwl** [breezy-weather/breezy-weather#416]
### Link to publicly available documentation of the API

http://www.bom.gov.au/catalogue/data-feeds.shtml

### Available and not available data

Has everything you need for forecasts except for maybe allergens.

### Are you going to develop yourself the new source for the app?

I don't have the time at the moment.

### Give a bit more details or context about this source

This source is the official Australian Government source and Australian's swear by it.

### Acknowledgements

- [X] This source has a free-tier available (no mandatory credit card info), and if it a main weather source, it includes free hourly forecast
- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written the name of the source as the title of this issue.
- [X] I have updated the app to **[version 4.6.3 or later](https://github.com/breezy-weather/breezy-weather/releases/latest)** and this source is not part of it.

**Comment by papjul** [comment]
How do you get forecast for given coordinates? Some people use current location or would like to switch an existing location with source X to BOM source.

So we either need:
- Endpoints by coordinates
- Reverse geocoding endpoint that gives the closest city and its ID

**Comment by HelmetOwl** [comment]
I've done a bit of research.

This file gives the list of station codes and their coordinates: ftp://ftp.bom.gov.au/anon2/home/ncc/metadata/sitelists/stations.zip. You then need to use them to formulate your call to the server. Unfortunately, it also includes the closed stations, so you'd have to filter them out (using the "end" column).

Source: https://stackoverflow.com/questions/39534018/how-to-use-bom-api-for-weather-tide-and-swell (the answer from danwild).

**Comment by papjul** [comment]
This doesn't answer my question, I'm not looking for weather at a specific station. How can I get weather for specific coordinates (longitude and latitude)? For example, if I add my current location with GPS, how can BOM give me the forecast for where I am right now?

**Comment by HelmetOwl** [comment]
Apologies; I understood your request for "endpoints by coordinates" to mean the coordinates of each station. Unfortunately, I think the reality is that you need to get the user's current coordinates and then _you_ locate their closest station, which is where the coordinates of each station would come into the picture.

> if I add my current location with GPS, how can BOM give me the forecast for where I am right now?

I don't think any service would give you the forecast for the exact location where you are; they find the closest station that they offer and give you the forecast there. Many _do_ calculate the closest station for you, though.

They do have this site [http://www.bom.gov.au/australia/meteye/](http://www.bom.gov.au/australia/meteye/), where it does it automatically (when you click on the map it initially uses the coordinates in the title of the popup until it finds the closest station), but I can't find an API for the functionality.

**Comment by HelmetOwl** [comment]
> that’s a basic feature I expect from a weather source; all of our sources support something like that. Or at least, if they don’t, they at least provide a reverse geocoding endpoint (AccuWeather works like that).

Page 10 of [this document](http://www.bom.gov.au/catalogue/adfdUserGuide.pdf) has clarified it. It looks like it's part of their registered service; I think that means one has to pay.

> we can't keep a hardcoded list of stations, and loop through all of them to find the nearest one, and I am not aware of any weather app doing something like that. Or at least, it’s probably not a good idea. If you somehow manage to make it work by computing coordinates and nearest station, that would probably mean a lot of code added for everyone not interested by this source (+ any hardcoded station list you bundle) + a lot of maintenance from the project, so I'm not sure I would accept such a pull request.

In terms of what I was thinking for the implementation, I would've suggested a generic implementation that takes a list of stations/IDs and coordinates and the device coordinates and finds the closest point, which could've been used for other future sources too. One could use GitHub Actions to update the list of stations for each release.

> The alternative would be to implement "lightweight" sources

This is an interesting idea because it allows people to optimise their home sources, which they might care more about, but also have an everyday location source for when they're out and about.

> that would mean a lot of work for a too narrow case and for only one specific country.

I understand your position but the work could be reused for other (national) sources as needed so it's not a total waste, so it would have merit.

> this is not an API, it’s just an endpoint that returns HTML, we can’t parse something like that

My intention wasn't for you to parse that webpage; I just hoped you'd maybe be able to deduce the method they were using or see a link to an API that I'd missed.

**Comment by papjul** [comment]
> > we can't keep a hardcoded list of stations, and loop through all of them to find the nearest one, and I am not aware of any weather app doing something like that. Or at least, it’s probably not a good idea. If you somehow manage to make it work by computing coordinates and nearest station, that would probably mean a lot of code added for everyone not interested by this source (+ any hardcoded station list you bundle) + a lot of maintenance from the project, so I'm not sure I would accept such a pull request.
> 
> In terms of what I was thinking for the implementation, I would've suggested a generic implementation that takes a list of stations/IDs and coordinates and the device coordinates and finds the closest point, which could've been used for other future sources too.
> 
> I understand your position but the work could be reused for other (national) sources as needed so it's not a total waste, so it would have merit.

This isn't contradicting what I'm saying, we would still need to bundle a list of Australian stations for everyone using the app, and maintain an additional system only used by one or a few sources. This app is mostly only maintained by me and I don't want it to grow as a "monster" of things that even paid apps don't do, as I'm already having a hard time keeping up with all issues with current features, many that I don't even use myself (so I'm doing free support for things I don't even care about!).


> Page 10 of [this document](http://www.bom.gov.au/catalogue/adfdUserGuide.pdf) has clarified it. It looks like it's part of their registered service; I think that means one has to pay.

I'm sorry they only provide this as a paid service, in that case, the "middle server" idea is probably the best here.
Someone made something like that for DWD: https://brightsky.dev/
It would also be easily usable by other weather apps.


> > this is not an API, it’s just an endpoint that returns HTML, we can’t parse something like that
> 
> My intention wasn't for you to parse that webpage; I just hoped you'd maybe be able to deduce the method they were using or see a link to an API that I'd missed.

The method is the one I'm asking for: they call an endpoint with coordinates as parameters, but that endpoint returns the weather forecast as HTML, not JSON or XML.
