### ISSUE TITLE
"Current location" displayed instead of actual location name with Open-Meteo and Open-Weather

### ISSUE THREAD

**Issue by paperluca27** [breezy-weather/breezy-weather#417]
### Steps to reproduce

When selecting Open-Meteo or Open-Weather as Main Source and current location as location, the main page shows "Current location" instead of the actual location name. Changing the main source to Accuweather display the actual name of the city. The name of the city can be found with Open-Meteo or Open-Weather when searching in the locations tab, but selecting it there would prevent from showing updated locations when traveling.
![WhatsApp Image 2023-08-23 at 15 04 04](https://github.com/breezy-weather/breezy-weather/assets/142995501/87f65f96-1dbb-4a09-b479-c33c440f705b)
![WhatsApp Image 2023-08-23 at 15 14 21](https://github.com/breezy-weather/breezy-weather/assets/142995501/7dcad17d-8900-45a4-9452-0b4edc42e204)
![WhatsApp Image 2023-08-23 at 15 16 14](https://github.com/breezy-weather/breezy-weather/assets/142995501/36da42a1-8eac-455e-a721-91da0c05fad5)
![WhatsApp Image 2023-08-23 at 15 16 39](https://github.com/breezy-weather/breezy-weather/assets/142995501/ccbf9315-dc6c-480b-b8c7-d600112be9f3)

### Expected behavior

The actual name of the location in which you currently are situated should be displayed E.G. "Rome" and change according to eventual changes of location.

### Actual behavior

"Current location" get displayed everywhere you are.

### Weather source used

Open-Meteo

### Breezy Weather version

4.6.6-beta

### Android version

GrapheneOS Android 13

### Device

Pixel 7a

### Other details

I tried multiple fresh installs, changing default location search sources, the application has access to GPS location and this problem is present only with Open Meteo and Open Weather while Accuweather behaves as expected, France Meteo gives the actual location, but wrong weather and MET Norway gives "Current location" and wrong weather.
I'm located in Italy.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I read the [Frequently Asked Questions](https://github.com/breezy-weather/breezy-weather/blob/main/HELP.md) document and followed instructions if relevant.
- [X] I have updated the app to **[version 4.6.3 or later](https://github.com/breezy-weather/breezy-weather/releases/latest)**.
- [X] I wrote my request in English, and any screenshot I attached are also in English (language can be changed from Settings > Appearance)

**Comment by papjul** [comment]
These sources don't support reverse geocoding (at the moment).

See here which sources support it:
https://github.com/breezy-weather/breezy-weather/blob/main/docs/SOURCES.md
