### ISSUE TITLE
[Gadgetbridge] Forecasts are sent for incorrect days

### ISSUE THREAD

**Issue by joserebelo** [breezy-weather/breezy-weather#418]
### Steps to reproduce

Right now is 2023-08-23 15:07 UTC.

The forecasts sent to Gadgetbridge are expected to be from the next day onward (so in this case 2023-08-24, 2023-08-25, ...).

However, the forecasts are being sent starting from the previous day (2023-08-22). This is not expected, and results in wrong days sent to the gadgets.

### Expected behavior

The forecasts array should contain the forecasts from the next day onward (so 2023-08-24, 2023-08-25, ...).

### Actual behavior

We can see that the `location.weather?.dailyForecast` contains the forecasts from even the previous day:

```
result = {ArrayList@33305}  size = 16
 0 = {Daily@33311} Daily(date=Tue Aug 22 00:00:00 GMT+01:00 2023, ...
 1 = {Daily@33312} Daily(date=Wed Aug 23 00:00:00 GMT+01:00 2023, ...
 2 = {Daily@33313} Daily(date=Thu Aug 24 00:00:00 GMT+01:00 2023, ...
 3 = {Daily@33314} Daily(date=Fri Aug 25 00:00:00 GMT+01:00 2023, ...
 4 = {Daily@33315} Daily(date=Sat Aug 26 00:00:00 GMT+01:00 2023, ...
 5 = {Daily@33316} Daily(date=Sun Aug 27 00:00:00 GMT+01:00 2023, ...
 6 = {Daily@33317} Daily(date=Mon Aug 28 00:00:00 GMT+01:00 2023, ...
 7 = {Daily@33318} Daily(date=Tue Aug 29 00:00:00 GMT+01:00 2023, ...
 8 = {Daily@33319} Daily(date=Wed Aug 30 00:00:00 GMT+01:00 2023, ...
...
```

### Weather source used

Open-Meteo

### Breezy Weather version

56a58fdc

### Android version

Android 13

### Device

Not relevant

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I read the [Frequently Asked Questions](https://github.com/breezy-weather/breezy-weather/blob/main/HELP.md) document and followed instructions if relevant.
- [X] I have updated the app to **[version 4.6.3 or later](https://github.com/breezy-weather/breezy-weather/releases/latest)**.
- [X] I wrote my request in English, and any screenshot I attached are also in English (language can be changed from Settings > Appearance)

**Comment by joserebelo** [comment]
Sucks that this isn't very well documented, I [added a small note](https://codeberg.org/Freeyourgadget/Gadgetbridge/commit/20d0d61ed8b792a60e0887d52cee2fb9303481d4).

**Comment by papjul** [comment]
Not sending yesterday makes sense, but it's curious to not include forecast for today, wouldn't users be interested by how the weather will be today/tonight?

**Comment by joserebelo** [comment]
That is already included in the root of the object, which contains the today min/max temps, and current condition code.
