### ISSUE TITLE
Dutch translations from weblate aren't being merged.

### ISSUE THREAD

**Issue by BabyBenefactor** [breezy-weather/breezy-weather#423]
### Steps to reproduce

not applicable

### Expected behavior

not applicable

### Actual behavior

not applicable

### Weather source used

-

### Breezy Weather version

-

### Android version

-

### Device

-

### Other details

Hi there.

A few days ago I spent 2 hours translating all the strings on Weblate to Dutch. This is one of the first times of me using Weblate. Is it normal that this isn't being merged or is there anything wrong with the translation? Please let me know. Thanks!

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I read the [Frequently Asked Questions](https://github.com/breezy-weather/breezy-weather/blob/main/HELP.md) document and followed instructions if relevant.
- [X] I have updated the app to **[version 4.6.4 or later](https://github.com/breezy-weather/breezy-weather/releases/latest)**.
- [X] I wrote my request in English, and any screenshot I attached are also in English (language can be changed from Settings > Appearance)

**Comment by papjul** [comment]
2 days and this is a bug? I'm not a robot, please allow a few days!
There are 526 pending changes, it’s not a trivial task to review them.
There are also other pull requests pending reviews, and Weblate still hasn't committed/push its own anyway.

**Comment by BabyBenefactor** [comment]
I am sorry and I did not intent to upset you.
It was the first time of me using weblate, and I did not know that it could take a few days for translations to get merged. Im sorry for that.
Thanks for merging anyway and please keep up this amazing project!
