### ISSUE TITLE
Date formats are broken in Russian

### ISSUE THREAD

**Issue by gaussandhisgun** [breezy-weather/breezy-weather#424]
### Steps to reproduce

1. Set the app language to Russian
2. Open the main page or create a widget

### Expected behavior

All the dates in the app should display correctly

### Actual behavior

Most dates have their month replaced with "MMM" 

### Weather source used

any

### Breezy Weather version

4.6.4-beta (f-droid)

### Android version

Android 13 (ProjectBlaze 2.5 EOL)

### Device

miatoll

### Other details

 
![Screenshot_20230824-233229_Breezy Weather~2](https://github.com/breezy-weather/breezy-weather/assets/63512006/761de626-249a-46e5-aa29-d430864eb794)
![Screenshot_20230824-233559_Breezy Weather~2](https://github.com/breezy-weather/breezy-weather/assets/63512006/91e6d40d-d74a-4e4c-bc8a-9c9cf5992d3a)

From what I've seen, the issue only persists in Russian, no other slavic languages are affected. The screenshots are in Russian because its relevant to the issue.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I read the [Frequently Asked Questions](https://github.com/breezy-weather/breezy-weather/blob/main/HELP.md) document and followed instructions if relevant.
- [X] I have updated the app to **[version 4.6.4 or later](https://github.com/breezy-weather/breezy-weather/releases/latest)**.
- [X] I wrote my request in English, and any screenshot I attached are also in English (language can be changed from Settings > Appearance)

**Comment by papjul** [comment]
The translator broke date formats by changing special codes to the cyrillic counterpart. I didn't revert the M letter as I thought it was using the same character as in latin, but I guess it was a different character looking the same?

**Comment by papjul** [comment]
Fixed on Weblate, will be available on next merge

**Comment by papjul** [comment]
Fixed in 44aea0632df1f5cf5c5268333f75814d4402ceed
