### ISSUE TITLE
Weather sound effects

### ISSUE THREAD

**Issue by Sherlock-Holo** [breezy-weather/breezy-weather#436]
### Describe your idea

if it's a thunderstorm today, there will be a rainy sound effect in the MIUI weather(the MIUI team removed it at the latest version but a lot of people like this), It would be great if the breezy-weather could add some weather sound effect

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] My idea is not related to a question covered in the [Frequently Asked Questions](https://github.com/breezy-weather/breezy-weather/blob/main/HELP.md) document, or a feature described in the [Homepage](https://github.com/breezy-weather/breezy-weather/blob/main/docs/HOMEPAGE.md) document.
- [X] I have updated the app to **[version 4.6.4 or later](https://github.com/breezy-weather/breezy-weather/releases/latest)**.
- [X] I understand that this app is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY, so I may not get a positive reply to my request, if any at all.

**Comment by papjul** [comment]
This is the kind of thing that would lead to more annoyance than benefits (just a gimmick), and I’m pretty sure it was the reason it was removed from the app you're mentioning (unless MIUI team gave another reason?):
- What if someone is playing music when opening the app? Should it take the focus or overlap the music?
- What if someone is in public and just want to check the weather and it just starts playing sound in front of everyone?

Technically, it’s also not trivial. We also need free assets of quality.

I’m sure there are other apps specialized in listening to rain sounds or things like that, that handles that much better ;)
