### ISSUE TITLE
Cannot select new main source as secondary source when main source is changed and before it is saved

### ISSUE THREAD

**Issue by LuccoJ** [breezy-weather/breezy-weather#443]
### Steps to reproduce

1. Have a source using Open-Meteo (save the setting!)
2. Do Edit → Weather Sources
3. Change the Main source to AccuWeather
4. Tap Pollen (or Allergen)

### Expected behavior

Open-Meteo (at least) should be an option.

### Actual behavior

The only option under Pollen/Allergen remains "Main source".

### Weather source used

AccuWeather and Open-Meteo

### Breezy Weather version

4.6.5-beta

### Android version

Android 13

### Device

Oneplus 8T

### Other details

But now Cancel, Save, Edit again, and Open-Meteo becomes possible as a secondary source for Pollen/Allergen.

So no option is actually blocked, but people must know that they have to Save first, and then go back in, if they want to select secondary sources. This is not intuitive, and I think the secondary sources should be available immediately.

https://github.com/breezy-weather/breezy-weather/assets/1684791/21c24cd7-84e1-48ca-b8c9-27f3d8fbff3a

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I read the [Frequently Asked Questions](https://github.com/breezy-weather/breezy-weather/blob/main/HELP.md) document and followed instructions if relevant.
- [X] I have updated the app to **[version 4.6.5 or later](https://github.com/breezy-weather/breezy-weather/releases/latest)**.
- [X] I wrote my request in English, and any screenshot I attached are also in English (language can be changed from Settings > Appearance), unless my issue only happens with a specific language
- [X] I understand that this app is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY, so I may not get a positive reply to my request, if any at all.

**Comment by papjul** [comment]
> This is not intuitive, and I think the secondary sources should be available immediately.

I agree. It was not done before because it's overly complicated to fix, it would require to recalculate all available sources each time the main source is changed. I will fix this on a rainy day.
