### ISSUE TITLE
Can't use a country-restricted secondary source with current location if main source has no reverse geocoding

### ISSUE THREAD

**Issue by Dizzybog** [breezy-weather/breezy-weather#448]
### Steps to reproduce

When using any weather source on **current** **location.** Met Norway is not available as source under precipitation minute by minute. It is available when location is set manually.
![Screenshot_2023-09-04-16-15-31-75_8b90da7a90336dddbe1fd9fd7538077a](https://github.com/breezy-weather/breezy-weather/assets/129987880/1085c699-ee2e-4771-a6f7-70d51a0be2a0)

### Expected behavior

Met should be available as source.
![Screenshot_2023-09-04-16-16-42-01_8b90da7a90336dddbe1fd9fd7538077a](https://github.com/breezy-weather/breezy-weather/assets/129987880/04e0c22e-67d2-4257-8842-4e36429a4ef1)

### Actual behavior

Met Norway is not available as source under precipitation minute by minute.

### Weather source used

Open-meteo

### Breezy Weather version

4.6.5

### Android version

Android 13

### Device

OnePlus 11

### Other details

I live in Norway.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I read the [Frequently Asked Questions](https://github.com/breezy-weather/breezy-weather/blob/main/HELP.md) document and followed instructions if relevant.
- [X] I have updated the app to **[version 4.6.5 or later](https://github.com/breezy-weather/breezy-weather/releases/latest)**.
- [X] I wrote my request in English, and any screenshot I attached are also in English (language can be changed from Settings > Appearance), unless my issue only happens with a specific language
- [X] I understand that this app is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY, so I may not get a positive reply to my request, if any at all.

**Comment by papjul** [comment]
This is because Open-Meteo doesn't have reverse geocoding, and we are not able to detect you're in a country valid for precipitation forecast. Unfortunately, a location that has coordinates that can change bring troubles for many features :/

As a workaround, you can try this:
1) Switch main source to Météo-France
2) Save
3) Switch precipitation source to MET No
4) Switch main source to Open-Meteo
5) Save

**Comment by papjul** [comment]
Was fixed a few versions ago, thanks to the offline reverse geocoding by country we added
