### ISSUE TITLE
Settings freeze after theme change

### ISSUE THREAD

**Issue by Cod3dDOT** [breezy-weather/breezy-weather#452]
### Steps to reproduce

Open Settings -> Appearance -> Dark mode
Change Dark mode to an opposite value
(Dark -> Light, Light -> Dark, or any other combination that forces the change in theme)

### Expected behavior

The app changes theme and continues to work

### Actual behavior

The Settings activity relaunches and freezes. Using "swipe back" returns to main screen, with the theme changed. Reopening the settings works fine.

### Weather source used

Not applicable

### Breezy Weather version

4.6.6-beta

### Android version

Android 13

### Device

Pixel 4a

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I read the [Frequently Asked Questions](https://github.com/breezy-weather/breezy-weather/blob/main/HELP.md) document and followed instructions if relevant.
- [X] I have updated the app to **[version 4.6.5 or later](https://github.com/breezy-weather/breezy-weather/releases/latest)**.
- [X] I wrote my request in English, and any screenshot I attached are also in English (language can be changed from Settings > Appearance), unless my issue only happens with a specific language
- [X] I understand that this app is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY, so I may not get a positive reply to my request, if any at all.

**Comment by papjul** [comment]
I also notice it when changing language. Would be good to pinpoint the version that introduced the regression. Seems recent (a dependency update?).

**Comment by papjul** [comment]
Your investigations seem to indicate that Compose 1.5.x is at fault. Reverting is not an option as it is linked with Kotlin version and other dependencies will pull 1.5.x (as a minimum required version) even if we set an older version.

**Comment by papjul** [comment]
Still reproducible with new updates.
Latest check: https://github.com/breezy-weather/breezy-weather/commit/b9c3d72afcb0f09be0cb6e54cbc5514327cc3698

**Comment by papjul** [comment]
I think it's fixed now?
