### ISSUE TITLE
Unreadable text in dark theme in about page

### ISSUE THREAD

**Issue by HotarunIchijou** [breezy-weather/breezy-weather#454]
### Steps to reproduce

![](https://github.com/breezy-weather/breezy-weather/assets/113282550/c0fc825a-3712-4685-ac7c-b3724a33a733)

### Expected behavior

The color of the text should be lighter 

### Actual behavior

It actually pretty dark and unreadable

### Weather source used

Doesn't matter

### Breezy Weather version

4.6.5-beta

### Android version

Doesn't matter 

### Device

Doesn't matter

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I read the [Frequently Asked Questions](https://github.com/breezy-weather/breezy-weather/blob/main/HELP.md) document and followed instructions if relevant.
- [X] I have updated the app to **[version 4.6.5 or later](https://github.com/breezy-weather/breezy-weather/releases/latest)**.
- [X] I wrote my request in English, and any screenshot I attached are also in English (language can be changed from Settings > Appearance), unless my issue only happens with a specific language
- [X] I understand that this app is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY, so I may not get a positive reply to my request, if any at all.

**Comment by papjul** [comment]
Opening this to contributions. Be careful about impacts elsewhere (this can also improve readability elsewhere but also worsen it)

**Comment by min7-i** [comment]
@papjul I think this issue can be closed as it was solved with #1023.
