### ISSUE TITLE
Migrate to Jetpack Compose

### ISSUE THREAD

**Issue by HotarunIchijou** [breezy-weather/breezy-weather#455]
### Describe your idea

Migrate from XML to Compose, just why not
https://developer.android.com/codelabs/jetpack-compose-migration#0

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] My idea is not related to a question covered in the [Frequently Asked Questions](https://github.com/breezy-weather/breezy-weather/blob/main/HELP.md) document, or a feature described in the [Homepage](https://github.com/breezy-weather/breezy-weather/blob/main/docs/HOMEPAGE.md) document.
- [X] I have updated the app to **[version 4.6.5 or later](https://github.com/breezy-weather/breezy-weather/releases/latest)**.
- [X] I understand that this app is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY, so I may not get a positive reply to my request, if any at all.

**Comment by papjul** [comment]
Can you give more details?

We already use Jetpack Compose, and when possible, we rewrite existing XML.
However, Jetpack Compose doesn't cover all cases, or can be limited on some.
For example, there is no stable support of Compose on widgets.
So, please be more specific in your request.
Which part of the code do you need to be written in Compose and why?

**Comment by HotarunIchijou** [comment]
I think that all or most of things in the [Layout](https://github.com/breezy-weather/breezy-weather/tree/main/app/src/main/res/layout) should be rewrited to compose as it's the Google's most modern recommend method

**Comment by papjul** [comment]
Yes, but while this method is recommended, as I said, it's not yet ready for everything, so please be more specific.
Half of the layout folder are about widgets, and they won't be rewritten. First, because Glance is not stable yet, and secondly, because we will make new widgets with a global vision, not rewrite existing ones. But this will be done as part of a global widget strategy not as a "rewrite in Compose" because XML is not deprecated and still works fine (and sometimes better!).
Jetpack Compose is also known to be way more slow, especially in debug builds, so it's really not convenient for a developer.

**Comment by HotarunIchijou** [comment]
Literally every card is written on XML. I'm not saying it's bad, there's just a newer way, but if you don't want to rewrite you can leave it as is

**Comment by papjul** [comment]
> Literally every card is written on XML.

It's not. I rewrote header details, alerts, allergens and details cards in Compose.

> I'm not saying it's bad, there's just a newer way, but if you don't want to rewrite you can leave it as is

Come on, Compose is already used everywhere in this app, you're not teaching me about a newer way.

You still don't answer my question, it’s a deaf talk, closing as it leads nowhere. 

What needs to be rewritten will be done as Compose when it will rewritten, such as "daily view" redesign, or "widgets" redesign, but a whole app rewrite is not planned. But if you want to do it yourself as you seemed very interested in it, you're free to submit a pull request and I will review it.
