### ISSUE TITLE
 bring original (compact) header style back

### ISSUE THREAD

**Issue by rhjdvsgsgks** [breezy-weather/breezy-weather#460]
### Describe your idea

hi

i think the new line by line header not pretty as the old design. it waste too much space and cover too much background animation. especially when select much of header object.

i suggest to add a option of switching to old header style

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] My idea is not related to a question covered in the [Frequently Asked Questions](https://github.com/breezy-weather/breezy-weather/blob/main/HELP.md) document, or a feature described in the [Homepage](https://github.com/breezy-weather/breezy-weather/blob/main/docs/HOMEPAGE.md) document.
- [X] I have updated the app to **[version 4.6.5 or later](https://github.com/breezy-weather/breezy-weather/releases/latest)**.
- [X] I understand that this app is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY, so I may not get a positive reply to my request, if any at all.

**Comment by papjul** [comment]
You can do that from Settings > Main screen > Details in header. Remove everything and save.
