### ISSUE TITLE
only one alert showed on main screen

### ISSUE THREAD

**Issue by rhjdvsgsgks** [breezy-weather/breezy-weather#461]
### Steps to reproduce

find some city that have two alert on same day

### Expected behavior

two alerts been shown on main screen. just like geometry weather

### Actual behavior

only first alert shown. you need to click in to alert screen to see more

### Weather source used

accu

### Breezy Weather version

4.6.5-beta

### Android version

android 11

### Device

any

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I read the [Frequently Asked Questions](https://github.com/breezy-weather/breezy-weather/blob/main/HELP.md) document and followed instructions if relevant.
- [X] I have updated the app to **[version 4.6.5 or later](https://github.com/breezy-weather/breezy-weather/releases/latest)**.
- [X] I wrote my request in English, and any screenshot I attached are also in English (language can be changed from Settings > Appearance), unless my issue only happens with a specific language
- [X] I understand that this app is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY, so I may not get a positive reply to my request, if any at all.

**Comment by papjul** [comment]
Only current alerts are shown on main screen in Breezy Weather to avoid wasting space with alerts that aren't currently valid.
