### ISSUE TITLE
met office / datapoint source

### ISSUE THREAD

**Issue by rhjdvsgsgks** [breezy-weather/breezy-weather#462]
### Link to publicly available documentation of the API

https://www.metoffice.gov.uk/binaries/content/assets/metofficegovuk/pdf/data/datapoint_api_reference.pdf

### Available and not available data

windGusts
windDegree
relativeHumidity
pressure
windSpeed
realFeelTemperature
temperature
visibility
weatherCode
uvIndex

maybe more. i didn't read the document carefully

### Are you going to develop yourself the new source for the app?

no. because my computer is broken right now. and need few month to fix. but i can write it if you can wait few month

### Give a bit more details or context about this source

seems like they operated by government. maybe have better accuracy on some specific country?

they also have map overlay support

### Acknowledgements

- [X] This source has a free-tier available (no mandatory credit card info), and if it a main weather source, it includes free hourly forecast
- [X] If this is a weather source request, I checked that endpoints are by coordinates, or that there is a reverse geocoding endpoint.
- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written the name of the source as the title of this issue.
- [X] I have updated the app to **[version 4.6.5 or later](https://github.com/breezy-weather/breezy-weather/releases/latest)** and this source is not part of it.
- [X] I understand that this app is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY, so I may not get a positive reply to my request, if any at all.

**Comment by papjul** [comment]
> https://www.metoffice.gov.uk/binaries/content/assets/metofficegovuk/pdf/data/datapoint_api_reference.pdf
>     * [x]  If this is a weather source request, I checked that endpoints are by coordinates, or that there is a reverse geocoding endpoint.

I don't see that one in the document you sent.
