### ISSUE TITLE
Translate: Hourly forcast part

### ISSUE THREAD

**Issue by tomac4t** [breezy-weather/breezy-weather#463]
### Steps to reproduce

"9下午" (9 PM) is not normal Chinese expression (I mark it in the below screenshot). I suggest use "下午9时" or  "21时" (24-hour system) in it, But I don't find the string in Weblate.

![weather](https://github.com/breezy-weather/breezy-weather/assets/47532693/f760319d-0093-4617-85b4-14094080f1b9)
(Left: Geometric Weather; Right: Breezy Weather)

### Expected behavior

Use normal Chinese expression like "下午9时" or "21时"...

### Actual behavior

Not normal expression like "9下午"...

### Weather source used

AccuWeather

### Breezy Weather version

4.6.5-beta

### Android version

Android 11

### Device

N/A

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I read the [Frequently Asked Questions](https://github.com/breezy-weather/breezy-weather/blob/main/HELP.md) document and followed instructions if relevant.
- [X] I have updated the app to **[version 4.6.5 or later](https://github.com/breezy-weather/breezy-weather/releases/latest)**.
- [X] I wrote my request in English, and any screenshot I attached are also in English (language can be changed from Settings > Appearance), unless my issue only happens with a specific language
- [X] I understand that this app is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY, so I may not get a positive reply to my request, if any at all.

**Comment by papjul** [comment]
It's an Android bug that is usually fixed by Chinese manufacturers. If it is not, you can force 24-hour system in Android settings.
