### ISSUE TITLE
Precipitation Forecast widget

### ISSUE THREAD

**Issue by nrestell** [breezy-weather/breezy-weather#464]
### Describe your idea

A widget that is simply the Precipitation Forecast for the next 60 mins. It would show nothing on there graph of no precipitation forecast but one precipitation was forecast out would show on the graph (add in the app). It's useful to look at your phone and see at a glance of rain is forecast soon. Yes, the forecast would be out of date until it refreshed but could still be useful.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] My idea is not related to a question covered in the [Frequently Asked Questions](https://github.com/breezy-weather/breezy-weather/blob/main/HELP.md) document, or a feature described in the [Homepage](https://github.com/breezy-weather/breezy-weather/blob/main/docs/HOMEPAGE.md) document.
- [X] I have updated the app to **[version 4.6.5 or later](https://github.com/breezy-weather/breezy-weather/releases/latest)**.
- [X] I understand that this app is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY, so I may not get a positive reply to my request, if any at all.

**Comment by papjul** [comment]
A widget that show nothing under most conditions? Meh

What about #336?
