### ISSUE TITLE
安卓的小组件

### ISSUE THREAD

**Issue by yoke686** [breezy-weather/breezy-weather#466]
### Describe your idea

安卓手机为什么不能在桌面上添加一个小组件呢？我觉得这个小组件功能非常好用

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] My idea is not related to a question covered in the [Frequently Asked Questions](https://github.com/breezy-weather/breezy-weather/blob/main/HELP.md) document, or a feature described in the [Homepage](https://github.com/breezy-weather/breezy-weather/blob/main/docs/HOMEPAGE.md) document.
- [X] I have updated the app to **[version 4.6.5 or later](https://github.com/breezy-weather/breezy-weather/releases/latest)**.
- [X] I understand that this app is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY, so I may not get a positive reply to my request, if any at all.

**Comment by papjul** [comment]
Je ne parle pas chinois, désolé

**Comment by yoke686** [comment]
> Je ne parle pas chinois, désolé

Sorry, it's my problem. I just found this function.
