### ISSUE TITLE
[Technical] Migrate code to Kotlin

### ISSUE THREAD

**Issue by papjul** [breezy-weather/breezy-weather#47]
### Describe your suggested feature

In progress technical improvement

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to **[latest version](https://github.com/breezy-weather/breezy-weather/releases/latest)**.

**Comment by TheGamer1002** [comment]
ooh this'll take a while

**Comment by papjul** [comment]
Completed in d4723e91fe0f6cb9cc54954e7537fca07fa5781f, still more work to do for a modern code base, but at least, it will be easier to work on the project from now on
