### ISSUE TITLE
Bug: Can't add Hourly Trend widget

### ISSUE THREAD

**Issue by cheintz** [breezy-weather/breezy-weather#472]
### Steps to reproduce

1. Long press on background of home screen
2. Widgets
3. Breezy Weather
4. Drag "hourly trend" to home screen
5. Note no popup window and no widget placed

### Expected behavior

Popup to configure widget, followed by widget on home screen (other widgets work fine)

### Actual behavior

No popup to configure widget, no widget on home screen

### Weather source used

AccuWeather

### Breezy Weather version

4.6.6-beta

### Android version

Android 13 GrapheneOS

### Device

Pixel 7 Pro

### Other details

Other widgets, such as weekly, work fine. 

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I read the [Frequently Asked Questions](https://github.com/breezy-weather/breezy-weather/blob/main/HELP.md) document and followed instructions if relevant.
- [X] I have updated the app to **[version 4.6.6 or later](https://github.com/breezy-weather/breezy-weather/releases/latest)**.
- [X] I wrote my request in English, and any screenshot I attached are also in English (language can be changed from Settings > Appearance), unless my issue only happens with a specific language
- [X] I understand that this app is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY, so I may not get a positive reply to my request, if any at all.

**Comment by cheintz** [comment]
As an aside, for some reason, the Breezy widgets (and Geometric Weather widgets) have much more (and excessive) whitespace between them in GOS, compared to other apps, like Simple Calendar.

**Comment by papjul** [comment]
Please share your crash log:
1. Breezy Weather Settings
2. Debug > Share crash log
3. Go to Android/data/org.breezyweather/cache/breezyweather_crash_logs.txt
4. Check there is nothing confidential in it (such as your coordinates/location) and send it here (or DM me on Matrix).

**Comment by fearmusa** [comment]
[breezyweather_crash_logs.txt](https://github.com/breezy-weather/breezy-weather/files/12655609/breezyweather_crash_logs.txt)

Yes, I had the same problem. After a few tries, the witget was created. After the first try, the application gave an error and closed.
