### ISSUE TITLE
Dark Mode doesn't darken the tiles on the app home screen

### ISSUE THREAD

**Issue by Kaffeebohnson** [breezy-weather/breezy-weather#480]
### Steps to reproduce

Setting the app to dark mode doesn't darken the tiles on the app home screen: they remain bright white.
![Screenshot_20230921-131201_Breezy Weather](https://github.com/breezy-weather/breezy-weather/assets/55648945/f8ef83d2-d63d-420f-a9e7-1bcb182efbf4)

### Expected behavior

The tiles should get tinted dark grey or black

### Actual behavior

The tiles stay white

### Weather source used

Accuweather

### Breezy Weather version

4.6.7-beta

### Android version

Android 12

### Device

Galaxy Note 10

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I read the [Frequently Asked Questions](https://github.com/breezy-weather/breezy-weather/blob/main/HELP.md) document and followed instructions if relevant.
- [X] I have updated the app to **[version 4.6.7 or later](https://github.com/breezy-weather/breezy-weather/releases/latest)**.
- [X] I wrote my request in English, and any screenshot I attached are also in English (language can be changed from Settings > Appearance), unless my issue only happens with a specific language
- [X] I understand that this app is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY, so I may not get a positive reply to my request, if any at all.

**Comment by papjul** [comment]
Dark mode can be customized in Settings > Appearance:
- Dark mode
- Day / Night mode for locations
