### ISSUE TITLE
Feels like chart

### ISSUE THREAD

**Issue by fearmusa** [breezy-weather/breezy-weather#481]
### Describe your idea

Along with the temperature graph, temperatures such as feels like can also be shown in graphs.It can be viewed both daily and hourly. It can also be a separate graph or it can only be displayed in the same graph with the switch. Like on off 
![Screenshot_20230922-161123_Breezy Weather](https://github.com/breezy-weather/breezy-weather/assets/127376654/f6ec74bd-f5a3-4194-b00e-8d45e6ffe223)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] My idea is not related to a question covered in the [Frequently Asked Questions](https://github.com/breezy-weather/breezy-weather/blob/main/HELP.md) document, or a feature described in the [Homepage](https://github.com/breezy-weather/breezy-weather/blob/main/docs/HOMEPAGE.md) document.
- [X] I have updated the app to **[version 4.6.7 or later](https://github.com/breezy-weather/breezy-weather/releases/latest)**.
- [X] I understand that this app is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY, so I may not get a positive reply to my request, if any at all.

**Comment by papjul** [comment]
Implemented in 2155d085abf72f2e86a031ad1099f96bf29d7704
