### ISSUE TITLE
Notification Widget Temperature Icon Incorrect when Updates Fail

### ISSUE THREAD

**Issue by supsm** [breezy-weather/breezy-weather#485]
### Steps to reproduce

This is a bit tedious to reproduce but the issue should be pretty easy to understand.
1. Enable Notification Widget (the one that sends you a silent notification containing temperature, forecast, etc)
2. Close app
3. Make sure a notification is sent (notif A)
4. Disable all internet, this should trigger the automatic refresh to fail (in practice this would be likely spotty internet)
5. Wait for the next refresh, should get a notification saying "x Update(s) Failed"
6. Re-enable internet
7. Wait for next refresh (notif B)

### Expected behavior

The temperature in the notification icon should match notif B, the most recent update

### Actual behavior

It actually still retains the temperature from notif A, and all subsequent updates will use this as long as the "x Update(s) Failed" notification is not cleared

### Weather source used

Accuweather

### Breezy Weather version

4.6.7-beta

### Android version

Android 13

### Device

Google Pixel 7

### Other details

Basically, when updates fail, the temperature is no longer updated. I think this might be because the notification never fully disappears due to the presence of the "x Update(s) Failed" notification, so the icon is never updated (this is just speculation, I know almost nothing about notifications in android and the notification widget in this app).
A quick and easy fix would just be to remove the "x Update(s) Failed" notification when a successful update occurs (if possible, of course). Most users probably only care about the latest update anyway, so hiding past failed updates shouldn't be an issue.
 
For these screenshots, the current temperature is 61 degrees and the old temperature is 63 degrees.
Here is an image of the status bar display:
![Screenshot_20230920-082446_1](https://github.com/breezy-weather/breezy-weather/assets/60897356/c92f298a-39be-4fd4-9aaf-39782905490c)
And an image of the notification itself (some areas like location and forecast are blocked for my privacy, but they are irrelevant):
<img width="493" alt="Screenshot_20230920-082405" src="https://github.com/breezy-weather/breezy-weather/assets/60897356/1ec077cc-e8f6-4fd7-b122-000d952b965e">

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I read the [Frequently Asked Questions](https://github.com/breezy-weather/breezy-weather/blob/main/HELP.md) document and followed instructions if relevant.
- [X] I have updated the app to **[version 4.6.7 or later](https://github.com/breezy-weather/breezy-weather/releases/latest)**.
- [X] I wrote my request in English, and any screenshot I attached are also in English (language can be changed from Settings > Appearance), unless my issue only happens with a specific language
- [X] I understand that this app is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY, so I may not get a positive reply to my request, if any at all.

**Comment by papjul** [comment]
Android only start our background update when there is network available, so your step-by-step is not valid.

> For these screenshots, the current temperature is 61 degrees and the old temperature is 61 degrees.

Unclear to me. How can you have a different current temperature if it failed to update? And why is it 61° in both cases?

> A quick and easy fix would just be to remove the "x Update(s) Failed" notification when a successful update occurs (if possible, of course). Most users probably only care about the latest update anyway, so hiding past failed updates shouldn't be an issue.

I disagree with that. Failed updates should never happen. If it happened, the app should never clear them and keep showing them to you until you remediate the issue (or report it here if it is an issue on our side).

**Comment by supsm** [comment]
> > For these screenshots, the current temperature is 61 degrees and the old temperature is 61 degrees.

> Unclear to me. How can you have a different current temperature if it failed to update? And why is it 61° in both cases?

Sorry, that is a typo. The old temperature is 63 degrees and the current temperature is 61 degrees

> Failed updates should never happen. If it happened, the app should never clear them and keep showing them to you until you remediate the issue (or report it here if it is an issue on our side).

I hadn't considered that. My own use case is with a vpn which can sometimes have issues reconnecting when in and moving out of range of wifi networks, so I forgot that there were more important error messages than failure to connect. Perhaps there could be some sort of option to suppress connection errors, or change the icon to display that an error has occurred, since the bigger annoyance here is that I don't know the displayed icon is wrong until I view all notifications.

**Comment by papjul** [comment]
> > Failed updates should never happen. If it happened, the app should never clear them and keep showing them to you until you remediate the issue (or report it here if it is an issue on our side).
> 
> I hadn't considered that. My own use case is with a vpn which can sometimes have issues reconnecting when in and moving out of range of wifi networks, so I forgot that there were more important error messages than failure to connect. Perhaps there could be some sort of option to suppress connection errors, or change the icon to display that an error has occurred, since the bigger annoyance here is that I don't know the displayed icon is wrong until I view all notifications.

Network errors should never be notified, since Android doesn't run the job in that case. For the remaining rare network issues, they happen in your case, but they can also be due to DNS issues, hosts issues, so they should definitely be reported so user can take action.

> > > For these screenshots, the current temperature is 61 degrees and the old temperature is 61 degrees.
> 
> > Unclear to me. How can you have a different current temperature if it failed to update? And why is it 61° in both cases?
> 
> Sorry, that is a typo. The old temperature is 63 degrees and the current temperature is 61 degrees

I also meed an answer to my first question to start investigating ;)

**Comment by supsm** [comment]
> Network errors should never be notified, since Android doesn't run the job in that case.

It does for someone like me, since the network appears to be connected, but the VPN isn't routing packets to the server properly. Browsers and other apps will simply hang instead of reporting that the internet is off.

> How can you have a different current temperature if it failed to update?

Sorry, missed that one. It failed to update at some point, but after that, it successfully updated again. So the current temperature is actually correct and current (from the image you can see the notification is from just 7 minutes ago), but due to the failed update (6 hours ago in the image), the change isn't reflected in the icon. In order the events are:
- ~7 h ago: Successful update (63 degrees)
- 6h ago: Failed update
- more failed or successful updates not shown
- 7m ago: Successful update (61 degrees)
Hopefully this is clear, please let me know if you need any more info.

**Comment by papjul** [comment]
> due to the failed update (6 hours ago in the image), the change isn't reflected in the icon. In order the events are:
> 
> * ~7 h ago: Successful update (63 degrees)
> * 6h ago: Failed update
> * more failed or successful updates not shown
> * 7m ago: Successful update (61 degrees)
> 
> Hopefully this is clear, please let me know if you need any more info.

This is what I don't understand, what does it have to do with the failed update? We never show the temperature icon on the failed update notification, so I don't understand where this 63° icon is coming from. Could it be a caching issue on Android side? According to your screenshots, the notification-widget seems to correctly update, both icon and content, so where is that 63° from?

**Comment by supsm** [comment]
> This is what I don't understand, what does it have to do with the failed update? We never show the temperature icon on the failed update notification (we use a cloud icon), so I don't understand where this 63° icon is coming from.

I believe it is from the last successful update prior to the failed update. I'm not 100% sure since I didn't witness it, but it does match roughly with what I expect the temperature to be. This also applies to other examples that I did not screenshot where the temperature difference is more drastic. I will attempt more controlled experiments to verify this.

**Comment by papjul** [comment]
In either case, the notification-widget is replaced by a newer one, and we can indeed see from your screenshot that no other notification has this old icon but the group icon. This looks like a bug on Android side to me.

**Comment by supsm** [comment]
Actually my guess seems to be incorrect. It looks like the icon always displays 63 degrees regardless of the previous temperature. I'll do some more digging to find where this value comes from.

**Comment by supsm** [comment]
Some further testing shows that isn't the case either. It doesn't seem to retain the temperature value of the last successful update, but it also doesn't appear to be a fixed value.
