### ISSUE TITLE
No GPS icon when using current location

### ISSUE THREAD

**Issue by RafiMuhluvch33s3** [breezy-weather/breezy-weather#488]
### Steps to reproduce

1. Install the breezy weather
2. Set up the current location
3. Tap back button
4. Main menu said failed to get location

### Expected behavior

The app should show that it's using gps. There's should be a gps icon in use. The location should be close to accurate.

### Actual behavior

The app can't access gps. There's no gps icon in use. The location is not loaded. It doesn't crash though.

### Weather source used

AccuWeather

### Breezy Weather version

4.6.8-beta

### Android version

Android 11

### Device

KDDI SOV40

### Other details

App version: 4.6.8-beta (standard, 40608
Android version: 11 (SDK 30)
Android build ID: 55.2.C.3.21
Device brand: KDDI
Device manufacturer: Sony
Device name: SOV40
Device model: SOV40
Device product name: SOV40_jp_kdi

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I read the [Frequently Asked Questions](https://github.com/breezy-weather/breezy-weather/blob/main/HELP.md) document and followed instructions if relevant.
- [X] I have updated the app to **[version 4.6.7 or later](https://github.com/breezy-weather/breezy-weather/releases/latest)**.
- [X] I wrote my request in English, and any screenshot I attached are also in English (language can be changed from Settings > Appearance), unless my issue only happens with a specific language
- [X] I understand that this app is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY, so I may not get a positive reply to my request, if any at all.

**Comment by papjul** [comment]
Please screenshot the Native API section of Settings > Location.

**Comment by RafiMuhluvch33s3** [comment]
![Screenshot_20230925-195921](https://github.com/breezy-weather/breezy-weather/assets/93971382/b664d317-1426-4d5e-8031-635c4a81ae56)

**Comment by papjul** [comment]
I edited my comment, I also need the debug logs, please ;)

**Comment by RafiMuhluvch33s3** [comment]
`App version: 4.6.8-beta (standard, 40608
Android version: 11 (SDK 30)
Android build ID: 55.2.C.3.21
Device brand: KDDI
Device manufacturer: Sony
Device name: SOV40
Device model: SOV40
Device product name: SOV40_jp_kdi`
Here's the debug log not much in there

**Comment by RafiMuhluvch33s3** [comment]
`Errors during refresh


! Android: Failed to find current location
  - Current location`
 I got something on the background process

**Comment by papjul** [comment]
1) Can you get location on other apps?
2) Did you get your location at least once since the last time you rebooted your phone?

App process to get current location is:
- Wait 10 sec to get last known location from Android (if you never got any location since you last rebooted your phone, 10 sec is not enough). If you have Google Apps, Android should also fallback to network location. Of course, if you're inside a building, don't expect the GPS to work.
- We fallback to last known location from the app, if Android doesn't have one
- Since you just added the location, you don't have any known location, so we just fail as a last resort

Note that I'm not using current location myself, I'm saying that from my understanding of the code and from other people who are able to use it.

**Comment by RafiMuhluvch33s3** [comment]
1. Yes I can get location from other apps such as Google maps and Trail sense
2. Yes I get my location correct since the las reboot.

I found workaround:
I open GMaps and breezy weather at once. Then somehow breezy weather caught the actual closest location. This works but a bit ugly.

I don't know about programming, but geometric weather can access gps independently without trigger from other apps.

**Comment by papjul** [comment]
It's curious because we didn't change the process much since Geometric Weather.

@Cod3dDOT Can you look into it?

**Comment by papjul** [comment]
1. Does it work with an IP provider such as IP.SB (Settings > Location)?
2. Do you have the issue with Open-Meteo as main source?

Just want to make sure nothing goes wrong with the reverse geocoding.

3. If you said yes to 1 and 2, can you try previous Breezy Weather and let me know when was the issue introduced (you said it was a regression from Geometric Weather)? You don't need to try all versions, just install major ones 4.X.0 and then when you find it, try previous minor versions, if relevant

**Comment by RafiMuhluvch33s3** [comment]
1. No, I can access weather data from openmeteo by manually picking location name and triggering using GMaps.
2. Yes, IP.SB works even though it's not as accurate.

**Comment by papjul** [comment]
My mistake, I need 3 also for your case

**Comment by RafiMuhluvch33s3** [comment]
I chose AccuWeather for all version

4.0.5 --> get my location right but no gps icon at the first time. When refreshing it shows the icon and get my location right.
4.1.3 --> hard to pull gps data, but couple if refreshes gets it right. Shows the gps icon.
4.2.1 --> same as 4.1.3
4.3.0 --> gets my location right, shows the gps icon. Nailed it first time.
4.4.1 --> same as 4.3.0 but a bit laggy
4.5.4 --> same as 4.3.0
4.6.0 --> same as 4.3.0
4.6.4 --> same as 4.3.0
4.6.5 --> get my location right but no gps icon. When refreshing no gps icon.
4.6.6 --> same as 4.6.5
4.6.7 --> same as 4.6.5

**Comment by papjul** [comment]
So, if I understand correctly, it works in all versions?

V4.6.8-beta didn't change anything except Open-Meteo source and translations.

Should it be closed?

**Comment by RafiMuhluvch33s3** [comment]
Well, the gps icon is quite useful to indicate that the app is working properly. The lack of indicator is somewhat worrying.

**Comment by papjul** [comment]
What do you mean "GPS icon"?
What makes you worrying exactly?

**Comment by papjul** [comment]
> Gps icon is the icon that shows if gps is used.

Screenshot please?

My understanding was that you weren't able to get your location right, not that some icon is missing. Note that for efficiency and battery-friendly reasons, we do not query GPS all the time, we do some caching when it's been only a few minutes since last refresh.

> The worrying part is that someone may flag this as malicious app that fooled the phone system.

Who is that someone? Can you give real-life cases?

**Comment by nutpantz** [comment]
I also don't get gps location, and it does not bring up the gps indictor in the to bar. It did trigger to ask it allowed to use gps.
On my Samsung tab a7 light tablet Android 13. Gps works fine for 5 other apps. Indicator quickly shows up.

Crash log is 2.4 mb i have nothing that can read that.

**Comment by papjul** [comment]
> Crash log is 2.4 mb i have nothing that can read that.

That seems unusually high, can you upload it? Thanks!

**Comment by nutpantz** [comment]
> `@`
[breezyweather_crash_logs.txt](https://github.com/breezy-weather/breezy-weather/files/12813136/breezyweather_crash_logs.txt)
``

Tried on my pixel 6 and it also fails, but it shows the gps indicator at shower the exact same time as it fails.

**Comment by papjul** [comment]
Thanks, these logs look device-specific and unrelated to your issue.
I'm out of ideas and can't reproduce on my device, so I will leave it open to contributions.

**Comment by nutpantz** [comment]
Are you using gps from Android api or fused location (network)from Google services api?

**Comment by papjul** [comment]
Releases from Breezy Weather currently don't use Fused, but we have a code available in case we want to deliver the app on Play Store some day.

Currently, it just asks Android to do the job, so it can use GPS or network depending on how your device is set up.
On my side, I don't have any network provider, it can only use GPS.

**Comment by nutpantz** [comment]
Also if i start a background gps app like gps logger from fdroid, and it gets my location and keeps constantly updating that. Then breasy weather will get my location also.

**Comment by papjul** [comment]
The code was slightly rewritten a few versions ago, can you check if you still experiencing issues with latest v5.2.7?
