### ISSUE TITLE
Dutch translation in air quality is not good

### ISSUE THREAD

**Issue by Benjie1984** [breezy-weather/breezy-weather#489]
### Steps to reproduce

In english Air quality - fair

In dutch luchtkwaliteit - eerlijk.  is wrong

Eerlijk means honest 

Fair can be translated too eerlijk 

But in air quality, it should be REDELIJK instead of EERLIJK.

I hope in an next update it can be changed

### Expected behavior

In english Air quality - fair

In dutch luchtkwaliteit- redelijk

### Actual behavior

In english Air quality - fair

In dutch luchtkwaliteit - eerlijk.  is wrong

Eerlijk means honest 

Fair can be translated too eerlijk 

But in air quality, it should be REDELIJK instead of EERLIJK.

I hope in an next update it can be changed

### Weather source used

Accuweather

### Breezy Weather version

V4.6.8

### Android version

Android 13

### Device

Samsung galaxy s22 plus 

### Other details

![Screenshot_20230926_011807_Breezy Weather](https://github.com/breezy-weather/breezy-weather/assets/146039391/525c9e8e-372d-49a0-9851-83b2adda2787)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I read the [Frequently Asked Questions](https://github.com/breezy-weather/breezy-weather/blob/main/HELP.md) document and followed instructions if relevant.
- [X] I have updated the app to **[version 4.6.7 or later](https://github.com/breezy-weather/breezy-weather/releases/latest)**.
- [X] I wrote my request in English, and any screenshot I attached are also in English (language can be changed from Settings > Appearance), unless my issue only happens with a specific language
- [X] I understand that this app is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY, so I may not get a positive reply to my request, if any at all.

**Comment by papjul** [comment]
Incorrect template used, this is a translation issue.

**Comment by Benjie1984** [comment]
Hi im sorry for all this im new,
i never did any work on a app or something
 i dont know what template, l Just thought i give you  a heads up
 ill install the app when its on playstore with the righ transnationale have a nice day



Met vriendelijke groet


Ben-Yamin Garmes.



-------- Oorspronkelijk bericht --------
Van: Julien Papasian ***@***.***>
Datum: 26-09-2023 08:49 (GMT+01:00)
Aan: breezy-weather/breezy-weather ***@***.***>
Cc: Benjie1984 ***@***.***>, Author ***@***.***>
Onderwerp: Re: [breezy-weather/breezy-weather] Dutch translation in air quality is not good (Issue #489)


Incorrect template used, this is a translation issue.

**Comment by papjul** [comment]
No worries, I don't speak tens of languages, they are translated by the community. If you can't translate yourself, just wait for someone else to do it ;)
