### ISSUE TITLE
Swedish Meteorological and Hydrological Institute (SMHI) API

### ISSUE THREAD

**Issue by Mr-Bajs** [breezy-weather/breezy-weather#490]
### Link to publicly available documentation of the API

https://opendata.smhi.se/apidocs/

### Available and not available data

Meteorological forecasts and observations in Sweden

### Are you going to develop yourself the new source for the app?

open to contributions

### Give a bit more details or context about this source

Data from the Swedish Meteorological and Hydrological Institute and it's released under Creative Commons BY 4.0 licence.

API example https://opendata.smhi.se/apidocs/metfcst/examples.html
API demo https://opendata.smhi.se/apidocs/metfcst/demo_point.html

### Acknowledgements

- [X] This source has a free-tier available (no mandatory credit card info), and if it a main weather source, it includes free hourly forecast
- [X] If this is a weather source request, I checked that endpoints are by coordinates, or that there is a reverse geocoding endpoint.
- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written the name of the source as the title of this issue.
- [X] I have updated the app to **[version 4.6.7 or later](https://github.com/breezy-weather/breezy-weather/releases/latest)** and this source is not part of it.
- [X] I understand that this app is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY, so I may not get a positive reply to my request, if any at all.

**Comment by papjul** [comment]
LGTM, probably a bit harder to implement than other traditional API due to the way "parameters" is constructed in the json response. But should be made easier thanks to Kotlin collections.
