### ISSUE TITLE
Improve the hourly forecast short term condition dialog style

### ISSUE THREAD

**Issue by nvllz** [breezy-weather/breezy-weather#495]
### Describe your idea

I think it would be much clearer if the app presented the line "Rain will continue for 93 min" as "Rain will continue until 09:22 (AM/PM if needed)". It's valid from the time of refresh, so the user checking the thing has to have the last refresh time in mind, because this text is static. 
There are several types of short term dialogs in this place ("Rain starting in 29 min" etc). I want them all to show the precipitation time (sync hour + time until condition, styled as HH:MM).

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] My idea is not related to a question covered in the [Frequently Asked Questions](https://github.com/breezy-weather/breezy-weather/blob/main/HELP.md) document, or a feature described in the [Homepage](https://github.com/breezy-weather/breezy-weather/blob/main/docs/HOMEPAGE.md) document.
- [X] I have updated the app to **[version 4.6.7 or later](https://github.com/breezy-weather/breezy-weather/releases/latest)**.
- [X] I understand that this app is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY, so I may not get a positive reply to my request, if any at all.

**Comment by papjul** [comment]
This text is provided by AccuWeather, not by the app.

You may be interested by work on #336 however
