### ISSUE TITLE
Temperature as status bar icon -> follow system font

### ISSUE THREAD

**Issue by Coffee-Viking** [breezy-weather/breezy-weather#496]
### Describe your idea

Currently, the temperature is displayed in a quite large and ugly font compared to the original geometric weather (left in the side by side comparison).

Ideally I'd like it to follow the system font to blend in seamlessly.

### Other details

![IMG_20231001_183629](https://github.com/breezy-weather/breezy-weather/assets/12423506/44444d7e-f831-4442-af84-260abfb63aa7)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] My idea is not related to a question covered in the [Frequently Asked Questions](https://github.com/breezy-weather/breezy-weather/blob/main/HELP.md) document, or a feature described in the [Homepage](https://github.com/breezy-weather/breezy-weather/blob/main/docs/HOMEPAGE.md) document.
- [X] I have updated the app to **[version 4.6.7 or later](https://github.com/breezy-weather/breezy-weather/releases/latest)**.
- [X] I understand that this app is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY, so I may not get a positive reply to my request, if any at all.

**Comment by papjul** [comment]
Which one is from Geometric Weather and which one is from Breezy Weather?

On my side, it looks like your first icon and matches clock font.

If it looks like the 2nd icon on your screenshot, please open an issue using the bug template. If it looks like the 1st icon, it's normal.

It won't be possible to go back to Geometric Weather behavior, as Geometric Weather stored all temperatures from -140° to 140° as images in the APK which was very inefficient and didn't support Kelvin unit.

**Comment by Coffee-Viking** [comment]
@papjul it looks like the second icon, left is from geometric weather (which follows the font type but not size). Ideally I'd want to match both type and size.

Will open a bug report then.
