### ISSUE TITLE
Explain the “China” sources

### ISSUE THREAD

**Issue by GrimPixel** [breezy-weather/breezy-weather#498]
### Describe your idea

It is unclear which sources are used for “China”. Only by viewing the code can one conclude that it comes from Xiaomi.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] My idea is not related to a question covered in the [Frequently Asked Questions](https://github.com/breezy-weather/breezy-weather/blob/main/HELP.md) document, or a feature described in the [Homepage](https://github.com/breezy-weather/breezy-weather/blob/main/docs/HOMEPAGE.md) document.
- [X] I have updated the app to **[version 4.6.7 or later](https://github.com/breezy-weather/breezy-weather/releases/latest)**.
- [X] I understand that this app is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY, so I may not get a positive reply to my request, if any at all.

**Comment by papjul** [comment]
Sources for "China" are written either:
- in location list
- in the footer on main screen of each location

**Comment by GrimPixel** [comment]
My question is, why other sources are written as Open-Weather, AccuWeather, etc., and it is “China” instead of “小米天气“?

**Comment by papjul** [comment]
This source was already there when I forked the project. It used to be called "Caiyun" and it was wrong, so I just fixed the name with "China", but I guess you could call it " Mixed China sources", I just don't speak Chinese so I don't know how to say it.

We don't decide which sources are mixed, the server itself decide. China is the only mixed source we have.

**Comment by GrimPixel** [comment]
Judging from the link, it is from Xiaomi. It should be 小米天气.
Talking about that “mixed”, data from those other sources are also gathered from different sources. They are all “mixed”.
