### ISSUE TITLE
Rename “China” with “小米天气”

### ISSUE THREAD

**Issue by GrimPixel** [breezy-weather/breezy-weather#500]
### Describe your idea

Seeing https://github.com/breezy-weather/breezy-weather/blob/main/app/src/main/java/org/breezyweather/sources/china/ChinaService.kt, it is clear that the API is for 小米天气, a service that seems to be combining data from 彩云天气 for the most part and 中国环境监测总站 for air quality index. The API of 小米天气 is available at https://github.com/huanghui0906/API/blob/master/XiaomiWeather.md

### Other details

One thing still unclear: 彩云天气 is providing air quality index data, too. https://caiyunapp.com/. So the data from 小米天气 may be the same as the data from 彩云天气.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] My idea is not related to a question covered in the [Frequently Asked Questions](https://github.com/breezy-weather/breezy-weather/blob/main/HELP.md) document, or a feature described in the [Homepage](https://github.com/breezy-weather/breezy-weather/blob/main/docs/HOMEPAGE.md) document.
- [X] I have updated the app to **[version 4.6.7 or later](https://github.com/breezy-weather/breezy-weather/releases/latest)**.
- [X] I understand that this app is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY, so I may not get a positive reply to my request, if any at all.

**Comment by papjul** [comment]
Data is combined from:
- 北京天气
- 彩云天气
- 中国环境监测总站

This is already displayed in app.

Only China is supported on this source, hence why this name is used. We can rename it "Mixed China sources" in Chinese if you want, so we stay clear about that.

If someone wants to implement ColorfulClouds API directly, we can remove the "China" source.

**Comment by papjul** [comment]
> Actually, 北京天气 is not a proper noun. It means “weather in Beijing”. There is no such a service called “北京天气”.

What's weatherbj if it's not Weather Beijing? Can you provide the correct name?

**Comment by GrimPixel** [comment]
I tried to use the search and I didn't find the string 'weatherbj'. It's not in this repository, not mentioned on that XiaomiWeather.md.
I found it at https://github.com/WangDaYeeeeee/GeometricWeather/blob/b2373551ea97232176afd8cd82dd75f1ef53c8b8/app/src/main/java/wangdaye/com/geometricweather/weather/json/caiyun/CaiYunMainlyResult.java#L16, where it says “北京气象局”, which means “Beijing Weather Bureau”. In reality, there is a “北京市气象局” (Beijing Municipal Weather Bureau) http://bj.cma.gov.cn/, which is responsible for the weather in Beijing only. Its seems that the author messed it up.

**Comment by papjul** [comment]
Do you have an official link (Chinese or English) to the API documentation?
The one you sent doesn't look official.
Thank you!

**Comment by GrimPixel** [comment]
Looks like there is no such an official documentation for 小米天气 online. The API of 彩云天气 is available at https://docs.caiyunapp.com/docs/intro

**Comment by papjul** [comment]
Thank you for the information!
Caiyun, unfortunately, doesn't provide a free tier.

I'm closing this issue in favor of #510
