### ISSUE TITLE
Icons in location shortcuts not updated

### ISSUE THREAD

**Issue by staryil** [breezy-weather/breezy-weather#503]
### Steps to reproduce

When I long press on the app icon it shows my saved locations with an icon of the current weather. But these icons are only updated if I reboot the phone.
I disabled background internet for the app, but shouldn't these icons be updated if I open the app and update the forecast?

### Expected behavior

See above...

### Actual behavior

See above...

### Weather source used

Accuweather

### Breezy Weather version

4.6.8-beta

### Android version

13

### Device

Pixel 7a

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I read the [Frequently Asked Questions](https://github.com/breezy-weather/breezy-weather/blob/main/HELP.md) document and followed instructions if relevant.
- [X] I have updated the app to **[version 4.6.7 or later](https://github.com/breezy-weather/breezy-weather/releases/latest)**.
- [X] I wrote my request in English, and any screenshot I attached are also in English (language can be changed from Settings > Appearance), unless my issue only happens with a specific language
- [X] I understand that this app is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY, so I may not get a positive reply to my request, if any at all.

**Comment by papjul** [comment]
Screenshot of long press on home screen and another of main screen of the app please
