### ISSUE TITLE
New source 心知天气

### ISSUE THREAD

**Issue by GrimPixel** [breezy-weather/breezy-weather#508]
### Link to publicly available documentation of the API

https://docs.seniverse.com/api/start/start.html

### Available and not available data

Available:
#### weather
temperature, feels_like (apparent temperature), pressure, humidity, visibility, wind_direction, wind_direction_degree, wind_speed, wind_scale, clouds (cloud amount), dew_point, precipitation, wind_speed, wind_scale, rainfall
#### aqi
aqi, pm25, pm10, so2, no2, co, o3, primary_pollutant, quality
#### alarm
type, level
#### living index
suggeston, chinese_caalendar
#### geography
sun: sunrise, sunset
moon: rise, set, fraction, phase, phase_name
#### others
ocean, agriculture, climate, etc.

### Are you going to develop yourself the new source for the app?

It depends on my schedules in the future

### Give a bit more details or context about this source

There are many fields that are absent in other services. It would be best if all fields of a service are supported.

### Acknowledgements

- [X] This source has a free-tier available (no mandatory credit card info), and if it a main weather source, it includes free hourly forecast
- [X] If this is a weather source request, I checked that endpoints are by coordinates, or that there is a reverse geocoding endpoint.
- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written the name of the source as the title of this issue.
- [X] I have updated the app to **[version 4.6.7 or later](https://github.com/breezy-weather/breezy-weather/releases/latest)** and this source is not part of it.
- [X] I understand that this app is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY, so I may not get a positive reply to my request, if any at all.

**Comment by papjul** [comment]
> [x] This source has a free-tier available (no mandatory credit card info), and if it a main weather source, it includes free hourly forecast

I can't seem to find this in the pricing: https://www.seniverse.com/pricing

> [x] If this is a weather source request, I checked that endpoints are by coordinates, or that there is a reverse geocoding endpoint.

I can't seem to find this, neither an endpoint by coordinates, or a reverse geocoding endpoint. There is an Excel file with a list of city ID, however no endpoint to get the direct result.
