### ISSUE TITLE
condensed header and 7 day forecast.

### ISSUE THREAD

**Issue by nutpantz** [breezy-weather/breezy-weather#509]
### Describe your idea

Right now on tablets and other devices the weather header is centered on screen wasting a lot of screen real estate above and cutting off much of the weekly forecast below. 
It would be nice is there was an option to condense the screen to get the maximum information with a glance. 
Would be very useful especially for devices for seniors who don't work with technology well.
Ie: are not good with s swiping up down etc for details because of motor control. Learning new things etc

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] My idea is not related to a question covered in the [Frequently Asked Questions](https://github.com/breezy-weather/breezy-weather/blob/main/HELP.md) document, or a feature described in the [Homepage](https://github.com/breezy-weather/breezy-weather/blob/main/docs/HOMEPAGE.md) document.
- [X] I have updated the app to **[version 4.6.7 or later](https://github.com/breezy-weather/breezy-weather/releases/latest)**.
- [X] I understand that this app is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY, so I may not get a positive reply to my request, if any at all.

**Comment by papjul** [comment]
Which device are you using?

> Would be very useful especially for devices for seniors who don't work with technology well.

Can you elaborate a bit? What issues are seniors running into exactly? I want to make sure we fix the correct friction points.

> It did be nice is there was an option to condense the screen to get the maximum information with a glance.

This also seems a bit contradictory with the previous point. We try to match Material design recommendations for spacing, especially as seniors tend to increase display or font size of their device, so we can't make it more compact, to avoid having texts overlap (actually, we still have #86 due to elements being too condensed!).

**Comment by nutpantz** [comment]
![Screenshot_20231005_082049_Breezy Weather](https://github.com/breezy-weather/breezy-weather/assets/12160507/8d34a496-e1a1-49af-b4fa-85924fc5a254)


As you can see there is a lot of unused space.

**Comment by papjul** [comment]
You don't answer the questions.

The left and right space are for the drawer. If you don't like it, you can hold your tablet in portrait mode which will display more info, as you like it.

The top space is for the background elements (here, clouds) and it is part of the design. If you don't like it, well, there are tons of other weather apps without it.

Material Design 3 is here to stay, but small adjustments to the existing design are possible, please answer the questions so I can make the correct diagnosis and make the appropriate changes ;)

**Comment by nutpantz** [comment]
You wanted to know why seniors would have issues. As you can see in the images. There are no background elements, there is also usually no need for other locations and not taking up as much space as they do.

I am just pointing out the wasted space Regardless if it meets material 3 design. Which i suspect is designed not for effective use of space.

**Comment by papjul** [comment]
> You wanted to know why seniors would have issues. As you can see in the images.

Your images don't answer my question, it’s actually the opposite as it is not set up as most seniors would do as I explained in my previous message. Your request looks more like what a power user would want, quite the opposite.

> There are no background elements

There are. On your screenshots, clouds are in the background, and they will fade out as your scroll so they don't overlap with texts. If we were to reduce the white space on top, clouds would overlap text and it would be hard to read (white on white).

It’s also worth mentioning that this padding on top was reduced compared to Geometric Weather, the original app, to have a middle ground between "too much space" and "doesn't breathe".

> I am just pointing out the wasted space Regardless if it meets material 3 design. Which i suspect is designed not for effective use of space.

You're right, letting the design breathe is independent of Material Design 3. It is a good thing to not be overwhelmed by too many information. To take a different example than Material Design, it is heavily used by Apple with their large areas of white space to communicate a sense of simplicity and to reflect the user-friendliness of its products, which appeal to senior users.

The layout of landscape mode of tablet is inherited from Geometric Weather, and there is no plan to change that. If you like compact info over design, Windy.com comes to my mind (a weather app with compact tables of info, for power users like you), or anything else from the tons of other weather apps out there to try ;)
