### ISSUE TITLE
Replace the words "Current location" with the actual location's name

### ISSUE THREAD

**Issue by mrtootoo** [breezy-weather/breezy-weather#513]
### Describe your idea

Both the app and widget don't display the actual location name, just the words "Current location"

### Other details

Some areas have multiple weather data locations, other locations may have few or maybe the closest one is very far away.  Knowing the location of the displayed weather information is important.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] My idea is not related to a question covered in the [Frequently Asked Questions](https://github.com/breezy-weather/breezy-weather/blob/main/HELP.md) document, or a feature described in the [Homepage](https://github.com/breezy-weather/breezy-weather/blob/main/docs/HOMEPAGE.md) document.
- [X] I have updated the app to **[version 4.6.7 or later](https://github.com/breezy-weather/breezy-weather/releases/latest)**.
- [X] I understand that this app is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY, so I may not get a positive reply to my request, if any at all.

**Comment by papjul** [comment]
App displays the current location name... for weather sources that support such feature.

Did you check in [this document](https://github.com/breezy-weather/breezy-weather/blob/main/docs/SOURCES.md) that your weather source supports reverse geocoding?

**Comment by mrtootoo** [comment]
> App displays the current location name... for weather sources that support such feature.
> 
> Did you check in [this document](https://github.com/breezy-weather/breezy-weather/blob/main/docs/SOURCES.md) that your weather source supports reverse geocoding?

I am not a coder, but am familiar with other similar products.  Macropinch Weather and [Martykan Forcastie](https://github.com/martykan/forecastie) both display location of their displayed weather data.  I believe they use the same sources as you.

**Comment by papjul** [comment]
You don't answer the question. What source are you using for current location?

**Comment by mrtootoo** [comment]
> You don't answer the question. What source are you using for current location? Is the user documentation showing that that source supports reverse geocoding?

I am not a coder and do not understand your question whether or not the source supports reverse geocoding?  I do know other open source weather projects use the same weather sources as you and they do provide weather data location name.

**Comment by papjul** [comment]
You don't need to be a coder to read an **user** documentation. Sending again the link: https://github.com/breezy-weather/breezy-weather/blob/main/docs/SOURCES.md

If you don't want to, at least tell us which source you're using for your current location!

Reverse geocoding is the process of converting coordinates (longitude, latitude) to an address (what you're asking). When you ask for "current location", we only know your longitude and latitude, we don't know your address, so we need that reverse geocoding process to get an address amd not " Current location".

For example, Open-Meteo doesn't support reverse geocoding atm. See this issue: open-meteo/geocoding-api#6

**Comment by mrtootoo** [comment]
Macropinch Weather and [Martykan Forcastie](https://github.com/martykan/forecastie) both use [OpenWeather](https://openweathermap.org/)

**Comment by papjul** [comment]
Timezone is a mandatory field. Reverse geocoding of OpenWeather does not support timezone so we can't use it. Feel free to use other weather apps that don't depend on timezone info.

**Comment by mrtootoo** [comment]
I know Forcastie uses OpenWeather.  I know my system has not Google Services.  Maybe @robinpaulson with [Martykan Forcastie](https://github.com/martykan/forecastie) could help.  I wish you all the luck with your development.

**Comment by papjul** [comment]
I'm pretty sure this app doesn't need the timezone because they parse a string date including timezone from the forecast instead of storing it separately in the location. However, Breezy Weather is an app using multiple sources, we need the timezone separately, as some sources use an Unix timestamp or just give us UTC+0. An app tailored for usage with OpenWeather can do whatever they want, but if we want multiple sources, we need some common way of working.

By the way, OpenWeather no longer match criteria for inclusion in Breezy Weather as they require credit card information, so this source is now provided "as-is".
