### ISSUE TITLE
Drop space between degree symbol and number (or make it optional at least)

### ISSUE THREAD

**Issue by dbenjaminmiller** [breezy-weather/breezy-weather#515]
### Describe your idea

Right now, temperatures display as follows:

23⁰ or 23 ⁰C

When there is a temperature unit, there's a space between the number and the symbol. When there is no temperature unit, there is no space.

This was a conscious design decision in Geometric Weather: https://github.com/WangDaYeeeeee/GeometricWeather/issues/483. This decision was made on the basis that this is the SI standard for writing units (23 mm, 23 ⁰C).

But this is inconsistent with both how "unitless" temperatures are displayed and with how almost every other weather app displays temperatures. It's also (subjectively) kind of ugly, especially in widgets.

Not only that, it's not how weather apps tend to show degrees. The vast majority I can find (including Google's) show 23⁰C or simply 23⁰.

I find the incongruity particularly apparent in widgets, especially in the styles (tile, symmetry) where the unitless and united temperatures are shown together.

A space may be expected in scientific prose, but I think a lack of space is what's expected in a weather app. At the very least, this should be an option.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] My idea is not related to a question covered in the [Frequently Asked Questions](https://github.com/breezy-weather/breezy-weather/blob/main/HELP.md) document, or a feature described in the [Homepage](https://github.com/breezy-weather/breezy-weather/blob/main/docs/HOMEPAGE.md) document.
- [X] I have updated the app to **[version 4.6.7 or later](https://github.com/breezy-weather/breezy-weather/releases/latest)**.
- [X] I understand that this app is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY, so I may not get a positive reply to my request, if any at all.

**Comment by papjul** [comment]
My arguments from WangDaYeeeeee/GeometricWeather#211 are still valid.

> But this is inconsistent with both how "unitless" temperatures are displayed

Please show me where we put unitless temperatures in the app, I will fix it, a temperature should never be without unit.

> Not only that, it's not how weather apps tend to show degrees. The vast majority I can find (including Google's) show 23⁰C or simply 23⁰.

It's not because all other weather apps are wrong, that we have to be as well. Actually, what you should be doing is report the issue to Google, not here, where we are doing it right.

Btw, you're using "superscript 0" instead of "degree" (⁰ vs °) in your messages.

> A space may be expected in scientific prose, but I think a lack of space is what's expected in a weather app.

It's a wrong assumption, it's not to be applied on scientific prose only, it is a typesetting rule. If developers are not respecting this rule, I'm not surprised as I don't expect them to have knowledge of typography, but people whose it's the job or who are familiar with it will respect it. Besides units, there are other typographic rules we respect more in this app than what other apps usually do, and it's a good thing if we do things better than other apps.

> At the very least, this should be an option.

Of course, a typography rule is not an option.

**Comment by dbenjaminmiller** [comment]
> Please show me where we put unitless temperatures in the app, I will fix it, a temperature should never be without unit.

Every instance with only the degree symbol, and not a specific unit, is a unitless temperature. There is no such temperature as "23°" without specifying what the unit is. A degree Celsius is a unit of temperature; a degree Fahrenheit is a unit of temperature. But there's no unit specified by "degree" alone.

> It's not because all other weather apps are wrong, that we have to be as well. Actually, what you should be doing is report the issue to Google, not here, where we are doing it right.

If the vast majority of others are writing something differently, then it is probably not because you are right and they are wrong, but because there is a difference in style.

> Btw, you're using "superscript 0" instead of "degree" (⁰ vs °) in your messages.

That's true, as I used the wrong keyboard shortcut. To be clear, I'm not suggesting using anything other than the Unicode symbol for degrees (which is already being done).

> It's a wrong assumption, it's not to be applied on scientific prose only, it is a typesetting rule. If developers are not respecting this rule, I'm not surprised as I don't expect them to have knowledge of typography, but people whose it's the job or who are familiar with it will respect it. Besides units, there are other typographic rules we respect more in this app than what other apps usually do, and it's a good thing if we do things better than other apps.

There is more than one typographic style in the world. Different styles prevail in different contexts. There are many style guides commonly used by professional typographers and copy editors which specify that a space is *not* to be put between the number and the degree symbol.

The Chicago Manual of Style, one of the mostly common style guides in the United States, says (17th ed.):

> **9.16 Numbers with abbreviations and symbols.** [...] A space is normally used between the numeral and the unit of measure, except in a few cases — for example, with degree, percent, and prime symbols (but see also 10.58)

> **10.58 SI units and abbreviations — spacing.** [...] In SI usage as in general usage, a space usually appears between the numeral and any abbreviation or symbol. Contrary to general usage, however, SI usage also stipulates a space before a percentage sign (%) or before a degree symbol used for temperature.

The (US) National Center for Atmospheric Research has a [style guide](https://docs.google.com/document/d/1lDiqpGRPhAiiAJPopBMPvbo4C6jZ_x3lymTV-ezZezo) which says:

> **degrees**—Always spell out first use in NCAR|UCAR News stories: minus 40 degrees Fahrenheit. In report and other uses, write the degree symbol closed up: 30°N (in nontechnical/outreach writing, 30° north), 30°F. Do not use "degrees" or the degree symbol for the Kelvin scale: 280 Kelvin, 280 K.

The (US) National Renewable Energy Laboratory (a national laboratory of the US Department of Energy) [says](https://www.nrel.gov/comm-standards/editorial/temperature.html):

> Use a degree symbol (°) with temperatures expressed in the Celsius and Fahrenheit scales but not with kelvins (just use K). Don't leave a space between the number and the letter for °C and °F, but leave a space between the number and K.
> 72°F
> 0 K 

The National Geographic Style Manual [says](https://sites.google.com/a/ngs.org/ngs-style-manual/home/T/temperatures):

> Generally express in figures, no space before or period after C or F; spell out the expressions "below zero" and "minus" except in conversions.
> [...]
> C is the abbreviation for Celsius, cap C, no space or period.  When writing out, use degrees with zero or values greater than one:
>> 23 degrees Celsius, zero degrees Celsius; minus 4°C or -4°C
>
> F is the abbreviation for Fahrenheit:
>> 32°F (no spaces, no period); 0°C (32°F)


This demonstrates that there are significant style guides indicating that a space should *not* be used. There are also, of course, style guides that say a space should be used. Some guides call for a thin space. Then you have the Associated Press, which calls for "23 C" or "73 F" rather than using a degree symbol at all (The *Guardian* in Britain calls for *23C (73F)*). Many newspapers write out "degrees" in their reporting, rather than using a symbol. And so on.

For another example, current [US White House reports](https://www.whitehouse.gov/wp-content/uploads/2021/10/US-Long-Term-Strategy.pdf) use the "23°C" style. [British government reports](https://www.gov.uk/guidance/climate-change-explained) also use the "23°C" style. This seems to be very common in the English language. (Perhaps not coincidentally, Google is based in the US.)

As for other apps and services, most (from a cursory look) seem to either omit the space or use only a degree symbol:

* Apple Weather: 23°
* (former) Dark Sky: 23°
* Google: 23°C
* The Weather Channel: 23°
* AccuWeather: 23° or (a bit unusually) 23°C (with a small *C*, sometimes placed below the degree symbol)
* OpenWeather: 23°C

> Of course, a typography rule is not an option.

Of course it's an *option*. There is more than one way to write things, and different style standards reflect that. (Even if it were not codified in a style guide, the fact that other apps do it would [establish that it is a style in common use](https://en.wikipedia.org/wiki/Linguistic_description).) There is more than one typographical style in the world (for many things, not just temperature symbols) and not following a particular style is not indicative of ignorance.

The expected standards also vary with language and country; the SI guide and ISO 31-0 both say that a percent sign should be separated from the number, as in *55 %*, which is the common use in some languages, but the vast majority of English-language style guides prescribe *55%*, which is the almost universal use in English (and some other languages).

Besides this, when the temperature unit is set to Kelvin, the widgets use "296K" on the home screen where "23 °C" would be found, which I find has nowhere near the common support that "23°C" has in style guides.

**Comment by papjul** [comment]
> > Please show me where we put unitless temperatures in the app, I will fix it, a temperature should never be without unit.
> 
> Every instance with only the degree symbol, and not a specific unit, is a unitless temperature. There is no such temperature as "23°" without specifying what the unit is. A degree Celsius is a unit of temperature; a degree Fahrenheit is a unit of temperature. But there's no unit specified by "degree" alone.

That I can fix, and actually, it has been annoying me for some time. However, in my tests, it didn’t render well with a C as big as the number, that’s why I put it aside for some time.

> > It's not because all other weather apps are wrong, that we have to be as well. Actually, what you should be doing is report the issue to Google, not here, where we are doing it right.
> 
> If the vast majority of others are writing something differently, then it is probably not because you are right and they are wrong, but because there is a difference in style.

> As for other apps and services, most (from a cursory look) seem to either omit the space or use only a degree symbol:
> 
>     * Apple Weather: 23°
> 
>     * (former) Dark Sky: 23°
> 
>     * Google: 23°C
> 
>     * The Weather Channel: 23°
> 
>     * AccuWeather: 23° or (a bit unusually) 23°C (with a small _C_, sometimes placed below the degree symbol)
> 
>     * OpenWeather: 23°C

So, can we agree copying other apps is not a good thing, since almost all other apps are using a “degree” alone which is not valid?

> Some guides call for a thin space.

Yes, we use a kind of thin space a lot in French, but unfortunately, they almost always render as a normal space in apps, so we cannot use it :(

> > Of course, a typography rule is not an option.
> 
> Of course it's an _option_. There is more than one way to write things, and different style standards reflect that. (Even if it were not codified in a style guide, the fact that other apps do it would [establish that it is a style in common use](https://en.wikipedia.org/wiki/Linguistic_description).) There is more than one typographical style in the world (for many things, not just temperature symbols) and not following a particular style is not indicative of ignorance.

Let me reword differently then:

> There is more than one typographic style in the world. Different styles prevail in different contexts. There are many style guides commonly used by professional typographers and copy editors which specify that a space is _not_ to be put between the number and the degree symbol.

Do people following the Chicago Manual of Style offer you an option to turn on spaces before units when you read their papers? Does Wikipedia (English) offer you an option to drop spaces before units? More generally, is there a single app in this world that offer such an option? When you decide a typographic style, you stick to it everywhere. And I would say that a support that targets worldwide, such as Breezy Weather or Wikipedia, should use the International Standard.

> The expected standards also vary with language and country; the SI guide and ISO 31-0 both say that a percent sign should be separated from the number, as in _55 %_, which is the common use in some languages, but the vast majority of English-language style guides prescribe _55%_, which is the almost universal use in English (and some other languages).

IMO this is very inconsistent. The SI guide says that we should put a space almost everywhere, but in English, depending on some guides, sometimes you put it, sometimes not. Should there also be a separate option as well for percent or can we agree to use an international standard?

> Besides this, when the temperature unit is set to Kelvin, the widgets use "296K" on the home screen where "23 °C" would be found, which I find has nowhere near the common support that "23°C" has in style guides.

I think "296K" would display when "23°" is displayed, not "23 °C" (otherwise, it would be "296 K"). This will be fixed when I will add the full unit everywhere.

**Comment by dbenjaminmiller** [comment]
> That I can fix, and actually, it has been annoying me for some time. However, in my tests, it didn’t render well with a C as big as the number, that’s why I put it aside for some time.

To be clear, I'm _not_ saying that's a bug; I think that those instances in which 23° is displayed (for example, in a widget), it would make no sense to display 23 °C instead. It is not denominated in a unit, but I don't need it to be — I know that a degree on my home screen means a degree Celsius and not Fahrenheit or Rankine or whatever.

> So, can we agree copying other apps is not a good thing, since almost all other apps are using a “degree” alone which is not valid?

No, as I don't think that validly showing units (always having a full "°C" whenever a Celsius temperature is displayed) is a good design idea (and I think that especially for widgets that I wouldn't be alone in thinking that).

> Do people following the Chicago Manual of Style offer you an option to turn on spaces before units when you read their papers? Does Wikipedia (English) offer you an option to drop spaces before units? More generally, is there a single app in this world that offer such an option? When you decide a typographic style, you stick to it everywhere. And I would say that a support that targets worldwide, such as Breezy Weather or Wikipedia, should use the International Standard.

The people writing papers obviously do not offer you the opportunity to change their typography when you read them. English Wikipedia doesn't do this for units, either (nor for varieties of English — it doesn't stick to a single standard version of English). However, the date templates on English Wikipedia do offer multiple formats (whereas a style guide would give only one date format to be used).

In any case, we're talking about an app, not a literary work. And different typographical options are actually very common in computer systems. They are often found in localization settings (and are often tied at least by default to the choice of langauge or region, although some of these variations are not strictly specific to regions either). Most computer systems have options for first day of the week (Sunday or Monday per the civil calendar of different countries), temperature units (if not spaces), number spacing and separators (use of spaces, periods and commas in numbers), date formatting, etc. And locale selections also (in many cases) determine the use of typography in general — here in Québec, for instance, there are some differences from the typographical standards used in France (as relate to capitalization and the omission of spaces before certain punctuation marks where a full-width space would be used in French typography).

> IMO this is very inconsistent. The SI guide says that we should put a space almost everywhere, but in English, depending on some guides, sometimes you put it, sometimes not. Should there also be a separate option for percent or can we agree to use an international standard?

The SI is supposed to standardize scientific units in use; it's not intended to be an internationally applicable guide to general typography. "23 °C" and "50 %" are hardly universal typographic standards, and virtually no general-interest publication is consulting the SI standards for typography. And why should they? That's not the goal of the SI.

Anyway, if you really want to see "23 °C" on a widget, sure (though I think to many of us that would "render poorly," as you say — this is an aesthetic judgment, but I'd agree that it would be a worse option), but why can't some of us have "23°" or "23°C"? Some mild string formatting (especially in line with common variants) could certainly be added (I could even write a PR for it not long from now) and I don't know why it needs to be dismissed out of hand.

**Comment by papjul** [comment]
> Most computer systems have options for first day of the week (Sunday or Monday per the civil calendar of different countries), temperature units (if not spaces), number spacing and separators (use of spaces, periods and commas in numbers), date formatting, etc.

But you're talking about operating systems. If there is such a thing natively provided by Android through SDK, I can use it, sure, but if there isn't, not every app you use is going to implement their own regional settings, that would be too redundant.

But I doubt Android provides that, because in the case of units, I disagree it's a regional setting. I checked Android and KDE (Linux) and while I could find regional settings, I couldn't find one about how units should be displayed. The only customization possible for units was for currency. Can you give a few real-life examples of regional settings of units (percent, temperature)?

> here in Québec, for instance, there are some differences from the typographical standards used in France (as relate to capitalization and the omission of spaces before certain punctuation marks where a full-width space would be used in French typography).

However, that one is a regional setting. And we do have a string available to customize it, so you can create fr-CA to remove that space (although, my understanding is that both are valid, but omission is more common).

> why can't some of us have "23°" or "23°C"?

Because the solution is either:
- An option. See Breezy Weather policy regarding new preferences: https://github.com/breezy-weather/breezy-weather/blob/main/CONTRIBUTE.md#new-preference
- A translation, but it isn't tied to a language/country, see Wikipedia formatting style in English, for example

**Comment by dbenjaminmiller** [comment]
For temperature units, no, Android doesn't provide a specific setting.

* Side note: percentage sign space actually *is* covered by language settings in Android. The native Android settings app shows "23%" in English, Mexican Spanish and Hungarian (just what I tested) and "23 %" in French, German and Spanish Spanish and apps can use the language setting to determine which to use.
I would suggest that an option is actually a very generally useful thing. As you point out, maybe someone prefers to have "23°" in their widget and maybe someone else wants "23°C".

I would suggest a "short form/long form" formatting option where, under units, anyone can choose how the formatting is done consistently throughout the app. Anywhere where "23°" is used right now is the compact form and anywhere where "23 °C" is used is the full form. So for each context you could choose between 23°, 23°C, 23 °C, 23C, 23... either this could be done as a custom text string or as a menu selection (the former being, I suppose, more general, but the latter more simple to implement).

Not only are there different language-based or regional styles, someone might prefer to show the "C" (or not) based on aesthetic/size considerations, so I think it would be an option with fairly broad utility and (just from my glance at the code) not that hard to do (especially if it's from a menu of pre-selected options).

**Comment by papjul** [comment]
>     * Side note: percentage sign space actually _is_ covered by language settings in Android. The native Android settings app shows "23%" in English, Mexican Spanish and Hungarian (just what I tested) and "23 %" in French, German and Spanish Spanish and apps can use the language setting to determine which to use.

It's probably in this class then: https://developer.android.com/reference/android/icu/text/NumberFormat#PERCENTSTYLE
I will try to use it.

>       I would suggest that an option is actually a very generally useful thing.

And I'm pretty sure of the opposite, that it wouldn’t be useful because no one would care about that option, and it would do more harm than good. I explain why in https://github.com/breezy-weather/breezy-weather/blob/main/CONTRIBUTE.md#new-preference

For a more detailed article about UX considerations, you can read: https://blog.prototypr.io/the-swiss-knife-complex-how-a-features-focus-approach-can-harm-your-product-937bbae891fb

> an option with fairly broad utility and (just from my glance at the code) not that hard to do (especially if it's from a menu of pre-selected options).

If it has such a broad utility, why isn’t there a single weather app implementing it?
Being hard to do is not the question here. There are tons of simple things to do I refuse, because I have to stick to some guidelines to keep the app simple to use. A lot of people don't like these decisions, but it’s fine, actually the vast majority of people are silently happy with this fork, and for the others, they can have a look at all other weather apps or just fork it like I did, it’s FOSS.

**Comment by dbenjaminmiller** [comment]
> If it has such a broad utility, why isn’t there a single weather app implementing it?

Because almost every weather app is using a compact form already (especially for widgets). 23° (or 23°C) is much more common than 23 °C because the information that's relevant to the user is almost always the number rather than the type of degree unit.

I actually care far more about the widget (with limited space) using 23° and not 23 °C (and the corresponding immediate juxtaposition of 23° and 23 °C in some widget configs) than I do about whether or not a space can be turned off in the main app display.

If I were going to propose something _without_ options, it would be to consistently use 23° (without a C or space) in widgets to emphasize the number over the unit. This is already the behavior in about half the uses in widgets. Users of other apps don't seem to get confused too often about what type of degree it is.

Inside the actual app, the central display of the temperature doesn't really bother me. It's more just the home screen widget inconsistency.

**Comment by papjul** [comment]
> I actually care far more about the widget (with limited space)

Widgets are being rewritten, I can tell the person in charge of it that the short form of unit is preferred, or at least make sure there is enough space to display, although as I told you, I don't like it much as I feel it's important.

Let me give an example with another feature someone wanted, it was to display both Celsius and Fahrenheit in widgets. If you display both as °, you can't differentiate them. More generally, it is important, some examples that come to mind: when sharing screenshots, making widgets templates, it's important to show the full unit.

**Comment by dbenjaminmiller** [comment]
Displaying both C and F, sure, although this feels like another level of options to deal with that.

As for screenshots, I don't get why it's important to show the full unit there. The general look/layout is the same whether you're using Celsius or Fahrenheit; a sample template screenshot only needs to show the shape/positioning since it's not being used to convey the actual temperature. The user will know what choice they made so it shouldn't be ambiguous in practice 99.9% of the time.
