### ISSUE TITLE
Improve 2x1 widget

### ISSUE THREAD

**Issue by xmha97** [breezy-weather/breezy-weather#524]
### Describe your idea

https://github.com/davidtakac/prognoza

![Screenshot_2023-10-11-01-50-25-153_com miui home](https://github.com/breezy-weather/breezy-weather/assets/23485114/fbf6b79d-ee15-45d2-8e9a-3403dda6c695)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] My idea is not related to a question covered in the [Frequently Asked Questions](https://github.com/breezy-weather/breezy-weather/blob/main/HELP.md) document, or a feature described in the [Homepage](https://github.com/breezy-weather/breezy-weather/blob/main/docs/HOMEPAGE.md) document.
- [X] I have updated the app to **[version 4.6.9 or later](https://github.com/breezy-weather/breezy-weather/releases/latest)**.
- [X] I understand that this app is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY, so I may not get a positive reply to my request, if any at all.

**Comment by xmha97** [comment]
Sorry, I just saw the comets
How can I open the issue?
cc: @papjul

**Comment by papjul** [comment]
Go to Issues tab, tap the green New button, choose the "Idea" template.

Write an informative title.

In the "Describe your idea" section, describe your idea in details.

If you have multiple ideas, please open a New issue for each of them.
