### ISSUE TITLE
Remove This at Opening

### ISSUE THREAD

**Issue by Glassto** [breezy-weather/breezy-weather#529]
### Describe your idea

It would be great, at opening, if this would be removed:
 
![Screenshot_20231011-221821_Breezy Weather](https://github.com/breezy-weather/breezy-weather/assets/102603092/b4c44af2-ee51-4412-a643-33c3f82f43ac)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] My idea is not related to a question covered in the [Frequently Asked Questions](https://github.com/breezy-weather/breezy-weather/blob/main/HELP.md) document, or a feature described in the [Homepage](https://github.com/breezy-weather/breezy-weather/blob/main/docs/HOMEPAGE.md) document.
- [X] I have updated the app to **[version 4.6.9 or later](https://github.com/breezy-weather/breezy-weather/releases/latest)**.
- [X] I understand that this app is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY, so I may not get a positive reply to my request, if any at all.

**Comment by papjul** [comment]
What should be removed? Splash screen is mandatory, if you don't define one, you get a white blank screen anyway

**Comment by Glassto** [comment]
Hello,
papjul

Sorry for the inconvenience, but I use some apps that, idk, somehow bypass the splash screen (Poweramp, ViMusic).

**Comment by papjul** [comment]
What does that mean?
Splash screen is just a nice way to get into the app while it loads. All apps have a loading time, although recent Android versions tend to be very optimized so it's showing it very quickly now.
