### ISSUE TITLE
Add "TheWeatherChannel" as provider to Breezy

### ISSUE THREAD

**Issue by Glassto** [breezy-weather/breezy-weather#530]
### Describe your idea

I suggest integrating TheWeatherChannel as a weather provider within the Breezy app. This would offer users a more comprehensive and accurate weather forecast, as TheWeatherChannel is known for its precise and up-to-date weather data. 

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] My idea is not related to a question covered in the [Frequently Asked Questions](https://github.com/breezy-weather/breezy-weather/blob/main/HELP.md) document, or a feature described in the [Homepage](https://github.com/breezy-weather/breezy-weather/blob/main/docs/HOMEPAGE.md) document.
- [X] I have updated the app to **[version 4.6.9 or later](https://github.com/breezy-weather/breezy-weather/releases/latest)**.
- [X] I understand that this app is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY, so I may not get a positive reply to my request, if any at all.

**Comment by papjul** [comment]
Please use "Source" template
