### ISSUE TITLE
Support android 13+ per app language feature

### ISSUE THREAD

**Issue by Mr-Bajs** [breezy-weather/breezy-weather#532]
### Describe your idea

Since android 13 you can set app language in android settings, rather then in the apps themselfs or following the systems language. Even its not hard or inconvenient to change language settings in the apps themself, its more convenient and you get a better overview and a granular control.

https://developer.android.com/guide/topics/resources/app-languages

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] My idea is not related to a question covered in the [Frequently Asked Questions](https://github.com/breezy-weather/breezy-weather/blob/main/HELP.md) document, or a feature described in the [Homepage](https://github.com/breezy-weather/breezy-weather/blob/main/docs/HOMEPAGE.md) document.
- [X] I have updated the app to **[version 4.6.9 or later](https://github.com/breezy-weather/breezy-weather/releases/latest)**.
- [X] I understand that this app is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY, so I may not get a positive reply to my request, if any at all.

**Comment by papjul** [comment]
What about languages not supported by Android? I have an Esperanto user who told me that support for this language was removed on one of his apps after this app moved to this native way.

**Comment by papjul** [comment]
Reopening for further investigation. Esperanto and Kabyle are not natively supported by Android, so needs investigation on these cases.

Implementation: the language preference in app must redirect to the native language settings on Android ≥ 13 and use the current language preferences on Android < 13.

**Comment by papjul** [comment]
Fixed in c8fc27541587aa38000ddfa5584e5ed9c6a01f44
