### ISSUE TITLE
Weather widget takes user to incorrect date

### ISSUE THREAD

**Issue by biff80** [breezy-weather/breezy-weather#533]
### Steps to reproduce

1. Select weather widget (i.e. "clock+daily+weekly" widget, but there many be others) and post it
2. Pick a forecasted weather date in the weekly widget (e.g. Tuesday...not the current day)
3. App will take display detailed forecast data one day behind the targeted date (e.g. Monday) instead of the day selected

### Expected behavior

When picking a forecasted weather date on the widget, it should take user to the forecasted date, not the previous date

### Actual behavior

When clicking on the weather widget and selecting a forecasted date, it displays the detailed information for the day just previous to the date selected. For example, if I select the weather forecast for October 19th, it will take me to the forecast for October 18th. If I select it for October 15th, it will show data for October 14th.

### Weather source used

OpenMeteo

### Breezy Weather version

4.6.9 Beta

### Android version

Android 13

### Device

Asus Zenfone 9

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I read the [Frequently Asked Questions](https://github.com/breezy-weather/breezy-weather/blob/main/HELP.md) document and followed instructions if relevant.
- [X] I have updated the app to **[version 4.6.9 or later](https://github.com/breezy-weather/breezy-weather/releases/latest)**.
- [X] I wrote my request in English, and any screenshot I attached are also in English (language can be changed from Settings > Appearance), unless my issue only happens with a specific language
- [X] I understand that this app is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY, so I may not get a positive reply to my request, if any at all.

**Comment by papjul** [comment]
Fixed in #526
