### ISSUE TITLE
Temperature without unit in Notification-widget

### ISSUE THREAD

**Issue by Glassto** [breezy-weather/breezy-weather#534]
### Steps to reproduce

1. Go to Settings
2. Select Widget & Live Wallpaper
3. Scroll Down and Enable "Notification Widget"
4. Select "Style" as Native
5. Open Android Notification Bar

### Expected behavior

It should show the temperature: 
![Screenshot_20231017-195001_Breezy Weather](https://github.com/breezy-weather/breezy-weather/assets/102603092/2035a7f6-d085-421d-8fea-14650156fa34)

### Actual behavior

I do not know what "3.1" mean:
![Screenshot_20231017-194947_Breezy Weather](https://github.com/breezy-weather/breezy-weather/assets/102603092/a0836ea8-c322-45b7-8f8b-f38ee3085ab0)

### Weather source used

 Open-Meteo

### Breezy Weather version

4.6.9-beta

### Android version

Android 9

### Device

Samsung Galaxy Note 8

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I read the [Frequently Asked Questions](https://github.com/breezy-weather/breezy-weather/blob/main/HELP.md) document and followed instructions if relevant.
- [X] I have updated the app to **[version 4.6.9 or later](https://github.com/breezy-weather/breezy-weather/releases/latest)**.
- [X] I wrote my request in English, and any screenshot I attached are also in English (language can be changed from Settings > Appearance), unless my issue only happens with a specific language
- [X] I understand that this app is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY, so I may not get a positive reply to my request, if any at all.

**Comment by papjul** [comment]
>     * [x]  I wrote my request in English, and any screenshot I attached are also in English (language can be changed from Settings > Appearance), unless my issue only happens with a specific language

Please attach screenshots in English

**Comment by Glassto** [comment]
I have attached screenshots in English.
Thanks,
