### ISSUE TITLE
Precipation graph slightly falling when values stay the same

### ISSUE THREAD

**Issue by MatsG23** [breezy-weather/breezy-weather#538]
### Steps to reproduce

1. Scroll down to the precipation graph for the next hours
2. Find a spot where the temperature stays the same for multiple hours in a row 

### Expected behavior

The precipation graph should be flat.

### Actual behavior

The precipation graph sometimes falls between two exact same values.

![Screenshot_20231017-155953](https://github.com/breezy-weather/breezy-weather/assets/60609373/279ccf3c-8904-47fb-8808-c64e944a7ce0)

### Weather source used

OpenWeather

### Breezy Weather version

4.6.10-beta

### Android version

GrapheneOS 2023101300 (based on Android 14)

### Device

Google Pixel 6a

### Other details

This issue will likely also be there for the other precipation graph (next days).

Related to https://github.com/breezy-weather/breezy-weather/issues/369

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I read the [Frequently Asked Questions](https://github.com/breezy-weather/breezy-weather/blob/main/HELP.md) document and followed instructions if relevant.
- [X] I have updated the app to **[version 4.6.9 or later](https://github.com/breezy-weather/breezy-weather/releases/latest)**.
- [X] I wrote my request in English, and any screenshot I attached are also in English (language can be changed from Settings > Appearance), unless my issue only happens with a specific language
- [X] I understand that this app is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY, so I may not get a positive reply to my request, if any at all.

**Comment by papjul** [comment]
It's unrelated to #369 which is "Precipitation in next hour".

I guess it's reproducible in Geometric Weather, not a regression?

**Comment by papjul** [comment]
Oh, now I understand!
It's actually not an issue! In Breezy Weather, we now have a 0.1 Celsius degree precision, while in Geometric Weather, we only had 1 degree precision. So, your different 15 degrees are not actually equal to 15.0, they may vary from 14.5 to < 15.5, which explains the very slight difference you can see ;)

**Comment by papjul** [comment]
Probably, but would be inelegant with increased Android display size.

Additionally that decimal is not very useful from a "feeling" point, and would clutter a bit more the interface. I prefer to let the chart breathe as it is now ;)
