### ISSUE TITLE
[Open-Meteo] Add feels like temperature in overview on main screen

### ISSUE THREAD

**Issue by min7-i** [breezy-weather/breezy-weather#54]
### Steps to reproduce

1. Choose a location with Open-Meteo as the weather provider.
2. Go the the main screen.
3. Check the info at the top.
4. It only shows the temperature, wind, uv-index and humidity.
5. The feels like temperature is missing.

### Expected behavior

The feels like temperature should be visible on the main screen in the info section at the top.

As the feels like temperature is shown both in the daily as well as in the hourly details view, I'd assume that Open-Meteo does provide this info.

<details><summary>screenshot of hourly details</summary>

![InkedScreenshot_20230622-100950](https://github.com/breezy-weather/breezy-weather/assets/97251923/b735cfe5-d0bb-42c4-9020-59fbd14f5566)

</details>

### Actual behavior

The feels like temperature is missing on the main screen.

<details><summary>screenshot</summary>

![InkedScreenshot_20230622-100941](https://github.com/breezy-weather/breezy-weather/assets/97251923/0e67c436-0a2b-4868-b690-99d1a694f756)

</details>

### Weather provider used

Open-Meteo

### Breezy Weather version

4.0.0-alpha

### Android version

Android 13 (GrapheneOS)

### Device

Google Pixel 6a

### Other details

The feels like temperature is shown in the info on the main screen when using AccuWeather or OpenWeather as the weather provider.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to **[latest version](https://github.com/breezy-weather/breezy-weather/releases/latest)**.

**Comment by papjul** [comment]
Feels Like temperature is not part of current API:
https://api.open-meteo.com/v1/forecast?latitude=52.52&longitude=13.41&current_weather=true

For humidity, it is extrapolated from humidity in the forecast following hour.

However, I don't think it would be good to do the same for this case (mixing current temperature with forecast apparant temperature).

I would recommand to wait for https://github.com/open-meteo/open-meteo/issues/312 for the time being.

**Comment by min7-i** [comment]
Thanks for the explanation. Then it makes sense to wait for the feature to be implemented in Open-Meteo.

It might help to add a "feels like temperature" entry to the [comparison of the weather providers](https://github.com/breezy-weather/breezy-weather/blob/main/docs/PROVIDERS.md), so that it's clear which provider supports it. By the way, the overview is very helpful 👍

**Comment by papjul** [comment]
787bc10a8df27d9343a3ffd91f9152626e8b9cad now picks feels like temperature from the closest hour at the time of refresh
