### ISSUE TITLE
[Open-Meteo] Days in Daily forecast incorrectly display the day before, on days after DST is observed

### ISSUE THREAD

**Issue by fuzzmz** [breezy-weather/breezy-weather#543]
### Steps to reproduce

Using version 4.6.10-beta, in the Daily forecast card Sunday is shown twice.

![duplicate_daily_forecast](https://github.com/breezy-weather/breezy-weather/assets/1335181/c8fa0703-6804-485a-9b2d-8f9105c4aa38)

### Expected behavior

Daily forecast should not contain duplicate entries.

### Actual behavior

Daily forecast contains duplicate entries.

### Weather source used

Open-Meteo

### Breezy Weather version

4.6.10-beta

### Android version

Android 10

### Device

OnePlus 5T

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I read the [Frequently Asked Questions](https://github.com/breezy-weather/breezy-weather/blob/main/HELP.md) document and followed instructions if relevant.
- [X] I have updated the app to **[version 4.6.10 or later](https://github.com/breezy-weather/breezy-weather/releases/latest)**.
- [X] I wrote my request in English, and any screenshot I attached are also in English (language can be changed from Settings > Appearance), unless my issue only happens with a specific language
- [X] I understand that this app is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY, so I may not get a positive reply to my request, if any at all.

**Comment by papjul** [comment]
Open-Meteo sends us the following dailys:

2023-10-26 00:00
2023-10-27 00:00
2023-10-28 00:00
2023-10-28 23:00
2023-10-29 23:00
and so on

In database, timezone is Europe/Paris, so it should apply the DST after 2023-10-28 02:00. To be investigated, especially why other sources are unaffected.

**Comment by fuzzmz** [comment]
Has also been reported upstream in https://github.com/open-meteo/open-meteo/issues/488

**Comment by papjul** [comment]
I didn't report it upstream, because I was unsure if it's an upstream bug. In theory, 2023-10-29 is without DST, so with the "Europe/Paris" timezone info, app should be able to apply UTC+2 before 2023-10-29, and UTC+1 after.

**Comment by papjul** [comment]
Reading details on issue opened upstream, I can confirm this is an issue on Open-Meteo side.

**Comment by papjul** [comment]
A workaround will be available from next version.
