### ISSUE TITLE
Add support for timezones on Gadgetbridge

### ISSUE THREAD

**Issue by rany2** [breezy-weather/breezy-weather#544]
### Steps to reproduce

1. Enable GadgetBridge communication in Breezy Weather
2. Notice that weather data on watch is off by current timezone offset

### Expected behavior

I believe that Breezy Weather has an error might be sending timestamps with the timezone when it should be in UTC.

### Actual behavior

Time data on watch is off by the current timezone offset. So if on GMT+2, the data on the watch will be that time plus 2 hours.

### Weather source used

Any

### Breezy Weather version

4.6.10-beta

### Android version

Android 14

### Device

Pixel 6

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I read the [Frequently Asked Questions](https://github.com/breezy-weather/breezy-weather/blob/main/HELP.md) document and followed instructions if relevant.
- [X] I have updated the app to **[version 4.6.10 or later](https://github.com/breezy-weather/breezy-weather/releases/latest)**.
- [X] I wrote my request in English, and any screenshot I attached are also in English (language can be changed from Settings > Appearance), unless my issue only happens with a specific language
- [X] I understand that this app is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY, so I may not get a positive reply to my request, if any at all.

**Comment by papjul** [comment]
A timestamp is universal, it doesn't hold a timezone. Anywhere in the world, right now, we have the same timestamp.

There is no timezone field in the fields expected by Gadgetbridge, so I believe that it's just that Gadgetbridge doesn't handle timezones at the moment.

Tagging @joserebelo for info.

**Comment by joserebelo** [comment]
Yup, timestamps are always in UTC, there should be no need for a timezone. Please open an issue on Gadgetbridge including your device - it's most likely a device-specific bug.

**Comment by rany2** [comment]
@joserebelo I suspected that the timestamp that is sent by Breezy Weather is not in UTC. That was what I meant as I don't have this issue with other providers.

**Comment by joserebelo** [comment]
Timestamps do not have a timezone by definition (they are the number of seconds / milliseconds since January 1st, 1970 at 00:00 UTC). However, if you see a different behavior with other providers, that is not expected. Could you still confirm what's your device?

**Comment by rany2** [comment]
Closing, I think it might have been receiving the old good data from the Zepp app when I tested. Maybe Weather Notification does not set the sunrise/sunset causing the old good data to show. I'll make a new issue in GadgetBridge now with more details.

After retesting with Quick Weather this time, seems like this isn't an issue with Breezy Weather at all.
