### ISSUE TITLE
Translations doesn't always work

### ISSUE THREAD

**Issue by Mr-Bajs** [breezy-weather/breezy-weather#545]
### Steps to reproduce

Some translations doesn't seam to always translate, but fallback to english. I have System language set to english but have BreezyWeather set to Swedish in the app.
Some strings and widget doen't seam to translate to my app set language. 

Examples:
Is says untranslated "_44 min .ago_" in the upper right corner but some times is translates fine.

The weekly widget sometime doesn't translate "_Mon, Tue, Wen, Thu,_" etc, this updates to the right language when you open app through the widget.

### Weather source used

OpenWeather & Open-Meteo

### Breezy Weather version

4.6.10-beta

### Android version

Android 14 / GrapheneOS

### Device

Google Pixel Tablet

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I read the [Frequently Asked Questions](https://github.com/breezy-weather/breezy-weather/blob/main/HELP.md) document and followed instructions if relevant.
- [X] I have updated the app to **[version 4.6.10 or later](https://github.com/breezy-weather/breezy-weather/releases/latest)**.
- [X] I wrote my request in English, and any screenshot I attached are also in English (language can be changed from Settings > Appearance), unless my issue only happens with a specific language
- [X] I understand that this app is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY, so I may not get a positive reply to my request, if any at all.

**Comment by papjul** [comment]
Is this a duplicate of #326? Basically, if you force close the app after changing language, and reopen, it works fine?
