### ISSUE TITLE
Integration with Smartspacer

### ISSUE THREAD

**Issue by SABRE1982** [breezy-weather/breezy-weather#546]
### Describe your idea

Integration with Smartspacer (https://github.com/KieronQuinn/Smartspacer) would allow Breezy Weather to be used inside of the At A Glance smartspace (Pixel devices) and the widget (all other devices). This would allow people to use the (subjectively) useful functionality of At A Glance alongside the excellent Breezy Weather app, without sacrificing more screen real estate. 

### Other details

https://github.com/KieronQuinn/Smartspacer

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] My idea is not related to a question covered in the [Frequently Asked Questions](https://github.com/breezy-weather/breezy-weather/blob/main/HELP.md) document, or a feature described in the [Homepage](https://github.com/breezy-weather/breezy-weather/blob/main/docs/HOMEPAGE.md) document.
- [X] I have updated the app to **[version 4.6.10 or later](https://github.com/breezy-weather/breezy-weather/releases/latest)**.
- [X] I understand that this app is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY, so I may not get a positive reply to my request, if any at all.

**Comment by pacjo** [comment]
Shameless self promotion: https://github.com/pacjo/SmartspacerPlugins

**Comment by papjul** [comment]
@SABRE1982 does it fit your need?
