### ISSUE TITLE
Android: Failed to find current location

### ISSUE THREAD

**Issue by Zhoneym** [breezy-weather/breezy-weather#549]
### Steps to reproduce

![Screenshot_20231103-151033_Breezy Weather](https://github.com/breezy-weather/breezy-weather/assets/140673973/36d6c097-6e7a-4bb6-a1e5-6936ffb91eb6)

### Expected behavior

Succeed to find current location 

### Actual behavior

Android: Failed to find current location

### Weather source used

中国

### Breezy Weather version

4.6.10-beta

### Android version

Android 13 LineageOS 20 20231028

### Device

essential ph-1（mata）

### Other details

![Screenshot_20231103-151033_Breezy Weather](https://github.com/breezy-weather/breezy-weather/assets/140673973/5bd88f84-e83e-45a6-a044-7afb6dced656)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I read the [Frequently Asked Questions](https://github.com/breezy-weather/breezy-weather/blob/main/HELP.md) document and followed instructions if relevant.
- [X] I have updated the app to **[version 4.6.10 or later](https://github.com/breezy-weather/breezy-weather/releases/latest)**.
- [X] I wrote my request in English, and any screenshot I attached are also in English (language can be changed from Settings > Appearance), unless my issue only happens with a specific language
- [X] I understand that this app is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY, so I may not get a positive reply to my request, if any at all.

**Comment by papjul** [comment]
Tap the "Help" button and follow all steps
