### ISSUE TITLE
The weather condition text is still Chinese when system language is English

### ISSUE THREAD

**Issue by Gluneklairo** [breezy-weather/breezy-weather#554]
### Steps to reproduce

When location is in China, the weather condition text is Chinese. 
When location is in US and Japan, the text is English.
![Screenshot_20231106-150109_Breezy Weather](https://github.com/breezy-weather/breezy-weather/assets/65527723/515ff6e5-acc7-4510-8be1-05b5c89695a5)

### Expected behavior

The weather condition text should be in English. 

### Actual behavior

The weather condition text is Chinese while the other part of the app is English. 

### Weather source used

AccuWeather

### Breezy Weather version

4.6.10-beta

### Android version

Android 13

### Device

OnePlus 8T

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I read the [Frequently Asked Questions](https://github.com/breezy-weather/breezy-weather/blob/main/HELP.md) document and followed instructions if relevant.
- [X] I have updated the app to **[version 4.6.10 or later](https://github.com/breezy-weather/breezy-weather/releases/latest)**.
- [X] I wrote my request in English, and any screenshot I attached are also in English (language can be changed from Settings > Appearance), unless my issue only happens with a specific language
- [X] I understand that this app is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY, so I may not get a positive reply to my request, if any at all.

**Comment by papjul** [comment]
I cannot reproduce. When adding Beijing, weather condition is in French (which is my language) with AccuWeather source. Please delete the location and re-add, making sure you use AccuWeather.

**Comment by Gluneklairo** [comment]
> I cannot reproduce. When adding Beijing, weather condition is in French (which is my language) with AccuWeather source. Please delete the location and re-add, making sure you use AccuWeather.

Oh it works LOL, so it will just fetch the language which matches the location for the first time I guess.

**Comment by papjul** [comment]
Not really, but if you changed language, you will need to refresh the weather to get updated texts.

If it was already updated less than 5 minutes before changing languages, you may need to wait to avoid caching issues.

**Comment by papjul** [comment]
> If it was already updated less than 5 minutes before changing language, you may need to wait to avoid caching issues.

Was fixed in v4.6.11
