### ISSUE TITLE
Met Eireann

### ISSUE THREAD

**Issue by Feakster** [breezy-weather/breezy-weather#555]
### Link to publicly available documentation of the API

https://data.gov.ie/dataset/met-eireann-weather-forecast-api

### Available and not available data

Full documentation available here:
https://data.gov.ie/dataset/met-eireann-weather-forecast-api/resource/027da6d5-d819-48d1-9b16-331dba169bd1

For each timestep of the API there are two distinct forecast blocks:

### Timing:

It displays the forecast time “from” and “to”; for Harmonie as data is outputted in 1 hour intervals the “from” and “to” times are the same.

```xml
<time datatype="forecast" from="2019-03-07T17:00:00Z" to="2019-03-07T17:00:00Z">
```

### Location:

It displays the “altitude” (m), “latitude” and “longitude” values of the location.

```xml
<location altitude="9" latitude="54.7211" longitude="-8.7237">
```

### Temperature:

The air temperature 2m above the ground is given in degrees Celsius.

```xml
<temperature id="TTT" unit="celsius" value="7.6"/>
```

### Wind Direction and speed:

The direction of the wind is given in degrees from 0 to 360. The cardinal direction is also given i.e. southwest SW.

```xml
<windDirection id="dd" deg="353.1" name="N"/>
```

The wind speed is given in metres per second and in the Beaufort scale. The SI unit for wind speed is m/s. In order to convert to km/h the value must be multiplied by 3.6. Interestingly, some Norwegian text is still in the output file e.g. Lett bris is light breeze in English!

```xml
<windSpeed id="ff" mps="4.6" beaufort="3" name="Lett bris"/>
```

### Humidity:

Relative humidity has a maximum value of 100 percent.

```xml
<humidity value="74.7" unit="percent"/>
```

### Pressure:

Pressure is given in units of hPa.

```xml
<pressure id="pr" unit="hPa" value="1002.0"/>
```

### Cloud:

There is a general level of cloudiness called NN, with a maximum of 100. Then there are three types of cloud cover, Low, Medium and High; again they will have a maximum of 100. See here for further details. https://cloudatlas.wmo.int/clouds-definitions.html

```xml
<cloudiness id="NN" percent="62.1"/>
<lowClouds id="LOW" percent="62.1"/>
<mediumClouds id="MEDIUM" percent="0.0"/>
<highClouds id="HIGH" percent="0.0"/>
```

### Dewpoint temperature:

This is the temperature at which the air would become saturated. If it equals the actual temperature (TTT) we have 100% humidity so rain, mist, fog or low cloud.

```xml
<dewpointTemperature id="TD" unit="celsius" value="3.3"/>
</location>
</time>
```

---

## 2.5.2 Forecast Block B

The second block in the file is related to rainfall accumulations and weather symbol. It is important to note that precipitation and the appropriate weather symbol e.g. ’Cloudy’ are computed for a period of time.
Note that rainfall accumulations for different time periods are not directly comparable.  For example, the rainfall accumulation for a 6-hour period should be divided by the number of hours before comparing it with a 1-hour accumulation.  This can give rise to incorrect impressions when graphing output.

### Timing:

It displays the forecast time “from” and “to”. Two distinct times are required to calculate the accumulated rainfall. For Harmonie, as data is outputted in 1 hour intervals the “from” and “to” times will differ by one hour as you can see in this example.

```xml
<time datatype="forecast" from="2019-03-07T16:00:00Z" to="2019-03-07T17:00:00Z">
```

### Location:

It displays the “altitude”, “latitude” and “longitude” values of the location.

```xml
<location altitude="9" latitude="54.7211" longitude="-8.7237">
```

### Precipitation unit:

Rain will be output in millimetres (mm).
The minvalue, value and maxvalue values are derived from statistical analysis of the forecast, and refer to the lower (20th percentile), middle (60th percentile) and higher (80th percentile) expected amount.  If minvalue and maxvalue are not output, value is the basic forecast amount.

```xml
<precipitation unit="mm" value="0.0" minvalue="0.0" maxvalue="0.1"/>
```

### Weather symbol:
The WDB computes the weather symbol for this period of time. In this case the main weather feature is cloud. This corresponds to number 4 in their list of weather symbols. 

```xml
<symbol id="PartlyCloud" number="3"/>
```

The weather symbol is derived from a combination of temperature, humidity, cloud cover, precipitation.

```xml
</location>
</time>
```

The forecast blocks A and B will be repeated up to 54 times from the start of forecast until the Harmonie forecast is exhausted. At this point there will be a change over to the ECMWF model. The only difference will be that the data will be output in 1/3/6 hour intervals. This will continue up to 10 days from the start date of the forecast. As there is potential for the data intervals to vary both in number returned and, in future, in the size of the interval, your application should take account of the intervals returned in the xml.

### Are you going to develop yourself the new source for the app?

I have no knowledge of the languages used to create the app. I can work with XML in R if that's any use.

### Give a bit more details or context about this source

Since moving to Ireland I have found that none of the existing sources are particularly accurate in describing the current weather or predicting the future weather.

### Acknowledgements

- [X] This source has a free-tier available (no mandatory credit card info and trials don’t count as “free”), and if it is a main weather source, it includes free hourly forecast
- [X] If this is a weather source request, I checked that endpoints are by coordinates, or that there is a reverse geocoding endpoint.
- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written the name of the source as the title of this issue.
- [X] I have updated the app to **[version 4.6.10 or later](https://github.com/breezy-weather/breezy-weather/releases/latest)** and this source is not part of it.
- [X] I understand that this app is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY, so I may not get a positive reply to my request, if any at all.

**Comment by papjul** [comment]
Will require adding `kotlinx-serialization-xml` as a dependency (we don't have any XML source at the moment).

Guide to implement a new source: https://github.com/breezy-weather/breezy-weather/blob/main/CONTRIBUTE.md
