### ISSUE TITLE
[AccuWeather] Weather refresh sometimes fail

### ISSUE THREAD

**Issue by asfhyb** [breezy-weather/breezy-weather#557]
![Screenshot_20231109-142507](https://github.com/breezy-weather/breezy-weather/assets/117192153/6d0cb09a-a929-49b8-b9f6-2ded3a00db74)
### Steps to reproduce

update manually or automatically 

### Expected behavior

weather should refresh 

### Actual behavior

weather refresh failed 

### Weather source used

ACCUWEATHER

### Breezy Weather version

4.6.11-beta

### Android version

android 12

### Device

inifinix note 12

### Other details

this problem occurs yesterday until now 

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I read the [Frequently Asked Questions](https://github.com/breezy-weather/breezy-weather/blob/main/HELP.md) document and followed instructions if relevant.
- [X] I have updated the app to **[version 4.6.11 or later](https://github.com/breezy-weather/breezy-weather/releases/latest)**.
- [X] I wrote my request in English, and any screenshot I attached are also in English (language can be changed from Settings > Appearance), unless my issue only happens with a specific language
- [X] I understand that this app is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY, so I may not get a positive reply to my request, if any at all.

**Comment by papjul** [comment]
More details please:
- A reproducible location (not necessarily yours, but maybe one in the same province, for example)
- A screenshot in English of the error
- Your crash log (Settings > Debug)

Thanks!

**Comment by asfhyb** [comment]
--------- beginning of main
11-09 14:24:47.366 23471 23471 E g.breezyweathe: Not starting debugger since process cannot load the jdwp agent.
11-09 14:24:47.582 23471 23500 E QT      : [QT]file does not exist
11-09 14:24:47.742 23471 23498 E OpenGLRenderer: Device claims wide gamut support, cannot find matching config, error = EGL_SUCCESS
11-09 14:24:47.981 23471 23498 E OpenGLRenderer: fbcNotifyFrameComplete error: undefined symbol: fbcNotifyFrameComplete
11-09 14:24:47.981 23471 23498 E OpenGLRenderer: fbcNotifyNoRender error: undefined symbol: fbcNotifyNoRender
App version: 4.6.11-beta (standard, 40611
Android version: 12 (SDK 31)
Android build ID: X663-H6915ABCEFGHIO-S-GL-230918V670
Device brand: Infinix
Device manufacturer: INFINIX MOBILITY LIMITED
Device name: Infinix-X663
Device model: Infinix X663
Device product name: X663-GL

**Comment by asfhyb** [comment]
![breezy weather.txt](https://github.com/breezy-weather/breezy-weather/files/13304773/breezy.weather.txt)

@papjul

**Comment by papjul** [comment]
I need all of them

**Comment by papjul** [comment]
Seems like there is an error 400 returned by AccuWeather when using a language different than English.

Can you confirm you can refresh with language set as English (UK)?

**Comment by asfhyb** [comment]
![breezy weather.txt](https://github.com/breezy-weather/breezy-weather/files/13304773/breezy.weather.txt)

@papjul

**Comment by asfhyb** [comment]
@papjul ![breezyweather.txt](https://github.com/breezy-weather/breezy-weather/files/13305132/breezyweather.txt)

its happened again

**Comment by papjul** [comment]
Logs will not be helpful here unfortunately, the issue is on AccuWeather issue.

You can use a different source for the time being, and retry in a few days.

**Comment by asfhyb** [comment]
thanks for help @papjul

**Comment by papjul** [comment]
I can't seem to reproduce now, looks like it has been fixed, can you retry?

**Comment by asfhyb** [comment]
@papjul it's ok now everything works fine thanks

**Comment by asfhyb** [comment]
i will report if this happens again @papjul
