### ISSUE TITLE
How To Change Temperature Unit To Calcius? 

### ISSUE THREAD

**Issue by Killerxdplayz** [breezy-weather/breezy-weather#558]
### Steps to reproduce

Cant change Unit

### Expected behavior

Unit should be Changed

### Actual behavior

I Want To Change Farenhite To Celcius

### Weather source used

Accuweather

### Breezy Weather version

Letest 

### Android version

Android 6

### Device

Galaxy J7

### Other details

Need To Change 

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I read the [Frequently Asked Questions](https://github.com/breezy-weather/breezy-weather/blob/main/HELP.md) document and followed instructions if relevant.
- [X] I have updated the app to **[version 4.6.11 or later](https://github.com/breezy-weather/breezy-weather/releases/latest)**.
- [X] I wrote my request in English, and any screenshot I attached are also in English (language can be changed from Settings > Appearance), unless my issue only happens with a specific language
- [X] I understand that this app is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY, so I may not get a positive reply to my request, if any at all.

**Comment by pdpapper** [comment]
The option is availabke under Settings (gear icon) > Appearance > Units
