### ISSUE TITLE
Animation settings: change of settings requires app restart

### ISSUE THREAD

**Issue by min7-i** [breezy-weather/breezy-weather#56]
### Steps to reproduce

1. Open the settings.
2. Open the appearance settings.
3. Change the background animation from enabled to disabled.
4. Go back to the main screen.
5. The forms from the animation are still visible, but the background is not animated anymore.
6. Restart the app.
7. Now the monocolored background is shown.
(I actually like the frozen background from step 5 more than the monocolored background 😁)

This behavior is similar for the gravity sensor setting. Both disabling and enabling it requires an app restart.

I don't know if this also affects the other two animation settings "list animation" and "item animation" because I've no idea what those settings do.

### Expected behavior

The changed settings should be applied directly without an app restart or at least there should be a toast asking to restart the app, similar to the one shown when changing the app language in the settings.

### Actual behavior

The changed settings aren't applied without a restart which makes it seem as if they don't have any effect.

### Weather provider used

not relevant

### Breezy Weather version

4.0.0-alpha

### Android version

Android 13 (GrapheneOS)

### Device

Google Pixel 6a

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to **[latest version](https://github.com/breezy-weather/breezy-weather/releases/latest)**.

**Comment by papjul** [comment]
> I don't know if this also affects the other two animation settings "list animation" and "item animation" because I've no idea what those settings do.

They don't require restart. List animation is the animation of cards as you scroll, and item animation are little elements such as moon and sun on its arc. Settings will be reworked and a rewording will be done where required.
