### ISSUE TITLE
[AccuWeather] No weather alerts in Alaska

### ISSUE THREAD

**Issue by mattvchandler** [breezy-weather/breezy-weather#562]
### Steps to reproduce

1. Weather service issues an alert
2. Alert appears in geometric weather
3. Alert does not appear in breezy weather

### Expected behavior

Alerts should appear and create a notification when issued

### Actual behavior

No alert was issued and there was a surprise (to me) snow storm

### Weather source used

AccuWeather

### Breezy Weather version

4.6.11-beta

### Android version

Android 13 (lineageOS 20)

### Device

Motorola MotoG7

### Other details

Regression from geometric weather. I have not received a single weather alert in the months that I've used breezy, while my other device has received several from geometric

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I read the [Frequently Asked Questions](https://github.com/breezy-weather/breezy-weather/blob/main/HELP.md) document and followed instructions if relevant.
- [X] I have updated the app to **[version 4.6.11 or later](https://github.com/breezy-weather/breezy-weather/releases/latest)**.
- [X] I wrote my request in English, and any screenshot I attached are also in English (language can be changed from Settings > Appearance), unless my issue only happens with a specific language
- [X] I understand that this app is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY, so I may not get a positive reply to my request, if any at all.

**Comment by papjul** [comment]
Can you give an example of city in which you have alerts in Geometric Weather and not in Breezy Weather?

**Comment by mattvchandler** [comment]
[Fairbanks, Alaska](https://www.accuweather.com/en/us/fairbanks/99701/weather-forecast/346836)

The alert from this morning seems to have ended already.

**Comment by papjul** [comment]
If the issue is that past alerts are no longer shown in Breezy Weather, it's a new intended behavior. I also no longer show future alerts on main screen (but you can access them by tapping on main screen).

If the issue is that background refreshes are not working (and thus, not sending notifications), I refer you to Settings > Background updates to make sure they are enabled at a reasonable interval, and you followed troubleshooting steps.

If that still doesn't help, I let you give me an example of location.

**Comment by mattvchandler** [comment]
It wasn't a past alert, and I don't think it's a notification or background issue. I've had both apps open at the same time and geometric will show the alert on the top card, but breezy doesn't.

If I get some free time, I'll try to find another city that's got an active alert and see how that shows up in each app, and if we get another alert here I'll ping this issue. We usually have air quality alerts through most of the winter

**Comment by mattvchandler** [comment]
I found one - Utqiagvik, AK

This is the current status in geometric. Note the high surf advisory

![sketch-1699940014426](https://github.com/breezy-weather/breezy-weather/assets/1538163/42c96ae2-20b2-40c3-80aa-5f87cf044405)

And here's the same in breezy:

![sketch-1699940015095](https://github.com/breezy-weather/breezy-weather/assets/1538163/69e703ef-bf4c-4b86-b2fb-5dc7ec4f79ea)

**Comment by papjul** [comment]
Usually, this kind of alert is not valid for the whole town, but only for the coast.

In Geometric Weather, we would take all alerts emitted for all parts of the town, sometimes resulting in known duplicate alert notifications, which we no longer have now. In Breezy Weather, we show alerts for the specific longitude and latitude, which for a big city, is arbitrarily in the middle of the town.

If you do care about flood alerts, I would recommand either searching for a more specific neighborhood, or switch to "current location". Or you can wait for #10 which will allow to specify a specific point on the map, but it might not be before sone time.

**Comment by papjul** [comment]
I just checked, and there is nothing wrong on app side. AccuWeather returns no alert for 71.29138,-156.79465. It does for other places known for having alerts.

You say this is a very small town, that may be true, but from what I can see by playing with spoofed locations around, it seems to cover a rather large area from AccuWeather side. Just having a very small portion of this area covered by an alert is enough to trigger an alert for the whole town, on Geometric Weather side.

I'm not going to spend more time troubleshooting flood alerts, they are known to be unpredictable with AccuWeather and obscure as to how they are computed, and everything is matching data given by the source. If you have other type of alerts, I can analyze them, but chances are high that it will also be matching source data.

My suggestion is to switch to a different secondary source for alerts at the bottom of the location, if AccuWeather is an unreliable source for you.

**Comment by mattvchandler** [comment]
Here's a special weather statement from NOAA that's currently active for my actual area. 
[](https://www.accuweather.com/en/us/fairbanks/99701/weather-warnings/346836?alertId=2606575&areaId=fairbanks-metro-area)
The statement is issued for the whole Tanana valley, so my location is definitely impacted. No indication of the alert is present in breezy, but geometric reported it.

I'd really like to use breezy over geometric since geometric is no longer developed, but these alerts are important, so I can't uninstall it yet

**Comment by papjul** [comment]
Please follow my suggestions.

I just tried right now and taking a random point in Fairbanks, I can confirm AccuWeather doesn't return any alert.

However, I'm not sure if I take a correct point as the alert is only valid for "Fairbanks Metro Area" and I'm not sure where this area is located exactly.
See: https://alerts.weather.gov/cap/ak.php?x=1

**Comment by mattvchandler** [comment]
https://forecast.weather.gov/MapClick.php?zoneid=AKZ844 has a map of the Fairbanks Metro Area. It encompasses the whole of the city of Fairbanks, and the other nearby towns. I'm definitely in that area, and the alert should have applied to my location. I got the predicted snow to show for it.

The snow alert is over now, but this morning I was able to see it on the accuweather page (which is https://www.accuweather.com/en/us/fairbanks/99701/weather-forecast/346836) and in the accuweather android app for my area, as well their page for several other locations around here. The snow alert was issued for the entire valley, which is an area on the order of 100000 km². You should have seen it for any point you picked.

My only guess is that it is something to do with how breezy is calling the accuweather API. Clearly accuweather's service is showing an alert on their own tools for my area. Perhaps it is because all of the alerts I've noticed so far are not considered severe?

If you're still interested in debugging this, there's currently an air quality alert set to go through Sunday afternoon here: https://www.accuweather.com/en/us/fairbanks/99701/weather-warnings/346836?alertId=2606630&areaId=fairbanks-metro-area

**Comment by papjul** [comment]
> My only guess is that it is something to do with how breezy is calling the accuweather API.

> In Geometric Weather, we would take all alerts emitted for all parts of the town, sometimes resulting in known duplicate alert notifications, which we no longer have now. In Breezy Weather, we show alerts for the specific longitude and latitude, which for a big city, is arbitrarily in the middle of the town.


> Clearly accuweather's service is showing an alert on their own tools for my area.

Probably because they show you alerts for the city, and not for your lon/lat. I have no idea why this issue only happens in Alaska, we make absolutely no difference in how we call this endpoint in Alaska or other places in the world.

You can "fake" your current position with a mock app to Marseille, France right now and you will definitely see an alert, so it's an issue on AccuWeather API (not the same as website).

**Comment by papjul** [comment]
Starting from next version, you will be able to add NWS either as your main weather source or as a secondary source for alerts. Hopefully, this should be a more reliable source for alerts than AccuWeather.

**Comment by mattvchandler** [comment]
I've been using this app again in anticipation of the NWS source being added (which is a welcome feature - thanks!), and somehow the weather alerts are working now with accuweather. I'm not sure what's changed. I'm on v4.6.14-beta of the app now, so maybe something was fixed since v4.6.11-beta, or maybe something changed on the accuweather side.

Either way, this problem appears to be resolved, so I'll close the issue.

**Comment by papjul** [comment]
Absolutely nothing changed on that matter on Breezy Weather side. We still use the same endpoint that returned 0 alerts back then. I'm glad it works for you now! :)
