### ISSUE TITLE
Apply graphcast AI tech. (as a weather source) in the future 

### ISSUE THREAD

**Issue by pein0saga** [breezy-weather/breezy-weather#575]
### Describe your idea

I think this google-deepmind can improve this APP

GraphCast: Learning skillful medium-range global weather forecasting

[google-deepmind/graphcast](https://github.com/google-deepmind/graphcast)
https://github.com/google-deepmind/graphcast

### Other details

[[2212.12794] GraphCast: Learning skillful medium-range global weather forecasting](https://arxiv.org/abs/2212.12794)
https://arxiv.org/abs/2212.12794

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] My idea is not related to a question covered in the [Frequently Asked Questions](https://github.com/breezy-weather/breezy-weather/blob/main/HELP.md) document, or a feature described in the [Homepage](https://github.com/breezy-weather/breezy-weather/blob/main/docs/HOMEPAGE.md) document.
- [X] I have updated the app to **[version 4.6.11 or later](https://github.com/breezy-weather/breezy-weather/releases/latest)**.
- [X] I understand that this app is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY, so I may not get a positive reply to my request, if any at all.

**Comment by papjul** [comment]
Please create an issue with the "New source" template
