### ISSUE TITLE
Graphcast: a deep learning-based system developed by Google Deepmind

### ISSUE THREAD

**Issue by pein0saga** [breezy-weather/breezy-weather#576]
### Link to publicly available documentation of the API

https://github.com/google-deepmind/graphcast

### Available and not available data

Graphcast:
Upper-air fields are z (geopotential), q (specific humidity), t (temperature), u (U component of wind), v (V component of wind), w (vertical wind component) on the following pressure levels: 1000hPa, 925hPa, 850hPa, 700hPa, 600hPa, 500hPa, 400hP, 300hPa, 250hPa, 200hPa, 150hPa, 100hPa and 50hPa

The single-level fields are msl (mean sea level pressure), 10u (10 metre U wind component), 10v (10 metre U wind component), and 2t (2 metre temperature). 

### Are you going to develop yourself the new source for the app?

No

### Give a bit more details or context about this source

https://github.com/ecmwf-lab/ai-models-graphcast
https://github.com/google-deepmind/graphcast

google-deepmind/graphcast

[2212.12794] GraphCast: Learning skillful medium-range global weather forecasting
https://arxiv.org/abs/2212.12794

https://charts.ecmwf.int/products/graphcast_medium-mslp-wind850?base_time=202311270000&projection=opencharts_europe&valid_time=202311270600

https://www.ecmwf.int/en/forecasts/dataset/machine-learning-model-data

### Acknowledgements

- [X] This source has a free-tier available (no mandatory credit card info and trials don’t count as “free”), and if it is a main weather source, it includes free hourly forecast
- [X] If this is a weather source request, I checked that endpoints are by coordinates, or that there is a reverse geocoding endpoint.
- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written the name of the source as the title of this issue.
- [X] I have updated the app to **[version 4.6.11 or later](https://github.com/breezy-weather/breezy-weather/releases/latest)** and this source is not part of it.
- [X] I understand that this app is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY, so I may not get a positive reply to my request, if any at all.

**Comment by papjul** [comment]
> [X] If this is a weather source request, I checked that endpoints are by coordinates, or that there is a reverse geocoding endpoint.

Link to documentation of API endpoints please?
