### ISSUE TITLE
Scroll stutters on devices with 90+ Hz

### ISSUE THREAD

**Issue by foxjaw** [breezy-weather/breezy-weather#588]
### Steps to reproduce

Easy. Just scroll the main page top & bottom

### Expected behavior

Not expecting any framedrops.

### Actual behavior

Framedrops occur

### Weather source used

AccuWeather

### Breezy Weather version

4.6.11-beta

### Android version

Android 14

### Device

Pixel 7

### Other details

I did see couple of issues on stutters. But those didn't help. And maintainer locked them.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I read the [Frequently Asked Questions](https://github.com/breezy-weather/breezy-weather/blob/main/HELP.md) document and followed instructions if relevant.
- [X] I have updated the app to **[version 4.6.12 or later](https://github.com/breezy-weather/breezy-weather/releases/latest)**.
- [X] I wrote my request in English, and any screenshot I attached are also in English (language can be changed from Settings > Appearance), unless my issue only happens with a specific language
- [X] I understand that this app is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY, so I may not get a positive reply to my request, if any at all.

**Comment by papjul** [comment]
> The device is 90Hz where framedrops are very much visible compared to scrolling elsewhere.

Can you make a record?
When was the app installed?
