### ISSUE TITLE
provide option to disable Gyroscopic animations

### ISSUE THREAD

**Issue by foxjaw** [breezy-weather/breezy-weather#589]
### Describe your idea

Gyrocope animations could be very distracting to some users. So provide a toggle to disable those moving backgrounds.

### Other details

Disabling the sensor usage might reduce framedrops & improve performance.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] My idea is not related to a question covered in the [Frequently Asked Questions](https://github.com/breezy-weather/breezy-weather/blob/main/HELP.md) document, or a feature described in the [Homepage](https://github.com/breezy-weather/breezy-weather/blob/main/docs/HOMEPAGE.md) document.
- [X] I have updated the app to **[version 4.6.12 or later](https://github.com/breezy-weather/breezy-weather/releases/latest)**.
- [X] I understand that this app is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY, so I may not get a positive reply to my request, if any at all.

**Comment by papjul** [comment]
You can turn off animations of main screen, including gravity sensor from Settings > Main screen
