### ISSUE TITLE
weatherbit

### ISSUE THREAD

**Issue by Hare89** [breezy-weather/breezy-weather#59]
### Describe your suggested feature

Is there posibility of adding new providers in future like weatherbit and here.com

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to **[latest version](https://github.com/breezy-weather/breezy-weather/releases/latest)**.

**Comment by papjul** [comment]
Yes, there is, please read https://github.com/breezy-weather/breezy-weather/blob/main/CONTRIBUTE.md

I wasn't sure if it was a question or a request, if it is a request, please open a different issue for here.com.

**Comment by papjul** [comment]
I got no reply so I tagged your issue as "Open to contributions" but if you want to work on it, let me know and I will remove it to avoid two persons working on the same provider at the same time.

**Comment by papjul** [comment]
After reviewing this API, we noticed that no hourly forecast was available in the free-tier.

We decided weather sources without a free-tier with hourly forecast didn’t match project criteria for inclusion.

If you want to use your subscription key, you can try this implementation: https://github.com/Cod3dDOT/breezy-weather/tree/weatherbit
However, it was done blindly as we don’t have a subscription and you will need to rebase regularly.
