### ISSUE TITLE
Option to disable notification "update(s) failed"

### ISSUE THREAD

**Issue by GuiSousa135** [breezy-weather/breezy-weather#592]
### Describe your idea

Option to disable the "update(s) failed" notification, this message appears when the location is disabled and the app tries to update the data

### Other details

When the automatic update is on, this ends up bothering the user, so it would be interesting to be able to disable

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] My idea is not related to a question covered in the [Frequently Asked Questions](https://github.com/breezy-weather/breezy-weather/blob/main/HELP.md) document, or a feature described in the [Homepage](https://github.com/breezy-weather/breezy-weather/blob/main/docs/HOMEPAGE.md) document.
- [X] I have updated the app to **[version 4.6.12 or later](https://github.com/breezy-weather/breezy-weather/releases/latest)**.
- [X] I understand that this app is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY, so I may not get a positive reply to my request, if any at all.

**Comment by papjul** [comment]
Just disable the notification channel "Background updates" on Android app settings.
