### ISSUE TITLE
Dark mode doesn't apply to Alerts page

### ISSUE THREAD

**Issue by UjuiUjuMandan** [breezy-weather/breezy-weather#595]
### Steps to reproduce

1. Enable dark mode
2. Received an alert, and open it

### Expected behavior

The background should be dark

### Actual behavior

![photo_2023-12-11_17-54-50](https://github.com/breezy-weather/breezy-weather/assets/125150101/4d83b175-b634-4594-98f8-306173bffcc3)

### Weather source used

中国

### Breezy Weather version

4.6.12-beta

### Android version

Android 14

### Device

Google Pixel 5

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I read the [Frequently Asked Questions](https://github.com/breezy-weather/breezy-weather/blob/main/HELP.md) document and followed instructions if relevant.
- [X] I have updated the app to **[version 4.6.12 or later](https://github.com/breezy-weather/breezy-weather/releases/latest)**.
- [X] I wrote my request in English, and any screenshot I attached are also in English (language can be changed from Settings > Appearance), unless my issue only happens with a specific language
- [X] I understand that this app is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY, so I may not get a positive reply to my request, if any at all.

**Comment by papjul** [comment]
Can you screenshot your Settings > Appearance page?

**Comment by UjuiUjuMandan** [comment]
My bad, I enabled Day / Night mode for locations, which will prefer local sunrise/sunset time whatever system theme is.
