### ISSUE TITLE
An option to remove unneccessary text from the widgets

### ISSUE THREAD

**Issue by ViktorKahu** [breezy-weather/breezy-weather#597]
### Describe your idea

1) Currently, the text in the widgets describes that, what is already evident from the graphics. For example, a picture of the sun, and text underneath saying "Sunny Weather".

I would prefer to just leave the graphic and not have the text doubling up the information.

The text depicting the temperature would need to be centered properly.

Currently the text is not centered, cut off, looks ugly and out of place, doubles up information and generally needs attention.

2) Ability to add the uv index to the information in the widget (next to the temperature or underneath it). In some parts of the world with the hole in the ozone layer right above, its critical information.

3) The correct way do depict decimal points is with a dot, not a comma (eg: 29.2)

Thanks for your time and attention.

### Other details

![Screenshot_20231214-110555~2](https://github.com/breezy-weather/breezy-weather/assets/125934998/aa3c1baf-4bfe-43ea-9cc1-f1e2d1b27d3f)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] My idea is not related to a question covered in the [Frequently Asked Questions](https://github.com/breezy-weather/breezy-weather/blob/main/HELP.md) document, or a feature described in the [Homepage](https://github.com/breezy-weather/breezy-weather/blob/main/docs/HOMEPAGE.md) document.
- [X] I have updated the app to **[version 4.6.12 or later](https://github.com/breezy-weather/breezy-weather/releases/latest)**.
- [X] I understand that this app is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY, so I may not get a positive reply to my request, if any at all.

**Comment by papjul** [comment]
One idea per issue, please.

> The correct way do depict decimal points is with a dot, not a comma (eg: 29.2)

Fractional formatting is provided by the language you use. Switch to English in the settings and it will use a dot.

**Comment by mario-g98** [comment]
In order not to open another issue, may I suggest rounding the degree shown in widgets to a whole number, so that it matches the degree shown when opening the app. Or at least give the option in widget's preferences.

**Comment by papjul** [comment]
One idea per issue, please.
