### ISSUE TITLE
Allergen info doesn't show up no matter what service provider you use

### ISSUE THREAD

**Issue by TheOnlineUser** [breezy-weather/breezy-weather#603]
### Steps to reproduce

1. Enable Settings > Main Screen > Cards > ensure Pollen is selected as an option that'll display
2. Select any source as the Weather Source
3. You won't see any pollen/allergen info on the home screen despite it being enabled. 

I tried this app months ago and it had the same problem then. Nothing has changed. 

### Expected behavior

I should see allergen/pollen information but I don't. 

### Actual behavior

I don't see pollen/allergen details.

### Weather source used

Any

### Breezy Weather version

4.6.12-beta

### Android version

Android 14

### Device

Samsung Galaxy S23 Ultra 

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I read the [Frequently Asked Questions](https://github.com/breezy-weather/breezy-weather/blob/main/HELP.md) document and followed instructions if relevant.
- [X] I have updated the app to **[version 4.6.12 or later](https://github.com/breezy-weather/breezy-weather/releases/latest)**.
- [X] I wrote my request in English, and any screenshot I attached are also in English (language can be changed from Settings > Appearance), unless my issue only happens with a specific language
- [X] I understand that this app is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY, so I may not get a positive reply to my request, if any at all.

**Comment by papjul** [comment]
Pollen info is only supported in North America for AccuWeather, and Europe for Open-Meteo. [See docs](https://github.com/breezy-weather/breezy-weather/blob/main/docs/SOURCES.md).

If you know a source that supports pollen info wherever you live, please let us know.

**Comment by papjul** [comment]
> I live in North America and am using AccuWeather. Any ideas why the app is only showing pollen levels for some areas but not others?

I don't know, what's your area? Is there pollen somewhere right now? It's winter.

**Comment by papjul** [comment]
I do see 0 / m³ for most allergens for this city in Breezy Weather with AccuWeather, with some mold forecast for Dec 25th and Dec 26th.
