### ISSUE TITLE
Immediate crash when opening app for the first time

### ISSUE THREAD

**Issue by Thebear375** [breezy-weather/breezy-weather#604]
### Steps to reproduce

1. Install app
2. Open app
3. App immediately closes

### Expected behavior

App should open and function

### Actual behavior

App doesn't even open.

### Weather source used

None

### Breezy Weather version

Latest beta

### Android version

Android 14

### Device

Google pixel 6 pro

### Other details

Log-
[BreezyWeather2023-12-18-19-30-01.txt](https://github.com/breezy-weather/breezy-weather/files/13709714/BreezyWeather2023-12-18-19-30-01.txt)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I read the [Frequently Asked Questions](https://github.com/breezy-weather/breezy-weather/blob/main/HELP.md) document and followed instructions if relevant.
- [X] I have updated the app to **[version 4.6.12 or later](https://github.com/breezy-weather/breezy-weather/releases/latest)**.
- [X] I wrote my request in English, and any screenshot I attached are also in English (language can be changed from Settings > Appearance), unless my issue only happens with a specific language
- [X] I understand that this app is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY, so I may not get a positive reply to my request, if any at all.

**Comment by papjul** [comment]
1) Was it working with a previous version? If so, when did it stop working?
2) Do you use a custom ROM?
3) I see an error related to colors/theme, did you customize something on your system?

Thanks!

**Comment by Thebear375** [comment]
> 1) Was it working with a previous version? If so, when did it stop working?
> 2) Do you use a custom ROM?
> 3) I see an error related to colors/theme, did you customize something on your system?
> 
> Thanks!

I'm on latest A14 December patch, and I use iconify to change theme colors. I never had a problem until I updated the other day. I rolled back, but that was the same. It probably has something to do with iconify, but what would it matter if I change colors of my device theme? Nothing in the theme changes the name of anything or deletes any resources. I had previous beta working with the theme before updating. I may have had the app going before setting the theme on previous build though. I'll try disabling theme and installing the app before theming again

**Comment by papjul** [comment]
Magisk modules heavily modify how the system works. They can intercept how an Android SDK function is supposed to behave.

According to your crash log, I seem to understand that color of `com.google.android.material.R.attr.colorOnPrimaryContainer` is invalid.

Try disabling all Magisk modules and retry. Let us know of the result ;)
