### ISSUE TITLE
Incorrect Wind threshold line

### ISSUE THREAD

**Issue by eengnr** [breezy-weather/breezy-weather#609]
### Steps to reproduce

Hi, thanks for your app!

Currently it's a little windy here and I noticed that the wind threshold line seems to be odd.

The threshold for wind currently says 5.5 as "Schwacher Wind"/"Gentle breeze" (wind_strength_3). But it should be wind_strength_4 instead, because 4 starts at 5.5 m/s. The text on the right should match the number on the left.

![Screenshot_20231223-093046](https://github.com/breezy-weather/breezy-weather/assets/31403422/90104035-22d4-4e7f-a228-b5fed9162d68)

Even when switching to Bft, I'm not sure if the correct threshold is shown.
![Screenshot_20231223-093523](https://github.com/breezy-weather/breezy-weather/assets/31403422/7cc5ba01-45b9-41f7-b321-233ee2523ed5)
4 Bft is on the 3 Bft threshold line (probably caused by rounding?), but if the threshold in Bft is the same like in m/s, then 5.5 m/s = 4 Bft instead of 3.

### Expected behavior

Threshold should have the correct text and value 🙂

### Actual behavior

Threshold doesn't have the correct text/value

### Weather source used

Open-Meteo

### Breezy Weather version

4.6.12-beta

### Android version

Android 14

### Device

Pixel 7

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I read the [Frequently Asked Questions](https://github.com/breezy-weather/breezy-weather/blob/main/HELP.md) document and followed instructions if relevant.
- [X] I have updated the app to **[version 4.6.12 or later](https://github.com/breezy-weather/breezy-weather/releases/latest)**.
- [X] I wrote my request in English, and any screenshot I attached are also in English (language can be changed from Settings > Appearance), unless my issue only happens with a specific language
- [X] I understand that this app is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY, so I may not get a positive reply to my request, if any at all.

**Comment by papjul** [comment]
All threshold lines in app are based on the upper limit of the "category". Up to 5.5 m/s is Gentle breeze. Everything 5.5 m/s and above is no longer Gentle breeze.

Taking another example with air quality: with your logic, threshold for good air quality would be on y=0 on the y axis. While air quality index is still good between 0 and 20, not only at 0.
