### ISSUE TITLE
Here.com

### ISSUE THREAD

**Issue by Hare89** [breezy-weather/breezy-weather#61]
### Describe your suggested feature

If there is possibility of adding this provider it seems more accurate in some conditions than others...

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to **[latest version](https://github.com/breezy-weather/breezy-weather/releases/latest)**.

**Comment by papjul** [comment]
I got no reply so I tagged your issue as "Open to contributions" but if you want to work on it, let me know and I will remove it to avoid two persons working on the same provider at the same time.

**Comment by Cod3dDOT** [comment]
Key takeaways after working on this yesterday:

Here.com destination weather api has 2 major versions: v1 and v3. It seems that v1 is locked behind an enterprise subscription, while v3 is available on a free base plan, but the differences are minimal.

v3 features:
Available: Current weather, hourly forecast, 7 day forecast, astrology, precipitation, wind, alerts*, NWS alerts*, reverse geocoding.
Not available: air quality, alerts*

*About alerts:
There are 2 endpoints: `/report` and `/alerts`.
`/report`  includes some limited form of alerts and NWS alerts.
`/alerts` endpoint is not available on base plan (access denied with my api key), but the format seems much nicer.

**Comment by Cod3dDOT** [comment]
> Thank you, should I remove the "Open to contributions" if you are working on it?
> Yep, but see below
> I think we should support both. On AccuWeather, depending on the type of key, I use a more precise endpoint for air quality, for example.
> Agree. However, I am afraid I will not be able to get my hands on an enterprice key. I will try my best to add support for it though.

Currently, during testing with a base plan, some data seems missing or requires some post-processing. In particular, the api spec says that daily forecasts with seperated times of day and simple daily forecasts should report same data, but uvIndex and temperature/high temp/low temp are not present in both. Total preciptation over a time span is not reported at all.

There are several issues to fix, but will probably create a draft PR this weekend and see where to go from there.

**Comment by papjul** [comment]
> > I think we should support both. On AccuWeather, depending on the type of key, I use a more precise endpoint for air quality, for example.
> 
> Agree. However, I am afraid I will not be able to get my hands on an enterprice key. I will try my best to add support for it though.

Don’t worry, leave it like that, avoid making it broken for enterprise users ;)

> Currently, during testing with a base plan, some data seems missing or requires extensive post-processing. In particular, the api spec says that forecasts with separated times of day and simple daily forecasts should report the same data, but uvIndex and temp/high temp/low temp values are not present in both. Total precipitation is not reported at all.

First, I would add a popular city in United States to ensure it’s correctly supported by their models.

Then, I wouldn’t worry about missing data, especially in daily. It’s a know fact that Geometric Weather was made with daytime/nighttime in mind. If your API doesn’t report total precipitation for daytime/nighttime separately, don’t worry, it will automatically be completed with hourly data. Same thing with temperature. FYI, MET.no has no daily AT ALL. Everything is created from hourly.

We only support total precipitati

**Comment by papjul** [comment]
Implemented in 7e1028da13bd494e2166f74e5c8019d3fe5048e0
