### ISSUE TITLE
Rankine Temperature Scale

### ISSUE THREAD

**Issue by spitfire94** [breezy-weather/breezy-weather#610]
### Describe your idea

If the *Kelvin* scale is to be supported, so should the *[Rankine](https://en.wikipedia.org/wiki/Rankine_scale)* scale. 

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] My idea is not related to a question covered in the [Frequently Asked Questions](https://github.com/breezy-weather/breezy-weather/blob/main/HELP.md) document, or a feature described in the [Homepage](https://github.com/breezy-weather/breezy-weather/blob/main/docs/HOMEPAGE.md) document.
- [X] I have updated the app to **[version 4.6.12 or later](https://github.com/breezy-weather/breezy-weather/releases/latest)**.
- [X] I understand that this app is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY, so I may not get a positive reply to my request, if any at all.

**Comment by papjul** [comment]
> If the _Kelvin_ scale is to be supported, so should the _[Rankine](https://en.wikipedia.org/wiki/Rankine_scale)_ scale.

Why not, but what about Delisle, Newton, Réaumur and Rømer scales?

What's your use case in the context of weather? I never saw someone using it in Kelvin, even less in Rankine.
