### ISSUE TITLE
Widget data not getting updated (except time)

### ISSUE THREAD

**Issue by andrei-cb** [breezy-weather/breezy-weather#613]
### Steps to reproduce

Create the widget during the night, observe it during the day.

How widget looks on screen:
![IMG_20231230_094141](https://github.com/breezy-weather/breezy-weather/assets/5099150/d88b1a3a-4417-4551-944f-6fd234cd4bba)

How it looks in the preview:
![IMG_20231230_094116](https://github.com/breezy-weather/breezy-weather/assets/5099150/7f700a0c-7084-4d4c-95ac-a1483562e0c5)

### Expected behavior

Widget icons and temperature should get updated 

### Actual behavior

Widget icons and temperature are not getting updated.

### Weather source used

AccuWeather

### Breezy Weather version

4.16.12-beta

### Android version

Android 13

### Device

Xiaomi 12

### Other details

xiaomi.eu Rom, Miui 14

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I read the [Frequently Asked Questions](https://github.com/breezy-weather/breezy-weather/blob/main/HELP.md) document and followed instructions if relevant.
- [X] I have updated the app to **[version 4.6.12 or later](https://github.com/breezy-weather/breezy-weather/releases/latest)**.
- [X] I wrote my request in English, and any screenshot I attached are also in English (language can be changed from Settings > Appearance), unless my issue only happens with a specific language
- [X] I understand that this app is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY, so I may not get a positive reply to my request, if any at all.

**Comment by andrei-cb** [comment]
Widgets from other weather apps, for example Weather M8 (which is no longer available on play store) were refreshing just fine.

**Comment by papjul** [comment]
I can't reproduce your issue with the same widget.

> * [x]  I read the [Frequently Asked Questions](https://github.com/breezy-weather/breezy-weather/blob/main/HELP.md) document and followed instructions if relevant.

Do you confirm you followed BEFORE the issue was reproduced? If so, can you give more details about how the app is set up right now? A few screenshots would be appreciated as well.

**Comment by andrei-cb** [comment]
Yes, I did check the FAQ.  I don't get any errors and the values are updating fine within the app. Background updates, battery optimizations, etc, shouldn't matter since the widget remains stuck after I manually open the app and update the weather too.


https://github.com/breezy-weather/breezy-weather/assets/5099150/e88d8edb-c909-4d0d-a036-47a8f0ba2ebd
![1703933272673](https://github.com/breezy-weather/breezy-weather/assets/5099150/ef8ade44-eb5a-42d1-a048-a70aded8a843)
![1703933272668](https://github.com/breezy-weather/breezy-weather/assets/5099150/5e09c644-b4d5-4575-b541-9efd0baf4105)
![1703933272665](https://github.com/breezy-weather/breezy-weather/assets/5099150/17639892-408e-415f-8f5a-50982f1ffc57)

**Comment by papjul** [comment]
Does it update if you go to your location list, switch your first location and second location, then switch back? (Add a second location if necessary, for the purpose of the test)

**Comment by andrei-cb** [comment]
It stays the same, doesn't get updated. If I go to "Widgets & Live wallpaper" >"Clock + Daily + Weekly" (widgets in use) the data looks fine, but it remains the same on my home screen.

**Comment by papjul** [comment]
We have no refresh trigger on app side when wallpaper is changed. If it works after the wallpaper is changed and it doesn't update when you change your first location, it's almost certain it is a problem with your homescreen app. Try a different one maybe? Although the cause might be at a higher level (MIUI).

**Comment by andrei-cb** [comment]
I doubt it's an issue with the home screen app if other widgets, including third party widgets are working fine? Maybe Breezy needs additional support for MIUI?

**Comment by papjul** [comment]
I'm not aware of a MIUI-specific method to refresh widgets and I can't add support for exotic behaviors not reproducible on a standard Android phone.

A quick search on Google suggests to change Battery saver to "Ultra" then switch back to "No restriction". Worth trying.

**Comment by andrei-cb** [comment]
It was an issue with the software. Got a new system update today and the issue was resolved. Thanks for the help with troubleshooting this.
