### ISSUE TITLE
Integration of other weather service providers

### ISSUE THREAD

**Issue by koxaman** [breezy-weather/breezy-weather#619]
### Describe your idea

I have a weather station whose data I want to display. You can use it to register / submit data to two publicly available service providers:

- Wunderground https://www.wunderground.com/wundermap / https://www.wunderground.com/dashboard/pws/INRAI1
- Weathercloud https://app.weathercloud.net/map / https://app.weathercloud.net/d9790356487#current

Is it possible for any of these to be included in the application as an optional service provider? To see my own external temperament

Thanks in advance :)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] My idea is not related to a question covered in the [Frequently Asked Questions](https://github.com/breezy-weather/breezy-weather/blob/main/HELP.md) document, or a feature described in the [Homepage](https://github.com/breezy-weather/breezy-weather/blob/main/docs/HOMEPAGE.md) document.
- [X] I have updated the app to **[version 4.6.13 or later](https://github.com/breezy-weather/breezy-weather/releases/latest)**.
- [X] I understand that this app is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY, so I may not get a positive reply to my request, if any at all.

**Comment by papjul** [comment]
Please create an issue using the "New source" template
