### ISSUE TITLE
Weird looking monochrome icon

### ISSUE THREAD

**Issue by tsiflimagas** [breezy-weather/breezy-weather#62]
### Steps to reproduce

1. Install the app
2. Enable monochrome icons in system settings (Android 13)

### Expected behavior

The icon should look like the regular one, just monochrome. 

### Actual behavior

The icon resembles to the regular one, but the figure of the sun in it is distorted. 

### Weather provider used

Any

### Breezy Weather version

4.0.0-alpha_fdroid

### Android version

Android 13

### Device

Xiaomi Redmi note 8

### Other details

![Screenshot_20230622-204654_1](https://github.com/breezy-weather/breezy-weather/assets/45879751/24da4c1a-fe8f-477b-a3d9-54528c4771d2)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to **[latest version](https://github.com/breezy-weather/breezy-weather/releases/latest)**.

**Comment by papjul** [comment]
This should be fixed with d32757e80969d0422157e41f375abf74636adbb1

As I don't have an Android 13 device, I will let you confirm with next release before closing ;)

**Comment by tsiflimagas** [comment]
Yes! I can confirm it's ok now.
![Screenshot_20230624-000344_1](https://github.com/breezy-weather/breezy-weather/assets/45879751/b073788a-51d2-48cf-98ec-2233f5b22a6c)
