### ISSUE TITLE
Support for The Weather Company free personal stations observations

### ISSUE THREAD

**Issue by koxaman** [breezy-weather/breezy-weather#620]
### Link to publicly available documentation of the API

https://github.com/xebia-functional/android-wunderground-client

### Available and not available data

I have a weather station whose data I want to display. You can use it to register / submit data to two publicly available service providers:

    Wunderground https://www.wunderground.com/wundermap / https://www.wunderground.com/dashboard/pws/INRAI1

           info: 
            https://github.com/xebia-functional/android-wunderground-client
            https://github.com/winfred/wunderground
            https://github.com/michaelckelly/wunderground
            https://github.com/leoherzog/WundergroundStationForwarder

    Weathercloud https://app.weathercloud.net/map / https://app.weathercloud.net/d9790356487#current

            info:
            https://github.com/nimarion/WeathercloudScraper

Is it possible for any of these to be included in the application as an optional service provider? To see my own external temperament

Thanks in advance :)

### Are you going to develop yourself the new source for the app?

unfortunately I can't program

### Give a bit more details or context about this source

I can not answer this

### Acknowledgements

- [X] This source has a free-tier available (no mandatory credit card info and trials don’t count as “free”), and if it is a main weather source, it includes free hourly forecast
- [X] If this is a weather source request, I checked that endpoints are by coordinates, or that there is a reverse geocoding endpoint.
- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written the name of the source as the title of this issue.
- [X] I have updated the app to **[version 4.6.13 or later](https://github.com/breezy-weather/breezy-weather/releases/latest)** and this source is not part of it.
- [X] I understand that this app is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY, so I may not get a positive reply to my request, if any at all.

**Comment by papjul** [comment]
The documentation you linked is about a library discontinued 10 years ago… did you use this data somewhere else outside this website?

WUnderground doesn't seem to provide any API anymore. If you can find the pricing list with a free-tier, please link it here.

**Comment by koxaman** [comment]
I have indicated several sources in the description. Did you look at those too, can't they be used either?

Because I wasn't only thinking about wunderground, but also about weathercloud.

**Comment by papjul** [comment]
I'm looking for "Link to publicly available documentation of the API", you only sent link to HTML page of your station and libraries.

We can't use libraries, we need data in either JSON or XML format, with documentation.

Please open a different issue if you need support for another source than Wunderground (one source per issue).

But " Wunderground API" and "Weathercloud API" keywords show no positive result on Google, so unless I missed something, I think it's not possible?

Additionally, Breezy Weather is mainly a forecast app. If you only have current conditions, and no hourly/daily forecast, this can't be implemented as the app would look very empty without forecast.

**Comment by cloneofghosts** [comment]
I believe he is looking for The Weather Company PWS API which does still exist and the endpoints can be found [here](https://docs.google.com/document/d/1eKCnKXI9xnoMGRRzOL1xPCBihNV2rOet08qpE_gArAY/edit). Just looking at the available API endpoints it doesn't offer any hourly forecasts or conditions outside what is offered by the PWS weather station.

I know that The Weather Company does offer daily/hourly/currently APIs but from what I can tell they don't seem to be available for free. People have found the API key that TWC used on their websites and have accessed the site that way but I'm not sure if you would be willing to use that key for this project.

**Comment by koxaman** [comment]
Unfortunately, I couldn't find any other source. But as it was written before me and there is truth in it. This site only provides current and historical data. No prediction. Thus, it would be difficult to mix the data with predictive service.

**Comment by papjul** [comment]
> I believe he is looking for The Weather Company PWS API which does still exist and the endpoints can be found [here](https://www.ibm.com/docs/en/environmental-intel-suite?topic=apis-pws-observations-current-conditions).

Currently, we don't provide ability to mix observations from one source with forecast from another source.

If we add this possibility, two questions:
1) is there a "search for closest station by longitude/latitude" endpoint? From what I can see in docs, it seems you need to provide an ID of station, but app cannot magically guess it.
2) if so, are these endpoints available with the free API key?

**Comment by papjul** [comment]
> > 2. if so, are these endpoints available with the free API key?
> 
> Here is a [list of APIs](https://docs.google.com/document/d/1eKCnKXI9xnoMGRRzOL1xPCBihNV2rOet08qpE_gArAY/edit) that are available to users with a PWS station. Looks like searching by lat/long is included with the free API.

Just to be sure: is this a publicly free API or a privately free API for contributors?

**Comment by cloneofghosts** [comment]
Those API endpoints are only available to people who have a weather station contribute data to Wunderground. As I stated in a previous comment that people have found the API key used on the Wunderground website and use that to query the API. I figure that's probably not a route you would want to take.

**Comment by papjul** [comment]
Legal aspects aside, relying on an API key that is not ours and could stop working any time would frustrate all users once it is implemented and suddenly no longer works, and no user (except a few contributors) is able to subscribe to get a free key.
