### ISSUE TITLE
Add location name to daily forecast notification title 

### ISSUE THREAD

**Issue by bush911** [breezy-weather/breezy-weather#623]
### Describe your idea

- When several locations enabled, it is necessary to known which location notification is showing up.
- Also any chance to add precipitation probability to widgets  please!

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] My idea is not related to a question covered in the [Frequently Asked Questions](https://github.com/breezy-weather/breezy-weather/blob/main/HELP.md) document, or a feature described in the [Homepage](https://github.com/breezy-weather/breezy-weather/blob/main/docs/HOMEPAGE.md) document.
- [X] I have updated the app to **[version 4.6.14 or later](https://github.com/breezy-weather/breezy-weather/releases/latest)**.
- [X] I understand that this app is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY, so I may not get a positive reply to my request, if any at all.

**Comment by papjul** [comment]
One idea per issue please!

Notification-widget always work with your first location in your location list, unless you set it up for multiple locations, in that case location name is present.

Precipitation probability is available in widgets as custom subtitle.

**Comment by bush911** [comment]
> One idea per issue please!
> 
> Notification-widget always work with your first location in your location list, unless you set it up for multiple locations, in that case location name is present.
> 
> Precipitation probability is available in widgets as custom subtitle.

Thank you. I just found the custom subtitle in  “daily + weekly " widget. I previously tried to find in "clock + daily+ weekly " widget.
Please forgive my ignorance 😁
