### ISSUE TITLE
Daily high/low displaying improperly with MET Norway

### ISSUE THREAD

**Issue by Para-lyzed** [breezy-weather/breezy-weather#629]
### Steps to reproduce

1. Set location in Breezy Weather to Tacoma, WA, USA (Pierce County)
2. Set weather provider to MET Norway
3. View daily weather graph
4. Check yr.no, the official consumer facing weather provider using MET Norway's data
5. See discrepancy in daily high/lows
6. Potentially see a daily low that is *higher* than a daily high

### Expected behavior

Data should match what is shown on yr.no (perhaps the API reports the wrong data, but this is quite strange). Daily lows should NEVER display above daily highs.

### Actual behavior

Data does not match that of yr.no, which uses MET Norway data. Daily lows sometimes appear higher than daily highs.

### Weather source used

MET Norway

### Breezy Weather version

4.6.14-beta

### Android version

Android 13

### Device

OnePlus 7 Pro

### Other details

I am attaching images to describe the problem. These screenshots were all taken at about the same time.

What I see on my home town (more prominent than the Tacoma example, but I'm not comfortable sharing it):

![Screenshot_20240112-161515_Breezy Weather](https://github.com/breezy-weather/breezy-weather/assets/73729354/94be2507-773a-4dd1-985f-edc2ed5e1c3e)

What I see with the Tacoma example:

![Screenshot_20240112-163110_Breezy Weather](https://github.com/breezy-weather/breezy-weather/assets/73729354/3a7d6997-b102-4b01-ac31-881ae83c3906)

Data from yr.no (the official weather provider for MET Norway's data):

![Screenshot_20240112-162241_Cromite](https://github.com/breezy-weather/breezy-weather/assets/73729354/00f09e48-d83c-46c6-97bf-68260c444731)

The provider setting for both my home town and Tacoma:

![Screenshot_20240112-162315_Breezy Weather](https://github.com/breezy-weather/breezy-weather/assets/73729354/61ed32dd-7439-415d-a07a-8be4039f96d9)

The highs and lows are not the same between yr.no and Breezy Weather, despite using the same provider. Additionally, the graph of daily lows and highs occasionally places a daily low above a daily high, as illustrated in the screenshots. This is very strange behavior, and I don't know if it is an issue with MET Norway's API, or with Breezy Weather. I don't know how to use their API to check the data.

EDIT: Found another example with Oslo, Norway:

![Screenshot_20240112-164729_Breezy Weather](https://github.com/breezy-weather/breezy-weather/assets/73729354/bdd2e1c2-e992-4527-8257-3347f2004934)

![Screenshot_20240112-164927_Cromite](https://github.com/breezy-weather/breezy-weather/assets/73729354/be58cb68-a91a-4cd3-84ba-3017a4fdc6e4)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I read the [Frequently Asked Questions](https://github.com/breezy-weather/breezy-weather/blob/main/HELP.md) document and followed instructions if relevant.
- [X] I have updated the app to **[version 4.6.14 or later](https://github.com/breezy-weather/breezy-weather/releases/latest)**.
- [X] I wrote my request in English, and any screenshot I attached are also in English (language can be changed from Settings > Appearance), unless my issue only happens with a specific language
- [X] I understand that this app is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY, so I may not get a positive reply to my request, if any at all.

**Comment by papjul** [comment]
We don't have high/low for the whole day (00:00 to 23:59), especially with MET.no which only report hourly forecast.

As you can see with the weather icons or if you tap on a day to access more details, we split a day into two moments: daytime and (over)nighttime.

You can read more in documentation here: https://github.com/breezy-weather/breezy-weather/blob/main/docs/HOMEPAGE.md#daily-forecast

You can match each daytime and nighttime with their hourly forecast counterpart to check there is no discrepancy.

So yes, technically, especially in your country, it's possible to have a hotter overnight than day.

I let you close the issue if it's all good for you?

**Comment by Para-lyzed** [comment]
I see, that makes sense then. I'll go ahead and close the issue. I mistakenly thought that the daily temp graphs were daily high/lows, but since that is not the case, there should be no issue.
