### ISSUE TITLE
Live wallpaper settings don't open

### ISSUE THREAD

**Issue by NBA613** [breezy-weather/breezy-weather#63]
### Steps to reproduce

Tap Live wallpaper option in settings
Notification says "Unable to start live wallpaper preview context"

### Expected behavior

Should open Wallpaper preview and options to edit and save.

### Actual behavior

Shows this:

![Screenshot_20230623-133401](https://github.com/breezy-weather/breezy-weather/assets/110447969/6d4d5945-887b-4353-8f38-856028a52335)

### Weather provider used

Any

### Breezy Weather version

4.0.0-Alpha

### Android version

Android 13

### Device

Pixel 6 Pro

### Other details

- Issue I opened last August for Geometric Weather - https://github.com/WangDaYeeeeee/GeometricWeather/issues/406
- Live wallpaper can be selected from Pixel wallpaper settings

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to **[latest version](https://github.com/breezy-weather/breezy-weather/releases/latest)**.

**Comment by papjul** [comment]
Do you also have this issue with Geometric Weather?

**Comment by NBA613** [comment]
Yes. I attached a link to the issue I opened there as well.
