### ISSUE TITLE
Persistent notification doesn't work and can be deleted even with persistent option enabled

### ISSUE THREAD

**Issue by pokemaster974** [breezy-weather/breezy-weather#634]
### Steps to reproduce

1. Install Breezy Weather
2. Go to options, then Widgets & Live wallpaper
3. Enable the "Persistent" option
![Screenshot_20240120-153242_Breezy Weather](https://github.com/breezy-weather/breezy-weather/assets/28442699/c93dd8da-3b7b-400e-b275-181f2a9a03cc)
5. Swipe the notification to the right

### Expected behavior

Notification is expected to be persistent.

### Actual behavior

Notification is swiped and deleted.
Before the swipe :
![Screenshot_20240120-153257_Breezy Weather](https://github.com/breezy-weather/breezy-weather/assets/28442699/f98f86e5-74a9-427e-a4dc-8e9a63bb3f4e)

After the swipe :
![Screenshot_20240120-153320_Breezy Weather](https://github.com/breezy-weather/breezy-weather/assets/28442699/6136a903-3b4a-405b-b9cd-ff1494123f08)

### Weather source used

AccuWeather

### Breezy Weather version

4.6.14-beta

### Android version

Android 14

### Device

Xiaomi Mi 9

### Other details

It _could_ be an issue with the Android 14 because notifications were persistent with GW on Android 12. Switched to BW after upgrading my smartphone to a more recent Android 14 ROM.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I read the [Frequently Asked Questions](https://github.com/breezy-weather/breezy-weather/blob/main/HELP.md) document and followed instructions if relevant.
- [X] I have updated the app to **[version 4.6.14 or later](https://github.com/breezy-weather/breezy-weather/releases/latest)**.
- [X] I wrote my request in English, and any screenshot I attached are also in English (language can be changed from Settings > Appearance), unless my issue only happens with a specific language
- [X] I understand that this app is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY, so I may not get a positive reply to my request, if any at all.

**Comment by papjul** [comment]
> It could be an issue with the Android 14 because notifications were persistent with GW on Android 12. Switched to BW after upgrading my smartphone to a more recent Android 14 ROM.

Starting from Android 14, behavior of persistent notifications changed: now, they can be cleared, but they will stay sticky if you tap the “Clear all” button.

Note that in my experience, if you clear the notification, it should come back very soon again in the notification bar, so it should not be a problem.

**Comment by pokemaster974** [comment]
> > It could be an issue with the Android 14 because notifications were persistent with GW on Android 12. Switched to BW after upgrading my smartphone to a more recent Android 14 ROM.
> 
> Starting from Android 14, behavior of persistent notifications changed: now, they can be cleared, but they will stay sticky if you tap the “Clear all” button.
> 
> Note that in my experience, if you clear the notification, it should come back very soon again in the notification bar, so it should not be a problem.

Thanks for the clarification. Is there a solution to make no sound when the notification comes back after a swipe ? I saw that I can mark it as silent, but it won't be anymore on top of the other notifications.

**Comment by papjul** [comment]
Go to app settings on Android side (not in app), go to Notifications, tap the "Widget" notification channel, and make it silent
