### ISSUE TITLE
Air Quality Index error

### ISSUE THREAD

**Issue by BakedCrossiant** [breezy-weather/breezy-weather#636]
### Steps to reproduce

Use application normally

### Expected behavior

Air quality should be classed as "Excellent"
![Screenshot_20240121-182521](https://github.com/breezy-weather/breezy-weather/assets/10992590/4a50e445-d2e4-420f-87d6-6e4c8f700c4e)

### Actual behavior

Air Quality is classed as "Fair"
![Screenshot_20240121-182416](https://github.com/breezy-weather/breezy-weather/assets/10992590/59ac0950-fd96-4042-b089-fd26ea265e66)

### Weather source used

AccuWeather

### Breezy Weather version

4.6.13-beta

### Android version

Android 14

### Device

Google Pixel 6

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I read the [Frequently Asked Questions](https://github.com/breezy-weather/breezy-weather/blob/main/HELP.md) document and followed instructions if relevant.
- [X] I have updated the app to **[version 4.6.14 or later](https://github.com/breezy-weather/breezy-weather/releases/latest)**.
- [X] I wrote my request in English, and any screenshot I attached are also in English (language can be changed from Settings > Appearance), unless my issue only happens with a specific language
- [X] I understand that this app is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY, so I may not get a positive reply to my request, if any at all.

**Comment by papjul** [comment]
20 is the beginning of the "Fair" scale.
AQI is calculated for each pollutant, then we take the highest AQI of all pollutants.
In your case, the highest AQI is from PM2.5.
As you can see in your screenshot, PM2.5 has an AQI of 20 with a Fair label.
I don't know if 20 should fall into the Excellent or Fair category, as it is unclear in the specifications, but the behavior is consistent on Breezy Weather while it's not on AccuWeather side as we can see from your screenshot (sometimes 20 is labelled "Excellent", sometimes " Fair").
Additionally, having the upper category starting at the first value included is consistent with other scales we use (such as Beaufort wind scale) so I'm not willing to fix a minor detail that might not even an error in the first place.
