### ISSUE TITLE
Add the option to launch the clock when touching the hour in the widget to bring all the options and not only the alarm

### ISSUE THREAD

**Issue by hnavia** [breezy-weather/breezy-weather#648]
### Describe your idea

Back in the day, when using Geometric Weather, if I touched the hour in the widget, the regular clock screen opened showing all the different configurations/options like:

- Alarm
- World Clock
- Chronometer
- Timer

In Breezy Weather, if I touch the time (hour) in the widget, I only get the alarm screen.

This is a bit annoying if I want to use the chronometer or the timer as I need to actually search for the regular clock app.

### Other details

Mobile device: Samsung S23 Ultra
Android Version: 14

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] My idea is not related to a question covered in the [Frequently Asked Questions](https://github.com/breezy-weather/breezy-weather/blob/main/HELP.md) document, or a feature described in the [Homepage](https://github.com/breezy-weather/breezy-weather/blob/main/docs/HOMEPAGE.md) document.
- [X] I have updated the app to **[version 4.6.14 or later](https://github.com/breezy-weather/breezy-weather/releases/latest)**.
- [X] I understand that this app is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY, so I may not get a positive reply to my request, if any at all.

**Comment by papjul** [comment]
This is a device-specific issue, or probably Clock-app specific (maybe try installing a different app?), as I don't reproduce.
I'm pretty sure there was no change on this matter since Geometric Weather.
Did you try tapping on Geometric Weather widget from a Samsung S23 Ultra with Android 14?
If you can reproduce in Geometric Weather, you can contact Samsung and let them know you don't like this change. Here is the technical detail to help them troubleshooting: Apps that use an `Intent` of `AlarmClock.ACTION_SHOW_ALARMS` open the Clock app on Alarm tab but without the ability to change to other tabs (World Clock, Chronometer, Timer) [if I understood correctly].

**Comment by papjul** [comment]
Additionally, there is no intent to open the clock. We only have the choice between alarm (what is used by default clock widget and by Breezy Weather) or timers.

**Comment by hnavia** [comment]
Hi,

Thanks for the update. Yeah I thought it could be something like that. I will try to reach out Samsung but probably I won't be able to achieve anything :(.

Would it be possible to add an option that allow us which app to launch when touching the time? Maybe that could work as a workaround?

**Comment by papjul** [comment]
It's not justified for a weather app to request the permission to list all apps installed. If I were to request publication on Google Play Store, I would be denied.

Additionally, it would be very technical for an user to customize this, as they would need to tell us which component to start from the selected app.

Finally, that doesn't fit an actual need, no one wants their weather app to open some random other app when tapping the clock.

It's better to ask a billions-dollars company to fix their bugs than ask every app developers to put in place workarounds that bloat the app ;)

**Comment by papjul** [comment]
> I will try to reach out Samsung but probably I won't be able to achieve anything :(.

@hnavia What did Samsung tell you? We get reports from other users, it's very annoying

**Comment by hnavia** [comment]
Hi @papjul I got no answer. I don't think this is something important to them.
