### ISSUE TITLE
[4.7.0] National sources with default search can add incompatible locations from search

### ISSUE THREAD

**Issue by papjul** [breezy-weather/breezy-weather#653]
We didn't have this case before, but 4.7.0 introduces many national sources so we need to handle this.

Basically, national sources usually don't have a location search feature, so we fallback to Open-Meteo search. Unfortunately, this means searching for every cities on this planet, including all of which are not compatible with the national source, resulting in error.

We need to filter results. A filter by one or more country codes should be enough as a beginning. Unfortunately, Open-Meteo doesn't allow to filter by country code, so we need to filter the full result list.

**Comment by bush911** [comment]
I can't wait for this major update, I have been keep checking changelog.md  as well as release section
