### ISSUE TITLE
Wind map

### ISSUE THREAD

**Issue by Enetzlsg** [breezy-weather/breezy-weather#654]
### Describe your idea

Adding a wind map would be awesome in order to get a fast idea of wind direction over the map (check out weawow or iOS weather app, for instance). 

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] My idea is not related to a question covered in the [Frequently Asked Questions](https://github.com/breezy-weather/breezy-weather/blob/main/HELP.md) document, or a feature described in the [Homepage](https://github.com/breezy-weather/breezy-weather/blob/main/docs/HOMEPAGE.md) document.
- [X] I have updated the app to **[version 4.6.14 or later](https://github.com/breezy-weather/breezy-weather/releases/latest)**.
- [X] I understand that this app is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY, so I may not get a positive reply to my request, if any at all.

**Comment by papjul** [comment]
> check out weawow or iOS weather app, for instance

They are not open sources, I can't check what they use as a source.

Can you link a free source from which we can borrow wind map data? Thanks!

(Kinda duplicate with #23)

**Comment by papjul** [comment]
Merging with #23
