### ISSUE TITLE
Weather Update Error Opens .txt file

### ISSUE THREAD

**Issue by Disaster2life** [breezy-weather/breezy-weather#658]
### Steps to reproduce

1. (Not sure how this happened but somehow) Fail to update weather data
2. Get Notification regarding failure to update data
3. Click on notification 

### Expected behavior

I would expect that the app would open and give me a reason and try to update the data again or offer me some more information I could report here regarding the failure to update the data

### Actual behavior

Android offers me a choice in how to open the file, and it opens an error .txt file which contains all the Cities' data that it failed to update in it.

### Weather source used

AccuWeather

### Breezy Weather version

4.6.14-beta

### Android version

Android 13

### Device

OnePlus 9R (Rebadged OnePlus 8T for the Indian Market)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I read the [Frequently Asked Questions](https://github.com/breezy-weather/breezy-weather/blob/main/HELP.md) document and followed instructions if relevant.
- [X] I have updated the app to **[version 4.6.14 or later](https://github.com/breezy-weather/breezy-weather/releases/latest)**.
- [X] I wrote my request in English, and any screenshot I attached are also in English (language can be changed from Settings > Appearance), unless my issue only happens with a specific language
- [X] I understand that this app is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY, so I may not get a positive reply to my request, if any at all.

**Comment by papjul** [comment]
You need to go to Settings > Debug for the full debug message.

Errors in .txt are user-friendly messages.

"Weather data refresh failed" is a generic error message shown when we failed to identify the error that happened (we have about ~15 known types of errors).

**Comment by loucasal** [comment]
It seems that #421 is (part of) what @Disaster2life would expect.

**Comment by Disaster2life** [comment]
Ah, my apologies this is redundant then, did not use those terms to find that existing issue, but yes essentially what that issue suggests, I assumed this was a bug and not intended behaviour, my apologies again.

**Comment by papjul** [comment]
Why was it closed? I was expecting the debug stacktrace to fix your weather data refresh issue.

**Comment by Disaster2life** [comment]
Oh the weather refresh works now, probably didnt work then because I was underground in the metro, the issue was solely about the txt file which I thought was strange.
