### ISSUE TITLE
Add alert color on alert detail page

### ISSUE THREAD

**Issue by Marko-98** [breezy-weather/breezy-weather#661]
### Describe your idea

Hello!

This is my proposal. I think the entire alerts section should be somewhat redesigned. Currently, it's just too bland with no colors whatsoever. It's boring to look at that.

<img src="https://github.com/breezy-weather/breezy-weather/assets/129692860/cc95e454-38dc-4df2-b506-b53aa4aa2082" width=25%> 

&nbsp;
I though we add a little color to it, to grab user's attention. You could add small border around the alert in corresponding color. It would be awesome if you could also change the background of the alert, but, of course, with less opacity for better readability. I was thinking something like this.

<img src="https://github.com/breezy-weather/breezy-weather/assets/129692860/d753abde-555a-412b-b839-aa52defd62ac" width=25%>

&nbsp;
Same goes for the alert part on the main screen; it should change to corresponding color as well, but again, with less opacity for better readability. 
If there are more warnings at the same time, color should be chosen to represent the most dangerous alert.

<img src="https://github.com/breezy-weather/breezy-weather/assets/129692860/94ebdc61-3241-409c-aacd-9f992ca8c114" width=25%>

&nbsp;
Only three colors would be used; 

- yellow – moderate warning
- orange – severe warning
- red – extreme warning

Keep in mind:  these are just sketches of how I would like it to look, made really quick with MS Paint.

Have a nice day!

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] My idea is not related to a question covered in the [Frequently Asked Questions](https://github.com/breezy-weather/breezy-weather/blob/main/HELP.md) document, or a feature described in the [Homepage](https://github.com/breezy-weather/breezy-weather/blob/main/docs/HOMEPAGE.md) document.
- [X] I have updated the app to **[version 4.6.14 or later](https://github.com/breezy-weather/breezy-weather/releases/latest)**.
- [X] I understand that this app is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY, so I may not get a positive reply to my request, if any at all.

**Comment by papjul** [comment]
Regarding color of alerts, we have to respect colors of national meteorological services of respective countries, we can't have purple and blue alerts appearing differently as these colors mean something to people from these countries.

Regarding design, we honor Material Design guidelines, we can't have vibrant colors in the background like this. Basically, we have a primarly (dynamic) and secondary colors + dark/light theme. We do blend alert icon colors on home screen (which are only small touches of colors) to make them less vibrant and have better contrast, but even that is hard to do. For example, yellow still does not have a good contrast and even appear slightly olive. So I let you imagine how hard it would be if we had to put text on top of that.

Best I can suggest is to add the same alert icon from home screen on each alert card on alert detail page.

What do you think?

**Comment by Marko-98** [comment]
> Regarding color of alerts, we have to respect colors of national meteorological services of respective countries, we can't have purple and blue alerts appearing differently as these colors mean something to people from these countries.

That shouldn't be an issue because you're using AccuWeather as source for alerts. They use the same colors in warnings for all countries, if I remember correctly.

> Regarding design, we honor Material Design guidelines, we can't have vibrant colors in the background like this. Basically, we have a primarly (dynamic) and secondary colors + dark/light theme. We do blend alert icon colors on home screen (which are only small touches of colors) to make them less vibrant and have better contrast, but even that is hard to do. For example, yellow still does not have a good contrast and even appear slightly olive. So I let you imagine how hard it would be if we had to put text on top of that.

Would it be possible to do something like this? With text of a different color regarding the warning.
<img src="https://github.com/breezy-weather/breezy-weather/assets/129692860/4939bc24-a651-4be5-8faf-030b12122066" width=50%>

Is yellow then completely out of question? Because I was thinking something like #FBE09F as it's not too vibrant. So it would look like this:
<img src="https://github.com/breezy-weather/breezy-weather/assets/129692860/cad42f42-6b79-4189-bc8a-49fcd316086d" width=50%>

> Best I can suggest is to add the same alert icon from home screen on each alert card on alert detail page.

That would be good as well.

**Comment by Marko-98** [comment]
Thanks for trying though. If that won't work, you can always just add an icon on alerts.

One more question, not regarding alerts. When I set app language to my local one (Croatian), some parts stay on English.

Is it possible to have entire UI in Croatian? Maybe you can implement something when API says _"Partly cloudly"_ that would automatically change it to _"Djelomično oblačno"_?

I'm currently using app on English, but would like to use it in Croatian if it's entirely translated. :)

**Comment by papjul** [comment]
Croatian translation was completed 10 days ago so it will be fully translated for next version, except of course anything that comes untranslated from weather sources. We don't know when API gives us something untranslated. Although you mentioned AccuWeather, they do provide Croatian.

Note: If you just refreshed weather and immediately switched from English to Croatian, you may need to wait a few minutes before refreshing weather data as cached data with English texts will be reused otherwise.

If you would like to contribute to translation in the future, please check: https://hosted.weblate.org/projects/breezy-weather/breezy-weather-android/#information
