### ISSUE TITLE
Round current temperature in widgets to a whole number

### ISSUE THREAD

**Issue by mario-g98** [breezy-weather/breezy-weather#668]
### Describe your idea

The to main points I see in favour of displaying the current temperature in widgets as a whole number are:

-  This will make the widgets UI less cluttered and easer to read the information.
- It will make it coherent to the main app info. Now if the temperature on the widget is with decimal number, when clicked on it the app is opened and a whole number is displayed.

![Screenshot_2024-02-11-09-56-25-42_8b90da7a90336dddbe1fd9fd7538077a_1](https://github.com/breezy-weather/breezy-weather/assets/49582442/cc21d936-8aeb-4491-90f3-862da4f3b346)
![Screenshot_2024-02-11-09-56-12-65_b783bf344239542886fee7b48fa4b892_1](https://github.com/breezy-weather/breezy-weather/assets/49582442/1bc9b452-e635-4d3a-845b-d470de1e601e)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] My idea is not related to a question covered in the [Frequently Asked Questions](https://github.com/breezy-weather/breezy-weather/blob/main/HELP.md) document, or a feature described in the [Homepage](https://github.com/breezy-weather/breezy-weather/blob/main/docs/HOMEPAGE.md) document.
- [X] I have updated the app to **[version 4.6.14 or later](https://github.com/breezy-weather/breezy-weather/releases/latest)**.
- [X] I understand that this app is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY, so I may not get a positive reply to my request, if any at all.

**Comment by papjul** [comment]
Currently, we round the temperature in the following cases:
- Current temperature on home screen, because it is animated, there is a transition between whole numbers. Also, indeed, since it's a very big text, showing 80.5 °F would quickly take a lot of space.
- Temperature charts, because if we take daily temperature chart as an example, adding decimals to the 10 showing temperatures would quickly clutter the interface

In all other cases (widgets, tile, daily details, hourly details, etc), we show it rounded to 1 decimal. Why? Because that's the data from the source, we should avoid "altering" that data, so everywhere where it doesn't cause any clutter or problem with animations, we do it. On widget, it's just one text and a small text, so I don't share your opinion on the cluttering.

Let's take the other side of the chessboard: what would you think if we implemented what you suggest and someone opens an issue saying "now that you rounded the current temperature everywhere, I have no way to get access to the exact measured temperature from the station, I have to go to MySource official website to get the exact value, so please revert"?

**Comment by mario-g98** [comment]
I would like to cite your comment on another issue:

> While it's generally a good idea to only show rounded values in the app (decimals would clutter the interface uselessly as no one makes the difference between 28.6 °C and 29.4 °C), it would be much better to save them in database with decimals included.

In the same spirit, no one makes the difference between 6.5 °C and 7 °C. 

The key words here is "consistency" and "simplicity". You have made such a beautiful UI and I find it very unpleasing to have different current temperatures shown on the widget and on the home screen. Every time I click on the widget and open the app my mind is like "The numbers are different, maybe the app hasn't updated yet.", then I swipe a couple of times until I realize that the numbers are rounded differently.

Also, did someone complain for rounding the numbers on the home screen?

If you think someone will, please just add a checkbox in widgets' preferences.

**Comment by mario-g98** [comment]
Ironically, none of the providers show decimals on their websites:

OpenWeather:
![Screenshot from 2024-02-11 11-36-32](https://github.com/breezy-weather/breezy-weather/assets/49582442/5ad9b72b-7416-4265-b697-1b58eca9239a)

AccuWeather:
![Screenshot from 2024-02-11 11-36-43](https://github.com/breezy-weather/breezy-weather/assets/49582442/bd65958b-44c0-4eaa-99ca-311a9012b510)

Meteofrance:
![Screenshot from 2024-02-11 11-36-59](https://github.com/breezy-weather/breezy-weather/assets/49582442/c80c733b-f6c7-4ac8-b0f3-51b8a828587f)

Met Norway:
![Screenshot from 2024-02-11 11-37-11](https://github.com/breezy-weather/breezy-weather/assets/49582442/49d59b46-067e-4dfa-bfe5-1da02cd00e84)

**Comment by min7-i** [comment]
In general, I'm neutral about this issue, however, after reading papjul's comment, I wondered why the text widget that I'm using isn't showing decimals. Hence, I tested the widgets on my phone and realized that only the **clock + daily (vertical)** widget with the view style set to either **tile** or **vertical** shows the current temperature with decimals. _In Geometric Weather those two view styles don't show any decimal places._

I also checked the code of the widgets and when the `getTemperature` function is used to get the current temperature, it is called with decimals set to zero `getTemperature(context, unit, 0)`. The two view styles mentioned above are the exception:
https://github.com/breezy-weather/breezy-weather/blob/0ad0213abe93628336f70a17c0ec3ac1b85a35ce/app/src/main/java/org/breezyweather/remoteviews/presenters/ClockDayVerticalWidgetIMP.kt#L264-L273

I don't know if this is intential, but looking at it from a consistency point of view, it might not be a bad idea to remove decimals here.

**Comment by papjul** [comment]
Thank you for the time you spent. Then, I will requalify as a bug and take a second look.

**Comment by papjul** [comment]
You were right, that's indeed the only place in widgets where we don't round.
Widgets being in "basic maintenance" mode, I will not think too much about the case, and just make it the same behavior as other widgets.
I will keep the decimals in the system tile though, as I use it and I like it with decimals x)
