### ISSUE TITLE
[MET No] Add support for alerts

### ISSUE THREAD

**Issue by papjul** [breezy-weather/breezy-weather#671]
As a primary and secondary source.

Currently, geojson including polygons is heavily discouraged for production:
https://api.met.no/weatherapi/metalerts/1.1/documentation

In the future, URL would be: `https://api.met.no/weatherapi/metalerts/1.1/.json?lang=no|en&lat,lon=X,Y`

**Comment by wertzuz** [comment]
New Api Version is out:
https://api.met.no/weatherapi/metalerts/2.0/documentation

geojson should be now suitable to add, it's in official beta-status

**Comment by papjul** [comment]
Is available in v5.2.8 (not by default).

Let us know if you notice before us when API is stable, so it becomes the recommended source for alerts for Norway (until then, it will remain AccuWeather).
