### ISSUE TITLE
Different providers for same data in current weather

### ISSUE THREAD

**Issue by itsHenry35** [breezy-weather/breezy-weather#686]
### Describe your idea

Add current weather for a second time in order to compare and decide the weather data from different sources.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] My idea is not related to a question covered in the [Frequently Asked Questions](https://github.com/breezy-weather/breezy-weather/blob/main/HELP.md) document, or a feature described in the [Homepage](https://github.com/breezy-weather/breezy-weather/blob/main/docs/HOMEPAGE.md) document.
- [X] I have updated the app to **[version 4.6.14 or later](https://github.com/breezy-weather/breezy-weather/releases/latest)**.
- [X] I understand that this app is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY, so I may not get a positive reply to my request, if any at all.

**Comment by papjul** [comment]
That would require a whole change of technical design. In the current technical state, there can only be one current location; breaking this unicity would break the app without a major redesign. Additionally, the GPS location is fetched during the weather refresh, and not separately. This means that if we had two (or more) current locations, we would query the GPS twice which is heavily inefficient and may completely break the app as I am not sure you're allowed to do that.

In the end, what you are asking is technically difficult and time-consuming with the current Breezy Weather code.

Fortunately, there are two much easier alternatives to consider:
1) Add your city manually by location search twice: one with the first source you want to try, and one with the second source you want to try. Then when you're done comparing and decided on which source to keep, change the weather source for "current location" and delete the two manually added location.
2) Add your current location with source 1. Write down any data you want to compare. Change current location to use source 2. Compare the data and decide if you want to use source 1 or source 2.
