### ISSUE TITLE
Publish on Google Play Store

### ISSUE THREAD

**Issue by mcandre** [breezy-weather/breezy-weather#690]
### Steps to reproduce

1. Search for Breezy Weather on Google Play Store.

### Expected behavior

The app appears in the app store.

### Actual behavior

App not available in the standard Google Play Store.

### Weather source used

AccuWeather

### Breezy Weather version

4.6.14

### Android version

Android 13

### Device

Google Pixel 6a

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I read the [Frequently Asked Questions](https://github.com/breezy-weather/breezy-weather/blob/main/HELP.md) document and followed instructions if relevant.
- [X] I have updated the app to **[version 4.6.14 or later](https://github.com/breezy-weather/breezy-weather/releases/latest)**.
- [X] I wrote my request in English, and any screenshot I attached are also in English (language can be changed from Settings > Appearance), unless my issue only happens with a specific language
- [X] I understand that this app is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY, so I may not get a positive reply to my request, if any at all.

**Comment by papjul** [comment]
It's not a bug, it's a feature.
