### ISSUE TITLE
Icons in top app bars are hard to see when using monochrome theme

### ISSUE THREAD

**Issue by min7-i** [breezy-weather/breezy-weather#709]
### Steps to reproduce

1. Enable the monochrome theme (not the greyscale accessibility setting!) in Android.
2. Open Breezy Weather.
3. Go to the location management page, the settings screen or the about page.

(The main page and the location search are not affected.)

### Expected behavior

The icons have a color that provides enough contrast to see them on the app bar.

In 4.6.14-beta while using light mode the icons were displayed in black. While using dark mode the icons were displayed in white.

### Actual behavior

When light mode is used the icons are white. While dark mode is used the icons are black. This makes it very hard to see them at all.

### Weather source used

N/A

### Breezy Weather version

5.0.0-alpha

### Android version

Android 14 (GrapheneOS)

### Device

Google Pixel 6a

### Other details

This does not happen in 4.6.14-beta. See comparison below (you might need to turn up your screen brightness to see the icons). You'll notice that the colors of the floating action buttons also changed.

| 4.6.14-beta | 5.0.0-alpha |
| --- | --- |
| ![4 6 14-beta-dark](https://github.com/breezy-weather/breezy-weather/assets/97251923/fb2ef8c9-a3f1-406d-a796-2cae083f98f5) | ![5 0 0-alpha-dark](https://github.com/breezy-weather/breezy-weather/assets/97251923/2e0a4d3a-04e6-43de-b108-ef637eaa3958) |
| ![4 6 14-beta-light](https://github.com/breezy-weather/breezy-weather/assets/97251923/a48de5a1-1bb5-400e-a7fd-72b281647293) | ![5 0 0-alpha-light](https://github.com/breezy-weather/breezy-weather/assets/97251923/8a8ffcdd-f00c-495e-b722-e742cc97a689) |

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I read the [Frequently Asked Questions](https://github.com/breezy-weather/breezy-weather/blob/main/HELP.md) document and followed instructions if relevant.
- [X] I have updated the app to **[version 4.6.14 or later](https://github.com/breezy-weather/breezy-weather/releases/latest)**.
- [X] I wrote my request in English, and any screenshot I attached are also in English (language can be changed from Settings > Appearance), unless my issue only happens with a specific language
- [X] I understand that this app is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY, so I may not get a positive reply to my request, if any at all.

**Comment by papjul** [comment]
>     1. Enable the monochrome theme (not the greyscale accessibility setting!) in Android.

Where do I find this?

**Comment by min7-i** [comment]
On my device it's in settings -> Wallpaper & Style:
<img src="https://github.com/breezy-weather/breezy-weather/assets/97251923/c992cdc9-ad44-43b0-aeb6-8c3c16034a0c" width=50%>

But I don't know if that's a feature which is exclusive to Android 14.

**Comment by papjul** [comment]
Yes, this is possible. I will try to test on an emulator, but that kills my computer resources everytime ^^'

**Comment by min7-i** [comment]
Okay, I think I found the source of the issue. The tint of the icons is currently set to use `MaterialTheme.colorScheme.onPrimaryContainer`. See here for instance:
https://github.com/breezy-weather/breezy-weather/blob/bbd08a7de04e822955346426cb967252e28dbc36/app/src/main/java/org/breezyweather/common/ui/widgets/insets/FitSystemBarComposeWrappers.kt#L98

The color of the container is set to use `MaterialTheme.colorScheme.surface`. So it would make more sense to set the tint to `MaterialTheme.colorScheme.onSurface`.

This fixes the issue with the monochrome theme and also sets the icons to white (or close to white) in dark mode instead of using a color variant of the theme which I always found a bit weird.
