### ISSUE TITLE
Add "feels like" section in the 5 day forecast widget

### ISSUE THREAD

**Issue by popogomo** [breezy-weather/breezy-weather#712]
### Describe your idea

The 5-day forecast widget currently shows Date, City and the current temperature (along with time and the forecast for 5 days). It will be amazing if you also add "Feels Like" temperature underneath the current temperature and above the day forecast (you can probably increase the space a little in between and put it there, or somewhere else in the widget) as suggested in the attached screenshot:

![222](https://github.com/breezy-weather/breezy-weather/assets/118138132/996e72d1-d77e-4f0c-87c8-b11f96166c35)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] My idea is not related to a question covered in the [Frequently Asked Questions](https://github.com/breezy-weather/breezy-weather/blob/main/HELP.md) document, or a feature described in the [Homepage](https://github.com/breezy-weather/breezy-weather/blob/main/docs/HOMEPAGE.md) document.
- [X] I have updated the app to **[version 4.6.14 or later](https://github.com/breezy-weather/breezy-weather/releases/latest)**.
- [X] I understand that this app is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY, so I may not get a positive reply to my request, if any at all.

**Comment by rocex** [comment]
Actually, I'd like to have a widget like this that merges Clock+Daily(Detail) with Clock+Daily+Weekly.

![2024-02-27_172757](https://github.com/breezy-weather/breezy-weather/assets/9346138/c80cd9e0-3e65-4da5-bf04-714050cb5222)


![2024-02-27_173720](https://github.com/breezy-weather/breezy-weather/assets/9346138/6d2839a3-0174-4a19-b971-dafcd863e627)

**Comment by papjul** [comment]
> Actually, I'd like to have a widget like this that merges Clock+Daily(Detail) with Clock+Daily+Weekly.

Please create a different issue, thanks!

**Comment by papjul** [comment]
Moving to #446
