### ISSUE TITLE
Widgets - Visual changes are not applied immediately

### ISSUE THREAD

**Issue by min7-i** [breezy-weather/breezy-weather#714]
### Steps to reproduce

1. Select a new widget to add on your home screen, e.g. the hourly trend widget.
2. In the widget configuration screen, change the background color or any other setting that affects the visual style of the widget.
3. Click on done.

### Expected behavior

The widget's style matches the one shown in the preview of the widget.

<img src="https://github.com/breezy-weather/breezy-weather/assets/97251923/aa873548-dcd4-4bea-a757-77112d579f2c" width=50%>

### Actual behavior

The widget has the default style and all customizations are missing.

![home screen](https://github.com/breezy-weather/breezy-weather/assets/97251923/9a9d43f3-c02b-4a83-b5a5-27467a23e045)

### Weather source used

N/A

### Breezy Weather version

5.0.0-alpha

### Android version

Android 14 (GrapheneOS)

### Device

Google Pixel 6a

### Other details

Pull-to-refresh in Breezy Weather works as a workaround to update the widget on the home screen.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I read the [Frequently Asked Questions](https://github.com/breezy-weather/breezy-weather/blob/main/HELP.md) document and followed instructions if relevant.
- [X] I have updated the app to **[version 4.6.14 or later](https://github.com/breezy-weather/breezy-weather/releases/latest)**.
- [X] I wrote my request in English, and any screenshot I attached are also in English (language can be changed from Settings > Appearance), unless my issue only happens with a specific language
- [X] I understand that this app is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY, so I may not get a positive reply to my request, if any at all.

**Comment by papjul** [comment]
Ah, yes, that famous line of code I thought "Is it actually used?", now I know when it is. Thank you for your report, will look into it!
