### ISSUE TITLE
Some Details Not Displaying In Header

### ISSUE THREAD

**Issue by Hamster45105** [breezy-weather/breezy-weather#715]
### Steps to reproduce

1. Add a lot of details to the header (the amount may vary slightly depending on the phone screen size).
2. Go back to the home screen.
3. You'll see that some details are missing.

For example, in this image I have selected five details for the header and the app is only displaying four:

![image](https://github.com/breezy-weather/breezy-weather/assets/133548095/a33c44ab-ae5a-472c-ad04-fe609a560618)

### Expected behavior

There are a few options here:

1. It should display all five details in one row.
2. There should be a limit to how many details you can add (no more than can fit on the screen).
3. The app displays the details over two rows instead of one.

### Actual behavior

Not all details are displayed.

### Weather source used

Not relevant

### Breezy Weather version

v5.0.1-alpha

### Android version

One UI 6.0 - Android 14

### Device

Samsung Galaxy A54

### Other details

The new header looks really nice, so you should definitely stick with this design!

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I read the [Frequently Asked Questions](https://github.com/breezy-weather/breezy-weather/blob/main/HELP.md) document and followed instructions if relevant.
- [X] I have updated the app to **[version 4.6.14 or later](https://github.com/breezy-weather/breezy-weather/releases/latest)**.
- [X] I wrote my request in English, and any screenshot I attached are also in English (language can be changed from Settings > Appearance), unless my issue only happens with a specific language
- [X] I understand that this app is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY, so I may not get a positive reply to my request, if any at all.

**Comment by Hamster45105** [comment]
Great, thanks for the explanation! This does make sense.

**Comment by amadeuskurisu02** [comment]
"Details" card is bad by design. You need to go to that card. Even if you move it to the top it'll move "Hourly" and "Daily" cards, which are as important to me as details. In the end, you need to perform more moves to see the same info, than before this redesing. It was much better, when all details were displayed in the header.

**Comment by papjul** [comment]
We are probably the only weather app that allow to customize which current details you want to put on top (most apps would probably decide for you 3 elements like Feels like, Wind and Humidity).

No one liked the previous design that was taking too much space. I never saw someone sending me a screenshot where there was more than 4 elements in header with the previous design, many would remove all of them and just let them go to the Details card. But I agree that technically, you were able to add 9 elements, which you probably did.

> Even if you move it to the top it'll move "Hourly" and "Daily" cards, which are as important to me as details.

When you say "details", you really mean all the 9 details available for current? Do you prioritize all 9 details over daily and hourly info? Can’t you just put 4 most important details in header, then the daily card, then the hourly card, and then the details card with less important details?

> It was much better, when all details were displayed in the header.

That seems very contradictory. In the old design, if you put all 9 details in the header, that would take as much space as a full Details card. Now you have 4 or 5 details on a row, and all remaining 4 or 5 on the Details card that you can put on top. This will take as much space as <5.0 way with all 9 details, where each of them would be on one row. And that is if your weather source provides you with all the 9 details, which is only happening during the day (UV index) and only with AccuWeather.

You can check the side-by-side comparison to see there was no loss of space:
<table>
<tr><td>Version 4.6.14</td><td>Version 5.0+</td></tr>
<tr><td>
<img src="https://github.com/breezy-weather/breezy-weather/assets/1449159/5fd5c7b0-1c82-4ccf-8d47-c643dbbf5f35" alt="Version 4.6.14" width="200" />
</td><td>
<img src="https://github.com/breezy-weather/breezy-weather/assets/1449159/a341a4d0-f824-407f-a3d5-14a161c1da74" alt="Version 5.0+" width="200" />
</td></tr>
</table>

For 99% of people satisfied with 4 or 5 details, this will actually reduce A LOT the space used on header to make room for daily and hourly cards.

You can also go the Geometric Weather way, by removing all details and only use the Details card.

**Comment by amadeuskurisu02** [comment]
I was wrong. I'm sorry.
