### ISSUE TITLE
New widget (mix of Clock+Daily(Detail) and Clock+Daily+Weekly)

### ISSUE THREAD

**Issue by rocex** [breezy-weather/breezy-weather#716]
### Describe your idea

In the case of only 3 days of weather, the vacant space is used to display some information of Daily, such as Feels like, Air quality, Update time, wind, humidity, UV intensity, etc.

![2024-02-27_172757](https://github.com/breezy-weather/breezy-weather/assets/9346138/c80cd9e0-3e65-4da5-bf04-714050cb5222)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] My idea is not related to a question covered in the [Frequently Asked Questions](https://github.com/breezy-weather/breezy-weather/blob/main/HELP.md) document, or a feature described in the [Homepage](https://github.com/breezy-weather/breezy-weather/blob/main/docs/HOMEPAGE.md) document.
- [X] I have updated the app to **[version 4.6.14 or later](https://github.com/breezy-weather/breezy-weather/releases/latest)**.
- [X] I understand that this app is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY, so I may not get a positive reply to my request, if any at all.

**Comment by sergio-nsk** [comment]
I want to get 4x1 or 5x1 widget like in M8 - location + current weather and 3+ forecast for coming hours. If I get them, I will switch from using M8 to Breezy-Weather.
![image](https://github.com/breezy-weather/breezy-weather/assets/18064360/81dac6c8-fb40-441c-b808-6c0c07461f01)

**Comment by papjul** [comment]
You're looking for Week widget in 3 days-mode.

**Comment by papjul** [comment]
Moving to #446

**Comment by papjul** [comment]
We won't implement it exactly like that, but the All in one widget from #937 should reach a similar goal. For more detailed conditions, we will also have a dedicated current widget that can be rather small.
