### ISSUE TITLE
Current Weather Text Incorrect using Environment Canada

### ISSUE THREAD

**Issue by cloneofghosts** [breezy-weather/breezy-weather#718]
### Steps to reproduce

When using the Environment Canada weather provider the current weather text doesn't match the one displayed on the Environment Canada website.

This is what Breezy Weather is showing for my location:

<img src="https://github.com/breezy-weather/breezy-weather/assets/10248058/0d4be392-5017-4e15-97a6-4d240da0efa9" width="400px">

This is what Environment Canada is showing for the Ottawa Airport (the station which is used for my location)

![image](https://github.com/breezy-weather/breezy-weather/assets/10248058/90f9f04a-b7fd-41d6-afb5-1a7a0a5d223f)

It seems to me that Breezy Weather is pulling the text from the hourly forecast instead of the current conditions.

### Expected behavior

The current weather text in Breezy Weather and Environment Canada should be the same.

### Actual behavior

The current weather text in Breezy Weather and Environment Canada are different.

### Weather source used

Environment Canada

### Breezy Weather version

5.0.2-alpha

### Android version

Android 14

### Device

Samsung Galaxy A53

### Other details

I wonder if this is anything to do with the fact that some stations don't report any current conditions so it's using the hourly data as a fallback.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I read the [Frequently Asked Questions](https://github.com/breezy-weather/breezy-weather/blob/main/HELP.md) document and followed instructions if relevant.
- [X] I have updated the app to **[version 4.6.14 or later](https://github.com/breezy-weather/breezy-weather/releases/latest)**.
- [X] I wrote my request in English, and any screenshot I attached are also in English (language can be changed from Settings > Appearance), unless my issue only happens with a specific language
- [X] I understand that this app is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY, so I may not get a positive reply to my request, if any at all.

**Comment by papjul** [comment]
We do use observations from the API, however that text you mention is not present in the API, it's only there in hourly forecast.

As we can see from your screenshot, weather icon for current is "partly cloudy", but text is "Sunny". Your analysis is probably right, the text is probably missing, so it's completed from hourly forecast. If that's the case, I will make a condition so that if weather code is not missing, then generate a text from the weather code instead of looking for hourly forecast ;)

**Comment by cloneofghosts** [comment]
It's weird that you mention that the API doesn't offer the current condition text. If I take a look at the Environment Canada data in Today Weather it does show the correct current condition text
![image](https://github.com/breezy-weather/breezy-weather/assets/10248058/c8ae9aac-6ab9-4386-9ba8-dfe7ec603990)

It could be that the API that Today Weather uses is different from the one that Breezy Weather uses. It could be that the one that Breezy Weather uses doesn't offer the text which I would find really strange if that's the case.

**Comment by papjul** [comment]
Thanks for your report!

I fixed the previous issue I told you about, and I actually found the text condition in the API, I just missed it when implementing ECCC, so it will be there in next version ;)

**Comment by cloneofghosts** [comment]
Oh awesome. I'm assuming that for stations which don't report any conditions it still uses hourly data for the icon/text right? If you want I can create a separate issue to discuss how that should be handled.

**Comment by papjul** [comment]
Yes, that's a weather-source independant feature. Do you have an example of a location I can try?

**Comment by cloneofghosts** [comment]
You can test with Kemptville, Ontario. Here's the link to the location on the Environment Canada website if you'd like to compare against https://weather.gc.ca/city/pages/on-74_metric_e.html

**Comment by papjul** [comment]
We do have observation for this location in API. But your link also mentions "Observed at: Kemptville", so maybe not a good example?

**Comment by cloneofghosts** [comment]
The Observed at: Kemptville text is just telling you the name of the station which the conditions were observed at. Underneath that it has text which states Condition: Not observed and there is no condition image above the current temperature.

When you look at a station which does have conditions such as the [Ottawa International Airport](https://weather.gc.ca/city/pages/on-118_metric_e.html) it shows the condition as Light Rain and above the current temperature it shows a rain icon. I included some screenshots to help demonstrate what I'm talking about:

| Kemptville| Ottawa |
| -- | -- |
|  ![image](https://github.com/breezy-weather/breezy-weather/assets/10248058/465d34b0-0b85-4e60-b3f2-a1f2106b47e9) | ![image](https://github.com/breezy-weather/breezy-weather/assets/10248058/540be697-679c-4700-9b01-281ed093a921) |

The Kemptville station reports some conditions but doesn't report the current conditions. For that station does the API return Not observed like the website or does it omit it completely?

**Comment by papjul** [comment]
We have an empty text for condition, but we do have weather icon, temperature, dewpoint, pressure, humidity, wind speed, wind gust

**Comment by cloneofghosts** [comment]
It's weird that you mention that there's a weather icon with no weather text as the station doesn't report any conditions so I would think both would be empty. Out of curiosity what icon is being returned from the API as when I did a quick check of the XML API it was blank as well.

**Comment by papjul** [comment]
Ah yes, you're right, Kemptville has icon `29` which I don't identify as a valid weather icon code, so I fallback to weather code from hourly, which means we show thunderstorms right now.

**Comment by cloneofghosts** [comment]
We might need a separate issue for this but I think in this case it might make more sense to display something like Not Observed or Not Available instead of using the hourly forecast.

I'm not really sure what to do about the background and icon as unlike [Chronus](https://github.com/DvTonder/Sample_icon_set?tab=readme-ov-file#original-yahoo-weather-codes) there isn't a na icon in any of the icon sets.

I had a thought about not having an icon displayed but people would likely get confused as to why there is no icon in the locations list/widgets.

**Comment by papjul** [comment]
Yes, it's a different issue. However, I don't think we can change much. This is a behavior common to all weather sources. It makes sense to use forecast for next hour when we have no observation data, as it is supposed to be accurate in such a short term. And as you said, not fallbacking to hourly would mean we would have no animations which is not a possibility.

Additionally, that's already what weather sources do themselves. For example, Open-Meteo reports "current" data in their API, and it's always based on the short-term forecast, as they have no observation stations data.

**Comment by cloneofghosts** [comment]
I get that falling back to the hourly forecasts probably makes the most sense in this situation. Considering there isn't a Not Available icon for any of the icon sets and introducing one would break compatibility. Today Weather always reports Clear for any stations without observations but for the majority of the time it wouldn't be accurate.

Maybe having a box or something stating that the station reports no observations and the displayed conditions are being pulled in from the hourly details would make sense.

**Comment by papjul** [comment]
> Maybe having a box or something stating that the station reports no observations and the displayed conditions are being pulled in from the hourly details would make sense.

There wouldn't be that disclaimer message on Open-Meteo although it's the same situation

**Comment by cloneofghosts** [comment]
Open-Meteo and PirateWeather in Canada use weather models which update hourly whereas Environment Canada has limited observation data for some locations and only update their forecasts 3 times a day (5 am Eastern, 11 am Eastern and 3:30 pm Eastern)

I guess there's no real solution here then as my suggestions either aren't feasible or you disagree with.
