### ISSUE TITLE
With main source set to Bright Sky no precipitation forecast

### ISSUE THREAD

**Issue by kalktresor** [breezy-weather/breezy-weather#719]
### Steps to reproduce

1. manually add location 
2. set main source to Bright Sky (DWD)
3. set Percipitation minute by minute source to either Open-Meteo or Accuweather
4.  save settings

### Expected behavior

Hourly and daily forecast trends should show precipitation 

### Actual behavior

hourly and daily trends do not show any precipitation forecast.

When i change main source to any other supported source (AccuWeather, Open-Meteo) it is working as expected and does show precipitation forecast.

### Weather source used

Bright Sky

### Breezy Weather version

5.0.2-alpha

### Android version

Android 14

### Device

Redmi Note 10

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I read the [Frequently Asked Questions](https://github.com/breezy-weather/breezy-weather/blob/main/HELP.md) document and followed instructions if relevant.
- [X] I have updated the app to **[version 4.6.14 or later](https://github.com/breezy-weather/breezy-weather/releases/latest)**.
- [X] I wrote my request in English, and any screenshot I attached are also in English (language can be changed from Settings > Appearance), unless my issue only happens with a specific language
- [X] I understand that this app is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY, so I may not get a positive reply to my request, if any at all.

**Comment by papjul** [comment]
Where in Germany can I find precipitation right now?

**Comment by papjul** [comment]
Nevermind, I think there is a misunderstanding of feature. Minutely forecast is different from hourly and daily forecast. You won't find minutely precipitation in hourly and daily.

Bright Sky will provide precipitation for daily and hourly if it's your main source. If there is no Precipitation tab in daily and hourly, it just means Bright Sky told us there will be no precipitation in the next few days (just tried with Hamburg city, the tab does show up).

**Comment by kalktresor** [comment]
Ok, thank you for explanation that it is indeed technically working as intended. 
but from a usability point of view i find it quite confusing it doesn't show the tab in hourly and daily even if there is no precipitation in the next days (why hide the 'good' news? ). i feel it could be mentioned in docs that if no precipitation tab is shown there is actually no precipitation in the next days

**Comment by papjul** [comment]
> i feel it could be mentioned in docs that if no precipitation tab is shown there is actually no precipitation in the next days

It is:
![image](https://github.com/breezy-weather/breezy-weather/assets/1449159/64d12f20-300f-466c-9db5-4f1d05a44ef7)

Not sure why I put it twice though.

Link to doc: https://github.com/breezy-weather/breezy-weather/blob/main/docs/HOMEPAGE.md

> why hide the 'good' news?

To avoid having the interface “bloated” with empty charts. For example, hourly trends can very lengthy, so there is no point having the user scroll horizontally looking for a precipitation, when there will be none across all the hourly forecast length. That way, the tab that is right after Precipitation will be shown right away, and you can get to it quicker ;)
