### ISSUE TITLE
location not updated on graphene os

### ISSUE THREAD

**Issue by trebr63** [breezy-weather/breezy-weather#721]
### Steps to reproduce

the location is never updated  on graphene os without play services 

### Expected behavior

the weather location update working in the background

### Actual behavior

fail to updated location

### Weather source used

accuweather ecccc canada

### Breezy Weather version

5.02 alpha

### Android version

android 14 runnig grapheneos

### Device

pixel8pro

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I read the [Frequently Asked Questions](https://github.com/breezy-weather/breezy-weather/blob/main/HELP.md) document and followed instructions if relevant.
- [X] I have updated the app to **[version 4.6.14 or later](https://github.com/breezy-weather/breezy-weather/releases/latest)**.
- [X] I wrote my request in English, and any screenshot I attached are also in English (language can be changed from Settings > Appearance), unless my issue only happens with a specific language
- [X] I understand that this app is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY, so I may not get a positive reply to my request, if any at all.

**Comment by papjul** [comment]
We do not use Google Play Services in the official releases. If it works when you have Google Play Services but not when you don't have them (I seem to understand that GrapheneOS allows you to turn them off?), it just means that your device failed to find your location with your GPS hardware component. The GPS requires you to be outdoor. If you're not, or if it times out, it will fallback to Google Play Services if you have them. All of this is handled by Android system, not by Breezy Weather. A good thing to try would be to open your maps application and settle your GPS position and then retry in Breezy Weather.

**Comment by trebr63** [comment]
thank you for the explaination  😃
