### ISSUE TITLE
Use system langage to request language of Alerts/Warnings/Watches (Canada)

### ISSUE THREAD

**Issue by gdevenyi** [breezy-weather/breezy-weather#722]
### Describe your idea

I am located in Quebec, due to this, the default weather alerts are provided in french. However, English alerts are available somewhere, as the WeatherCAN app (provided directly by Environment Canada) gives me the alerts in English.

I would like to request that the application interface be used to infer what language the alert be returned in.

I appear to be using the AccuWeather data source, which does provide a language option in its alert API:
https://developer.accuweather.com/accuweather-alerts-api/apis/get/alerts/v1/%7BlocationKey%7D

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] My idea is not related to a question covered in the [Frequently Asked Questions](https://github.com/breezy-weather/breezy-weather/blob/main/HELP.md) document, or a feature described in the [Homepage](https://github.com/breezy-weather/breezy-weather/blob/main/docs/HOMEPAGE.md) document.
- [X] I have updated the app to **[version 4.6.14 or later](https://github.com/breezy-weather/breezy-weather/releases/latest)**.
- [X] I understand that this app is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY, so I may not get a positive reply to my request, if any at all.

**Comment by papjul** [comment]
Salut ! We don't use system language for requests made to AccuWeather, we use the language set in Breezy Weather (although by default this app preference is set to follow system preference).

I seem to understand that you use AccuWeather source, not ECCC, right?

It works on my side:
![Screenshot_20240228-182817_Breezy Weather](https://github.com/breezy-weather/breezy-weather/assets/1449159/16937d70-37c7-4d52-a05f-0046908f4118)
![Screenshot_20240228-182820_Breezy Weather](https://github.com/breezy-weather/breezy-weather/assets/1449159/fabdfb5c-97fe-4634-ba9f-26774b3ce503)

**Comment by gdevenyi** [comment]
> I seem to understand that you use AccuWeather source, not ECCC, right?

Correct. I could find nowhere to change to the "recommended" ECCC.

The issue is while my alert on the main page is in English
![Screenshot_20240228-133838_Breezy Weather.png](https://github.com/breezy-weather/breezy-weather/assets/3001850/686baee7-ba32-4679-846d-9e08acba9ad0)

When I open the alert it is in French
![Screenshot_20240228-133845_Breezy Weather.png](https://github.com/breezy-weather/breezy-weather/assets/3001850/7249b64e-b7f4-4d1b-bf1f-8602ea94cd40)

**Comment by papjul** [comment]
If the title of the alert is in English, but the content in French, it means it successfully requested the weather in English and that AccuWeather doesn't have the English text and only show the French text.

It can be confirmed by going to AccuWeather website in English:
https://www.accuweather.com/en/ca/montreal/h3a/weather-warnings/56186

ECCC support was added from v5.0.0-alpha and above. They show as pre-releases at the moment, except Izzy repo which never take our pre-releases.

**Comment by gdevenyi** [comment]
> ECCC support was added from v5.0.0-alpha and above. 

Ok, seems like the docs need some versioning notes, as when I select "Help me choose" in the app it currently refers to features not available in the main release which is confusing. I'll try out the alpha. Merci!

**Comment by papjul** [comment]
Yes, I know about non-versioned docs issue.

There is usually not a lot of time between each stable versions so it's usually not a problem.

Additionally, V5.0 now auto-suggests the best sources depending on country so that doc becomes less and less relevant, except if you're a nerd like me who wants to know about the nifty details x)

**Comment by gdevenyi** [comment]
Can confirm ECCC source in the alpha release gives me the alerts in my preferred language. Thanks!
