### ISSUE TITLE
Chronus icon set mapping incorrect for some icons

### ISSUE THREAD

**Issue by cloneofghosts** [breezy-weather/breezy-weather#724]
### Steps to reproduce

I've been using my own Chronus icon packs with Breezy Weather and I've noticed that the icon mapping in Chronus for Thunder, Thunderstorm and Haze are off when compared to Breezy Weather.

Below is a comparison of my Google Now Chronus icon set and the default Pixel icon set in Breezy Weather. I've circled the icons which are mapped incorrectly for Chronus.

| Chronus | Breezy Weather |
| --- | --- |
| ![image](https://github.com/breezy-weather/breezy-weather/assets/10248058/395d38e6-4f57-4364-8e3f-2703a2e95d3b) | ![image](https://github.com/breezy-weather/breezy-weather/assets/10248058/f410cd27-38c5-4a96-947f-4c84785c3688)

### Expected behavior

Both icon sets should use similar icons for all conditions.

### Actual behavior

The icon set mapping in Chronus is slightly off when compared to Breezy Weather. 

### Weather source used

All

### Breezy Weather version

5.0.3-alpha

### Android version

Android 14

### Device

Samsung Galaxy A53

### Other details

[Here](https://github.com/DvTonder/Sample_icon_set?tab=readme-ov-file#original-yahoo-weather-codes) is a list of the icons and what they are mapped to in Chronus. My suggestions are Thunderstorms should be mapped to code 4 and Haze mapped to code 21. I'm not sure what the Thunder icon is supposed to represent as I haven't seen it being used by any of the providers so far and Breezy uses the same icon as Thunderstorms.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I read the [Frequently Asked Questions](https://github.com/breezy-weather/breezy-weather/blob/main/HELP.md) document and followed instructions if relevant.
- [X] I have updated the app to **[version 4.6.14 or later](https://github.com/breezy-weather/breezy-weather/releases/latest)**.
- [X] I wrote my request in English, and any screenshot I attached are also in English (language can be changed from Settings > Appearance), unless my issue only happens with a specific language
- [X] I understand that this app is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY, so I may not get a positive reply to my request, if any at all.

**Comment by min7-i** [comment]
_The Pixel icon pack that comes with Breezy Weather does not have a dedicated icon for every weather condition. That's why snow and hail, thunder and thunderstorm as well as fog and haze use the same icons._

> My suggestions are Thunderstorms should be mapped to code 4 and Haze mapped to code 21.

I just briefly looked add the linked list of weather codes and there seem to be some other inconsistencies. This is the current mapping for Chronus:
https://github.com/breezy-weather/breezy-weather/blob/7b76445704dd4218664277a472ecb138760ca927/app/src/main/java/org/breezyweather/theme/resource/providers/ChronusResourceProvider.kt#L107-L119

**Comment by cloneofghosts** [comment]
> _The Pixel icon pack that comes with Breezy Weather does not have a dedicated icon for every weather condition. That's why snow and hail, thunder and thunderstorm as well as fog and haze use the same icons._
> 

Yes, I am aware that Breezy Weather has less icons than Chronus as Chronus icon packs are based off the Yahoo condition codes from when they still offered an API.

> I just briefly looked add the linked list of weather codes and there seem to be some other inconsistencies, e.g. thunderstorm at night. This is the current mapping for Chronus:
> 
> https://github.com/breezy-weather/breezy-weather/blob/7b76445704dd4218664277a472ecb138760ca927/app/src/main/java/org/breezyweather/theme/resource/providers/ChronusResourceProvider.kt#L107-L119

I've only really noticed a difference with the Thunder, Thunderstorm and Haze icons being off when compared to Breezy Weather. Haze and Thunderstorm are pretty straight forward fixes since an icon code for them exists in Chronus. Not sure what to do about the Thunder icon. I assume it's meant to represent a thunderstorm without any rain? Chronus doesn't have an icon for that so you could either use the day/night thunderstorm icon or use the same icon as Thunderstorm.

**Comment by min7-i** [comment]
I updated the mapping as follows:
| weather type | old | new |
| --- | --- | --- |
| rain | 11 (showers) | 12 (rain) |
| haze | 19 (dust) | 21 (haze) |
| sleet | 5 (mixed rain and snow) | 18 (sleet) |
| thunder | 37 (isolated thunderstorms (day))<br>47 (scattered thundershowers (night)) | 4 (thunderstorms) |
| thunderstorm (night) | 45 (scattered showers (night)) | 47 (scattered thundershowers (night)) |

@cloneofghosts Could you please test the changes with your icon pack by using [this debug apk](https://github.com/breezy-weather/breezy-weather/actions/runs/8124894990/artifacts/1291954969)? _(The link only works when you're logged into Github.)_

**Comment by cloneofghosts** [comment]
As mentioned in the PR the changes look good to be merged in. Thanks for fixing this :)
