### ISSUE TITLE
I can't set resident city

### ISSUE THREAD

**Issue by asfhyb** [breezy-weather/breezy-weather#735]
### Steps to reproduce

1.open city
2.try to set resident city
3. no option 

### Expected behavior

resident city should appear 

### Actual behavior

no residents city

### Weather source used

ACCUWEATHER

### Breezy Weather version

5.0.3 alpha 

### Android version

android 12

### Device

inifinix note 12

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I read the [Frequently Asked Questions](https://github.com/breezy-weather/breezy-weather/blob/main/HELP.md) document and followed instructions if relevant.
- [X] I have updated the app to **[version 5.0.3 or later](https://github.com/breezy-weather/breezy-weather/releases/latest)**.
- [X] I wrote my request in English, and any screenshot I attached are also in English (language can be changed from Settings > Appearance), unless my issue only happens with a specific language
- [X] I understand that this app is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY, so I may not get a positive reply to my request, if any at all.

**Comment by papjul** [comment]
Check changelog of v5.0.0 and reopen an idea if needed: https://github.com/breezy-weather/breezy-weather/blob/main/CHANGELOG.md#version-500-alpha-2024-02-26
