### ISSUE TITLE
[Old Android versions] Removed widgets still showing in "Widgets in use"

### ISSUE THREAD

**Issue by Veraellyunjie** [breezy-weather/breezy-weather#743]
### Steps to reproduce

I can't reproduce it on another phone of different manufacturer and Android version.
What I did:
Install Breezy Weather
Place several widgets on the screen to find out how each of them looks
Remove those I don't find useful keeping Hourly trend and Daily Trend.
Go to Settings -> Widgets & Live wallpaper -> Widgets in use
3 there: Weekly, Hourly trend, Weekly trend _<-- phantom Weekly widget_
Add Weekly widget on the screen
Go to Settings -> Widgets & Live wallpaper -> Widgets in use
3 there: Weekly, Hourly trend, Weekly trend
Remove Weekly widget from the screen
Go to Settings -> Widgets & Live wallpaper -> Widgets in use
3 there: Weekly, Hourly trend, Weekly trend _<-- phantom Weekly widget_

I did try closing the app via Android bottom-right square button in order to ensure it rereads widgets, it doesn't help

### Expected behavior

When a widget is removed from screen, it disappears from "Widgets in use"

### Actual behavior

A removed widget is present at "Widgets in use"

### Weather source used

Open-Meteo

### Breezy Weather version

5.0.3-alpha from Izzy

### Android version

8.1.0

### Device

AGM A9

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I read the [Frequently Asked Questions](https://github.com/breezy-weather/breezy-weather/blob/main/HELP.md) document and followed instructions if relevant.
- [X] I have updated the app to **[version 5.0.3 or later](https://github.com/breezy-weather/breezy-weather/releases/latest)**.
- [X] I wrote my request in English, and any screenshot I attached are also in English (language can be changed from Settings > Appearance), unless my issue only happens with a specific language
- [X] I understand that this app is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY, so I may not get a positive reply to my request, if any at all.

**Comment by papjul** [comment]
I'm tagging as "dependency issue" as:
- We directly get the list of widgets from `AppWidgetManager`

https://github.com/breezy-weather/breezy-weather/blob/v5.0.3-alpha/app/src/main/java/org/breezyweather/remoteviews/presenters/WeekWidgetIMP.kt#L184-L188

- It's not reproducible in modern Android versions
- We can find similar bug reports for other apps from 2012-2013 which hints towards an old Android version bug
