### ISSUE TITLE
Crash when max font size and zoom

### ISSUE THREAD

**Issue by Veraellyunjie** [breezy-weather/breezy-weather#744]
### Steps to reproduce

I can't reproduce it on another phone of different manufacturer and Android version.

This is a grandma's phone, so both 
Android settings -> Display -> Font size
Android settings -> Display -> Screen zoom
are set to the rightmost notch.

Breezy weather crashes. It tries to open - I see app's background - but mid-loading it disappears.

It suffices to put either "Font size" or "Screen zoom" one notch to the left, and Breezy weather opens fine. Putting both "Font size" and "Screen zoom" to the left also works.

Screen size is 1080x2160
Language is Russian

---

Also please make it obvious where
Settings -> Debug -> Share crash logs
puts the log.
Coz it offers to open it in an editor but doesn't show where it is.
I had to open it in a text editor and resave to a known location.

[BreezyWeatherCrashLog.txt](https://github.com/breezy-weather/breezy-weather/files/14484477/BreezyWeatherCrashLog.txt)

### Expected behavior

App opens regardless of font and zoom

### Actual behavior

Max of both font and zoom prevents app from loading

### Weather source used

Open-meteo

### Breezy Weather version

5.0.3-alpha from Izzy

### Android version

8.1.0

### Device

AGM A9

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I read the [Frequently Asked Questions](https://github.com/breezy-weather/breezy-weather/blob/main/HELP.md) document and followed instructions if relevant.
- [X] I have updated the app to **[version 5.0.3 or later](https://github.com/breezy-weather/breezy-weather/releases/latest)**.
- [X] I wrote my request in English, and any screenshot I attached are also in English (language can be changed from Settings > Appearance), unless my issue only happens with a specific language
- [X] I understand that this app is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY, so I may not get a positive reply to my request, if any at all.

**Comment by papjul** [comment]
It seems curious as I have a much smaller device and setting both font size to max and display size to max don't crash app. Could there be another accessibility setting enabled?

At least, crash log was very helpful as it shows it's linked to the expandable credits on bottom of main screen.

Crash log is just a temporary file. You usually can find it in Recent files of your File manager app, or in `Android/data/org.breezyweather/cache/`.

Android version and manufacturer of the second device on which it can be reproduced would be useful here as well.

**Comment by min7-i** [comment]
I can reproduce this on my Google Pixel 6a (Android 14). It's working fine on my LG G6 (Android 9) though.

**Comment by papjul** [comment]
@min7-i @Veraellyunjie Can you both set language to English (US) and retry? I have a theory that the "See more" text doesn't fit on one line for some languages.

**Comment by Veraellyunjie** [comment]
> Can you both set language to English (US) and retry? I have a theory that the "See more" text doesn't fit on one line for some languages.

Confirmed. Opens fine while English. Crashes while Russian

**Comment by Veraellyunjie** [comment]
Confirmed on the second phone.

Screen resolution: 720x1480
Samsung Galaxy J6+
Android 10
Launcher: One UI 2.0

I use English there, so Breezy Weather opened fine.
Upon changing to Russian, it crashes

**Comment by min7-i** [comment]
> Can you both set language to English (US) and retry?

That work's.

**Comment by papjul** [comment]
@min7-i Can you retry in German 362e1346256743f50b81d1741f7a6fbb00bb959e?

**Comment by min7-i** [comment]
That fixed it 👍 

<img src="https://github.com/breezy-weather/breezy-weather/assets/97251923/7981c559-29e0-4f04-abf3-455318fb70af" width=25% />

**Comment by papjul** [comment]
Thanks for the confirmation! This will be in next version.
