### ISSUE TITLE
Statusbar temperature notification

### ISSUE THREAD

**Issue by rammmma** [breezy-weather/breezy-weather#749]
### Describe your idea

For people who use statusbar for primary channel of information. With + and - sings, not only -. 
I know that android weather apps use pictures (png, webp) for temperature notification. It takes a lot of work to draw Roboto, Google Sans, miui versions. If you need help for this I can make it (png) 

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] My idea is not related to a question covered in the [Frequently Asked Questions](https://github.com/breezy-weather/breezy-weather/blob/main/HELP.md) document, or a feature described in the [Homepage](https://github.com/breezy-weather/breezy-weather/blob/main/docs/HOMEPAGE.md) document.
- [X] I have updated the app to **[version 5.0.3 or later](https://github.com/breezy-weather/breezy-weather/releases/latest)**.
- [X] I understand that this app is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY, so I may not get a positive reply to my request, if any at all.

**Comment by papjul** [comment]
Go to Settings > Widgets & Live Wallpaper
Enable Notification widget
Enable Temperature as status bar icon

`+` sign is not mandatory so we don't put it as that would make the temperature text smaller due to Android requirement of an icon shape (square).
