### ISSUE TITLE
Support wear os 

### ISSUE THREAD

**Issue by zjm54321** [breezy-weather/breezy-weather#750]
### Describe your idea

Can this app support wear os 4? 

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] My idea is not related to a question covered in the [Frequently Asked Questions](https://github.com/breezy-weather/breezy-weather/blob/main/HELP.md) document, or a feature described in the [Homepage](https://github.com/breezy-weather/breezy-weather/blob/main/docs/HOMEPAGE.md) document.
- [X] I have updated the app to **[version 5.0.3 or later](https://github.com/breezy-weather/breezy-weather/releases/latest)**.
- [X] I understand that this app is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY, so I may not get a positive reply to my request, if any at all.

**Comment by papjul** [comment]
I just tried and it’s not possible. Here is the reason Android Studio gave me:

> For the `android.hardware.type.watch` uses-feature, android:required="false" is disallowed. A single APK for Wear and non-Wear devices is not supported.

Additionally, the design of Breezy Weather doesn’t meet the [design principles of Wear OS apps](https://developer.android.com/design/ui/wear/guides/foundations/design-principles).

If you still want to proceed anyway, you can add the following code:
```xml
<uses-feature
    android:name="android.hardware.type.watch" />
```

in [AndroidManifest.xml](https://github.com/breezy-weather/breezy-weather/blob/main/app/src/main/AndroidManifest.xml) and build it. The APK it will generate will only be compatible with Wear OS.

However, I must warn you, I just tried in an emulator and it’s almost impossible to use.
