### ISSUE TITLE
Swedish Pollen data source, Pollenrapporten

### ISSUE THREAD

**Issue by Mr-Bajs** [breezy-weather/breezy-weather#758]
### Link to publicly available documentation of the API

https://api.pollenrapporten.se/v1/pollen-types?offset=0&limit=100

### Available and not available data

Website: https://pollenrapporten.se/omwebbplatsen/attanvandapollenprognoserna.4.314e02dd13d69872ec0201.html (Swedish)

API Docs: https://api.pollenrapporten.se/docs (English)
API: https://api.pollenrapporten.se/v1/pollen-types?offset=0&limit=100

### Are you going to develop yourself the new source for the app?

No skills here :(

### Give a bit more details or context about this source

Data is managed by the Naturhistoriska Riksmuseet ([Swedish Museum of Natural History](https://en.wikipedia.org/wiki/Swedish_Museum_of_Natural_History)).

Data source should be credited as "Palynologiska laboratoriet vid Naturhistoriska riksmuseet" or in english Labratory of Palynology at Swedish Museum of Natural History.

### Acknowledgements

- [X] This source has a free-tier available (no mandatory credit card info and trials don’t count as “free”), and if it is a main weather source, it includes free hourly forecast
- [X] If this is a weather source request, I checked that endpoints are by coordinates, or that there is a reverse geocoding endpoint.
- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written the name of the source as the title of this issue.
- [X] I have updated the app to **[version 5.0.3 or later](https://github.com/breezy-weather/breezy-weather/releases/latest)** and this source is not part of it.
- [X] I understand that this app is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY, so I may not get a positive reply to my request, if any at all.

**Comment by papjul** [comment]
> * [X] If this is a weather source request, I checked that endpoints are by coordinates, or that there is a reverse geocoding endpoint.

I will let you confirm but it looks like this criteria is not met. The `/regions` endpoint does not give us the polygon that would have allowed us to check if our location if within the bounds of this source regions.

Additionally, we need pollen to be provided in spores per cubic meter unit. This data is not provided by this API from what I can see, there is only a "level" info that goes from 0 to 8 with an associated label. This data is too vague to be used.

**Comment by papjul** [comment]
Either we provide longitude and latitude as parameters and they return one matching region result OR they add for each region the polygon geometry of that region in the result so that we can know if our location is inside that polygon ;)
