### ISSUE TITLE
GeoSphere Austria

### ISSUE THREAD

**Issue by papjul** [breezy-weather/breezy-weather#763]
### Link to publicly available documentation of the API

https://dataset.api.hub.geosphere.at/v1/docs/

### Available and not available data

https://data.hub.geosphere.at/dataset/klima-v2-1h

### Are you going to develop yourself the new source for the app?

Maybe

### Give a bit more details or context about this source

Requested on Matrix

### Acknowledgements

- [X] This source has a free-tier available (no mandatory credit card info and trials don’t count as “free”), and if it is a main weather source, it includes free hourly forecast
- [X] If this is a weather source request, I checked that endpoints are by coordinates, or that there is a reverse geocoding endpoint.
- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written the name of the source as the title of this issue.
- [X] I have updated the app to **[version 5.0.3 or later](https://github.com/breezy-weather/breezy-weather/releases/latest)** and this source is not part of it.
- [X] I understand that this app is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY, so I may not get a positive reply to my request, if any at all.

**Comment by kosmoz** [comment]
Hi! I am interested in getting this source to work, so I did some research regarding the API and data availability. Here's what I found:

Geosphere provides several forecast datasets that could be relevant for this app. All are provided under the [Creative Commons Attribution 4.0](https://creativecommons.org/licenses/by/4.0/legalcode) license. 

The datasets can be accessed via 
`https://dataset.api.hub.geosphere.at/v1/timeseries/forecast/{resourceId}?parameters=...&lat_lon=lat,lon`. 
For example:
https://dataset.api.hub.geosphere.at/v1/timeseries/forecast/nwp-v1-1h-2500m?parameters=t2m&parameters=rr_acc&lat_lon=47.3948%2C13.6878

Available parameters can be retrieved via
`https://dataset.api.hub.geosphere.at/v1/timeseries/forecast/{resourceId}/metadata`.

API documentation is available [here](https://dataset.api.hub.geosphere.at/v1/openapi-docs#/forecast/Timeseries_Forecast_Metadata_timeseries_forecast__resource_id__metadata_get).

- [Kurzfristvorhersage](https://data.hub.geosphere.at/dataset/nowcast-v1-15min-1km) (short term forecast)
  - Resource ID: `nowcast-v1-15min-1km`
  - Temporal resolution: 15min
  - Spatial resolution: 1km
  - Scope: 3h
  - Update freq: 15min
  - <details>
      <summary>Parameters</summary>

      ```json
      [
        {
          "name": "dd",
          "long_name": "10m wind direction",
          "desc": "wind direction 10m above ground",
          "unit": "m s-1"
        },
        {
          "name": "ff",
          "long_name": "10m wind speed",
          "desc": "wind speed 10m above ground",
          "unit": "m s-1"
        },
        {
          "name": "fx",
          "long_name": "10m gust speed",
          "desc": "gust speed 10m above ground",
          "unit": "m s-1"
        },
        {
          "name": "pt",
          "long_name": "precipitation type",
          "desc": "precipitation type",
          "unit": ""
        },
        {
          "name": "rh2m",
          "long_name": "relative humidity 2m above ground",
          "desc": "relative humidity 2m above ground",
          "unit": "%"
        },
        {
          "name": "rr",
          "long_name": "precipitation sum",
          "desc": "precipitation sum",
          "unit": "kg m-2"
        },
        {
          "name": "t2m",
          "long_name": "air temperature 2m above ground",
          "desc": "air temperature 2m above ground",
          "unit": "degree_Celsius"
        },
        {
          "name": "td",
          "long_name": "dew point temperature 2m above ground",
          "desc": "dew point temperature 2m above ground",
          "unit": "degree_Celsius"
        }
      ]
      ```
    </details>
- [Hochauflösendes Wettermodell](https://data.hub.geosphere.at/dataset/nwp-v1-1h-2500m) (high resolution weather model)
  - Resource ID: `nwp-v1-1h-2500m`
  - Temporal resolution: 1h
  - Spatial resolution: 2.5km
  - Scope: 60h (2.5 days)
  - Update freq: 3h
  - <details>
      <summary>Parameters</summary>

      ```json
      [
        {
          "name": "cape",
          "long_name": "Convective available potential energy",
          "desc": "Convectively available potential energy",
          "unit": "m2 s-2"
        },
        {
          "name": "cin",
          "long_name": "Convective inhibition",
          "desc": "Convective inhibition",
          "unit": "J kg-1"
        },
        {
          "name": "grad",
          "long_name": "surface global radiation",
          "desc": "Surface downwelling shortwave is the sum of direct and diffuse solar radiation incident on the surface, and is sometimes called global radiation",
          "unit": "Ws m-2"
        },
        {
          "name": "mnt2m",
          "long_name": "minimum 2m temperature in the last forecast period",
          "desc": "Minimum 2m temperature in the last forecast intervall",
          "unit": "degree Celsius"
        },
        {
          "name": "mxt2m",
          "long_name": "maximum 2m temperature in the last forecast period",
          "desc": "Maximum 2m temperature in the last forecast intervall",
          "unit": "degree Celsius"
        },
        {
          "name": "rain_acc",
          "long_name": "total rainfall amount",
          "desc": "Accumulated total amount of rainfall since start of the forecast",
          "unit": "kg m-2"
        },
        {
          "name": "rh2m",
          "long_name": "relative humidity 2m above ground",
          "desc": "relative humidity 2m above ground",
          "unit": "%"
        },
        {
          "name": "rr_acc",
          "long_name": "total precipitation amount",
          "desc": "Accumulated total amount of liquid and solid precipitation since start of the forecast",
          "unit": "kg m-2"
        },
        {
          "name": "snow_acc",
          "long_name": "total surface snow amount",
          "desc": "Surface snow amount refers to the amount on the solid ground or on surface ice cover, but excludes, for example, falling snowflakes and snow on plants.",
          "unit": "kg m-2"
        },
        {
          "name": "snowlmt",
          "long_name": "snowlimit",
          "desc": "Height above ground where falling snow melts",
          "unit": "m"
        },
        {
          "name": "sp",
          "long_name": "surface pressure",
          "desc": "surface pressure",
          "unit": "Pa"
        },
        {
          "name": "sundur_acc",
          "long_name": "sunshine duration accumulated",
          "desc": "sunshine duration since forecast start",
          "unit": "s"
        },
        {
          "name": "sy",
          "long_name": "weather symbol",
          "desc": "Codes for GeoSphere Austria weather symbol.",
          "unit": "1"
        },
        {
          "name": "t2m",
          "long_name": "2m temperature",
          "desc": "air temperature 2m above ground",
          "unit": "degree Celsius"
        },
        {
          "name": "tcc",
          "long_name": "Total cloud cover",
          "desc": "total cloud cover",
          "unit": "1"
        },
        {
          "name": "u10m",
          "long_name": "10m wind speed in eastward direction",
          "desc": "wind speed in eastward direction",
          "unit": "m s-1"
        },
        {
          "name": "ugust",
          "long_name": "u component of maximum wind gust",
          "desc": "U component of maximum wind gust in the last forecast intervall",
          "unit": "m s-1"
        },
        {
          "name": "v10m",
          "long_name": "10m wind speed in northward direction",
          "desc": "wind speed in northward direction 10m above ground",
          "unit": "m s-1"
        },
        {
          "name": "vgust",
          "long_name": "v compoment of maximum wind gust",
          "desc": "V component of maximum wind gust in the last forecast intervall",
          "unit": "m s-1"
        }
      ]
      ```
    </details>
- [Schadstoffvorhersage Europa](https://data.hub.geosphere.at/dataset/chem-v1-1h-12km) (pollution forecast Europe)
  - Resource ID: `chem-v1-1h-12km`
  - Temporal resolution: 1h
  - Spatial resolution: 12km
  - Scope: 3 days
  - Update freq: daily
  - <details>
      <summary>Parameters</summary>

      ```json      [
        {
          "name": "no2surf",
          "long_name": "Nitrogen dioxide concentration close to the surface (lowest model level)",
          "desc": "Nitrogen dioxide concentration close to the surface (lowest model level)",
          "unit": "ug m-3"
        },
        {
          "name": "o3surf",
          "long_name": "Ozone concentration close to the surface (lowest model level)",
          "desc": "Ozone concentration close to the surface (lowest model level)",
          "unit": "mg m-3"
        },
        {
          "name": "pm10surf",
          "long_name": "PM10 concentration close to the surface (lowest model level)",
          "desc": "PM10 concentration close to the surface (lowest model level)",
          "unit": "ug m-3"
        },
        {
          "name": "pm25surf",
          "long_name": "PM2.5 concentration close to the surface (lowest model level)",
          "desc": "PM2.5 concentration close to the surface (lowest model level)",
          "unit": "ug m-3"
        }
      ]
      ```
    </details>
- [Schadstoffvorhersage Mitteleuropa](https://data.hub.geosphere.at/dataset/chem-v1-1h-4km) (pollution forecast central Europe)
  - Resource ID: `chem-v1-1h-4km`
  - Temporal resolution: 1h
  - Spatial resolution: 4km
  - Scope: 3 days
  - Update freq: daily
  - Parameters same as above

There is a different API for [warnings](https://data.hub.geosphere.at/dataset/warnungen-v1), which could be interesting: https://openapi.hub.geosphere.at/warnapi/v1/#/warnings/getWarningsForCoords

All APIs return some kind of GeoJSON.

I can see two potential problems with these APIs:
1. Weather forecast only for 2.5 days at most.
2. Mostly restricted to Austria (except for the pollution datasets), so limited usefulness for most people.

What do you think? Could this be an interesting addition to the app?

**Comment by papjul** [comment]
I was able to easily get a working hourly temperature working in 3b9b70e2a1e7ebbaf6761a194693d94b46a4e8ee. Will try to get all parameters working by next release :)

**Comment by papjul** [comment]
Is there something more specific than "central Europe" or "Europe" for `chem-v1-1h-12km` or `chem-v1-1h-4km`? I'm looking for a polygon or something like that. I would like to avoid querying the server for the available endpoints (what you mentioned) every time the user "current location" changes. If you can't find it, could you contact GeoSphere Austria and ask them? Thanks!

For warnings, I can filter on `countryCode = AT`.

**Comment by kosmoz** [comment]
There are bounding boxes on the documentation:
- `chem-v1-1h-12km`: 17.65 - 76.49 °N, -59.21 - 83.21 °E ([visualization](https://linestrings.com/bbox/#-59.21,17.65,83.21,76.49))
- `chem-v1-1h-4km`: 41.72 - 50.15 °N, 4.31 - 18.99 °E ([visualization](https://linestrings.com/bbox/#4.31,41.72,18.99,50.15))
- `nowcast-v1-15min-1km`: 45.5 - 49.48 °N, 8.1 - 17.74 °E ([visualization](https://linestrings.com/bbox/#8.1,45.5,17.74,49.48))

Is this accurate enough?

**Comment by papjul** [comment]
I missed it, that's perfect, thank you!

**Comment by kosmoz** [comment]
Awesome! :slightly_smiling_face:

**Comment by papjul** [comment]
There seems to be a bounding box to the hourly forecast as well, as documented:
https://linestrings.com/bbox/#5.49,42.98,22.1,51.82

However, when I add Dallas, TX, I can see forecast there, so I'm not sure what these bounding boxes are for? Is it an error?

**Comment by kosmoz** [comment]
I would be happy do some more digging if it helps but it probably won't be before Friday. From a quick search I don't have any answers.

For questions regarding the API there is a GitHub repo where we can open an issue and ask: https://github.com/Geosphere-Austria/dataset-api-docs

**Comment by papjul** [comment]
No problem, I can wait, you already helped me a lot!

**Comment by kosmoz** [comment]
Small update:

Regarding weather symbols, I found [this table](https://www.zamg.ac.at/cms/en/topmenu/infopoint/legend/weather_symbols) which shows a list available weather symbols. If you inspect an image in your browser you see an URL like this: https://www.zamg.ac.at/zamgWeb/common/img/www_sonne/symb02.png
I think the number in the file name corresponds to the value returned by the API. 

Regarding locations outside the bounding box, I tried Sao Paulo (https://dataset.api.hub.geosphere.at/v1/timeseries/forecast/nwp-v1-1h-2500m?parameters=sy&lat_lon=-23.5478%2C-46.6551) and it looks like the coordinates in the response GeoJSON are different than the ones requested. However the coordinates from the response are somewhere in Somalia… :shrug: For now, I think it should be assumed that responses for locations outside of the bounding box should not be relied upon.

I will open an issue in the Geosphere repo regarding these questions.

Regarding normal values, I found [this dataset](https://data.hub.geosphere.at/dataset/spartacus-v2-1d-1km), which could be of interest. From the description (translated):

> The gridded data set describes the spatial distribution of observed air temperature (minimum temperature (TN) and maximum temperature (TX)), precipitation (RR) and absolute sunshine duration (SA) from day to day since 1961 in kilometer resolution over Austria. In addition to the original daily resolution, monthly, seasonal and annual aggregates are available. The data set is operationally expanded on a daily basis.

**Comment by kosmoz** [comment]
I created https://github.com/Geosphere-Austria/dataset-api-docs/issues/30 and https://github.com/Geosphere-Austria/dataset-api-docs/issues/31 regarding these open questions.

**Comment by papjul** [comment]
Ah yes, I didn't notice in the feature that the returned latitude and longitude match the limits of the bbox.

4ced625922bef26ffaeb043de39f022b113e3eb0 enforces the bbox for hourly weather and adds weather symbols based on that table

> Regarding normal values, I found [this dataset](https://data.hub.geosphere.at/dataset/spartacus-v2-1d-1km), which could be of interest.

Thanks, I also thought of the Spartacus endpoint, I will try to see if I can use something from it.


Everything apart from alerts and normals is ready for next release.

**Comment by kosmoz** [comment]
Here is a translation of the table originally posted at https://github.com/Geosphere-Austria/dataset-api-docs/issues/30#issuecomment-2042539848:

Icon ID | Description
-- | --
1 | cloudless
2 | clear
3 | cloudy
4 | heavily cloudy
5 | overcast
6 | ground fog
7 | high fog
8 | light rain
9 | moderate rain
10 | strong rain
11 | sleet
12 | sleet
13 | sleet
14 | light snowfall
15 | moderate snowfall
16 | strong snowfall
17 | rain shower
18 | rain shower
19 | strong rain shower
20 | sleet shower
21 | sleet shower
22 | sleet shower
23 | snow shower
24 | snow shower
25 | strong snow shower
26 | thunderstorm
27 | thunderstorm
28 | strong thunderstorm 
29 | thunderstorm with sleet
30 | strong thunderstorm with sleet
31 | thunderstorm with snow
32 | strong thunderstorm with snow

**Comment by papjul** [comment]
Thanks!

Regarding warnings, I think it would be better if the API could fallback to German text when English text is missing, instead of showing no instructions, if you would like to report this issue as well.

This is the same alert in German:
![image](https://github.com/breezy-weather/breezy-weather/assets/1449159/4d75f8e2-e961-4464-a272-f114f3058cee)

And in English:
![image](https://github.com/breezy-weather/breezy-weather/assets/1449159/75abd84e-9562-4da1-8a86-282a806bb5a1)

**Comment by kosmoz** [comment]
> if you would like to report this issue as well

Unfortunately, the warnings API is separate and there is no public repository for it.
