### ISSUE TITLE
Widget Clock Daily Vertical Style Template Extra Line

### ISSUE THREAD

**Issue by jsetton** [breezy-weather/breezy-weather#765]
### Describe your idea

Migrating issue from https://github.com/WangDaYeeeeee/GeometricWeather/issues/151 and still relevant in the latest version.

Looking at the template drawing for the Clock + Daily (Vertical Style) 3 x 2 widget, it seems to indicate an extra line under the clock. which is not apparent on the actual widget. I was wondering if this was intended to be that way. I am asking because it would be nice to have that extra line display the current date.

**Template**
![template](https://user-images.githubusercontent.com/12190401/86860521-fff18d00-c092-11ea-91d3-ed50059ef740.jpg)

**Widget (Symmetry Style)**
![widget](https://user-images.githubusercontent.com/12190401/86860522-008a2380-c093-11ea-8af2-29e0f0d1b50a.jpg)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] My idea is not related to a question covered in the [Frequently Asked Questions](https://github.com/breezy-weather/breezy-weather/blob/main/HELP.md) document, or a feature described in the [Homepage](https://github.com/breezy-weather/breezy-weather/blob/main/docs/HOMEPAGE.md) document.
- [X] I have updated the app to **[version 5.0.3 or later](https://github.com/breezy-weather/breezy-weather/releases/latest)**.
- [X] I understand that this app is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY, so I may not get a positive reply to my request, if any at all.

**Comment by papjul** [comment]
I have no idea why the template looks that way. On your original issue, according to the developer, it looks like the feature is actually missing.

There are plans to redesign almost all widgets from legacy technologies, so I’m not sure in the current state if the widget will be exactly the same.

**Comment by papjul** [comment]
This widget won't be kept that way in the overhaul and there are no plans to add new features to legacy widgets
