### ISSUE TITLE
[Minor Issue] Pixel Icon Provider v3.0 has wrong internal version number / code

### ISSUE THREAD

**Issue by genericusername87** [breezy-weather/breezy-weather#766]
### Steps to reproduce

1.) Go to https://github.com/breezy-weather/pixel-icon-provider/releases
2.) Install [pixel-icon-provider-v3.0.apk](https://github.com/breezy-weather/pixel-icon-provider/releases/tag/v3.0)
3.) Open Settings -> Apps -> Pixel and check version number at the bottom screen

### Expected behavior

Should display:
"Version 3.0
       
org.breezyweather.pixeliconprovider
versionCode 3"

### Actual behavior

Displays:
"Version 2.0
       
org.breezyweather.pixeliconprovider
versionCode 2"

### Weather source used

Not applicable

### Breezy Weather version

Not applicable (breezy-weather-arm64-v8a-v5.1.0-beta-standard)

### Android version

Android 14

### Device

Google Pixel 6

### Other details

Posting it here since neither Breezy Weather Icon Packs nor Pixel Icon Provider have an own issue section.

This 'problem' might not really be relevant. The reason it bothers me is solely that Obtainium is constantly popping up for updates for the Pixel Icons because the detected installed version is minor to the detected release version from Github

But may ask why you decided to remove the icons from Breezy Weather Standard in the first place? I understand this for Fdroid version, but not really for Standard / GPlay.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I read the [Frequently Asked Questions](https://github.com/breezy-weather/breezy-weather/blob/main/HELP.md) document and followed instructions if relevant.
- [X] I have updated the app to **[version 5.0.3 or later](https://github.com/breezy-weather/breezy-weather/releases/latest)**.
- [X] I wrote my request in English, and any screenshot I attached are also in English (language can be changed from Settings > Appearance), unless my issue only happens with a specific language
- [X] I understand that this app is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY, so I may not get a positive reply to my request, if any at all.

**Comment by papjul** [comment]
Thanks for reporting! Re-released just now
