### ISSUE TITLE
Wind speed measurement unit cut off on main screen

### ISSUE THREAD

**Issue by Marko-98** [breezy-weather/breezy-weather#771]
### Steps to reproduce

Steps to reproduce:

1. Add location
2. Set wind speed to km/h in settings

![Screenshot_1](https://github.com/breezy-weather/breezy-weather/assets/129692860/c5e86518-492c-47d0-a914-e71b0eb67912)

### Expected behavior

Wind speed should be shown with text "km/h" in it's entirety.

### Actual behavior

Text "km/h" is cut off.

### Weather source used

AccuWeather

### Breezy Weather version

5.1.0-beta

### Android version

HyperOS, Android 14

### Device

Poco X5 Pro

### Other details

Other potential bug: when touching main weather info section, it looks like it tappable, but it's not. I'm not sure if it's intentional or not.

https://github.com/breezy-weather/breezy-weather/assets/129692860/ee6dfa23-d093-48d2-9e2a-130b1cac7bef

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I read the [Frequently Asked Questions](https://github.com/breezy-weather/breezy-weather/blob/main/HELP.md) document and followed instructions if relevant.
- [X] I have updated the app to **[version 5.0.3 or later](https://github.com/breezy-weather/breezy-weather/releases/latest)**.
- [X] I wrote my request in English, and any screenshot I attached are also in English (language can be changed from Settings > Appearance), unless my issue only happens with a specific language
- [X] I understand that this app is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY, so I may not get a positive reply to my request, if any at all.

**Comment by papjul** [comment]
It's an intended behavior.

If you don't like it, there are many options:
- Go to Settings > Main screen > Details screen, and replace “Wind” with a different detail
- Go to Settings > Main screen > Details screen, and remove one detail so you have 3 details at the same time, so it will fit better
- Go to Settings > Appearance > Units > Speed unit. Use a shorter unit such as the Beaufort scale.

Note: you may be interested in following #738

**Comment by Marko-98** [comment]
@papjul That helps!

What about the "issue" in the video? Is that intended too?

**Comment by papjul** [comment]
It has always been there for as far as I can remember. Someone spend time designing it that way, so I believe it is intentional. I don’t care if we have that effect or not, but since it has always been that way, it’s best to leave it that way to avoid the usual complaints when something changes even slightly.
