### ISSUE TITLE
[Bright Sky] Replace hours of sun with sunshine duration

### ISSUE THREAD

**Issue by martkol** [breezy-weather/breezy-weather#774]
### Steps to reproduce

At the bottom of the detail page of the day.
![Screenshot_20240310_152120_Breezy Weather](https://github.com/breezy-weather/breezy-weather/assets/55714786/dc03fe83-57dc-4e12-a2d7-bd4b5810ef00)

### Expected behavior

The predicted sunshine duration should be displayed.

### Actual behavior

The maximum achievable hours of sunshine during the day (if there were no clouds in the sky) are displayed. The data provided by the API is correct.

### Weather source used

Bright Sky

### Breezy Weather version

5.1.0 beta

### Android version

Android 13

### Device

Samsung Galaxy A52

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I read the [Frequently Asked Questions](https://github.com/breezy-weather/breezy-weather/blob/main/HELP.md) document and followed instructions if relevant.
- [X] I have updated the app to **[version 5.0.3 or later](https://github.com/breezy-weather/breezy-weather/releases/latest)**.
- [X] I wrote my request in English, and any screenshot I attached are also in English (language can be changed from Settings > Appearance), unless my issue only happens with a specific language
- [X] I understand that this app is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY, so I may not get a positive reply to my request, if any at all.

**Comment by papjul** [comment]
Technically, hours of sun is the number of hours between sunrise and sunset. However, it's true that there is one exception to this rule where hours of sun is actually sunshine duration, on AccuWeather source. All other sources use hours of sun.

Since I can understand sunshine duration is an information more interesting, I can make the same exception for Bright Sky.

**Comment by papjul** [comment]
Done for Open-Meteo and Bright Sky in 6f70d10ac0f405142dcfa49f8a12aa748ceed312
