### ISSUE TITLE
[AccuWeather] Incorrect display of precipitation in cm in texts when temperature units is configured as inches

### ISSUE THREAD

**Issue by papjul** [breezy-weather/breezy-weather#78]
### Steps to reproduce

1. Configure precipitation unit as inch
2. Refresh AccuWeather data
3. When there is precipitation, look at texts

### Expected behavior

Texts should show inches

### Actual behavior

Texts show inch

### Weather provider used

AccuWeather

### Breezy Weather version

4.0.3-alpha

### Android version

All

### Device

All

### Other details

This is due to data being always requested as metric, then converted as imperial.

There is a parser, but it only works with English and it seems it doesn't work anymore with precipitation.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to **[latest version](https://github.com/breezy-weather/breezy-weather/releases/latest)**.

**Comment by TheGamer1002** [comment]
Bump. Still occuring as of 4.6.13-beta.

**Comment by papjul** [comment]
Fixed in 4dfa5eba3b319d8531590e6779205d2c596c8d6d
