### ISSUE TITLE
AccuWeather's "minutecast"

### ISSUE THREAD

**Issue by KaKi87** [breezy-weather/breezy-weather#780]
### Describe your idea

It would be nice to have AccuWeather's minutecast in the app.

### Other details

"Minutecast" is mentioned [here](https://github.com/breezy-weather/breezy-weather/issues/756) but not in the same context.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] My idea is not related to a question covered in the [Frequently Asked Questions](https://github.com/breezy-weather/breezy-weather/blob/main/HELP.md) document, or a feature described in the [Homepage](https://github.com/breezy-weather/breezy-weather/blob/main/docs/HOMEPAGE.md) document.
- [X] I have updated the app to **[version 5.0.3 or later](https://github.com/breezy-weather/breezy-weather/releases/latest)**.
- [X] I understand that this app is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY, so I may not get a positive reply to my request, if any at all.

---

Thanks

**Comment by papjul** [comment]
> I don't know of that chart you're mentioning, where is it ?

Under hourly chart for compatible sources (AccuWeather, Open-Meteo, Météo France) AND when it's raining.

> However, MinuteCast doesn't cover 1 hour, but 4 hours, with minute-by-minute precision.

As far as I can see, the API supports 2 hours, but maybe there are more.

**Comment by KaKi87** [comment]
> AND when it's raining.

Well, the point of MinuteCast is to determine whether to go out at the specific present time and if no then how much time to wait, so the user needs the information immediately whether it's raining or not.

> the API supports 2 hours, but maybe there are more hours for some locations

My location is Limoges, France.

**Comment by papjul** [comment]
> > AND when it's raining.
> 
> Well, the point of MinuteCast is to determine whether to go out at the specific present time and if no then how much time to wait, so the user needs the information immediately whether it's raining or not.

I will complete my sentence so it’s more clear: when it’s raining **in the next 2 hours**. If there is no rain expected in the next 120 minutes, we don’t show an empty chart for efficient use of space and your time.

According to my tests, it’s not raining in Limoges right now, but you can try in Rouen (AccuWeather or Météo-France).

**Comment by KaKi87** [comment]
That looks nice indeed !

I still have two requests :

- please still display a "No precipitation for at least 120 min" message like AccuWeather does, it's only one line yet removes doubt thus resulting in better UX ;
- it would be nice to show the time in addition to the amount of rain when clicking the graph.

Thanks

**Comment by papjul** [comment]
It will be done as part of #369

**Comment by KaKi87** [comment]
Alright, thanks !
