### ISSUE TITLE
Open-Meteo: allow model selection

### ISSUE THREAD

**Issue by jbgi** [breezy-weather/breezy-weather#781]
### Describe your idea

Open-meteo provide a 'best match' model by default but users may want to try an alternative model (ie. using the `models` query param).

My use case is for France locations, where open-meteo 'best match' use `icon_d2` for most of the metropolitan area, whereas many users would rather want the Meteo-France models (see https://github.com/open-meteo/open-meteo/issues/214).

Keys to use for the `models` param here: https://github.com/Akylas/oss-weather/blob/6b454dd32af6ee917a704afea5b12e1852f9b9e4/app/services/providers/om.ts#L17-L44
(maybe only the seamless ones could be offered to reduce the list)

### Other details

Title of #21 is very (too?) broad but kind-of include this feature request (among other things?).

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] My idea is not related to a question covered in the [Frequently Asked Questions](https://github.com/breezy-weather/breezy-weather/blob/main/HELP.md) document, or a feature described in the [Homepage](https://github.com/breezy-weather/breezy-weather/blob/main/docs/HOMEPAGE.md) document.
- [X] I have updated the app to **[version 5.0.3 or later](https://github.com/breezy-weather/breezy-weather/releases/latest)**.
- [X] I understand that this app is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY, so I may not get a positive reply to my request, if any at all.

**Comment by papjul** [comment]
Yes, #21 will implement this feature. At the moment, this is the only per-location per-source setting to my knowledge, but we can keep #21 to track the technical implementation and your issue for the Open-Meteo models feature.

It’s a bit complex, because they can be combined, but I think some combinations are curious such as Best match + MeteoFrance Arome France. Or MeteoFrance Seamless + MeteoFrance Arome France HD. If some combinations don't make sense, the app should not suggest them.

**Comment by papjul** [comment]
It will be in next version. However, it’s a feature for advanced users. If a user does something stupid such as requesting only "Météo-France AROME France HD" for a location in United States, they may end up having to delete their location and re-add it.
