### ISSUE TITLE
[Android 10/MIUI] Colors issues when dark mode is enabled

### ISSUE THREAD

**Issue by BladeRyo** [breezy-weather/breezy-weather#790]
### Steps to reproduce

![Screenshot_2024-03-13-12-06-36-706_org breezyweather](https://github.com/breezy-weather/breezy-weather/assets/38330637/987d596a-0aaf-487e-b80e-af60d5580a30)

### Expected behavior

Font color should be black on tabs?

### Actual behavior

Font color is white on white tab making it unreadable.

### Weather source used

OpenWeather

### Breezy Weather version

5.1.2 beta

### Android version

Android 10

### Device

Pocophone F1

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I read the [Frequently Asked Questions](https://github.com/breezy-weather/breezy-weather/blob/main/HELP.md) document and followed instructions if relevant.
- [X] I have updated the app to **[version 5.1.1 or later](https://github.com/breezy-weather/breezy-weather/releases/latest)**.
- [X] I wrote my request in English, and any screenshot I attached are also in English (language can be changed from Settings > Appearance), unless my issue only happens with a specific language
- [X] I understand that this app is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY, so I may not get a positive reply to my request, if any at all.

**Comment by papjul** [comment]
Customized versions of Breezy Weather are not supported.

**Comment by BladeRyo** [comment]
Its not customized or modified, just downloaded the apk from your page.

**Comment by papjul** [comment]
The theme is customized, Breezy Weather doesn't look like this out of the box. Either by a module or by a modified Android system.

Here is what the app looks like when weather is partly cloudy:
<img src="https://github.com/breezy-weather/breezy-weather/raw/v5.1.2-beta/fastlane/metadata/android/en-US/images/phoneScreenshots/01-main-header-1.png" width="300" />

It looks like something tried to darken the app.

**Comment by BladeRyo** [comment]
Dont know who or what is doing it, its the only app i have this problem with. I just set dark mode in app settings, but using light just isnt working. 

![Screenshot_2024-03-13-13-48-59-054_org breezyweather](https://github.com/breezy-weather/breezy-weather/assets/38330637/b88f0b9d-84c4-4469-b287-de67fd0d77a4)


![Screenshot_2024-03-13-13-48-17-054_org breezyweather](https://github.com/breezy-weather/breezy-weather/assets/38330637/e51fabb0-0757-4900-abaa-85bc56425023)

Edit, upon more testing. Its overall phone dark mode that is wrecking havoc. Using light theme makes app look like yours, setting dark in app or system makes it go crazy. Maybe its UI from Pocophone, but its all stock. rom No mods at all.

**Comment by papjul** [comment]
What does Settings > Accessibility > Color inversion show?

**Comment by BladeRyo** [comment]
Everything is off, no accessibility options are used. 
Tried 3.013 Geometric Weather, same thing. Guess for some reason it doesn't play well on MIUI or older phones.
Going into settings and disabling dark mode for individual app fixes all these issues.

**Comment by papjul** [comment]
Are you sure you don't have any color inversion setting enabled?
This was an old Android 10 option that forced app to go into dark mode when they didn't support it, but it introduced a lot of readability issues. Fortunately, most apps support dark mode now, so this option should be disabled.
And I can see from your screenshot this really looks like color inversion:
https://www.techbone.net/xiaomi/user-manual/color-inversion

**Comment by BladeRyo** [comment]
![Screenshot_2024-03-13-15-03-03-905_com android settings](https://github.com/breezy-weather/breezy-weather/assets/38330637/95a70b8c-9b35-403c-b0ab-ba989ebe0c29)

No color inversion, checked developer mode if there is something enabled there, nope, all stock. As i say, everything on the phone shows fine, pictures are fine, as soon as i tried color inversion it affects everything, from gallery, desktop even camera.

**Comment by papjul** [comment]
Alright, then I have no idea, it's the first time I see a report like that, and you said that it dates back from Geometric Weather, so it's not like it's something recent.

I will leave the issue open in case other users are able to help you.

**Comment by GaucovyAero** [comment]
> Alright, then I have no idea, it's the first time I see a report like that, and you said that it dates back from Geometric Weather, so it's not like it's something recent.
> 
> I will leave the issue open in case other users are able to help you.

this is an issue specifically with older MIUI, as Xiaomi decided to force its own dark mode onto apps, not sure how one can work around this though

**Comment by papjul** [comment]
That was my understanding from a few readings.

Basically, what I understood is that "dark mode" switch is enabled by default on all apps and it tweaks colors of the app to make a fake dark mode.

What you need to do is turn off dark mode on settings of the app on MIUI side, and enable light or dark mode from Breezy Weather in-app settings.

**Comment by GaucovyAero** [comment]
i kindly suggest installing a custom rom, for example LineageOS, as your phone has huge community support and it would definitely fix your issue, just make sure to follow official instructions on their site and not some indian youtube videos
