### ISSUE TITLE
Some parts of the app use Android system language instead of manually set language

### ISSUE THREAD

**Issue by jfk93260** [breezy-weather/breezy-weather#791]
### Steps to reproduce

1. Change the app language to french
2. Refresh data

### Expected behavior

All UI content strings should stay translated in French

### Actual behavior

Some UI strings get reverted to English

![Screenshot_20240313-122226](https://github.com/breezy-weather/breezy-weather/assets/30798957/4f682847-cfbf-446a-bc82-b136654c9a6f)
![Screenshot_20240313-122234](https://github.com/breezy-weather/breezy-weather/assets/30798957/7d4da858-8107-4a79-a68f-6762b85c1f6a)

I know this is an old bug that was fixed a few versions ago but for some reason it's back

### Weather source used

All of them

### Breezy Weather version

5.1.1-beta

### Android version

Android 14

### Device

Sony Xperia 10 IV 

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I read the [Frequently Asked Questions](https://github.com/breezy-weather/breezy-weather/blob/main/HELP.md) document and followed instructions if relevant.
- [X] I have updated the app to **[version 5.1.1 or later](https://github.com/breezy-weather/breezy-weather/releases/latest)**.
- [X] I wrote my request in English, and any screenshot I attached are also in English (language can be changed from Settings > Appearance), unless my issue only happens with a specific language
- [X] I understand that this app is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY, so I may not get a positive reply to my request, if any at all.

**Comment by papjul** [comment]
Are you sure you refreshed? It says "44 min. ago".

What's your Android system languages preferences?

**Comment by jfk93260** [comment]
![Screenshot_20240313-131206](https://github.com/breezy-weather/breezy-weather/assets/30798957/8ba9a7a8-1e34-4e8b-b811-9387f09eabaf)

I can't do better than that ;)

I actually meant to say "one of the many data refresh that happens between the very first loading of the weather data and the actual present time, even the ones that happen automatically while I'm sleeping"... So i really can't tell if it's the 2nd or the 24th data refresh, I won't deny.
My phone is set to English.

**Comment by jfk93260** [comment]
By the way, thanks for the fix with the location name, you closed the issue before I got time to answer

**Comment by jfk93260** [comment]
Yes, it seems so 👍

**Comment by papjul** [comment]
Fixed in c8fc27541587aa38000ddfa5584e5ed9c6a01f44
