### ISSUE TITLE
Minor Tweak to Symmetry Widget Style

### ISSUE THREAD

**Issue by c0l4bin** [breezy-weather/breezy-weather#798]
### Describe your idea

In order to make the Symmetry Widget option more symmetrical, introduce a line break so the right side (Current weather condition and high/low temperatures) is displayed on two lines of text like the left side (Current location and current temperature).

<img width="540" alt="Screenshot_20240314-085629" src="https://github.com/breezy-weather/breezy-weather/assets/96123690/63a2eb19-8e73-46f4-bc0f-b7f13931150f">

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] My idea is not related to a question covered in the [Frequently Asked Questions](https://github.com/breezy-weather/breezy-weather/blob/main/HELP.md) document, or a feature described in the [Homepage](https://github.com/breezy-weather/breezy-weather/blob/main/docs/HOMEPAGE.md) document.
- [X] I have updated the app to **[version 5.1.3 or later](https://github.com/breezy-weather/breezy-weather/releases/latest)**.
- [X] I understand that this app is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY, so I may not get a positive reply to my request, if any at all.

**Comment by papjul** [comment]
There are plans to rewrite widgets and legacy (as opposed to Material You) widgets won't be kept (at least, they will be different). In the meantime, no improvements to the legacy widgets are planned
