### ISSUE TITLE
Add support for calendars other than Gregorian

### ISSUE THREAD

**Issue by alr86** [breezy-weather/breezy-weather#807]
### Describe your idea

Please add the ability to set the date to the solar date and the lunar date🙏

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] My idea is not related to a question covered in the [Frequently Asked Questions](https://github.com/breezy-weather/breezy-weather/blob/main/HELP.md) document, or a feature described in the [Homepage](https://github.com/breezy-weather/breezy-weather/blob/main/docs/HOMEPAGE.md) document.
- [X] I have updated the app to **[version 5.1.3 or later](https://github.com/breezy-weather/breezy-weather/releases/latest)**.
- [X] I understand that this app is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY, so I may not get a positive reply to my request, if any at all.

**Comment by papjul** [comment]
Can you give more details? You want to use the Solar or Lunar calendar instead of Gregorian calendar everywhere in the app?

**Comment by papjul** [comment]
Also, I can't find anything about this in Android docs, what is it? We do have Chinese lunar calendar, I don't know if that's the same thing you're looking for?

**Comment by alr86** [comment]
https://en.m.wikipedia.org/wiki/Solar_calendar

For example, in the pictures below, the date is written in the Gregorian calendar

![sketch-1710532129270](https://github.com/breezy-weather/breezy-weather/assets/65030817/c66d821a-dd0c-4db2-bcda-fc5c99215985)
![sketch-1710532065642](https://github.com/breezy-weather/breezy-weather/assets/65030817/124ed93b-d726-417b-9971-a85af8c7d1b2)

Please add the ability to choose the solar and lunar calendar in the settings

**Comment by alr86** [comment]
As far as I know, Android supports only Gregorian date by default, and to use the solar or lunar calendar, you must use libraries or codes available on the Internet.

**Comment by papjul** [comment]
Android SDK does have support for one of the solar calendars you linked, the Julian calendar.

However, what you said raise questions:
1) What calendar does Android show you?
2) If it does show you dates in the Gregorian calendar, why would a weather app show a different calendar? This is confusing

**Comment by alr86** [comment]
I meant the Solar Hijri calendar that use in iran
https://en.m.wikipedia.org/wiki/Solar_Hijri_calendar

By default, Android shows the date in the Gregorian date and it cannot be changed, and in order to use the another calendar, I must to install a separate calendar software.
For example, today is the Gregorian calendar is 4/3/2024 But it is on Solar Hijri calendar is 26/12/1402
I want the program to write 26/12 instead of 4/3

**Comment by papjul** [comment]
Much clearer now.
It does exist in Android since v7.0 under the name `IslamicCalendar`: https://developer.android.com/reference/android/icu/util/IslamicCalendar
We can use the *civil* variant of this calendar.

More generally, we need something to handle all calendars that exist:
- ChineseCalendar
- CopticCalendar
- EthiopicCalendar
- GregorianCalendar
- HebrewCalendar
- IndianCalendar
- IslamicCalendar
- BuddhistCalendar
- JapaneseCalendar
- TaiwanCalendar

**Comment by papjul** [comment]
We can automatically set the correct calendar based on user preference:
https://developer.android.com/reference/kotlin/androidx/core/text/util/LocalePreferences.CalendarType
