### ISSUE TITLE
[Recosanté] The pollen card shows incorrect data

### ISSUE THREAD

**Issue by Vsnmrn** [breezy-weather/breezy-weather#817]
### Steps to reproduce

1 For a French city, select Recosanté as the source for pollens
2 Look at what the pollen card shows
3 Then tap on the pollen card to see more details

### Expected behavior

The data should not change between the card and the details tab.

### Actual behavior

The data displayed may differ. More specifically, I noticed that a pollen category ("cypress" on the screenshots) was displayed on the pollen card while its level indicates "risque nul" when viewing the details.
![Screenshot_20240317_131212_Breezy Weather_1](https://github.com/breezy-weather/breezy-weather/assets/146990829/8f6261a5-7988-434c-b4f5-3f36535b81c1)
![Screenshot_20240317_131223_Breezy Weather_1](https://github.com/breezy-weather/breezy-weather/assets/146990829/de84ed0b-7851-4538-9c60-54f243d98f34)
(PS: don't know why the pollen types are displayed in french on the card and in english in the details tab, maybe its another bug)

### Weather source used

Recosanté

### Breezy Weather version

5.1.5 - standard

### Android version

Android 14

### Device

Samsung A54

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I read the [Frequently Asked Questions](https://github.com/breezy-weather/breezy-weather/blob/main/HELP.md) document and followed instructions if relevant.
- [X] I have updated the app to **[version 5.1.5 or later](https://github.com/breezy-weather/breezy-weather/releases/latest)**.
- [X] I wrote my request in English, and any screenshot I attached are also in English (language can be changed from Settings > Appearance), unless my issue only happens with a specific language
- [X] I understand that this app is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY, so I may not get a positive reply to my request, if any at all.

**Comment by papjul** [comment]
I have the same bulletin as you, and I checked the API, the correct value is the one on the main screen (in case you wanted to know).

There are known issues when switching language. The workaround is to clear cache and restart app. If you were taking the screenshot in English just for the test, just switch back to French :p

I will investigate what's going on with the cypress.

**Comment by Vsnmrn** [comment]
What a quick response! I was answering you when the commit was displayed!

Thank you!
