### ISSUE TITLE
Weather data from previous used sources should be discarded

### ISSUE THREAD

**Issue by Vsnmrn** [breezy-weather/breezy-weather#818]
### Steps to reproduce

1. Change the pollen source at the bottom of the main screen. For example, switch from OpenMeteo to AccuWeather.
2. Look at what the pollen card shows.

### Expected behavior

Categories not supported by the new source should not be displayed.

### Actual behavior

Some pollen categories can be displayed while the new pollen source does not support this type of pollen. In this case, the pollen rate displays "null". This does not affect the details tab.
![Screenshot_20240317_131149_Breezy Weather_1](https://github.com/breezy-weather/breezy-weather/assets/146990829/1e003394-025c-4229-809d-0b42c50d34c7)
![Screenshot_20240317_131154_Breezy Weather_1](https://github.com/breezy-weather/breezy-weather/assets/146990829/abac2fc5-e8c3-4c00-8768-b0caab59cc91)

### Weather source used

AccuWeather, Recosanté

### Breezy Weather version

5.1.5 - standard

### Android version

Android 14

### Device

Samsung A54

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I read the [Frequently Asked Questions](https://github.com/breezy-weather/breezy-weather/blob/main/HELP.md) document and followed instructions if relevant.
- [X] I have updated the app to **[version 5.1.5 or later](https://github.com/breezy-weather/breezy-weather/releases/latest)**.
- [X] I wrote my request in English, and any screenshot I attached are also in English (language can be changed from Settings > Appearance), unless my issue only happens with a specific language
- [X] I understand that this app is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY, so I may not get a positive reply to my request, if any at all.

**Comment by papjul** [comment]
The bug can be easily fixed, however I wonder: should we really keep data from a different pollen source?

Basically, when refreshing, we restore any data missing from the API. This is mostly used to complete *yesterday* data because most API only give future forecast, not previous forecast. However, when source 1 has forecast for 15 days, and you switch to source 2 which has forecast for 5 days, you will get 10 days of forecast from source 1. This can be really confusing.

I think I will do it that way: if source changed, don't restore any data, including yesterday data.

**Comment by Vsnmrn** [comment]
Okay, if I understand correctly, the problem does not only affect the pollen but all the information. I think I agree with you on how to solve this problem.

Besides, since I deleted my locations and added them again, everything seems to be working properly.

**Comment by papjul** [comment]
You're right, workaround is to re-add locations for impacted users :)

**Comment by papjul** [comment]
Fixed as part of #1514
