### ISSUE TITLE
Complete layout change option

### ISSUE THREAD

**Issue by madisnormal** [breezy-weather/breezy-weather#823]
### Describe your idea

Would be nice to have one like in Carrot Weather on IOS. Then you'd make any app you want. I personally would love to have a Dark Sky copycat layout.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] My idea is not related to a question covered in the [Frequently Asked Questions](https://github.com/breezy-weather/breezy-weather/blob/main/HELP.md) document, or a feature described in the [Homepage](https://github.com/breezy-weather/breezy-weather/blob/main/docs/HOMEPAGE.md) document.
- [X] I have updated the app to **[version 5.1.5 or later](https://github.com/breezy-weather/breezy-weather/releases/latest)**.
- [X] I understand that this app is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY, so I may not get a positive reply to my request, if any at all.

**Comment by papjul** [comment]
I don't have Carrot Weather or iOS, I don't know what you expect?

We recently made some progress towards modularization with notably a WIP for the source backend #692. In the end, the idea is to allow other apps to re-use our source engine. Then, developers can make their own presentation of the weather data.

I don't know if that answers your question?

**Comment by madisnormal** [comment]
Yes, thank you!
