### ISSUE TITLE
Improve privacy of the "Send weather to other apps" feature

### ISSUE THREAD

**Issue by papjul** [breezy-weather/breezy-weather#828]
As discussed in #778, we should warn users that any app can intercept the intent data, including precise longitude and latitude, name of the location and if it is the current location of the user.

This is especially important if we make the option always available, independent of installed apps.

We should also probably ask Gadgetbridge team if it would be possible to not send location info, and only weather data. I think most users would prefer that way.

**Comment by papjul** [comment]
Hi @joserebelo,

I'm a bit concerned about a few fields that were added in WeatherSpec v4:
- `longitude`
- `latitude`
- `isCurrentLocation`

That feels like a very risky operation to create an intent with that info, as apps which were not granted location permission could intercept that intent, and we don't know what they could do with it.

What is it used for and is it worth the privacy risk?

Regarding the remaining location info: the location name. I believe it can be useful, so we could offer an option in Breezy Weather to hide (or not) that info. What does Gadgetbridge do when there is no location name info?

**Comment by joserebelo** [comment]
@papjul some watches request them - their firmware is closed-source, and we can't really control that. We can fake the data, but the isCurrentLocation field is very useful - especially once #501 is merged (I did not manage to revisit it yet, but I will soon).

However, this does raise a good point regarding privacy - I had not noticed that the intent is broadcast to all apps. Wouldn't it make more sense to send a targetted intent by setting the package name? We could either let the user pick what app to send it to, or alternatively send it to all installed known apps.

**Comment by papjul** [comment]
Is it possible to send an intent to a specific app and signature? I'm not familiar with that, I just happened to find a non-Gadgetbridge app that was using the `WeatherSpec` intent (for legit purposes).

**Comment by joserebelo** [comment]
Not the signature, but you can use `intent.setPackage` to send the intent to a specific package.

So in `GadgetBridgeService#sendWeatherBroadcast`, something like

```python
for (package in KNOWN_PACKAGES) {
    if isAvailable(package) {
        val intent = Intent(GB_INTENT_ACTION)
            .setPackage(package)
            .putExtra(GB_INTENT_EXTRA, encoded)
            .setFlags(Intent.FLAG_INCLUDE_STOPPED_PACKAGES)

        context.sendBroadcast(intent)
    }
}
```

I did not test this, but I believe that this should be enough for other unknown apps to not be able to intercept it, mitigating the privacy concerns.

As more apps are supported, one could argue that a user might want app X to get location but not app Y, which would would require some sort of allowlist.

**Comment by papjul** [comment]
Thanks for the code!

I'm a bit undecided as I would prefer the user decides which apps he sent to, so that we don't have to maintain an arbitrary list of allowed apps, but that requires saving multichoices and adding a new permission to list apps of the decide which seems a bit overkill given most people don't use that feature.

Merging this change would prevent other legit apps the user might have from accessing the data, so yeah, IDK what to do yet.

**Comment by joserebelo** [comment]
@papjul I've experimented a bit, and I think it's possible to auto-discover apps that support receiving the expected intent:

```
val intent = Intent(GB_INTENT_ACTION)
pm.queryBroadcastReceivers(intent, PackageManager.GET_RESOLVED_FILTER)
```

And according to https://developer.android.com/training/package-visibility/declaring#intent-filter-signature, I think we can also use something like this:

```xml
<intent>
    <action android:name="nodomain.freeyourgadget.gadgetbridge.ACTION_GENERIC_WEATHER" />
</intent>
```

In the queries list, so that it would not be necessary to maintain the list of apps manually.

I think this would allow to also populate the WidgetsSettingsScreen programatically with the list of discovered apps.

However, I am able to always discover Gadgetbridge, even when removing the existing package names, so I am not sure if I'm doing something wrong and couldn't validate that this would work properly.

**Comment by papjul** [comment]
Thank you for your investigation!

I don't think we need signature verification if the user selects by themself which apps they want to send to.

**Comment by papjul** [comment]
@joserebelo Implemented if interested. I also made some refactoring to extract some of the logic from the `GadgetbridgeService`. I could not merge the `WeatherSpec` v4 pull request before the refactoring as some questions were still pending, so you will get some conflicts when rebasing, but don't worry, I can take care of adapting the changes once all issues have been resolved ;)

![IMG_20240409_181654](https://github.com/breezy-weather/breezy-weather/assets/1449159/e7778dff-6202-4978-8524-cddbed311741)
