### ISSUE TITLE
Live Wallpaper preview only works on automatic

### ISSUE THREAD

**Issue by Shagon94** [breezy-weather/breezy-weather#831]
### Steps to reproduce

1. Go to live wallpaper
2. Set weather to anything, e.g. thunderstorm
3. Apply
4. See that the live wallpaper didn't change

### Expected behavior

The live wallpaper should change

### Actual behavior

Nothing changed

### Weather source used

AccuWeather

### Breezy Weather version

5.1.7_fdroid

### Android version

Android 14

### Device

S21 FE

### Other details

https://github.com/breezy-weather/breezy-weather/assets/9140783/efca22e5-9a77-4c35-9cee-100f229d239d

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I read the [Frequently Asked Questions](https://github.com/breezy-weather/breezy-weather/blob/main/HELP.md) document and followed instructions if relevant.
- [X] I have updated the app to **[version 5.1.7 or later](https://github.com/breezy-weather/breezy-weather/releases/latest)**.
- [X] I wrote my request in English, and any screenshot I attached are also in English (language can be changed from Settings > Appearance), unless my issue only happens with a specific language
- [X] I understand that this app is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY, so I may not get a positive reply to my request, if any at all.

**Comment by papjul** [comment]
Done in 43cda0a9fc4fe1e441c07364e2e834e952bc9444, will be available in next version
