### ISSUE TITLE
Allow setting the background per-location

### ISSUE THREAD

**Issue by Shagon94** [breezy-weather/breezy-weather#832]
### Describe your idea

Right now the background uses the current weather, however I really like the night versions versus the day versions of the background.

It would be nice if we could force a specific view.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] My idea is not related to a question covered in the [Frequently Asked Questions](https://github.com/breezy-weather/breezy-weather/blob/main/HELP.md) document, or a feature described in the [Homepage](https://github.com/breezy-weather/breezy-weather/blob/main/docs/HOMEPAGE.md) document.
- [X] I have updated the app to **[version 5.1.7 or later](https://github.com/breezy-weather/breezy-weather/releases/latest)**.
- [X] I understand that this app is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY, so I may not get a positive reply to my request, if any at all.

**Comment by papjul** [comment]
That could be a bit confusing "thunderstorms with grail" *shows a clear night sky* 😆, but why not. I had some feedback about some people not liking some backgrounds such as clear day being too bright. That could actually be a nice workaround.

I would do it per-location and not for the whole app. Some people may want to use it to distinguish locations between each other.

**Comment by papjul** [comment]
Done in 43cda0a9fc4fe1e441c07364e2e834e952bc9444, will be available in next version
