### ISSUE TITLE
Widget: Allow more modifications by the user

### ISSUE THREAD

**Issue by John-Gee** [breezy-weather/breezy-weather#851]
### Describe your idea

Hello,

(I don't know the rules for widgets so apologies if that cannot be done.)
It'd be nice to be able to edit the widget and replace part of it as wanted. Ie on the daily + weekly I can only get one subtitle data, why not allow us to add more if wanted? Or the Clock + Daily Details allow us to remove the clock.

It'd also be great if the widget could be scrollable as that would allow to pack a lot more information in a smaller container. Not that you should care but this is what I'd like to have in one widget to illustrate the need for scrolling: optionally the Clock, Daily Details (with the ability to remove some), hourly and weekly in the same format (though maybe that could be tabbed, not sure). If not, being able to  put the current app's homepage as a widget would be great too!

Thanks for your app and reading this!

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] My idea is not related to a question covered in the [Frequently Asked Questions](https://github.com/breezy-weather/breezy-weather/blob/main/HELP.md) document, or a feature described in the [Homepage](https://github.com/breezy-weather/breezy-weather/blob/main/docs/HOMEPAGE.md) document.
- [X] I have updated the app to **[version 5.1.7 or later](https://github.com/breezy-weather/breezy-weather/releases/latest)**.
- [X] I understand that this app is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY, so I may not get a positive reply to my request, if any at all.

**Comment by papjul** [comment]
There are separate widgets without the clock.

It's not possible to tab or scroll in widgets (at least I never saw it anywhere).

The custom subtitle allows you to input many information, so you can create your own bulletin if you’d like to. Especially given I seem to understand you are limited in space, so you could use the Text widget, with Hide header enabled. And then write down your own textual widget.

Let me know if that helps?

**Comment by John-Gee** [comment]
- I see no Daily + Details without a clock, unless I'm missing something, apologies if that is the case.

- I have the ability to scroll in various calendar widgets, unless that's specific to those types of widgets but not sure why that would be. For example this has it: https://github.com/andstatus/todoagenda
Not sure about tabs, I don't remember any widget using them right now so I'll trust you on that.

- Well I have seen that in the commit allowing it, but it seems to be limited to text then no? Or can I add the more visual information?


Thanks a lot for the super quick reply!

**Comment by papjul** [comment]
> I see no Daily + Details without a clock, unless I'm missing something, apologies if that is the case.

I believe you can have the same details by writing a custom subtitle in the Text widget.

> I have the ability to scroll in various calendar widgets, unless that's specific to those types of widgets but not sure why that would be. For example this has it: https://github.com/andstatus/todoagenda
> Not sure about tabs, I don't remember any widget using them right now so I'll trust you on that.

Alright, I didn't know. That's not very common. But it seems possible with list and grids from what I can see. Which info do you want to list?

> Well I have seen that in the commit allowing it, but it seems to be limited to text then no? Or can I add the more visual information?

If you want to make exactly your own widget with visual information, you will have to write your own widget. There are already many options of layout (way too many IMO). We have plans to rewrite widgets with dynamic layout based on the available space, but not in the short term.

**Comment by John-Gee** [comment]
> I believe you can have the same details by writing a custom subtitle in the Text widget.

That sounds good, I'll give it a try!

> Alright, I didn't know. That's not very common. But it seems possible with list and grids from what I can see. Which info do you want to list?

I was hopeful the whole widget could be scrollable, so if I want to make it 4x1 I can still see all the information that I would in a 4x4 but I'd have to scroll for that. From your comment maybe scrolling isn't that flexible though.

> If you want to make exactly your own widget with visual information, you will have to write your own widget. There are already many options of layout (way too many IMO). We have plans to rewrite widgets with dynamic layout based on the available space, but not in the short term.

Yup being able to make it myself if what I want, not by code but from the app's UI if that makes sense? Dynamic layout sounds great too, but complicated I understand.

Thanks a lot!

**Comment by papjul** [comment]
"No code"-like feature does not exist in the Android world to my knowledge, especially from the app itself. But maybe you have an example of app in mind?

I believe you can write the UI part within Android Studio, but will still have to write some code to connect the elements to the relevant data.
