### ISSUE TITLE
The date should be removed from the hourly weather forecast. It is stupid to have a date in the 24-hour forecast for today.

### ISSUE THREAD

**Issue by muyicheng** [breezy-weather/breezy-weather#855]
First of all, why do you need to delete it? It would be silly to have a date here because it's hourly and it's messy to look at the information, and you've already told me what time the temperature was. It should be concise.

![Screenshot_20240329_040142_org breezyweather](https://github.com/breezy-weather/breezy-weather/assets/1614228/36abbfde-262b-4028-bd95-c6c4c58e54b7)

Remove the area I circled. I already know that it is an hourly forecast, so why should I just look at the date here? If you have other ideas, I suggest you make a switch that allows people to turn it on or off freely, and see how many people will choose to turn it off.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] My idea is not related to a question covered in the [Frequently Asked Questions](https://github.com/breezy-weather/breezy-weather/blob/main/HELP.md) document, or a feature described in the [Homepage](https://github.com/breezy-weather/breezy-weather/blob/main/docs/HOMEPAGE.md) document.
- [X] I have updated the app to **[version 5.1.7 or later](https://github.com/breezy-weather/breezy-weather/releases/latest)**.
- [X] I understand that this app is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY, so I may not get a positive reply to my request, if any at all.

**Comment by papjul** [comment]
You need the date to know which date the hour it applies to.

You can easily guess on the first day that it's today, but when you scroll and you're on day 13 of a 16-day hourly-forecast, not so easily anymore.
