### ISSUE TITLE
The translation of each hour needs to be improved. Chinese people don't use "时" to indicate the weather at each hour.

### ISSUE THREAD

**Issue by muyicheng** [breezy-weather/breezy-weather#856]
### Describe your idea

The reason is that it is a matter of habit. The way of adding Chinese characters to numbers is very unintuitive. Most of the time, it is usually used directly. It is the same as the English world. For example, 6 o'clock is directly expressed as 6:00. The reason is that it is intuitive. So when expressing each hour, it is directly displayed as 6:00, 7:00, 8:00 like this. If it is 12 hours, it is directly expressed as: 上午（ Morning）8:00, 下午（afternoon）4:00, 晚上（ Evening）8:00.

We do not use the notation am, pm.

![Screenshot_20240329_042531_com miui weather2](https://github.com/breezy-weather/breezy-weather/assets/1614228/950e5497-ee62-420c-9414-0c458c163f3d)
![Screenshot_20240329_040117_org breezyweather](https://github.com/breezy-weather/breezy-weather/assets/1614228/6a114026-c3b1-4bd2-84df-6b4c2c36df7a)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] My idea is not related to a question covered in the [Frequently Asked Questions](https://github.com/breezy-weather/breezy-weather/blob/main/HELP.md) document, or a feature described in the [Homepage](https://github.com/breezy-weather/breezy-weather/blob/main/docs/HOMEPAGE.md) document.
- [X] I have updated the app to **[version 5.1.7 or later](https://github.com/breezy-weather/breezy-weather/releases/latest)**.
- [X] I understand that this app is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY, so I may not get a positive reply to my request, if any at all.

**Comment by papjul** [comment]
"时" dates back from Geometric Weather which was developer by a Chinese. No one seemed to have complained in years to my knowledge.
