### ISSUE TITLE
Small widgets (1x1) on OneUI 6.1 lock screen ("complications")

### ISSUE THREAD

**Issue by chengyuhui** [breezy-weather/breezy-weather#858]
### Describe your idea

Samsung's OneUI 6.1 introduced the ability to add widgets that are shown on the lock screen as well as AOD (just like what iOS does). See https://www.androidauthority.com/one-ui-6-1-features-unpacked-3405334/ for introduction.
They are just regular widgets (1x1 to 4x1, can not be taller than 1) with
```xml
<meta-data android:name="widgetStyle" android:value="complication"/>
```
which removes them from the normal widget selection view (only on OneUI 6.1) and enables them to be added to the lock screen.

However, they are much smaller than normal 1x1 widgets (the official weather app uses 56dp), which means that all the current available widgets can not be directly plugged into them.

I have been prototyping with this using a local copy of the main branch, it mostly works (except some weird theming that results the text being the same color as background):
![图片](https://github.com/breezy-weather/breezy-weather/assets/1381736/5db4bb85-86e9-497f-a47b-f46cff647852)
left is breezy weather, right is official.

Are you guys open to the idea of supporting this?

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] My idea is not related to a question covered in the [Frequently Asked Questions](https://github.com/breezy-weather/breezy-weather/blob/main/HELP.md) document, or a feature described in the [Homepage](https://github.com/breezy-weather/breezy-weather/blob/main/docs/HOMEPAGE.md) document.
- [X] I have updated the app to **[version 5.1.7 or later](https://github.com/breezy-weather/breezy-weather/releases/latest)**.
- [X] I understand that this app is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY, so I may not get a positive reply to my request, if any at all.

**Comment by papjul** [comment]
I can't find your local branch? I would like to read the code to understand what kind of technical changes you need. Thanks!

**Comment by chengyuhui** [comment]
Oops, forgot to upload.
https://github.com/chengyuhui/breezy-weather/tree/oneui-complication here you are.
I basically copied the M3 widget and made it (much) smaller, along with some new items in the manifest.

**Comment by chengyuhui** [comment]
![图片](https://github.com/breezy-weather/breezy-weather/assets/1381736/1ed1eb4c-e8f3-482a-a0ca-3ca1a8fd8898)
FYI, this is what the system weather app provides (they are separate widgets). My idea is that maybe we can provide a customizable 1x1 widget that displays a single user-customizable value (or temperature + weather), and make it adaptive so that it is also useful for non-Samsung users?

**Comment by papjul** [comment]
There are plans to have a resizable Material You - Current widget, see https://github.com/breezy-weather/breezy-weather/issues/316#issuecomment-1773518554

Let me know if that could fit?

For other current details, I have a widget in mind to have something similar and customizable such as what we do with the header of the main screen of the app. This will be done as part of the widget rework to make a cleaner implementation of widgets, allowing choosing which location and multiple widgets of the same widget, etc. We started making some state of art and mockups, but at the moment, no one has the time to look into it anymore. In the meantime, only small fixes are incorporated as we have too much technical debt to integrate new features/widgets.

**Comment by chengyuhui** [comment]
If it can be resized to 56 dp and the font size changes accordingly, I guess that would be fine.

The only thing left then is to figure out a way to get this into the lock screen without affecting normal usage: if you set `widgetStyle` to `complication`, it will no longer show up when adding widgets to the home screen. If we make two duplicate widgets and only mark one with that meta-data, it will confuse users that are not on OneUI 6.1.

Maybe we start with `android:enabled="false"`  and only enable them when we detected a compatible system?

**Comment by papjul** [comment]
The plan is to allow to reside down to 50 dp, so that would be perfect.

> Maybe we start with `android:enabled="false"` and only enable them when we detected a compatible system?

I'm not sure how that would work? Anyway, I don't think the resizable widget will come any time soon. Does a system like Smartspacer work for your use case? I know they can get Breezy Weather data and display them in "At a glance" widgets, not sure if that's the same thing/reusable for lockscreen.

**Comment by chengyuhui** [comment]
Smartspacer also does not allow resizing. Could you point me to the documentation on how I can receive weather data as a third-party app? I might write my own widget that is plugged into Breezy Weather.

**Comment by chengyuhui** [comment]
Based on my understanding, I would need to install one of the hard-coded apps for this feature to be available (though I will be able to receive that broadcast without problem), otherwise no broadcast would be sent. That's fine for now, though I hope that these related changes will land soon🥺

I'll try to see what I can make on my own.

**Comment by chengyuhui** [comment]
Closing for now, as this is probably better implemented as a separate project instead of cramming reverse-engineered device-specific features into a single app. I'll keep an eye on the progress of #828.
