### ISSUE TITLE
[OpenWeather] Duplicate alerts in Russia

### ISSUE THREAD

**Issue by SpiritOTHawk** [breezy-weather/breezy-weather#859]
### Steps to reproduce

1. Use any language other than English
2. Wait for alert of rain, wind, fog, etc

### Expected behavior

One alert in one language

### Actual behavior

![Screenshot_20240329-135754](https://github.com/breezy-weather/breezy-weather/assets/76490476/eeefd01d-4eca-4f30-8ae0-41ca28ec9951) 
![Screenshot_20240329-140707](https://github.com/breezy-weather/breezy-weather/assets/76490476/d3c4b564-e4df-4254-a97b-ec1b09fe94df)
Two identical alerts in different languages

### Weather source used

Open-Meteo (OpenWeather for alerts)

### Breezy Weather version

5.1.7-fdroid

### Android version

Android 14

### Device

Nothing Phone 1

### Other details

Nothing OS 2.5.3.A

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I read the [Frequently Asked Questions](https://github.com/breezy-weather/breezy-weather/blob/main/HELP.md) document and followed instructions if relevant.
- [X] I have updated the app to **[version 5.1.7 or later](https://github.com/breezy-weather/breezy-weather/releases/latest)**.
- [X] I wrote my request in English, and any screenshot I attached are also in English (language can be changed from Settings > Appearance), unless my issue only happens with a specific language
- [X] I understand that this app is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY, so I may not get a positive reply to my request, if any at all.

**Comment by papjul** [comment]
Everything is good on Breezy Weather side:

We pass the `lang` parameter:
![image](https://github.com/breezy-weather/breezy-weather/assets/1449159/566ab9fc-cd6e-4206-81ad-21c2a54a869e)

And OpenWeather gives us this data:
![image](https://github.com/breezy-weather/breezy-weather/assets/1449159/28e476e5-05c0-4a6a-96ea-1946f4c0bf0a)

Please contact them and let us know the result/when it is fixed:
https://home.openweathermap.org/questions

**Comment by SpiritOTHawk** [comment]
Open weather ignore me

**Comment by papjul** [comment]
OpenWeatherMap is deprecated in next version #934
