### ISSUE TITLE
Header details splits into multiple lines when Android text size is increased

### ISSUE THREAD

**Issue by NBA613** [breezy-weather/breezy-weather#86]
### Steps to reproduce

See wind text

### Expected behavior

Should always be written on one line

### Actual behavior

Is sometimes written on 2 or even 3 lines (Depending on direction? Or too many characters on a line?)
Correct:
![Screenshot_20230626-023808~2](https://github.com/breezy-weather/breezy-weather/assets/110447969/3b58267c-522b-4b58-9953-916515b206b1)
W
in
d:
![Screenshot_20230626-102544](https://github.com/breezy-weather/breezy-weather/assets/110447969/404b089a-23a3-4359-9a03-7768b3bdb1a5)
Wi
nd:
![Screenshot_20230626-023824~2](https://github.com/breezy-weather/breezy-weather/assets/110447969/de1f58e0-6299-4b8c-960d-4e7298d69573)
Win
d:
![Screenshot_20230626-023812~2](https://github.com/breezy-weather/breezy-weather/assets/110447969/8c1bfe3a-c8da-4a28-87c9-83f4e224a774)

### Weather provider used

Any

### Breezy Weather version

4.0.3-Alpha

### Android version

Android 13

### Device

Pixel 6 Pro

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to **[latest version](https://github.com/breezy-weather/breezy-weather/releases/latest)**.

**Comment by papjul** [comment]
Screenshot from the README.md is from a Pixel 6:
<img src="https://github.com/breezy-weather/breezy-weather/assets/1449159/8d85c798-89b9-41c2-8340-a3d7108bb9ff" width="250" />

Please tell us your customized accessibility settings.

**Comment by min7-i** [comment]
I'd assume that the Pixel 6 from which the screenshot was taken has a smaller text size than the default.

On my Pixel 6a (same resolution as Pixel 6) with default display settings it looks like this:
![Screenshot_20230628-173124.png](https://github.com/breezy-weather/breezy-weather/assets/97251923/802bff83-6f45-465e-86e7-29f997704aaa)

Increasing the text size once creates the wrap around for some of the texts in the header:
![Screenshot_20230628-173419.png](https://github.com/breezy-weather/breezy-weather/assets/97251923/627d2c0e-8c05-4b1f-9513-a77e9282334e)

And it also cuts some of the longer weather descriptions (here from Open-Meteo):
![Screenshot_20230628-173956.png](https://github.com/breezy-weather/breezy-weather/assets/97251923/8ac8a8bd-2c5b-4f2a-b101-d84ab9d839e1)


Setting for text size (one step higher than the default):
![Screenshot_20230628-173735.png](https://github.com/breezy-weather/breezy-weather/assets/97251923/abb46bb3-90c1-4a54-9ff0-59df9524faad)

**Comment by papjul** [comment]
> I'd assume that the Pixel 6 from which the screenshot was taken has a smaller text size than the default.

Yes, I believe it was something like that, that's why I asked for customized accessibility settings.

That seems like something you would mention that you changed your Android default text size when reporting issues about text size 😅

I'm not very familiar with accessibility, I will check what I can do. If I need to ellipsis, should I do it with the "Wind" part? I hope it will be enough.

**Comment by NBA613** [comment]
So Pixel 6 Pro is the same. Default font size is level 2 out of 4. With default, everything is ok. I had mine increased one level, hence the issue with "wind". It's up to you if you're willing to accommodate that. Thanks!

**Comment by papjul** [comment]
4cc84ac2a474b496e8bdb7f3bd8be50da123e732 should help a bit

**Comment by limonovthesecond2** [comment]
Same in 4.5.2-beta on Redmi Note 10 Pro. When the font size is increased, the text in the header is difficult to read.

### Default size:
![Screenshot_2023-08-08-14-49-57-426_com android settings](https://github.com/breezy-weather/breezy-weather/assets/118817903/c3f107a1-4e39-43ae-a030-6e75dc6985f1)
![Screenshot_2023-08-08-14-50-12-289_org breezyweather](https://github.com/breezy-weather/breezy-weather/assets/118817903/aa87be4a-b535-4f79-bcd0-8696e1f940f0)

### Increased by 1 size:
![Screenshot_2023-08-08-14-50-18-942_com android settings](https://github.com/breezy-weather/breezy-weather/assets/118817903/6d231f7a-be16-4e89-afc4-c1aea692ae3b)
![Screenshot_2023-08-08-14-50-24-202_org breezyweather](https://github.com/breezy-weather/breezy-weather/assets/118817903/64b0484c-4a27-4657-9522-7e368c0faeaa)
![Screenshot_2023-08-08-14-50-28-711_org breezyweather](https://github.com/breezy-weather/breezy-weather/assets/118817903/ca0af212-5d4a-4a57-9bbf-1d6846c2fdee)


### Increased by 2 size:
![Screenshot_2023-08-08-14-50-37-686_com android settings](https://github.com/breezy-weather/breezy-weather/assets/118817903/c7fee17d-f246-458a-a178-cf512d0079f4)
![Screenshot_2023-08-08-14-50-42-873_org breezyweather](https://github.com/breezy-weather/breezy-weather/assets/118817903/03ae39ef-f353-4339-81a6-bad83d378b5c)
![Screenshot_2023-08-08-14-50-54-611_org breezyweather](https://github.com/breezy-weather/breezy-weather/assets/118817903/cff0ef58-a1fb-4e13-a90d-b76f905689aa)

**Comment by papjul** [comment]
0fe265c1a8bc18a8491487c0587271a1b5aba32c implements a new design for current details in header.
![image](https://github.com/breezy-weather/breezy-weather/assets/1449159/fa97cc9a-5d03-4908-97f7-9b13018acd3c)

If 4 items don't fit in the header for you, you can choose to put only 3 in settings, so I will consider this as fixed.
