### ISSUE TITLE
Optional “check for updates”

### ISSUE THREAD

**Issue by papjul** [breezy-weather/breezy-weather#864]
Some users prefer not having to install an app just to get updates, so this option would help them receiving updates.

It should be disabled by default.

Design:
- Add in Settings > Background updates, two new options, one to check manually for updates, and one to automatically check for updates once a day
- Last check for app updates datetime will be saved and when the background weather update is executed, it will check if last check app updates was more than 24 hours. If that's the case, it will check for app updates. If weather updates are disabled, it will be checked upon app opening if last check was more than 24 hours ago.
- When tapping on the notification, it will open the GitHub release in the browser, Breezy Weather won't become a package manager app
- By default, it won't be enabled
- Since GitHub is a non-free network, this feature won't be available in the `freenet` flavor
- When user has added at least one location, and first location was added more than 24 hours ago, it will prompt the user if they want to be notified of updates. Why? Because if we ask immediately when not a single location was added yet, it means it's a new user, so they will want to try to use the app first to be sure they like it. If we ask too early, users will most likely dismiss the notification as they don't know yet if they will keep the app
- Must check for notification permission on Android >= 13 when tapping "Check for updates", enabling background checkes, or when asking after 24 hours of usage

**Comment by Marko-98** [comment]
I was just about the suggest this. It's annoying I have to follow GitHub for new releases, then download the APK, and then install it.

You should add ability by which would app periodically check for updates. When update is found, notification should be displayed. There should also be an update button somewhere in the app, which would download the APK package and when download finishes, prompt user to install the update.

I saw many apps have that feature.

**Comment by papjul** [comment]
How do you get updates for your other apps? Only using Play Store?

Obtainium is a nice way to get updates from multiple sources: GitHub, F-Droid repos, etc, so that could be useful to you for other apps than just Breezy Weather.

**Comment by Marko-98** [comment]
> How do you get updates for your other apps? Only using Play Store?

Yeah. I don't have many apps installed outside of Google Play. It has pretty much everything I need. I have only few apps installed outside of it and Breezy Weather is the only one that requires me to check GitHub from time to time. 

> Obtainium is a nice way to get updates from multiple sources: GitHub, F-Droid repos, etc, so that could be useful to you for other apps than just Breezy Weather.

Honestly, I don't feel it's worth installing Obtainium just so I could update Breezy Weather. 🙂

**Comment by PRO-2684** [comment]
+1 for this feature... I was still using v4.6 of Breezy Weather when I thought: Hey this app hasn't been updated since I installed it, has it been discontinued too? After checking GitHub did I know that it doesn't check for updates 😥

**Comment by papjul** [comment]
This feature won't be enabled by default for privacy reasons, so I'm not sure you would have noticed.

Usually, an app store is better suited for managing updates.

It's not that easy to self-update, requires additional permissions which may be unwanted by some people, has different implementations depending on Android version, so it might just end up being a notification in the end.

I'm more in the Unix philosophy where each package does its own job. Having Obtainium to manage the updates of only 1 app is more efficient than having each app having a module to manage their own updates. In both cases, it's a background work, but I trust Obtainium and their expertise more than I trust myself to manage that ;)

**Comment by min7-i** [comment]
I fully agree with that. Why should an app integrate an update mechanism when there are other apps whose main purpose is exactly that. Beyond that, supporting self-updates most likely means dealing with related issues in the future. If it were up to me, I'd rather like the developers to be able to focus their time on developing features which contribute to the main purpose of the app.

---

For inspiration though, Seal has an integrated [update utility](https://github.com/JunkFood02/Seal/blob/main/app/src/main/java/com/junkfood/seal/util/UpdateUtil.kt) that covers checking for updates on the respective GitHub repo as well as downloading and installing them. I didn't go through all the details, but maybe that helps. Even if it's just for the part to check for updates.

**Comment by whitewallman** [comment]
> How do you get updates for your other apps? Only using Play Store?
> 
> Obtainium is a nice way to get updates from multiple sources: GitHub, F-Droid repos, etc, so that could be useful to you for other apps than just Breezy Weather.

Pixel Xpert is a perfect example of an app that has a self-update option. I'm not a developer and don't know the nuts and bolts, but I believe it's an API that occasionally checks the developer's GitHub releases.

**Comment by papjul** [comment]
Yes, but it takes time to develop it, to support all Android versions (install mechanisms greatly varies, some Xiaomi roms also have specific stuff), while installing Obtainium or (if you really don't want an app) subscribing to GitHub releases takes you less than a minute. So yeah, a lot of effort for a very little gain.

Basically, anything that has an easy workaround is treated as low priority compared to other feature requests ;)

**Comment by whitewallman** [comment]
> Yes, but it takes time to develop it, to support all Android versions (install mechanisms greatly varies, some Xiaomi roms also have specific stuff), while installing Obtainium or (if you really don't want an app) subscribing to GitHub releases takes you less than a minute. So yeah, a lot of effort for a very little gain.
> 
> Basically, anything that has one or multiple easy workarounds is treated as low priority compared to other feature requests ;)

Wow! I didn't realize subscribing to releases was a thing! I'll look into that. Thank you very much!

**Comment by whitewallman** [comment]
Noob question: where in GitHub do I subscribe to new releases?

**Comment by papjul** [comment]
![image](https://github.com/breezy-weather/breezy-weather/assets/1449159/abec8e87-002b-49f5-93a8-ea1183a403c9)

**Comment by whitewallman** [comment]
N

>  @![image](https://private-user-images.githubusercontent.com/1449159/322207628-abec8e87-002b-49f5-93a8-ea1183a403c9.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTMwMTQ3MDksIm5iZiI6MTcxMzAxNDQwOSwicGF0aCI6Ii8xNDQ5MTU5LzMyMjIwNzYyOC1hYmVjOGU4Ny0wMDJiLTQ5ZjUtOTNhOC1lYTExODNhNDAzYzkucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDQxMyUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA0MTNUMTMyMDA5WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9MmYyNTY4NTU5NzUzZGEwMWEwZjYyMGNkNmY1MTcwMjBjNzhjODQ4NzZkYTA5NjE3NmZlMWU1NmEwNmRhM2ZmZCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.892nG1DbwockdxjrYc14hEMHrnVJb5p-lkNAqfnAwEo)

I may just be dense, but I'm not seeing a pins section. 🥴
![Screenshot_20240413-091943](https://github.com/breezy-weather/breezy-weather/assets/109869840/3ef9f695-0d42-4002-9ee2-933c2b7e4010)

**Comment by whitewallman** [comment]
Tyvm!!

**Comment by papjul** [comment]
I edited the first post to add the design I will try to implement in one of the next minor releases. Hopefully, this should ultimately reduce the number of users asking for support with a (very) old version

**Comment by min7-i** [comment]
I don’t know if this is more of an edge case, but there might be users who don’t have notifications enabled, so I’m wondering if it would make sense to check/ask for notification permissions when enabling the update check to ensure that they receive the update notification.

**Comment by papjul** [comment]
Thanks, added to the design description

**Comment by papjul** [comment]
PR #1186 open.

Remains to do:
- If weather updates are disabled, it will be checked upon app opening if last check was more than 24 hours ago.
- When user has added at least one location, and first location was added more than 24 hours ago, it will prompt the user if they want to be notified of updates. Why? Because if we ask immediately when not a single location was added yet, it means it's a new user, so they will want to try to use the app first to be sure they like it. If we ask too early, users will most likely dismiss the notification as they don't know yet if they will keep the app
   - Requires to think about the design so that it doesn't become an annoying popup users dismiss without reading

**Comment by papjul** [comment]
Implemented:
- It will always run when doing a weather update, whether it's on the foreground or background. If it's been less than 24 hours since last check, it's ignored.
- A card similar to the "Stay informed" is added to the location list to suggest to the user to enable it. It's displayed as soon as the notification permission is granted (so the "24 hours ago after adding first location" rule is not implemented). This might be tweaked to find a better implementation that will make most users enable it
