### ISSUE TITLE
Add source of alerts in alert details page

### ISSUE THREAD

**Issue by Yibuki** [breezy-weather/breezy-weather#865]
### Steps to reproduce

Alarts displayed in BreezyWeather:
![Screenshot_20240330-220806](https://github.com/breezy-weather/breezy-weather/assets/93418350/af8a8e7e-b46b-4e57-8fc8-12203e1cb2c2)
![Screenshot_20240330-220811](https://github.com/breezy-weather/breezy-weather/assets/93418350/1f5ca768-a947-4f33-be70-cd720bf85e09)

Alarts displayed in AccuWeather:
![Screenshot_20240330-220903](https://github.com/breezy-weather/breezy-weather/assets/93418350/557ef7a4-d402-4d07-a743-c2cd845dccd3)
![Screenshot_20240330-220912](https://github.com/breezy-weather/breezy-weather/assets/93418350/8f9847d6-67e0-4461-9770-d65356f6b8b2)
![Screenshot_20240330-220919](https://github.com/breezy-weather/breezy-weather/assets/93418350/b4a80291-e0fa-460b-8d2c-2d9028737ff6)

### Expected behavior

It may display the details of the alart, such as time, weather, source and map just like the data source if user clicked the alart icon.

### Actual behavior

The alart details won't be displayed after I clicked the alart icon except the alart time when checking weather in Japan.
*Alart details can be displayed in Chinese cities.

### Weather source used

AccuWeather

### Breezy Weather version

5.1.7_gplay

### Android version

Android 11

### Device

Xperia 1 II

### Other details

Sometimes, there's only one alart but it still be folded as alarts and need to click it to check.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I read the [Frequently Asked Questions](https://github.com/breezy-weather/breezy-weather/blob/main/HELP.md) document and followed instructions if relevant.
- [X] I have updated the app to **[version 5.1.7 or later](https://github.com/breezy-weather/breezy-weather/releases/latest)**.
- [X] I wrote my request in English, and any screenshot I attached are also in English (language can be changed from Settings > Appearance), unless my issue only happens with a specific language
- [X] I understand that this app is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY, so I may not get a positive reply to my request, if any at all.

**Comment by papjul** [comment]
I guess we can add the source of alert when we have it.

Regarding map, we have no plan to add alerts radar. See also this document: https://github.com/breezy-weather/breezy-weather/blob/main/docs/RADAR.md

**Comment by Yibuki** [comment]
> > It may display the details of the alart, such as time, weather, source and map just like the data source if user clicked the alart icon.
> 
> We already display start and end date/time.
> 
> Can you clarify "weather"?
> 
> I guess we can add the source of alert when we have it.
> 
> Regarding map, we have no plan to add alerts radar (it's not even showing the affected area on your example?). See also this document: https://github.com/breezy-weather/breezy-weather/blob/main/docs/RADAR.md

Thanks for your reply, and I believe that will be solved.  
Sometimes Japan Meteorological Agency will post some notices such as agriculture suggestions. It can be displayed on Accu but can't be loaded to Breezy. I thought that may be some issues appeared when loading data from Accu.

And another problem is that it is difficult to swipe left and right to switch cities due to the bouncing animation effect or touch sensitivity. Hope to repair it :)

**Comment by papjul** [comment]
> Sometimes Japan Meteorological Agency will post some notices such as agriculture suggestions. It can be displayed on Accu but can't be loaded to Breezy. I thought that may be some issues appeared when loading data from Accu.

I have no reason to think they wouldn't be displayed if they are in the description of the alert. Please open a new issue if you find anything.

> And another problem is that it is difficult to swipe left and right to switch cities due to the bouncing animation effect or touch sensitivity. Hope to repair it :)

Unfortunately, since there are horizontal swipes in the daily and hourly forecasts, we can't make it too easy to swipe to avoid accidental swiping while looking at daily/hourly forecast. It was a frustration point for many users, and swipe distances of 50% of the screen are common in apps, although some implements "quick swipe" that allows to swipe on shorter distances if it was done very fast. I have, unfortunately, no idea how to do that.

**Comment by Yibuki** [comment]
> > Sometimes Japan Meteorological Agency will post some notices such as agriculture suggestions. It can be displayed on Accu but can't be loaded to Breezy. I thought that may be some issues appeared when loading data from Accu.
> 
> I have no reason to think they wouldn't be displayed if they are in the description of the alert. Please open a new issue if you find anything.
> 
> > And another problem is that it is difficult to swipe left and right to switch cities due to the bouncing animation effect or touch sensitivity. Hope to repair it :)
> 
> Unfortunately, since there are horizontal swipes in the daily and hourly forecasts, we can't make it too easy to swipe to avoid accidental swiping while looking at daily/hourly forecast. It was a frustration point for many users, and swipe distances of 50% of the screen are common in apps, although some implements "quick swipe" that allows to swipe on shorter distances if it was done very fast. I have, unfortunately, no idea how to do that.

Aw, I got it. It's a really thoughtful feature.
Thanks for your reply and best wishes :)
