### ISSUE TITLE
Materiał You 4x2 widget doesn't open the app

### ISSUE THREAD

**Issue by witooski** [breezy-weather/breezy-weather#869]
### Steps to reproduce

1. Upgrade breezy weather to the latest version 5.1.8 through F-Droid
2. Add Material You 4x2 widget to your home screen
3. Click on the widget
4. Notice that nothing happens, the app doesn't open

### Expected behavior

Breezy Weather app should open upon clicking on the Material You 4x2 widget.

### Actual behavior

Nothing happens when Material You 4x2 widget is clicked on the newest version of Breezy Weather (5.1.8).
I even reinstalled the app twice and added widget a couple of times, but still no joy.
Everything works perfectly fine with the previous version of Breezy Weather app (5.1.7)

### Weather source used

Open-Meteo

### Breezy Weather version

5.1.8 f-droid gplay

### Android version

Android 14 - GrapheneOS

### Device

Google Pixel 8

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I read the [Frequently Asked Questions](https://github.com/breezy-weather/breezy-weather/blob/main/HELP.md) document and followed instructions if relevant.
- [X] I have updated the app to **[version 5.1.8 or later](https://github.com/breezy-weather/breezy-weather/releases/latest)**.
- [X] I wrote my request in English, and any screenshot I attached are also in English (language can be changed from Settings > Appearance), unless my issue only happens with a specific language
- [X] I understand that this app is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY, so I may not get a positive reply to my request, if any at all.

**Comment by papjul** [comment]
Fixed in f2741755d4bed915ff7f28cc277773639ad75691

**Comment by witooski** [comment]
Awesome, thank you very much!!!

**Comment by mokazemi** [comment]
Thanks for solving it!
Does it also solve it's shape and size?
Since it used to be 3×2 now it's 4×2.

**Comment by papjul** [comment]
Please follow #316 for further improvements

**Comment by GABRIEL08-N** [comment]
In the future update we can change the size to 2x2

**Comment by papjul** [comment]
The minimum size is 3x1 if I remember correctly

**Comment by GABRIEL08-N** [comment]
> The minimum size is 3x1 if I remember correctly

But I want 2x2 because I have another widget next to it and it has no place

**Comment by papjul** [comment]
Have a look at the "Material You - Forecast" widget

**Comment by GABRIEL08-N** [comment]
Yes, but I don't like it

**Comment by GABRIEL08-N** [comment]
I want this one 
![Uploading Screenshot_20240404-131319.png…]()

**Comment by papjul** [comment]
Sorry, it is a 3x3 widget. Have a look at Square Home launcher if you want to force different sizes

**Comment by GABRIEL08-N** [comment]
> Sorry, it is a 3x3 widget. Have a look at Square Home launcher if you want to force different sizes

I understand, so I can't thank you anyway

**Comment by GABRIEL08-N** [comment]
> Sorry, it is a 3x3 widget. Have a look at Square Home launcher if you want to force different sizes

I understand, so I can't thank you anyway

**Comment by papjul** [comment]
Next update will make the widget adapt to its frame, down to 2x2 size. It's only possible from Android >= 12.

**Comment by GABRIEL08-N** [comment]
> Next update will make the widget adapt to its frame, down to 2x2 size. It's only possible from Android >= 12.

Glad to hear that I have android 14

**Comment by witooski** [comment]
> Next update will make the widget adapt to its frame, down to 2x2 size. It's only possible from Android >= 12.

Can you please let us know when we can expect the next update to show up? I find myself keep clicking the widget just to realize I need to open the weather app until we have new version available :)
Thanks!

**Comment by GABRIEL08-N** [comment]
> > Next update will make the widget adapt to its frame, down to 2x2 size. It's only possible from Android >= 12.
> 
> Can you please let us know when we can expect the next update to show up? I find myself keep clicking the widget just to realize I need to open the weather app until we have new version available :)
> Thanks!

Yes, nothing was heard, anyway we were waiting, we have nothing to do 🫡
