### ISSUE TITLE
Timezone of “Current location” not updating when device timezone is changed (on sources without reverse geocoding)

### ISSUE THREAD

**Issue by xill47** [breezy-weather/breezy-weather#870]
### Steps to reproduce

1. Be in Europe (local timezone equalient to UTC+1)
2. Go to Japan (UTC+9)
3. Open "Current location" screen
4. (Optional) Refresh 

### Expected behavior

Sunrise at 5:28

### Actual behavior

Sunrise at 21:28 (as if I am viewing it in my previous local timezone) 

![Screenshot_2024-03-31-21-01-38-31](https://github.com/breezy-weather/breezy-weather/assets/3391834/74566633-09c5-4e58-bfe5-6dde952ae24d)

### Weather source used

Default, Open-Meteo

### Breezy Weather version

5.1.8 (from Obtanium/Github) 

### Android version

Android 14

### Device

OnePlus 8T

### Other details

Location seems to be correct since I see the same weather forecast

When manually adding Tokyo, sunrise time is correct

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I read the [Frequently Asked Questions](https://github.com/breezy-weather/breezy-weather/blob/main/HELP.md) document and followed instructions if relevant.
- [X] I have updated the app to **[version 5.1.8 or later](https://github.com/breezy-weather/breezy-weather/releases/latest)**.
- [X] I wrote my request in English, and any screenshot I attached are also in English (language can be changed from Settings > Appearance), unless my issue only happens with a specific language
- [X] I understand that this app is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY, so I may not get a positive reply to my request, if any at all.

**Comment by papjul** [comment]
Unfortunately, Open-Meteo does not support reverse geocoding at the moment, so for current location, we take the timezone from your device, which should be the same.

I'm not sure if you report this issue with a device using the Europe timezone while you are in Japan, or if you report that you changed the timezone on your device and it’s not updated on current location? On the latter case, you can just delete the location, and recreate it as a workaround.

(Btw, it's not just rise/set times, all forecast is shifted)

**Comment by xill47** [comment]
My devices timezone was automatically changed. I did re-set it manually in the settings and the screen is the same. 

I can live with this weird timezone shift for now. Would it help if I test if it will shift back when I return to (changed because of DST) UTC+2?

**Comment by papjul** [comment]
> I can live with this weird timezone shift for now.

I would not recommend, this shifts some calculations that are day-based.

> Would it help if I test if it will shift back when I return to (changed because of DST) UTC+2?

If your device is -let’s say- Europe/Berlin, it will automatically handle switching between UTC+1 and UTC+2, so you shouldn't have any issue when you go back.
