### ISSUE TITLE
[Open-Meteo] Pollen data is missing a day

### ISSUE THREAD

**Issue by min7-i** [breezy-weather/breezy-weather#872]
### Steps to reproduce

1. Add the location "Hamburg".
2. Use Open-Meteo as main source and as source for pollen data.
3. Check the pollen card.
4. On the 31.03.2024 it shows data for the 30.03.2024

### Expected behavior

Pollen data for the 31.03.2024 is shown.

Open-Meteo does provide data for this day ([link](https://open-meteo.com/en/docs/air-quality-api/#latitude=53.5507&longitude=9.993&hourly=pm10,pm2_5,birch_pollen,grass_pollen&timezone=Europe%2FBerlin)):
![grafik](https://github.com/breezy-weather/breezy-weather/assets/97251923/ad57bea7-1f83-4bd8-bd89-e2eae6f9bb57)

### Actual behavior

The pollen card shows data for 30.03.2024 although today is the 31.03.2024. The 31.03. is missing in the list of pollen data. The 30.03. is followed by the 01.04.2024. See screenshots below under _other details_.

### Weather source used

Open-Meteo

### Breezy Weather version

5.1.8-standard

### Android version

Android 14 (GrapheneOS)

### Device

Google Pixel 6a

### Other details

When adding Hamburg as a new location and choosing Bright-Sky as the main source while keeping Open-Meteo as source for pollen, it correctly shows pollen data for the 31.03.2024 on the 31.03.2024.

<details>

<summary>screenshots</summary>

| Open-Meteo | Bright-Sky & Open-Meteo |
| --- | --- |
| ![Open-Meteo](https://github.com/breezy-weather/breezy-weather/assets/97251923/047b50ef-c42e-40ce-bd18-9708a54850b8) | ![Bright Sky_Open-Meteo](https://github.com/breezy-weather/breezy-weather/assets/97251923/66ae8dc2-f05b-4ba9-b497-60d67442d032) |

</details>

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I read the [Frequently Asked Questions](https://github.com/breezy-weather/breezy-weather/blob/main/HELP.md) document and followed instructions if relevant.
- [X] I have updated the app to **[version 5.1.8 or later](https://github.com/breezy-weather/breezy-weather/releases/latest)**.
- [X] I wrote my request in English, and any screenshot I attached are also in English (language can be changed from Settings > Appearance), unless my issue only happens with a specific language
- [X] I understand that this app is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY, so I may not get a positive reply to my request, if any at all.

**Comment by papjul** [comment]
I can't reproduce with a freshly added Hamburg, but I'm almost sure it's related to #543, since we construct the daily date with the date at 00:00 given by the Open-Meteo server.

Don't you have the wrong day also showing in the daily forecast?

**Comment by papjul** [comment]
Maybe I should always add 1 hour to the date provided by Open-Meteo server, and then set `HOUR = 0` to this new date. Dirty but would fix the mess that happens when we have a mix of old data from refresh before DST and refresh after DST.

**Comment by papjul** [comment]
> Don't you have the wrong day also showing in the daily forecast?

Ah yes, of course you don’t have the issue, because you use Bright Sky as your main source!

And since Bright Sky data is correct, but not Open-Meteo's, it creates a big mess :S

**Comment by papjul** [comment]
Workarounded, will have to wait for next DST to confirm the fix.

**Comment by min7-i** [comment]
> ... will have to wait for next DST to confirm the fix.

Adding e.g. Hamburg as a new location with Open-Meteo as main source today also caused this issue where 31.03. is missing. With your commit it also shows the 31.03., so I'd say that it fixed it 👍
