### ISSUE TITLE
[Open-Meteo, Ukraine] - missing day 2024-03-31

### ISSUE THREAD

**Issue by Veraellyunjie** [breezy-weather/breezy-weather#873]
### Steps to reproduce

Add a location in Ukraine, e.g. Kyiv
See daily forecast

### Expected behavior

day order: 03/30 03/31 04/01 ...

### Actual behavior

day order misses 03/31: 03/30 04/01 ...
(screenshot is not Kyiv, it's Kherson)
![Screenshot_20240331-211813_Breezy Weather](https://github.com/breezy-weather/breezy-weather/assets/75799052/a88b71f5-771a-4537-a7ad-ae612f1130f1)

### Weather source used

Open-Meteo

### Breezy Weather version

5.1.8 Izzy

### Android version

Android 8 and Android 10

### Device

AGM A9 and Samsung J6+

### Other details

I tried Open-Meteo for other countries - 03/31 is present
I tried switching to AccuWeather for Ukraine - 03/31 is present
I tried 3 Ukrainian cities with Open-Meteo - 03/31 is absent
I understand it might be Open-Meteo issue, not Breezy Weather's

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I read the [Frequently Asked Questions](https://github.com/breezy-weather/breezy-weather/blob/main/HELP.md) document and followed instructions if relevant.
- [X] I have updated the app to **[version 5.1.8 or later](https://github.com/breezy-weather/breezy-weather/releases/latest)**.
- [X] I wrote my request in English, and any screenshot I attached are also in English (language can be changed from Settings > Appearance), unless my issue only happens with a specific language
- [X] I understand that this app is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY, so I may not get a positive reply to my request, if any at all.

**Comment by papjul** [comment]
Same issue as #543 and #872, it's related to DST being wrongly handled on Open-Meteo side, it will be workarounded in next version. However, by the time it will be released, it will only be useful for next DST change in October.
