### ISSUE TITLE
Notification Widget Stuck On Some Other Style 

### ISSUE THREAD

**Issue by HonestAbe7** [breezy-weather/breezy-weather#874]
### Steps to reproduce

I go into my settings in the app and go to the widget section. Then I click the widget styles. I had it on daily forecast but I think 2 updates ago it went away and I just noticed. 

### Expected behavior

The daily forecast was shown in my notifications but not now.

### Actual behavior

Daily forecast not shown and not even any of the different styles are shown when I try to change to them.

### Weather source used

AccuWeather and now NWS too

### Breezy Weather version

5.1.7

### Android version

Android 10

### Device

LG355DL

### Other details

I had it on daily forecast but I think 2 updates ago it went away and just noticed. 

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I read the [Frequently Asked Questions](https://github.com/breezy-weather/breezy-weather/blob/main/HELP.md) document and followed instructions if relevant.
- [X] I have updated the app to **[version 5.1.8 or later](https://github.com/breezy-weather/breezy-weather/releases/latest)**.
- [X] I wrote my request in English, and any screenshot I attached are also in English (language can be changed from Settings > Appearance), unless my issue only happens with a specific language
- [X] I understand that this app is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY, so I may not get a positive reply to my request, if any at all.

**Comment by papjul** [comment]
Can you update to v5.1.8?

What are the steps to reproduce? I just enabled the notification-widget, tried to change the style, go back to "Daily", no issue noticed, the notification is correctly set in my notification bar.

**Comment by HonestAbe7** [comment]
Looks like the daily widget came back but please still look into this.

**Comment by papjul** [comment]
I can look into it, but you need to answer to my two questions.

**Comment by HonestAbe7** [comment]
I did update to the current version. Seems like all is well. Not sure what was going on.
