### ISSUE TITLE
Widget Is Chopped Off

### ISSUE THREAD

**Issue by HonestAbe7** [breezy-weather/breezy-weather#875]
### Steps to reproduce

I just installed the updated version 5.1.8 and noticed this.

### Expected behavior

The widget should not have changed to where it is chopped off.

![Screenshot_20240331-150828](https://github.com/breezy-weather/breezy-weather/assets/88217236/e9894fe4-ad72-4a06-b62e-a91646c3e25d)

### Actual behavior

Widget is chopped off

### Weather source used

AccuWeather and now NWS too

### Breezy Weather version

5.1.8

### Android version

Android 10

### Device

LG355DL

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I read the [Frequently Asked Questions](https://github.com/breezy-weather/breezy-weather/blob/main/HELP.md) document and followed instructions if relevant.
- [X] I have updated the app to **[version 5.1.8 or later](https://github.com/breezy-weather/breezy-weather/releases/latest)**.
- [X] I wrote my request in English, and any screenshot I attached are also in English (language can be changed from Settings > Appearance), unless my issue only happens with a specific language
- [X] I understand that this app is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY, so I may not get a positive reply to my request, if any at all.

**Comment by papjul** [comment]
What does the Google weather widget look like with the same dimensions?

**Comment by HonestAbe7** [comment]
The widget is not clickable but in the previous version it is. I appreciate the larger font in the current version.

**Comment by papjul** [comment]
You didn't answer the question, does the Google Weather widget have the same issue?

**Comment by HonestAbe7** [comment]
What Google Weather widget are you talking about?

**Comment by papjul** [comment]
"Material You - Current" is based on Google weather widget.
In v5.1.8, we made it look closer to Google widget, as requested in #316, so I see no issue here, except maybe that we don't support resizing to smaller widget shape (yet).

**Comment by HonestAbe7** [comment]
Ok. I thought the whole idea behind open source was to get away from and not be like Google? 

But yes, if you could in future versions resize the widget that would be great.

**Comment by papjul** [comment]
> I thought the whole idea behind open source was to get away from and not be like Google?

No, open source is defined by OSI here: https://opensource.org/osd
There's nothing discriminating against big companies. Remember Android is open source and belongs to Google.

This widget was made by the previous developer from the Google widget. If it was just me, I would not have done it, and I would just remove it as I don't particularly like this widget, but it's very popular so I try to keep it up-to-date with the Google widget (with a low priority though).

I proceed to close, please follow future developments of this widget will be on #316
