### ISSUE TITLE
Add Optional Refresh Button on Widget

### ISSUE THREAD

**Issue by Tanmandal** [breezy-weather/breezy-weather#879]
### Describe your idea

Add an optional refresh button on widget to refresh weather data from widget . It will be helpful if someone don't want the app running in the background to automatically refresh.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] My idea is not related to a question covered in the [Frequently Asked Questions](https://github.com/breezy-weather/breezy-weather/blob/main/HELP.md) document, or a feature described in the [Homepage](https://github.com/breezy-weather/breezy-weather/blob/main/docs/HOMEPAGE.md) document.
- [X] I have updated the app to **[version 5.1.8 or later](https://github.com/breezy-weather/breezy-weather/releases/latest)**.
- [X] I understand that this app is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY, so I may not get a positive reply to my request, if any at all.

**Comment by papjul** [comment]
The widget does not rely on the background refresh to update. Manual refreshes also work.

Also read FAQ: https://github.com/breezy-weather/breezy-weather/blob/main/HELP.md#can-you-make-weather-refresh-less-than-every-30-minutes--every-time-i-open-the-app--every-time-i-tap-on-widget--every-time-i-unlock-my-phone--every-second
