### ISSUE TITLE
Temperature value alignment

### ISSUE THREAD

**Issue by nvllz** [breezy-weather/breezy-weather#88]
### Steps to reproduce

Just open the app.. :D

### Expected behavior

The main value is expected to be centered correctly. Probably meant to be 33% for each 'tile', but for me it rendered as 32% here.

![breezy-w_200iq](https://github.com/breezy-weather/breezy-weather/assets/110673332/d435f57f-26e9-4bec-9aa3-3bda4aa0bbab)

### Actual behavior

![breezy-w](https://github.com/breezy-weather/breezy-weather/assets/110673332/689392dd-7866-4467-8a7f-5f957ea150f8)

### Weather provider used

n/a

### Breezy Weather version

4.0.4-alpha_fdroid

### Android version

Android 10

### Device

Galaxy s9+

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to **[latest version](https://github.com/breezy-weather/breezy-weather/releases/latest)**.

**Comment by papjul** [comment]
Temperature **value** is centered, it's temperature value **with unit** that is not centered.
It is an intended behavior to have temperature value centered above weather text.
On your first screenshot, temperature feels too much aligned on the left.

**Comment by papjul** [comment]
Search for "Weather app" on Google Images, you will see that ALL apps are only centering the value, without unit (or at least after tens of results I couldn't find an app with what you are asking).

Among results, I found one with an interesting implementation, see Xiaomi Weather app: https://play.google.com/store/apps/details?id=com.miui.weather2

What do you think?

**Comment by papjul** [comment]
Added in ea599eb0951e047dd09552af1a4375079dc6598d
