### ISSUE TITLE
[Android < 8.1] Widget clock + daily (vertical) crash

### ISSUE THREAD

**Issue by MaSHiNiK** [breezy-weather/breezy-weather#882]
### Steps to reproduce

1. Open widget menu
2. Drag "clock + daily (vertical)" widget to home screen

https://github.com/breezy-weather/breezy-weather/assets/80310257/e7576e75-29ed-4de3-a394-7f16c6a90540

### Expected behavior

The widget should be installed on the home screen

### Actual behavior

The widget settings window opens and instantly crashes or crashes before the menu is opened

### Weather source used

OpenMeteo

### Breezy Weather version

5.1.8-Standart-arm64-v8a

### Android version

Android 8.0

### Device

Huawei MediaTab t5 10

### Other details

The problem arose after I updated to version 1.5.8, I already had this widget on my home screen and after the update it only started showing notifications: "widget cannot load". 
Here is crash log:
[breezyweather_crash_logs.txt](https://github.com/breezy-weather/breezy-weather/files/14833533/breezyweather_crash_logs.txt)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I read the [Frequently Asked Questions](https://github.com/breezy-weather/breezy-weather/blob/main/HELP.md) document and followed instructions if relevant.
- [X] I have updated the app to **[version 5.1.8 or later](https://github.com/breezy-weather/breezy-weather/releases/latest)**.
- [X] I wrote my request in English, and any screenshot I attached are also in English (language can be changed from Settings > Appearance), unless my issue only happens with a specific language
- [X] I understand that this app is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY, so I may not get a positive reply to my request, if any at all.

**Comment by papjul** [comment]
Looks like there is a race condition on low Android versions: https://issuetracker.google.com/issues/300280216
I will bump the dependency version as soon as it's available.

Can you retry multiple times and see if it works at some point?

**Comment by 2013ZRZ** [comment]
Similarly, my device doesn't work properly with this Widget. When I open the Settings and set this Widget, it will restart immediately.

And the Live Wallpaper displayed all black.(This is an other bug.)

* Device: Honor 6A DLI-AL10
* System: EMUI 5.1.3 (Android 7.0 Nougat)
* Breezy Weather version: 5.1.8-Standard-armeabi-v7a
* Weather source used: AccuWeather

**Comment by MaSHiNiK** [comment]
> Looks like there is a race condition on low Android versions: https://issuetracker.google.com/issues/300280216 I will bump the dependency version as soon as it's available.
> 
> Can you retry multiple times and see if it works at some point?

I tried it about 10 times, the result is the same.

**Comment by papjul** [comment]
They say a fix is coming in the next few days. I will update and make a new release as soon as I can.

More generally, if you have the opportunity to look for more unofficial recent Android versions of your device, that would be better on a lot of aspects

**Comment by papjul** [comment]
Can you try v5.2.0?

**Comment by MaSHiNiK** [comment]
> Can you try v5.2.0?

Yep, widget now work fine
