### ISSUE TITLE
[Alert page] Status bar black text on dark background when theme is light with day/night mode enabled

### ISSUE THREAD

**Issue by itsHenry35** [breezy-weather/breezy-weather#883]
### Steps to reproduce

Open alerts
![Screenshot_20240402-181211_Breezy Weather](https://github.com/breezy-weather/breezy-weather/assets/58730749/0fe0091a-dfb6-4f81-ba3f-6ac0fa55bbe1)

### Expected behavior

should be light mode with light darkground

### Actual behavior

dark mode with weird status bar

### Weather source used

Accuweather

### Breezy Weather version

5.1.8

### Android version

Android 14

### Device

Xiaomi Marble

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I read the [Frequently Asked Questions](https://github.com/breezy-weather/breezy-weather/blob/main/HELP.md) document and followed instructions if relevant.
- [X] I have updated the app to **[version 5.1.8 or later](https://github.com/breezy-weather/breezy-weather/releases/latest)**.
- [X] I wrote my request in English, and any screenshot I attached are also in English (language can be changed from Settings > Appearance), unless my issue only happens with a specific language
- [X] I understand that this app is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY, so I may not get a positive reply to my request, if any at all.

**Comment by papjul** [comment]
Please screenshot `Settings` > `Appearance` in English.

What does main screen look like?

**Comment by itsHenry35** [comment]
> Please screenshot `Settings` > `Appearance` in English.
> 
> What does main screen look like?
> 
> Is it normal there is a yellow tint on your screenshot? Could the cause be external to the app?

![Screenshot_20240402-184045_Breezy Weather](https://github.com/breezy-weather/breezy-weather/assets/58730749/1f5ab461-b7fa-430a-973a-2d798d9bc6ab)
![Screenshot_20240402-184030_Breezy Weather](https://github.com/breezy-weather/breezy-weather/assets/58730749/9ebc59ce-881b-4284-8ea6-05c9e06622a8)

**Comment by papjul** [comment]
Thanks, I can reproduce with System preference = Light theme, and Day/Night mode for locations enabled.

**Comment by papjul** [comment]
Fixed in v5.2.3
