### ISSUE TITLE
Value for mould is always at 32767

### ISSUE THREAD

**Issue by eku** [breezy-weather/breezy-weather#884]
### Steps to reproduce

1. Choose AccuWeather as source
2. Select Munich as location
3. Show card for "Pollen and mould"

### Expected behavior

Value for mould shows real value or N/A if not available.

### Actual behavior

Value for mould is always at 32767 (=> 2^15 - 1)

![schimmel](https://github.com/breezy-weather/breezy-weather/assets/418685/933a9477-cf02-41b7-9ed2-876ea3585fc5)

### Weather source used

AccuWeather

### Breezy Weather version

5.1.7 (no newer version on IzzyOnDroid Repo via F-Droid)

### Android version

AOSP 13

### Device

Chinese brand

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I read the [Frequently Asked Questions](https://github.com/breezy-weather/breezy-weather/blob/main/HELP.md) document and followed instructions if relevant.
- [X] I have updated the app to **[version 5.1.8 or later](https://github.com/breezy-weather/breezy-weather/releases/latest)**.
- [X] I wrote my request in English, and any screenshot I attached are also in English (language can be changed from Settings > Appearance), unless my issue only happens with a specific language
- [X] I understand that this app is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY, so I may not get a positive reply to my request, if any at all.

**Comment by papjul** [comment]
That's a known bug for years on AccuWeather side. Nothing we can do on our side.

**Comment by eku** [comment]
> That's a known bug for years on AccuWeather side. 

Is it expected that the bug will be corrected?

> Nothing we can do on our side.

What do you think about completely hiding the value in such a case?

**Comment by papjul** [comment]
> Is it expected that the bug will be corrected?

I have no idea, but I wouldn't expect much after all these years.

> What do you think about completely hiding the value in such a case?

So:
- Monday: 15000
- Tuesday: no value
- Wednesday: 5000
- etc

User will think it's 0 on Tuesday. Even if the user don't know the exact value, they still know it's a high value and they need to take care of them if they are affected by mold allergies.
