### ISSUE TITLE
Daily graph of feels like shows temperature values

### ISSUE THREAD

**Issue by Zahrun** [breezy-weather/breezy-weather#897]
### Steps to reproduce

Check daily temperature and feels like graph, they show the same values although values are actually different and graphs have different shapes

### Expected behavior

Feels like daily graph should display feels like values

### Actual behavior

Temperature values are shown

### Weather source used

AccuWeather

### Breezy Weather version

5.1.8-standard

### Android version

/e/ OS 1.21.1-s

### Device

Fairphone 4

### Other details

![Screenshot_20240326-143228_Breezy Weather](https://github.com/breezy-weather/breezy-weather/assets/10415894/cd51b9c4-e51d-4b9f-ab04-ab02bb761c70)
![Screenshot_20240326-143236_Breezy Weather](https://github.com/breezy-weather/breezy-weather/assets/10415894/f67e326c-b8f3-4cf3-a4b3-0312279eb259)
![Screenshot_20240326-143311_Breezy Weather](https://github.com/breezy-weather/breezy-weather/assets/10415894/94f0a85b-9ada-4aa9-b753-277d0423c277)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I read the [Frequently Asked Questions](https://github.com/breezy-weather/breezy-weather/blob/main/HELP.md) document and followed instructions if relevant.
- [X] I have updated the app to **[version 5.1.8 or later](https://github.com/breezy-weather/breezy-weather/releases/latest)**.
- [X] I wrote my request in English, and any screenshot I attached are also in English (language can be changed from Settings > Appearance), unless my issue only happens with a specific language
- [X] I understand that this app is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY, so I may not get a positive reply to my request, if any at all.

**Comment by papjul** [comment]
Your analysis is correct, the chart is correct but the numbers displayed on the chart are not the feels like temperatures. The fix will be available in v5.1.9.

**Comment by Zahrun** [comment]
Thank you ♥
