### ISSUE TITLE
Enable Widget to Open Alternative Calendar Apps

### ISSUE THREAD

**Issue by ImranR98** [breezy-weather/breezy-weather#90]
### Describe your suggested feature

Tapping on the date in the widget currently opens the default calendar app, which may not be what the user wants. For example, the only calendar app that comes with GrapheneOS is the default AOSP app which is very outdated - I'd like to use the ProtonMail app instead.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to **[latest version](https://github.com/breezy-weather/breezy-weather/releases/latest)**.

**Comment by papjul** [comment]
Breezy Weather doesn't open in default calendar app, it's your Android system that does. Breezy Weather just asks to view calendar, your system is answering the request. Don't you have the same "issue" with other apps?

Few things to try:
1) Reset Graphene OS calendar default app preference (in Opened links Android app settings)
2) Disable Graphene OS calendar app
3) Report an issue to Graphene OS
4) Change ROM

![Screenshot_20230629-073807_Android System](https://github.com/breezy-weather/breezy-weather/assets/1449159/207eed06-d7d4-4b31-8a5b-af32fbfc5d4e)

**Comment by min7-i** [comment]
I use Etar calendar as default calendar app on GrapheneOS and tapping on the date of the Breezy Weather widget opens Etar. So, I wouldn't say that it's related to GrapheneOS.

However, it seems that Proton Calendar cannot be set as default. There's already an [idea](https://protonmail.uservoice.com/forums/932842-proton-calendar/suggestions/45333130-allow-proton-calendar-to-be-set-as-default-calenda) on Protonmail's uservoice to add this feature.

Not sure if that's the one with the most upvotes or if there are similar suggestions with more votes. But that's the one I found with a quick search.
