### ISSUE TITLE
[Clock Widgets] Time zone not updated with system

### ISSUE THREAD

**Issue by jaydenlo08** [breezy-weather/breezy-weather#904]
### Steps to reproduce

1. Add any widgets containing a clock
2. Change the time zone of your phone manually or automatically

### Expected behavior

The time zone of the clock widget should reflect the system's time zone.

### Actual behavior

The clock widget remains at the old time zone.
Restarting app  / force stop / removing widget and adding again doesn't fix it
(I use Lawnchair as home app but also tried reverting to stock home app)

### Weather source used

Open-Meteo

### Breezy Weather version

5.1.8

### Android version

Android 13

### Device

Samsung Galaxy S22

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I read the [Frequently Asked Questions](https://github.com/breezy-weather/breezy-weather/blob/main/HELP.md) document and followed instructions if relevant.
- [X] I have updated the app to **[version 5.1.8 or later](https://github.com/breezy-weather/breezy-weather/releases/latest)**.
- [X] I wrote my request in English, and any screenshot I attached are also in English (language can be changed from Settings > Appearance), unless my issue only happens with a specific language
- [X] I understand that this app is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY, so I may not get a positive reply to my request, if any at all.

**Comment by papjul** [comment]
The TimeZone of the widget is the timezone of your location, not of your device.
