### ISSUE TITLE
Custom Tabbed Widget

### ISSUE THREAD

**Issue by csm10495** [breezy-weather/breezy-weather#910]
### Describe your idea

It would be cool if there was a widget that had weather info in tabs. One tab for hourly forecast and one for daily forecast.

This is kind of similar to this widget in 1Weather:

![Screenshot_20240408-182855](https://github.com/breezy-weather/breezy-weather/assets/5749838/2e3ff01c-c6b8-41dc-95d0-8722bb9247fa)

Optimally it would be resizable. I personally use a 3x2.5 size. Even cooler would be the ability to pick from X different tabs and set their order, etc. Also having the ability to pick what is persistently shown regardless of tab would be nice.

Anyways, thanks for all.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] My idea is not related to a question covered in the [Frequently Asked Questions](https://github.com/breezy-weather/breezy-weather/blob/main/HELP.md) document, or a feature described in the [Homepage](https://github.com/breezy-weather/breezy-weather/blob/main/docs/HOMEPAGE.md) document.
- [X] I have updated the app to **[version 5.1.8 or later](https://github.com/breezy-weather/breezy-weather/releases/latest)**.
- [X] I understand that this app is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY, so I may not get a positive reply to my request, if any at all.

**Comment by papjul** [comment]
I didn't know you could make tabs in widgets. Can you share an open source app so I understand how it's done? Thanks

**Comment by csm10495** [comment]
I wish I knew of an open source example.

I don't know much about Android development. Worst case scenario: tabs can be simulated via buttons and changing the visibility of all items inside the other tabs to false and the visibility of items in the tab we clicked to true.

**Comment by papjul** [comment]
We reviewed and we didn't feel like interactive widgets are a good thing.
We have plans to make a compact widget with current, daily and hourly information together as part of #937 that might be something you will like. Individual and more compact current details, daily and hourly are also planned.
