### ISSUE TITLE
Use your own API as source 

### ISSUE THREAD

**Issue by nitanmarcel** [breezy-weather/breezy-weather#911]
### Describe your idea

I'm suggesting the ability to use a custom API as a provider that can be self hosted somewhere. This could be useful for people like me who are looking for a reliable source for the weather, such as governmental websites but they require to scrape the resepective website to retrieve data.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] My idea is not related to a question covered in the [Frequently Asked Questions](https://github.com/breezy-weather/breezy-weather/blob/main/HELP.md) document, or a feature described in the [Homepage](https://github.com/breezy-weather/breezy-weather/blob/main/docs/HOMEPAGE.md) document.
- [X] I have updated the app to **[version 5.1.8 or later](https://github.com/breezy-weather/breezy-weather/releases/latest)**.
- [X] I understand that this app is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY, so I may not get a positive reply to my request, if any at all.

**Comment by papjul** [comment]
If you host your own API website, we can use it.
However, I would not recommend scraping a website from a server, that would make too many requests and you would be banned.
It's best to scrap directly from Breezy Weather. We currently only have Json sources, but parsing HTML is allowed as long as you can make it reliable (it may require to be updated more often to keep up with websites changes than an API).
