### ISSUE TITLE
Make auto refresh on app launch (within 1.5hrs) smarter

### ISSUE THREAD

**Issue by brian6932** [breezy-weather/breezy-weather#916]
### Describe your idea

Expansion on #632.
So ever since you told me that some level of background refresh was required to get precipitation information, I set the app to background check once every 24hrs. Now the problem's that this currently only happens when `intervalInHour` is nullable.
https://github.com/breezy-weather/breezy-weather/blob/f6eb229181230e2194fd180cb7c621fb4127259b/app/src/main/java/org/breezyweather/common/basic/models/options/UpdateInterval.kt#L53-L54
High intervals introduce the same problem. Imo either a comparison to `1.5f` or a toggle for this feature should be made instead of just a null check.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] My idea is not related to a question covered in the [Frequently Asked Questions](https://github.com/breezy-weather/breezy-weather/blob/main/HELP.md) document, or a feature described in the [Homepage](https://github.com/breezy-weather/breezy-weather/blob/main/docs/HOMEPAGE.md) document.
- [X] I have updated the app to **[version 5.1.8 or later](https://github.com/breezy-weather/breezy-weather/releases/latest)**.
- [X] I understand that this app is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY, so I may not get a positive reply to my request, if any at all.

**Comment by papjul** [comment]
We made some improvements to the background process:
https://github.com/breezy-weather/breezy-weather/blob/main/docs/UPDATES.md

Quoting:
> At your selected refresh rate, this is what happens:
> - The weather for the first location is refreshed
> - The weather for secondary locations are:
> - not refreshed if you don’t use multi cities widget or notification-widget, or data sharing feature (they will, however, be automatically refreshed if outdated as soon as you try to access them in the app)
>  - otherwise, refreshed once a day at most to avoid battery/bandwidth consumption in the background from less-used locations

I heavily make some tests with many sources used and I barely get to 4 MB of consumption on month.

You can turn off Internet at night, turn on "no refresh when battery is low" to make it even lighter.

So there's no reason to set your refresh rate to once every 24 hours if you actually want 1.5 hours. Even the "Never" config doesn't make sense to me and I was just thinking yesterday I should add a warning when people are trying to set it to Never.

**Comment by papjul** [comment]
> Please re-read the last thread, you've forgotten why I want this

In the last thread, you said you turned off background updates, so it's not the same case.

> I don't want background refreshing at such high rates

There are intermediate steps between 1.5 hours and 24 hours, pick the one that is the most appropriate to you.

> I just don't want to pull to refresh for no reason

You have the "X hour ago" indicator on top left of your location that gives you a pretty good hint if your data is fresh or not. So you only pull to refresh if it's >= 2 hours ago.

> this is not good UX

Some people were not happy about the change that automatically refresh every 1.5 hours when refresh rate is set to Never (see #824), so what you consider a good UX may be a bad UX for someone else. I did it for the "Never" refresh rate as you may end up with very old updates if the user never manually refresh from time to time, but refreshing when you open the app every 1.5 hours when the background refresh rate is set to 24 hours makes no sense to me.

In the end, a good compromise is to set the background refresh rate to your liking and refresh manually based on the "refreshed X hour ago" indicator.

**Comment by papjul** [comment]
> So ever since you told me that some level of background refresh was required to get precipitation information, I set the app to background check once every 24hrs.

Just want to expand on that, just to be sure. You realize that you will only get the precipitation notification once every 24 hours? So, let's say the background update happens every day at 2:00 AM, you will get the precipitation notification if there is any precipitation between 2:00 AM and 3:59 AM. And you will get no notification about precipitation happening the rest of the day. Are you sure that's what you want?

**Comment by brian6932** [comment]
> Some people were not happy about the change that automatically refresh every 1.5 hours when refresh rate is set to Never

You can make a toggle Never (but refresh on open), or just a completely separate toggle, it doesn't have to be within the same drop down item.

> In the end, a good compromise is to set the background refresh rate to your liking and refresh manually based on the "refreshed X hour ago" indicator.

Strongly disagreed, that's not a compromise, it's just making it manual.

> Just want to expand on that, just to be sure. You realize that you will only get the precipitation notification once every 24 hours? So, let's say the background update happens every day at 2:00 AM, you will get the precipitation notification if there is any precipitation between 2:00 AM and 3:59 AM. And you will get no notification about precipitation happening the rest of the day. Are you sure that's what you want?

Yes, I want to know whether to take my umbrella in the morning.

**Comment by papjul** [comment]
> You can make a toggle Never (but refresh on open), or just a completely separate toggle, it doesn't have to be within the same drop down item.

Which weather app does that? Adding tons of options for edge-cases is a bad UX choice. Important preferences crawls under less important preferences, some options can become confusing if there are split into many, and some users can't even find basic settings #558 #659 You have no idea how many people request to have a preference for their own case. We would have 100+ more preferences if I had to say yes to every request so far.

> Strongly disagreed, that's not a compromise, it's just making it manual.

If you don't want to make it manual, use the background update setting which is intended for automatic refresh. For some reason, you stand on not using it.

> Yes, I want to know whether to take my umbrella in the morning.

So that's what I thought. The precipitation notification is based on precipitation nowcasting that is only valid for the next 2 hours. This does NOT tell you if there will be precipitation today. If you're interested in weather for today, you must use Today forecast notification which you can schedule to be sent every morning. It does not rely on background updates. However, if you set the background updates to Never, and never opens the app, you may end up with daily notifications being outdated with newer model predictions that are updated every 1-6 hours depending on models.

> It's why I valued the Dark(er) Sky app.

Feel free to use this app then. But I think you get it wrong, it's impossible to send a precipitation notification in the background if you don't have a background work, either scheduled like the today forecast notification, or periodic like weather update in the background. So that app is just having a background work without telling you it does have one.

**Comment by brian6932** [comment]
> Which weather app does that?

I mentioned Dark(er) Sky did, and I've used other weather apps that do as well.

> Which weather app does that? Adding tons of options for edge-cases is a bad UX choice.

Not supporting use cases is even worse UX.



> If you don't want to make it manual, use the background update setting which is intended for automatic refresh. For some reason, you stand on not using it.

This is not how I want to use my battery.



> If you're interested in weather for today, you must use Today forecast notification which you can schedule to be sent every morning.

Yes I use that.

> Feel free to use this app then.

It no longer exists on Android, the API was removed when it was bought out by Apple.

**Comment by papjul** [comment]
So you want to double every option to be:
- Never
- Never (but refreshes on open every 1.5 hours)
- 3 hours
- 3 hours (but refreshes on open every 1.5 hours)
- 6 hours
- 6 hours (but refreshes on open every 1.5 hours)
- 12 hours
- 12 hours (but refreshes on open every 1.5 hours)
- 24 hours
- 24 hours (but refreshes on open every 1.5 hours)

Why not add all combinations while we're at it?
- 24 hours
- 24 hours (but refreshes on open every 30 min)
- 24 hours (but refreshes on open every 1 hour)
- 24 hours (but refreshes on open every 1.5 hours)
- 24 hours (but refreshes on open every 3 hours)
- 24 hours (but refreshes on open every 6 hours)
- 24 hours (but refreshes on open every 12 hours)

I'm locking this thread as we both know continuing this discussion is just a waste of both our time, as you don't want to use the background refresh rate at a rate of your liking, and I don't want to implement your option.

> you promote the creation of pointless forks that could've just been simple toggles.

I think you're talking about flavors? Some people wanted different apps but I refused, it's only one app with variations to match criteria of inclusion of stores.

I promote only the standard version. And you know very well that if I could make it a toggle, I would've done it (who would choose the complex option if a simple one was available?). F-Droid default repo doesn't allow non-public API keys so a toggle is not possible. Some people don't like having a proprietary lib in their app, so adding the Google Play lib to the Standard version is not possible through a toggle. It's also incompatible with Izzy and F-Droid criteria of inclusion.

Feel free to use a weather app with only one flavor if different flavors feel too bloated for you.
