### ISSUE TITLE
[Open-Meteo] Location search - Better handle responses that include elements without timezone

### ISSUE THREAD

**Issue by min7-i** [breezy-weather/breezy-weather#921]
### Describe your idea

When using Open-Meteo as location search provider, it can happen that the [response](https://geocoding-api.open-meteo.com/v1/search?name=mexico&count=10&language=en&format=json) includes elements without a timezone, e.g. when searching for "mexico".

Currently, if a single element has no timezone, the entire response is not converted which means that no search results are displayed in the location search even if other elements in the response have a timezone.

It would be helpful, if the converter filtered elements without a timezone, so elements which have a timezone could be kept and displayed as search results.

### Other details

As far as I could see, [GeoNamesResultConverter](https://github.com/breezy-weather/breezy-weather/blob/abea97fe5e3c02aa1df3cc09f3b56c2b9d386ccf/app/src/src_nofdroid/org/breezyweather/sources/geonames/GeoNamesResultConverter.kt#L26) already handles this case.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] The idea I’m suggesting is not in the [list of features that will not be implemented](https://github.com/breezy-weather/breezy-weather/blob/main/README.md#features-that-will-not-be-implemented).
- [X] I have written a short but informative title.
- [X] I have updated the app to **[version 5.1.8 or later](https://github.com/breezy-weather/breezy-weather/releases/latest)**.
- [X] I understand that this app is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY, so I may not get a positive reply to my request, if any at all.

**Comment by papjul** [comment]
I see no empty `timezone` for this search? I even tried to change `count` to 50.

**Comment by min7-i** [comment]
The first result is missing the timezone property:
![grafik](https://github.com/breezy-weather/breezy-weather/assets/97251923/4e35fb45-5bac-4fac-8f08-e67ad95a1cab)

**Comment by papjul** [comment]
Ah, yes, I was looking for `"timezone": null`. Will fix that the same way as GeoNames, but probably worth checking other sources.
