### ISSUE TITLE
UK Met Office

### ISSUE THREAD

**Issue by Shadowvaporwarez** [breezy-weather/breezy-weather#923]
### Link to publicly available documentation of the API

https://datahub.metoffice.gov.uk/docs/f/category/site-specific/overview

### Available and not available data

Available: Daily Temp, Hourly Temp, Precipitation (with Now casting), air quality, wind, UV Index, Sunshine, Feels Like, Humidity, Dew Point, Cloud Cover, Visibility, Pressure, Ceiling, Pollen and Mould, Sun/Moon, Alerts, Temp Normals

### Are you going to develop yourself the new source for the app?

No

### Give a bit more details or context about this source

Currently it's seems like the European weather services accuracy for the UK isn't quite there. I was previously using Weawow with Foreca which defaults to using UKMO as it's source, so was wondering if this would be possible to add?

### Acknowledgements

- [X] This source has a free-tier available (no mandatory credit card info and trials don’t count as “free”), and if it is a main weather source, it includes free hourly forecast
- [X] If this is a weather source request, I checked that endpoints are by coordinates, or that there is a reverse geocoding endpoint.
- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written the name of the source as the title of this issue.
- [X] I have updated the app to **[version 5.1.8 or later](https://github.com/breezy-weather/breezy-weather/releases/latest)** and this source is not part of it.
- [X] I understand that this app is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY, so I may not get a positive reply to my request, if any at all.

**Comment by papjul** [comment]
1) Wasn't MET Office UK deprecating their APIs? I thought I read something about that. Better not implement something that is going to disappear.
2) Seems they require an API key :( Is a credit card or phone number required to register?
3) Where do you see nowcasting? I can only see hourly and daily endpoints

**Comment by Shadowvaporwarez** [comment]
Hi!

1. They've moved from DataPoint to DataHub
2. I've double checked and it does, sorry :(
3. Ignore me, being stupid

Possible to implement with the caveat that users need to generate their own API key?

**Comment by Shadowvaporwarez** [comment]
![Screenshot_2024-04-11-12-53-05-96_e4424258c8b8649f6e67d283a50a2cbc](https://github.com/breezy-weather/breezy-weather/assets/96532814/73fc1422-9bd5-4563-b591-65a4ff274e11)

This is the information requested

**Comment by papjul** [comment]
> Possible to implement with the caveat that users need to generate their own API key?

Yes, Pirate Weather and HERE sources are in this case, but they don't require personal information which is the problem here.

> ## Features that will not be implemented
> - Paid-only sources, too limited free-tier, or free-tier that requires privacy-invasive information (credit card info, phone number, etc)

We already support many sources that don't have these problems.

Even if someone would develop it, we won't accept it in the project, as it requires our developers to maintain it in the future.

However, our system is design to make it easy to implement any source, even those we don't allow in the project, but you will have to develop and maintain it on your own fork.
