### ISSUE TITLE
Weather data in airplane mode, 0:00 a.m. does not automatically update the number of weeks. 

### ISSUE THREAD

**Issue by rocex** [breezy-weather/breezy-weather#924]
### Steps to reproduce

I have a habit of setting my phone to "airplane mode" before going to bed at 11 p.m., so that Breezy can't update data online. When I woke up at 7:00 a.m., I found that the clock in the desktop widget had been adjusted to the current day, but Breezy also showed the date and day of the week yesterday, and I had to open the app or update the data once before the weather information would be updated to that day.

1. Set your phone to airplane mode
2. Wait until after 0:00 in the evening

### Expected behavior

The time, date, and day of the week should all be switched to the current day.

### Actual behavior

The first day of the week should be Friday, not Thursday

![](https://github.com/breezy-weather/breezy-weather/assets/9346138/dac20b6b-d50b-4610-ab60-94effc0f9108)

### Weather source used

china

### Breezy Weather version

 Breezy Weather v5.1.8

### Android version

andriod 10

### Device

huawei mate 30

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I read the [Frequently Asked Questions](https://github.com/breezy-weather/breezy-weather/blob/main/HELP.md) document and followed instructions if relevant.
- [X] I have updated the app to **[version 5.1.8 or later](https://github.com/breezy-weather/breezy-weather/releases/latest)**.
- [X] I wrote my request in English, and any screenshot I attached are also in English (language can be changed from Settings > Appearance), unless my issue only happens with a specific language
- [X] I understand that this app is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY, so I may not get a positive reply to my request, if any at all.

**Comment by papjul** [comment]
Widgets refresh depends on updates due to the validity of the forecast/current.

If you're offline, widgets won't be refreshed and data will be shown as if you were yesterday since the validity date is yesterday.

Best I can do is remove "Today" and put "Thu" instead, but I don't think it's really worth it…
