### ISSUE TITLE
Location name is 'current location' with Open Meteo

### ISSUE THREAD

**Issue by Shadowvaporwarez** [breezy-weather/breezy-weather#926]
### Steps to reproduce

1. Use Open Meteo as the source

### Expected behavior

1. Location name should appear (Using AccuWeather in this example)
![Screenshot_2024-04-11-14-01-53-61_8b90da7a90336dddbe1fd9fd7538077a](https://github.com/breezy-weather/breezy-weather/assets/96532814/49747e4b-e744-4cce-93d1-a5d2988c62aa)
![Screenshot_2024-04-11-14-01-56-57_3822ac0e29cfec8970059bb21d01f05e](https://github.com/breezy-weather/breezy-weather/assets/96532814/23d4ecfa-ac8d-4d06-bafb-b4c68c1048d3)

### Actual behavior

1. Location says current location in app and on widget
![Screenshot_2024-04-11-13-59-30-90_8b90da7a90336dddbe1fd9fd7538077a](https://github.com/breezy-weather/breezy-weather/assets/96532814/7c9c6b31-0fcd-47a0-a781-a17a5b13163f)
![Screenshot_2024-04-11-14-01-13-05_3822ac0e29cfec8970059bb21d01f05e](https://github.com/breezy-weather/breezy-weather/assets/96532814/bb528011-3b84-496a-86c0-6f8ad6be8b2f)

### Weather source used

Open Meteo

### Breezy Weather version

5.1.8

### Android version

Android 13

### Device

One Plus 11

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I read the [Frequently Asked Questions](https://github.com/breezy-weather/breezy-weather/blob/main/HELP.md) document and followed instructions if relevant.
- [X] I have updated the app to **[version 5.1.8 or later](https://github.com/breezy-weather/breezy-weather/releases/latest)**.
- [X] I wrote my request in English, and any screenshot I attached are also in English (language can be changed from Settings > Appearance), unless my issue only happens with a specific language
- [X] I understand that this app is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY, so I may not get a positive reply to my request, if any at all.

**Comment by papjul** [comment]
Open-Meteo does not support reverse geocoding, so we fallback to an offline reverse geocoder that is only able to guess your country. See [this document](https://github.com/breezy-weather/breezy-weather/blob/main/docs/SOURCES.md#location) for sources supporting more detailed reverse geocoding.
