### ISSUE TITLE
Add Gadgetbridge support

### ISSUE THREAD

**Issue by bbbhltz** [breezy-weather/breezy-weather#93]
### Describe your suggested feature

There are currently 3 apps that report wileatger data to Gadgetbridge. Would it be possible to add this feature in the future?

See https://codeberg.org/Freeyourgadget/Gadgetbridge/wiki/Weather 

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to **[latest version](https://github.com/breezy-weather/breezy-weather/releases/latest)**.

**Comment by papjul** [comment]
I don’t have a Gadgetbridge so someone needs to develop it and maintain it (fix bugs, support firmware updates, etc).
Please get in touch before to ensure this is done correctly ;)

If I understand correctly, the goal is to forward the weather information collected by Geometric Weather to another device that cannot get it by itself, right?

**Comment by bbbhltz** [comment]
Yes. That's right. The 3 apps that work with Gadgetbridge send the average temp and condition. I have no skills when it comes to this, just a preference for this app over the others.

Great work, by the way. Thanks!

**Comment by bbbhltz** [comment]
Ah, yes. I see that. My smart watch doesn't provide a forecast so I didn't know it did that. Sorry for the confusion.

**Comment by LuccoJ** [comment]
Forecast is indeed present among the information Gadgetbridge expects. Gadgetbridge has this interface with weather applications because Gadgetbridge itself has a strict policy of lacking any internet access of its own, to make users feel safe about the privacy of their wearables (which are all but private with most of the OEM apps).

**Comment by noodlejetski** [comment]
gosh, I'd love that. Gadgetbridge is the only reason why I keep to weather apps installed on my device (this one and QuickWeather).

**Comment by papjul** [comment]
Please show your interest upstream at https://codeberg.org/Freeyourgadget/Gadgetbridge/pulls/3077

If I'm not able to test the data without a device, I can't implement it.

**Comment by Commenter25** [comment]
The upstream PR has been merged, and they have added a section to their documentation about weather development. https://codeberg.org/Freeyourgadget/Gadgetbridge/wiki/Weather#weather-app-development

**Comment by papjul** [comment]
Thanks for the follow-up, please tell us when it gets released ;)

**Comment by LuccoJ** [comment]
@papjul you don't strictly need to wait for a release, because Gadgetbridge has [an F-Droid repository of nightly builds](https://freeyourgadget.codeberg.page/fdroid/repo/) (which I've used for a long time now without any issue of stability).

**Comment by papjul** [comment]
Good to know it should be available tomorrow.
