### ISSUE TITLE
[Open-Meteo] Wrong timezone on current location

### ISSUE THREAD

**Issue by pdscomp** [breezy-weather/breezy-weather#942]
### Steps to reproduce

1. Add a new widget to the homescreen that includes time/date
2. Time is one hour off from expected in both the preview and on the widget

### Expected behavior

Time should match my system time

### Actual behavior

Time is showing one hour earlier than expected

### Weather source used

Open-Meteo

### Breezy Weather version

5.1.8

### Android version

Android 14 / One UI 6.1

### Device

Samsung Galaxy Z Fold 5

### Other details

![Screenshot_20240414_142531_Breezy Weather](https://github.com/breezy-weather/breezy-weather/assets/1937248/84d07847-2043-4b44-8cf2-ec3b28a5fc63)
![Screenshot_20240414_142853](https://github.com/breezy-weather/breezy-weather/assets/1937248/853e464c-2ac1-43db-80f0-42bc055747d8)
![Screenshot_20240414_143140_Settings](https://github.com/breezy-weather/breezy-weather/assets/1937248/8f176f36-c73f-4481-894b-7237f1a0efbd)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I read the [Frequently Asked Questions](https://github.com/breezy-weather/breezy-weather/blob/main/HELP.md) document and followed instructions if relevant.
- [X] I have updated the app to **[version 5.1.8 or later](https://github.com/breezy-weather/breezy-weather/releases/latest)**.
- [X] I wrote my request in English, and any screenshot I attached are also in English (language can be changed from Settings > Appearance), unless my issue only happens with a specific language
- [X] I understand that this app is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY, so I may not get a positive reply to my request, if any at all.

**Comment by papjul** [comment]
Duplicate of #870?
