### ISSUE TITLE
Turn off notifications of low severity alerts

### ISSUE THREAD

**Issue by xxyxxyxyx1** [breezy-weather/breezy-weather#944]
### Describe your idea

I like to have system notification weather alerts for extreme weather. However, where I live, there is a low-level (1/4) wind warning on average once per day. It's just windy here, and the threshold for a warning is unreasonably low. 

I would like to be able to customize which weather warnings result in system notifications. I think this could be best accomplished with a "blacklist" of warnings that should _not_ be notified. We want warnings for all unexpected things, and we can add something to the blacklist when we receive it too often. 

The blacklist could simply consist of strings of text that. If a string is found in a warning, prevent the system notification from happening. 

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] The idea I’m suggesting is not in the [list of features that will not be implemented](https://github.com/breezy-weather/breezy-weather/blob/main/README.md#features-that-will-not-be-implemented).
- [X] I have written a short but informative title.
- [X] I have updated the app to **[version 5.1.8 or later](https://github.com/breezy-weather/breezy-weather/releases/latest)**.
- [X] I understand that this app is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY, so I may not get a positive reply to my request, if any at all.

**Comment by papjul** [comment]
What you're looking for is the severity:
- “Extreme” - Extraordinary threat to life or property
- “Severe” - Significant threat to life or property
- “Moderate” - Possible threat to life or property
- “Minor” – Minimal to no known threat to life or property
- “Unknown” - Severity unknown

Unfortunately, we have a few sources with only unknown severity, which would make it not working.

Alternatively, your suggestion is complex and opens the door to missing important alerts. I prefer someone receives more notifications than missing an important one.

I have an idea in mind to improve the system. However, first, I would like to focus on:

> where I live, there is a low-level (1/4) wind warning on average once per day

1. If it's the same alert every day, you shouldn't be notified of it every day. Can you give a bit more details?
2. Additionally, how were your previous weather apps notification of alerts working? I don't believe they had a regular expression system?

**Comment by papjul** [comment]
V5.2.1 will no longer send notifications for alerts with minimal to no known threat to life or property. You can still receive notifications for alerts with unknown severity.

**Comment by xxyxxyxyx1** [comment]
I am attaching example screenshots from the 4 notifications "level 1 of 4" that I received yesterday that I do not want. I also include 1 notification "level 2 of 4" that I received the day before that I do want. 

There are two notifications for wind gusts: 0800–1800, and 1324–1800

![image](https://github.com/breezy-weather/breezy-weather/assets/25559220/5e6ef590-2e67-42c9-8b18-e6f7c8cf2cdb)
![image](https://github.com/breezy-weather/breezy-weather/assets/25559220/2314e455-1d38-4781-a5af-776f5e1d1ba4)

There are two notifications for thunderstorms: 1517–1545, and 1650–1715
![image](https://github.com/breezy-weather/breezy-weather/assets/25559220/c46b0193-a881-416e-89a2-92f66d495cd2)
![image](https://github.com/breezy-weather/breezy-weather/assets/25559220/977b8584-7473-407d-91bb-4a1be1e1e137)


There is one notification from the day before for gale force gusts
![image](https://github.com/breezy-weather/breezy-weather/assets/25559220/75569acf-707e-4073-926e-0d6789bb5abb)

The previous weather app I used only gave notifications very rarely, I believe for alert levels 3/4 and 4/4. But that was on an old phone and I unfortunately do not remember the app name.

**Comment by papjul** [comment]
I believe you would be less spammed if you were using Bright Sky (DWD) source instead of AccuWeather as your alert source. I don't consider AccuWeather a reliable source for alerts (more generally, not a reliable weather source for Europe). They often send duplicate alerts, sometimes random start time/end time, some users reported missing alerts, etc.

**Comment by xxyxxyxyx1** [comment]
Thank you for the suggestion. However, I cannot figure out how to change my alert source in the app, are there instructions?

**Comment by papjul** [comment]
Either swipe from right to left on your location list, or tap the Edit button at the bottom of the main screen.

**Comment by papjul** [comment]
Global settings and per-location settings are two different things, so they should not be mixed.
Having two ways to access per-location settings is more than enough IMO

> scrolling to the bottom

#311 has plans to consider moving the "Edit" button to the top as a pencil icon on top right
