### ISSUE TITLE
Prevent horizontal swiping between locations on precipitation nowcasting chart

### ISSUE THREAD

**Issue by papjul** [breezy-weather/breezy-weather#947]
Add at least 2 locations, one with precipitation nowcasting.

When horizontally swiping to move the marker, it swipes to the next location instead.

It worked on the old chart, so maybe check if something particular was done:
https://github.com/breezy-weather/breezy-weather/tree/v5.1.8

**Comment by min7-i** [comment]
In the old version of the chart there was some logic to intercept touch events: https://github.com/breezy-weather/breezy-weather/blob/ee0473cc54392bdcdc43ebddca62ef112cb7a2eb/app/src/main/java/org/breezyweather/common/ui/widgets/precipitationBar/PrecipitationBar.kt#L221

This effectively prevented the touch event from being propagated to the parent which made it possible to move the marker in the chart.

For the new chart we don't have that anymore, but it's probably just a matter of applying the right modifier to the chart. `pointerInteropFilter` looks promising.

I'll look into it, but it might take a while.

**Comment by min7-i** [comment]
I found a solution. Just need to fine-tune it a bit.

**Comment by 2013ZRZ** [comment]
This problem has been solved, but when I upgraded to version 5.2.0, I can't switch time points by sliding horizontally in the precipitation nowcasting.

* Device: Honor 6A
* System: Android 7 Nougat
* Breezy Weather Version: 5.2.0_armeabi_v7a
