### ISSUE TITLE
Apps other then Gadgetbridge aren't available in "Send Gadgetbridge data" menu

### ISSUE THREAD

**Issue by pacjo** [breezy-weather/breezy-weather#948]
### Steps to reproduce

1. Update to 5.2.0
2. Try to add apps other then Gadgetbridge in "Send Gadgetbridge data" menu
3. See (well not an error) but incomplete list

### Expected behavior

1. All apps should appear

### Actual behavior

An incompleate list appears

### Weather source used

/

### Breezy Weather version

5.2.0

### Android version

Android 14

### Device

Android Studio Emulator / Redmi Note 10 Pro

### Other details

![Screenshot_20240415_200934](https://github.com/breezy-weather/breezy-weather/assets/56438628/a1700b5e-5f25-43e7-a6aa-e003d98cbb15)

This is probably a consequence of 015c1deccebfac8939dc2ef6e01c1f18ba5be6b9. 

I don't know how you're checking for available apps, I can add modify mine ([GenericWeather](https://github.com/pacjo/SmartspacerPlugins/tree/main/app/src/genericweather)) if needed.

There might be an issue with detecting the "support". I'm not registering any intent receivers. For me it's all handled by [Smartspacer](https://github.com/KieronQuinn/Smartspacer), with only code being [this](https://github.com/pacjo/SmartspacerPlugins/blob/f7dfa42678306688ec84d7f09235c3edad1ad660/app/src/genericweather/src/java/providers/GenericWeatherProvider.kt#L41).

Maybe a solution might be to register a dummy intent filter to make it visible to Breezy?

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I read the [Frequently Asked Questions](https://github.com/breezy-weather/breezy-weather/blob/main/HELP.md) document and followed instructions if relevant.
- [X] I have updated the app to **[version 5.2.0 or later](https://github.com/breezy-weather/breezy-weather/releases/latest)**.
- [X] I wrote my request in English, and any screenshot I attached are also in English (language can be changed from Settings > Appearance), unless my issue only happens with a specific language
- [X] I understand that this app is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY, so I may not get a positive reply to my request, if any at all.

**Comment by papjul** [comment]
I didn't know you could get an intent without declaring it in the manifest.

You will need to declare it. See line 447 of how Gadgetbridge does it:
https://codeberg.org/Freeyourgadget/Gadgetbridge/src/branch/master/app/src/main/AndroidManifest.xml

**Comment by pacjo** [comment]
Thanks for a quick response. I changed this:
```
        <provider
            android:name="providers.GenericWeatherProvider"
            android:authorities="${applicationId}.providers.weather"
            android:exported="true"
            android:permission="com.kieronquinn.app.smartspacer.permission.ACCESS_SMARTSPACER_BROADCASTS" />
```
to this
```
<provider
            android:name="providers.GenericWeatherProvider"
            android:authorities="${applicationId}.providers.weather"
            android:exported="true"
            android:permission="com.kieronquinn.app.smartspacer.permission.ACCESS_SMARTSPACER_BROADCASTS" >
            <intent-filter>
                <action android:name="nodomain.freeyourgadget.gadgetbridge.ACTION_GENERIC_WEATHER" />
            </intent-filter>
        </provider>
```
and now it shows up in the settings, but I still don't get intents.

It's probably because Smartspacer app gets them normally, then just calling a function in my plugin with the intent. Can we do something about it? (...just maybe (if possible) an "other apps" button should be made available?)

**Comment by Releece** [comment]
I have the same issue.
Device: OnePlus 11
OS: Android 14 (OxygenOS 14.0.0.601(EX01))
Breezy Weather: 5.2.0
Smartspacer: 1.7.2

Before, in order to use Breezy Weather as a weather source for Smartspacer I had to install GadgetBridge (which I don't have any use for) just so I could enable the toggle to send data to GadgetBridge, and in turn Smartpacer would receive the data.

This was then updated to a more general toggle to share data with other apps. Solving the problem of needing to install Gadgetbridge and I could succesfully share data with Smartspacer after uninstalling GadgetBridge.

Now with the most recent update to be able to select which apps you want to share to, if I press 'Send GadgetBridge data' I get 'No compatible packages found', while Smartspacer + the Smartspacer plugin to fetch weather data from other sources are installed, as they have always been throughout these updates on my device.


Please fix kindly :) Thanks for all the work on Breezy

**Comment by papjul** [comment]
> now it shows up in the settings

> just maybe (if possible) an "other apps" button should be made available?

So you don't need that if it's already listed?

> but I still don't get intents

We changed two things in the way we send intents:
- We added the `WeatherSecondaryJson` extra, a new feature from Gadgetbridge
- We set the package to which we send the intent

Both seem unrelated to your issue to me, as Gadgetbridge developer confirmed this new method works. If you can see your app listed, the intent will be sent to your app.

> It's probably because Smartspacer app gets them normally, then just calling a function in my plugin with the intent

Which package is listed? Smartspacer or your plugin app? The manifest with the intent is in your app, not in Smartspacer app, right?
