### ISSUE TITLE
[Open-Meteo] Weather data refresh failed

### ISSUE THREAD

**Issue by AnonemooseBear** [breezy-weather/breezy-weather#957]
### Steps to reproduce

1. Setup widget.
2. Wait until time passes for automatic update to run.
3. Receive error notification.

### Expected behavior

Weather in widget should update at specified intervals, and without having to open the full app.

### Actual behavior

An error file is produced.
![Screenshot_20240416_143453](https://github.com/breezy-weather/breezy-weather/assets/131646532/b9f78f13-eea2-4cbf-9dd5-546a70940892)

### Weather source used

Open-Meteo

### Breezy Weather version

5.1.8_fdroid

### Android version

9

### Device

Huawei Mate 20 PRO

### Other details

Within the app settings itself: refresh rate is set to 6hrs, ignore when battery is low - ENABLED, disable battery optimization - ALLOWED.

Within the phone settings: location - DENIED, mobile data & background data - ON.

Within the battery optimization settings the app is managed automatically. This means settings haven't been adjusted, and it has free reign to run at start-up, run in the background, and be launched by other apps.

I have manually entered locations for weather in the app itself, and this works fine. Once I open the app, the weather locations update normally; consequently, the widget also updates the weather. I just need the widget to update at the specified intervals, without having to open the app, instead of produce an error file & notification.

I'm unsure if this is related to issue #564 or not, because I'm not technical enough to understand it.

I can't update to 5.2.x as this is the most recent version available on fdroid - which is the way apps are sourced for this device. My repos have been updated. Frankly, you could consider requiring to update to a version that's not available a secondary issue here!
![Screenshot_20240416_210427_org fdroid fdroid](https://github.com/breezy-weather/breezy-weather/assets/131646532/231edeb6-c6bb-4813-aeed-05a24b72d6cb)
![Screenshot_20240416_210517_org fdroid fdroid](https://github.com/breezy-weather/breezy-weather/assets/131646532/b09ce674-0030-458f-b14c-3f046e6038c4)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I read the [Frequently Asked Questions](https://github.com/breezy-weather/breezy-weather/blob/main/HELP.md) document and followed instructions if relevant.
- [X] I have updated the app to **[version 5.2.0 or later](https://github.com/breezy-weather/breezy-weather/releases/latest)**.
- [X] I wrote my request in English, and any screenshot I attached are also in English (language can be changed from Settings > Appearance), unless my issue only happens with a specific language
- [X] I understand that this app is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY, so I may not get a positive reply to my request, if any at all.

**Comment by papjul** [comment]
> I can't update to 5.2.x as this is the most recent version available on fdroid - which is the way apps are sourced for this device. My repos have been updated. Frankly, you could consider requiring to update to a version that's not available a secondary issue here!

I'm sorry but v5.1.8 is no longer supported and F-Droid default repo is not recommended for getting updates. We have [other F-Droid repos](https://github.com/breezy-weather/fdroid-repo) available with faster updates. If you don't want to use them, everytime you have an issue, it takes you about 20 seconds to [download the APK](https://github.com/breezy-weather/breezy-weather/releases/latest) and to update, while it would take me way more time to understand that something you report was actually fixed since then. Also, we have more detailed errors in v5.2.0 that would help me troubleshooting, so please save your app maintainers their time and take these 20 seconds to update.

Once it's done and you can reproduce the issue with this new version, please export your crash log from `Settings` > `Debug`.

**Comment by Jean-BaptisteC** [comment]
If have similar problem with this error:
- API request limit reached

**Comment by papjul** [comment]
> If have similar problem with this error:
> 
>     * API request limit reached

It's not the same error and the same source. Please [read FAQ](https://github.com/breezy-weather/breezy-weather/blob/main/HELP.md#required-api-key-missing--api-requests-limit-reached--api-access-unauthorized--update-not-yet-available).

**Comment by Arecsu** [comment]
is there a way to disable getting those Weather data refresh failed notifications? I usually don't care if the app is available at that very specific time, but I do find annoying getting this notification out of the blue almost every day. Would be awesome to disable them! But I can't find the option

**Comment by papjul** [comment]
This issue is not reproducible in v5.2.0 on my side. If that still reproduces on your side after updating, please open a new issue and attach your crash log from `Settings` > `Debug`
