### ISSUE TITLE
[Settings] Display selected settings category as headline instead of "Settings"

### ISSUE THREAD

**Issue by min7-i** [breezy-weather/breezy-weather#99]
### Describe your suggested feature

When selecting a category in settings, e.g. "Notifications", use "Notifications" as the headline in the submenu instead of "Settings".

This would provide a little bit more context to the submenu screens:

| current representation | suggestion |
| --- | --- |
| ![settings headline](https://github.com/breezy-weather/breezy-weather/assets/97251923/c77ab452-0776-432b-af6c-9cb842cf863e) | ![settings headline suggestion](https://github.com/breezy-weather/breezy-weather/assets/97251923/549696c5-d1a0-4b00-8046-b799e10b03a4) |

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to **[latest version](https://github.com/breezy-weather/breezy-weather/releases/latest)**.

**Comment by papjul** [comment]
I noticed that, however it appears to be much more difficult to fix. The scaffold is defined once for settings activity, and all subpages are part of the same activity inside the scaffold. I don’t know why it was implemented this way, but this is probably not the correct implementation (it lacks transitions between pages). So it will be fixed as part of a more general rewriting ;)

**Comment by min7-i** [comment]
@papjul I did a bit of research. The current approach with a single scaffold seems to be valid. Apart from the title, the TopAppBar stays the same (back navigation plus action to open the AboutActivity) for all destinations and the content of the scaffold is already animated when it changes. So in my opinion there is no reason to have a separate scaffold per page.

The only thing I found is that it's not recommended to pass the navController to other composables. Instead, callbacks should be used to handle navigation.

I'd submit a PR that updates the navigation handling and introduces a dynamic title for the TopAppBar.

Additionally, when the title matches the current page, I'd also like to update the name of the notification options, if you agree. With "Notifications" already being the title of the notification page it feels redundant to include that part in the name of each notification option:
<img src="https://github.com/breezy-weather/breezy-weather/assets/97251923/b2cf4cfc-eae5-403e-a1c3-e9fc88b8f23d" width=30% />

**Comment by papjul** [comment]
Yes, it's a bit redundant, but the opposite (removing it) makes the reading feels a bit unclear, and would make all translations go through translation process again, with many translators not reading what it is about if it's too unclear. So, I would prefer we leave it that way.

**Comment by min7-i** [comment]
You've got a point there. I'll leave the strings unchanged.
