### ISSUE TITLE
widget I can't open the app via the widget

### ISSUE THREAD

**Issue by Debjit-007** [breezy-weather/breezy-weather#990]
### Steps to reproduce

So apparently if i set the widget to matireal you current 
I can't open n the app via tapping the widget 
But if i set it to matireal you forecast it works 
![Screenshot_20240421-060001](https://github.com/breezy-weather/breezy-weather/assets/119999168/50b40029-0a15-454b-9179-86a63ab74966)
I can't open it no matter how many times i tap on it 

### Expected behavior

I can't open the app via the widget matireal you current

### Actual behavior

It should open the application vua the weather widget 

### Weather source used

AccuWeather 

### Breezy Weather version

5.2.1_gplay

### Android version

Android 13

### Device

Moto g 52

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open OR closed issue.
- [X] I checked that my issue is not covered in the [Frequently Asked Questions](https://github.com/breezy-weather/breezy-weather/blob/main/HELP.md) document.
- [X] I have updated the app to **[version 5.2.1 or later](https://github.com/breezy-weather/breezy-weather/releases/latest)** and I can reproduce the issue in this version.
- [X] I wrote my request in English, and any screenshot I attached are also in English (language can be changed from Settings > Appearance), unless my issue only happens with a specific language. I can write in my native language under the English text, if necessary.
- [X] I understand that this app is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY, so I may not get a positive reply to my request, if any at all.

**Comment by papjul** [comment]
5.2.1_gplay doesn't exist, please update your 5.1.8
