### ISSUE TITLE
Clumsy Google translation into Russian Daily and Hourly weather forecast

### ISSUE THREAD

**Issue by ve1mi** [breezy-weather/breezy-weather#991]
### Steps to reproduce

In Russian, daily weather forecasts, words have no logical meaning. Not just a bad translation, but it makes no sense. 
The translation in the hourly forecast needs to be re-done, as no one writes or speaks like that. The meaning of the translation is correct, but it is written and sounds terrible. This is one example of translation through Google Translator or other programs, why the programs are still terrible. Please stop using Google Translator in complex sentences, it cannot translate into Russian correctly, just like from Russian into English.

### Expected behavior

![Screenshot_20240421-051406_Breezy Weather](https://github.com/breezy-weather/breezy-weather/assets/45261656/8473b424-3601-4971-a0b7-14c4a74c3493)
![Screenshot_20240421-050715_Переводчик](https://github.com/breezy-weather/breezy-weather/assets/45261656/58d01627-e344-4a66-87fd-569e94b6e4fd)
I translate what the application writes in Russian into English via Google Translate. Even in English it turns out to be a set of words. In Russian it looks even worse in meaning than in English in this screenshot. Because in Russian, punctuation marks change the meaning of a sentence.
In English it is written word for word like this, what is written in the hourly forecast in Russian: Sunday, Evening - Monday, Morning: rain expected
![Screenshot_20240421-053751_Breezy Weather](https://github.com/breezy-weather/breezy-weather/assets/45261656/fe29a624-0c24-4cac-8b40-24cfd4983a75)
The translation in the hourly forecast needs to be re-done, as no one writes or speaks like that. The meaning of the translation is correct, but it is written and sounds terrible. This is one example of translation through Google Translator or other programs, why the programs are still terrible.
Also In Russian, it is customary to write minutes with a dot after the abbreviation of the word minute = min = мин.  word min = мин often used to mean minimum

### Actual behavior

1

### Weather source used

AccuWeather 

### Breezy Weather version

5.2.1

### Android version

Android 14

### Device

Redmi note 11 pro 5g

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open OR closed issue.
- [X] I checked that my issue is not covered in the [Frequently Asked Questions](https://github.com/breezy-weather/breezy-weather/blob/main/HELP.md) document.
- [X] I have updated the app to **[version 5.2.1 or later](https://github.com/breezy-weather/breezy-weather/releases/latest)** and I can reproduce the issue in this version.
- [X] I wrote my request in English, and any screenshot I attached are also in English (language can be changed from Settings > Appearance), unless my issue only happens with a specific language. I can write in my native language under the English text, if necessary.
- [X] I understand that this app is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY, so I may not get a positive reply to my request, if any at all.

**Comment by papjul** [comment]
Yes, AccuWeather is bad at translating, not just in Russian. Use a different source maybe?
