### ISSUE TITLE
[ColorOS launcher] Material You - Current becomes tiny after reboot

### ISSUE THREAD

**Issue by ironcr** [breezy-weather/breezy-weather#992]
### Steps to reproduce

1.set the material widget
2.reboot or turn between dark（light） mode

### Expected behavior

Widgets should display properly and not be too small

### Actual behavior

![Screenshot_2024-04-21-10-53-50-71_b783bf344239542886fee7b48fa4b892](https://github.com/breezy-weather/breezy-weather/assets/57614241/4abbbc3a-48f4-43a3-b492-bdb50b5f3d48)

### Weather source used

AccuWeather

### Breezy Weather version

5.2.1

### Android version

Android14

### Device

oneplus12

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open OR closed issue.
- [X] I checked that my issue is not covered in the [Frequently Asked Questions](https://github.com/breezy-weather/breezy-weather/blob/main/HELP.md) document.
- [X] I have updated the app to **[version 5.2.1 or later](https://github.com/breezy-weather/breezy-weather/releases/latest)** and I can reproduce the issue in this version.
- [X] I wrote my request in English, and any screenshot I attached are also in English (language can be changed from Settings > Appearance), unless my issue only happens with a specific language. I can write in my native language under the English text, if necessary.
- [X] I understand that this app is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY, so I may not get a positive reply to my request, if any at all.

**Comment by papjul** [comment]
I cannot reproduce, neither by switching dark mode or rebooting.

What's your launcher?

Can you reproduce the same issue with the Google weather widget?

**Comment by ironcr** [comment]
> I cannot reproduce, neither by switching dark mode or rebooting.
> 
> What's your launcher?
> 
> Can you reproduce the same issue with the Google weather widget?

colorOS default launcher，This problem occurred after I updated the software to 5.1.8

**Comment by papjul** [comment]
Can you reproduce the issue with a different launcher?

What about my second question: Can you reproduce the same issue with the Google weather widget?

**Comment by ironcr** [comment]
![Screenshot_2024-04-21-14-55-27-62_3822ac0e29cfec8970059bb21d01f05e](https://github.com/breezy-weather/breezy-weather/assets/57614241/625bec1d-c68f-4d11-930e-9dc96237258f)
This problem did not happen when I switched the nova launcher. Regarding your second question, due to the lack of complete gapps in color os, there is no google weather widget available.

**Comment by papjul** [comment]
Alright, I thought it was the Google clock widget on your screenshot.

You need to contact colorOS developers to let them know of this bug. I believe they don't pass the correct constraints width/height of the widget, or something.

**Comment by ironcr** [comment]
> Alright, I thought it was the Google clock widget on your screenshot.
> 
> You need to contact colorOS developers to let them know of this bug. I believe they don't pass the correct constraints width/height of the widget, or something.

ok，i will response this issue

**Comment by TCreopargh** [comment]
Same problem here, messing with dp width settings may help reproducing it. Numerical Google Clock widgets also shrink under certain dp width settings.

**Comment by papjul** [comment]
> Same problem here, messing with dp width settings may help reproducing it. Numerical Google Clock widgets also shrink under certain dp width settings.

Also using ColorOS?
